### ISSUE TITLE
Service startup error

### ISSUE THREAD

**Issue by psyneex** [hiddify/hiddify-next#10]
Hi,
in macos ventura i get this error:
<img width="501" alt="Screenshot 2023-09-22 at 12 31 52 AM" src="https://github.com/hiddify/hiddify-next/assets/80076686/50c26594-7b27-4752-b0b2-a25f772d68f4">

and this is my network settings:
<img width="441" alt="Screenshot 2023-09-22 at 12 26 01 AM" src="https://github.com/hiddify/hiddify-next/assets/80076686/846590ab-2d5e-49d4-8d5d-d582c17ffa82">

**Comment by lymanjre** [comment]
Hi. Please check the latest update. That should be fixed
