### ISSUE TITLE
[BR] Small taskbar icon

### ISSUE THREAD

**Issue by Airuop** [hiddify/hiddify-next#102]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello
When the taskbar is in small view mode
Icon not displayed well

![image](https://github.com/hiddify/hiddify-next/assets/114985398/c2e70f67-6318-4a32-94bb-2a729b3859b3)
 

### Reproduce the Bug

Small taskbar icon

### Version

9.2

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed
