### ISSUE TITLE
1.4.1 may have a problem when get the resources from https://www.gstatic.com

### ISSUE THREAD

**Issue by 1nj0k** [hiddify/hiddify-next#1022]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When visiting google.com, I find v1.4.1 cannot get resources from www.gstatic.com (developer.android.com has the same problems).  However, I try using v1.4.0, it is OK. I am not sure whether this is caused by using the new geoip/geosite rule-sets.

This is the network log when using v1.4.1.
![1 4 1](https://github.com/hiddify/hiddify-next/assets/13143916/4f618fe2-73e2-46dc-b797-c2681cc40ca2)

This is the network log when using v1.4.0.
![1 4](https://github.com/hiddify/hiddify-next/assets/13143916/cfebc12a-3e80-4bb2-b757-824833487f46)

Besides, when using v1.4.1, box has io error logs when visiting www.gstatic.com. When using v1.4.0, there is no error log.

### Minimal Reproducible Example (MRE)

1. Visit google.com without caches
2. Open dev tools, www.gstatic.com cannot load correctly
3. Visit developer.android.com without caches, the website css cannot load correctly

### Version

v1.4.1dev

### Platform/OS

Linux

### Relevant log output

```shell
+0000 2024-07-09 09:09:10 ERROR [2481369805 6.14s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:***: dial tcp 142.251.12.95:443: i/o timeout
+0000 2024-07-09 09:09:15 ERROR [3340271510 5.0s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:***: dial tcp 74.125.68.94:443: i/o timeout
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by holmesian** [comment]
I encountered the same problem


Resources under domain names such as *. gstatic. com (e.g. ssl.gstatics. com) cannot be opened through hiddify next, but can be opened by other sing-box clients with the same configuration and same server.

**Comment by 1nj0k** [comment]
It sloved in v2.3.1.
