### ISSUE TITLE
IOS最新版本IPA下载404

### ISSUE THREAD

**Issue by bujieshi** [hiddify/hiddify-next#1023]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

IOS最新版本IPA下载404

### Minimal Reproducible Example (MRE)

IOS最新版本IPA下载404

### Version

v1.4.1

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by amirsaam** [comment]
Duplicate of #1029
