### ISSUE TITLE
[FR] Install via scoop

### ISSUE THREAD

**Issue by i314q159** [hiddify/hiddify-next#1024]
### Feature description

I made a simple demo to install Hiddify via scoop.

Hope that helps to add hiddify to the official repo of scoop.

https://github.com/i314q159/spice/blob/main/bucket/hiddify-next.json

**Comment by xiaoxstz** [comment]
This issue has been put on [scoop/extra #14037](https://github.com/ScoopInstaller/Extras/issues/14037)

**Comment by i314q159** [comment]
Well done,fellows

**Comment by b4imetu** [comment]
@i314q159 Now you can try `scoop install extras/hiddify`
