### ISSUE TITLE
The IPA files do not exist.

### ISSUE THREAD

**Issue by Airuop** [hiddify/hiddify-next#1029]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The IPA files are missing.

### Minimal Reproducible Example (MRE)

new realese The IPA files do not exist.

### Version

v.1.5.x

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by blahdy** [comment]
If you distribute it via testflight - why can't you share the ipa? The last one is 1.3.3

**Comment by amirsaam** [comment]
Even decrypting Hiddify IPA won't help because Hiddify uses Network Extension and won't work if the IPA is decrypted (like every other VPN apps)

**Comment by Airuop** [comment]
> Even decrypting Hiddify IPA won't help because Hiddify uses Network Extension and won't work if the IPA is decrypted (like every other VPN apps)



We can set up an ad-hoc or developer account, or we can do it another way.
All you have to do is add the IPA file, and we can get started!

**Comment by amirsaam** [comment]
@Airuop if you can do such, build the app from source.

**Comment by blahdy** [comment]
> Even decrypting Hiddify IPA won't help because Hiddify uses Network Extension and won't work if the IPA is decrypted (like every other VPN apps)

There's trollstore

**Comment by HailonZhon** [comment]
I built the iOS application from the source code, but it crashes on launch.

**Comment by blahdy** [comment]
Can someone dump the ipa from testflight?

**Comment by amirsaam** [comment]
> Even decrypting Hiddify IPA won't help because Hiddify uses Network Extension and it's only available for valid and paid developer accounts so it won't work if the IPA is decrypted (like every other VPN apps)
