### ISSUE TITLE
کار نکردن برنامه hiddify next در مک بوک پرو m3pro

### ISSUE THREAD

**Issue by mobinmoji** [hiddify/hiddify-next#1037]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

۱- من برنامه hiddify رو در مک بوک خود نصب کردم و کانفیگ مربوطه که در پنل هیدیفای ساختم رو بهش دادم و پینگ هم گرفتم ولی وقتی میزنم اجرا بشه میزنه connected ولی کار نمیکنه 
مشکل از کانفیگ ها نیست چون همون کانفیگ ها در برنامه هیدیفای اندروید و همچنین داخل ویندوز و حتی داخل اپ v2box مک بوک کار میکنه ولی روی برنامه هیدیفای کار نمیکنه نمیدونم مشکل کجاست
۲- یه سوال دیگه هم دارم اونم این که برنامه برای ios چی بریزم که روش کار کنه ؟

### Minimal Reproducible Example (MRE)

برنامه نصب میشه 
کانفیگ ها روی بقیه برنامه ها کار میکنه 
ولی روی برنامه hiddify خود مک بوک کار نمیکنه

### Version

v1.5.2

### Platform/OS

macOS, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by amirsaam** [comment]
@mobinmoji if you have been able to join beta program of iOS, you can install it on M-series Mac through TestFlight.
If not, you can use Sing-Box app.
We will check connectivity on macOS version
