### ISSUE TITLE
Routing rule dont work

### ISSUE THREAD

**Issue by lifeindarkside** [hiddify/hiddify-next#104]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When i switch on routing rule (Ru), i try open 2ip.ru and web page don't opened. But 2ip.io is work.

windows 11
Hiddify Next (v0.10.0)

### Reproduce the Bug

run as admin

switch on TUN mode

switch routing rule to Russia

connect
go to 2ip.io
go to 2ip.ru

### Version

0.10.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Erquint** [comment]
Now 2ip.ru just isn't proxified at all! This isn't a solution.
Why did you close this issue without referencing a commit?
