### ISSUE TITLE
can't open e-mail in China

### ISSUE THREAD

**Issue by lichaoyangnice** [hiddify/hiddify-next#1040]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I open the Hiddify,choosing system proxy,I can't open any e-mail websites that they are Chineses website

### Minimal Reproducible Example (MRE)

1.open Hiddify,location is China; 2.chose system proxy  3.visit https://mail.qq.com/

### Expected Behavior

can easily visit the  websites

### Version

1.5.2

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
would you please set dns to some local dns ? if it resolve the issue so i can fix it.

**Comment by lichaoyangnice** [comment]
> would you please set dns to some local dns ? if it resolve the issue so i can fix it.

Yes,I set it the local DNS,but it doesn't work
![PixPin_2024-07-15_09-12-11](https://github.com/user-attachments/assets/27841e63-bd4a-4694-8fb6-4c403ac67d88)

**Comment by lichaoyangnice** [comment]
> would you please set dns to some local dns ? if it resolve the issue so i can fix it.

Finally，I got a solution，set the remote DNS as  China DNS 114.114.114.114，it works！Thank you！
