### ISSUE TITLE
اعمال نشدن ای پی تمیز برای وارپ

### ISSUE THREAD

**Issue by mgelioo** [hiddify/hiddify-next#1045]
### What Happened?

یه باگی که وجود داره در نسخه ۱.۵.۲ اعمال نشدن ای پی تمیزی هست که توی تنظیمات وارپ همراه با پورت باید گذاشته بشه.
![IMG_20240712_173107_595](https://github.com/user-attachments/assets/257f0814-1dee-40b8-b33f-1ab2f9ed4654)

![IMG_20240712_173113_550](https://github.com/user-attachments/assets/a1f644da-0aa1-4df5-b444-b52e2e40ec57)

تو این عکس ها مشخصه ای پی تمیزی که برای وارپ گذاشته شده روی اندپوینت کانفیگ وارپ نمیاد و خود اپ همچنان داره به صورت auto ای پی و پورت رو ست میکنه.

### Version

1.5.2

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
invalid

برای WOW همین ای پی بهتره
