### ISSUE TITLE
VPN Tethering

### ISSUE THREAD

**Issue by NoRRt** [hiddify/hiddify-next#1046]
### Feature description

سلام و خسته نباشید به تیم سازنده Hiddify. 

This app requires vpn Tethering .
VPN Tethering

For example :

An application uses this method  NetMod VPN Client (V2Ray/SSH)

https://play.google.com/store/apps/details?id=com.netmod.syna&hl=en

![photo_2024-07-11_21-41-46](https://github.com/dyhkwong/SagerNet/assets/4822035/fd52295f-8137-4a35-a39b-8686a4e8310b)

**Comment by hiddify-com** [comment]
PR Welcomed.
We can not do it now
