### ISSUE TITLE
Shadowsocks deeplinks doesn't work?

### ISSUE THREAD

**Issue by uprt** [hiddify/hiddify-next#105]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In #61 @problematicconsumer said that deeplink for various protocols should work, and I see "ss://" prefix in the app code.

However, when I try to import from the clipboard a URL like "ss://2022-blake3-aes-128-gcm:lRmEQBJPsr264h5AF5zXqA%3D%[3D@myhostname.com](mailto:3D@myhostname.com):555#MyServer", Hiddify-Next says:
![278800958-08171944-7078-43c0-987c-375ee8c2285d](https://github.com/hiddify/hiddify-next/assets/15909793/f45ddd48-a4ae-48ac-aebe-03fc5cd3196f)

### Reproduce the Bug

Generate Shadowsocks-2022 link with ss:// prefix, e.g. by exporting it from Nekobox.
Try to import this link through clipboard to Hiddify on Windows.

### Expected Behavior

It should add a new server.

### Version

the latest one, v0.10.0 (1000) [prod]

### Platform/OS

Windows

### Relevant log output

```shell
10:22:57.745981 - [W] ProfilesRepositoryImpl: error parsing config
10:22:57.985714 - [W] ProfilesNotifier: failed to add profile
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Thanks for your report,
it has been fixed and will be released in the next version

by the way, you can use base64 of (2022-blake3-aes-128-gcm:lRmEQBJPsr264h5AF5zXqA%3D%) at this time for fixing your issue
