### ISSUE TITLE
UI Lag and Connect Issue

### ISSUE THREAD

**Issue by KatashiMilton** [hiddify/hiddify-next#1056]
**Describe the bug**
UI is so much laggy and i can't connect to the Servers 

app and Box.log

[app.log](https://github.com/user-attachments/files/16217759/app.log)
[box.log](https://github.com/user-attachments/files/16217761/box.log)

![image](https://github.com/user-attachments/assets/e4256d6b-711f-4b22-bb0d-8584277f92d2)

**Desktop (please complete the following information):**
 - OS: Windows 10 2H22
 - Browser Chrome
 - Version Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by hiddify-com** [comment]
fixed
