### ISSUE TITLE
عدم کارکرد tls padding

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#1059]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با فعالسازی و وارد کردن مقادیر مختلف tls padding، باز هم کانفیگ های vless ws tls با تایم اوت مواجه اند در حالیکه با خاموش کردن این آپشن، کانفیگ ها متصل می شوند و پینگ دارند!

این مشکل محدود به ورژن خاص یا سیستم عامل خاصی نیست و در صورت امکان، آن را برطرف کنید.

### Minimal Reproducible Example (MRE)

.

### Version

1.6.3

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by FlashWins** [comment]
از نظر منطقی، کارکرد TLS Padding زمانیست که TLS Fragment خاموش باشد. احتمالا این دو گزینه رو در کنار یکدیگر فعال می کنید که با Timeout مواجه می شوید.
