### ISSUE TITLE
Hiddify Next on Linux can't detect newer version to update to the latest version

### ISSUE THREAD

**Issue by Hiiirad** [hiddify/hiddify-next#107]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I was alerted to the availability of an updated version of the application through the Google Play Store on my mobile device, but I did not receive any notifications regarding the update on my computer. Even when I attempted to manually update the application by navigating to the "About" section within the application, I encountered the following notification:

![Screenshot from 2023-10-29 21-41-16](https://github.com/hiddify/hiddify-next/assets/26739670/3d82a35c-62f8-4d4e-9cc9-ec731f62a683)

### Reproduce the Bug

1. Go to 'About'
2. Select 'Check for update'

### Expected Behavior

I expected the application to suggest a newer version, but it didn't happen.

### Version

v0.9.2

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Fixed
