### ISSUE TITLE
[FR]hiddify Built-in socks5 free node

### ISSUE THREAD

**Issue by jujubeja** [hiddify/hiddify-next#1079]
### Feature description

socks5 has millions of free nodes in various countries. 
https://github.com/search?q=proxylist&type=repositories&s=updated&o=desc
https://github.com/zloi-user/hideip.me
Subscription https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks5.txt

**Comment by hiddify-com** [comment]
create a repository with
socks://user:pass@ip:port#name
or 
socks://ip:port#name
