### ISSUE TITLE
Build error on github workflow

### ISSUE THREAD

**Issue by mrafieefard** [hiddify/hiddify-next#1080]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Unable to get Xcode project information:
 2024-07-1[8](https://github.com/mrafieefard/hiddify-next-ios-build/actions/runs/9995500914/job/27628109830#step:6:9) 17:01:12.842 xcodebuild[4562:29363] Writing error result bundle to /var/folders/6g/_ypptv3n2fs80_zc0xz8p1d40000gn/T/ResultBundle_2024-18-07_17-01-0012.xcresult
xcodebuild: error: Could not resolve package dependencies:
  local binary target 'Libcore' at '/Users/runner/work/hiddify-next-ios-build/hiddify-next-ios-build/ios/Frameworks/Libcore.xcframework' does not contain a binary artifact.
  fatalError

### Minimal Reproducible Example (MRE)

I want to make ios ipa for sideload but I don't have any knowledge for flutter ios build 
this is workflow link you can see what happened 
https://github.com/mrafieefard/hiddify-next-ios-build/actions/runs/9995500914/job/27628109830

### Version

1.7.0

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by amirsaam** [comment]
@mrafieefard you should run `make ios-temp-prepare` for the first time you wanna try to build, afterwards `make ios-prepare`.

**Comment by mrafieefard** [comment]
So it is possible to run it on github actions

**Comment by amirsaam** [comment]
@mrafieefard checkout hiddify own actions, yes.

**Comment by mrafieefard** [comment]
Great I will check it
