### ISSUE TITLE
TUN mode failed to start

### ISSUE THREAD

**Issue by robin98** [hiddify/hiddify-next#109]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

While trying to start the APP in TUN mode in windows 10, it'll be failed after showing the below error:
`initialize inbound/tun[tun-in]: configure tun interface: The device is not ready for use.`

### Reproduce the Bug

1. Run the program as administrator
2. Go to settings -> Config options -> Inbound options
3. Active `Enable TUN`, disable the `set system proxy`
4. Back to the `Home` and then click on the `Tap to connect`

### Expected Behavior

After some time, a message like this will pop-up:

`initialize inbound/tun[tun-in]: configure tun interface: The device is not ready for use.`

### Version

v 0.10.0

### Platform/OS

Windows

### Additional Context

![Capture](https://github.com/hiddify/hiddify-next/assets/22413785/aeb9200d-8d5d-41c6-bb64-5e9453e01d53)

 P.S: At this moment, TUN mode is not working with v2rayN or nekoray also.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by amin2plus** [comment]
باید run as administrator بزنی برای tunمود، گزینه direct DNS رو هم چک کن که مقدار local نباشه، مثلا میتونی 8.8.8.8 رو بنویسی جای local

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
