### ISSUE TITLE
Duplicate app instance

### ISSUE THREAD

**Issue by AMIRALITVK** [hiddify/hiddify-next#1095]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

On linux, if the app is already opened but the window is closed to tray by clicking on app icon it opens again in another instance.
![Screenshot from 2024-07-22 11-59-03](https://github.com/user-attachments/assets/9124a71c-0ab9-44c2-a9f7-1dd006de3bf6)
![Screenshot from 2024-07-22 11-59-14](https://github.com/user-attachments/assets/ca0c3e64-61d4-4c18-8937-a8c0ae386402)

### Minimal Reproducible Example (MRE)

1. Open the app, 2. Click on close button to close the app to tray, 3. Open new app by clicking on the app icon from apps list

### Version

v1.5.2

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by AmirhosseinBrooklyn** [comment]
This bug has happened to me a lot and this bug has been there since the old versions, especially when I click on Hiddify several times, this happens.

**Comment by amirsaam** [comment]
It's caused by installing/updating Hiddify by different installers (e.g. msix and exe)

**Comment by AMIRALITVK** [comment]
It's on linux so there is no msix and exe.

**Comment by amirsaam** [comment]
My bad.

**Comment by hiddify-com** [comment]
It is the problem of appimage. each app has its own dedicated place
