### ISSUE TITLE
change proxy mode to full vpn in windows

### ISSUE THREAD

**Issue by thezass** [hiddify/hiddify-next#11]
hi please add option  to change hiddify next windows  system proxy to full vpn in windows

**Comment by AmirHosseinCV** [comment]
That would be really good. SingBox supports this option by default, and I think it is easy to implement.
References:
1. [SingBox Tun Documentation](https://sing-box.sagernet.org/configuration/inbound/tun/)
2. [SingBox official example](https://sing-box.sagernet.org/examples/tun/)

**Comment by problematicconsumer** [comment]
Hiddify next already supports TUN mode provided by singbox. It's not enabled by default, though. To enable, go to settings > config options and toggle enable TUN switch. Keep in mind, TUN mode requires elevated privileges.

**Comment by problematicconsumer** [comment]
UX will get better overtime, thanks for your feedback.
