### ISSUE TITLE
[FR] اضافه شدن آیکون برنامه در لیست اپلیکیشن های اندروید تی وی

### ISSUE THREAD

**Issue by shahroozservices** [hiddify/hiddify-next#110]
### Feature description

سلام، هیدیفای نکست رو وقتی روی اندروید تی وی نصب میکنی، در بین اپلیکیشن ها آیکون نداره و باید از طریق لیست کلی برنامه های نصب شده بازش کرد که مسیر خیلی سختی داره - این مشکل روی هیدیفای اندرویدقدیمی نبود، امکانش بررسی و راهنمایی بفرمایید؟

**Comment by problematicconsumer** [comment]
This should be fixed
