### ISSUE TITLE
نسخه v1.9.0 مشکل داره

### ISSUE THREAD

**Issue by mark522412** [hiddify/hiddify-next#1104]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

این نسخه وصل میشه ولی مرورگر هیچی باز نمیکنه. نسخه کامپیوتر منظورمه

### Minimal Reproducible Example (MRE)

connection

### Version

v1.9.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by amirsaam** [comment]
@mark522412 
با ری‌استارت ویندوز، مشکل حل نشد؟

**Comment by amirsaam** [comment]
Duplicate of #1096
