### ISSUE TITLE
[FR] Request to add "block nodes" and "whitelist" functions

### ISSUE THREAD

**Issue by dunkeng** [hiddify/hiddify-next#1115]
### Feature description

Request to add "block nodes" and "whitelist" functions
1. The reason for 'blocking nodes' is that some service providers provide invalid nodes.
For example, nodes that are only used for advertising display and cannot be actually used often have relatively low latency, resulting in URLTest automatically selecting the wrong node.
2. The reason for the 'whitelist' is that some domain names are not included in the official rules.
For example, a website is located abroad, but it is necessary to determine whether the visitor's IP address is in China. If it is not in China, the content cannot be browsed.

**Comment by hiddify-com** [comment]
We will include more advanced routing soon

**Comment by nikpivkin** [comment]
@hiddify-com  Is there a issue for tracking? Why is it closed?

**Comment by hiddify-com** [comment]
this feature is under development
