### ISSUE TITLE
App incompatibility with Android TV [FR] 

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [hiddify/hiddify-next#112]
### Feature description

Hello dear Hiddify team, unfortunately the Android version of HiddifyNext is not fully compatible with Android TV, the app icon is not displayed in the list of apps and it is not compatible with the TV control. Please make it compatible and supportable with Android TV as well.

**Comment by saeeddarestany** [comment]
+1

**Comment by hiddify-com** [comment]
Please let me know the issues of the pre-release for android TV
https://github.com/hiddify/hiddify-next/releases/draft

**Comment by problematicconsumer** [comment]
This issue is fixed in [v0.12.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.12.0). There are still some issues when trying to navigate sidebar which will be resolved in future releases (since they're related to framework bugs)

**Comment by AmirhosseinBrooklyn** [comment]
Hi again, Yes the problems I reported above are mostly fixed and thank you for your follow up.
But the only problem is that you cannot enter the menus and settings of the program with the control, and you can only turn on/off VPN & enter Subscription section.

**Comment by itsaeed1** [comment]
Hi . please fix the menu problem. also the application is not available in Android TV Google Play
