### ISSUE TITLE
Creating muptiple instance of app

### ISSUE THREAD

**Issue by Jolymmiles** [hiddify/hiddify-next#1123]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When we close app and open it again they dont open alredy started, they open new copy of app
![image](https://github.com/user-attachments/assets/9579c3bf-d467-4518-96f7-0fbabc20677a)

### Minimal Reproducible Example (MRE)

1. Install app on Fedora 40
2. Open app
3. Close app
4. Open app again not from tray
5. Success

### Expected Behavior

Open already running app.

### Version

v1.9.0

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
no way to resolve with app image

**Comment by Jolymmiles** [comment]
i use rpm
