### ISSUE TITLE
Routing for RU doesnt work

### ISSUE THREAD

**Issue by Jolymmiles** [hiddify/hiddify-next#1124]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When we set to route Russian traffic into direct its doesnt work. I see config all is ok, but its doesnt working.

### Minimal Reproducible Example (MRE)

1. Choose ru.
![image](https://github.com/user-attachments/assets/b0054009-8093-43fb-9d43-0f7f2cc8fd62)
2. Go to https://yandex.ru/internet/ and check ip.

### Expected Behavior

Routing ru to direct

### Version

v1.9.0

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
please give a link to geosite-ru.srs so i can add it, otherwise you need to enable to resolve destination for that

**Comment by Jolymmiles** [comment]
> please give a link to geosite-ru.srs so i can add it, otherwise you need to enable to resolve destination for that

resolve destination doesnt work, if i turn on it, all broke

**Comment by Jolymmiles** [comment]
> please give a link to geosite-ru.srs so i can add it, otherwise you need to enable to resolve destination for that

https://github.com/SagerNet/sing-geoip/tree/rule-set
