### ISSUE TITLE
Even decrypting Hiddify IPA won't help because Hiddify uses Network Extension and it's only available for valid and paid developer accounts so it won't work if the IPA is decrypted (like every other VPN apps)

### ISSUE THREAD

**Issue by chelaxian** [hiddify/hiddify-next#1133]
Even decrypting Hiddify IPA won't help because Hiddify uses Network Extension and it's only available for valid and paid developer accounts so it won't work if the IPA is decrypted (like every other VPN apps)

_Originally posted by @amirsaam in https://github.com/hiddify/hiddify-next/issues/1029#issuecomment-2250956019_
            
            Yes, but for iOS <=17.0 we can have such a trick! 
            
            Someone:
            1. Install last version of TestFlight Hiddify.ipa
            2. Decrypt IPA without NetworkExtention
            
            Others:
            1. Install original Hiddify 1.1.1 or 1.3.3 dev ipa via TrollStore
            2. Force Install via Trollstore decrypted Testflight Hiddify ipa without NetworkExtension over old one. This trick will preserve NetworkExtension from old version and add all other from new version.

**Comment by amirsaam** [comment]
Build from source and do it, it will only make things complicated for Hiddify team and increases number of issues people asking for help about this.
Such processes are not for ordinary users and more for advanced ones.

**Comment by amirsaam** [comment]
More information here -> #1135
