### ISSUE TITLE
[v2.0.5] profiles

### ISSUE THREAD

**Issue by AmoAlireza** [hiddify/hiddify-next#1144]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

profiles does not load + can't add new profile
![1](https://github.com/user-attachments/assets/269e6047-f466-466f-b84e-54c7bc13a0cc)
![2](https://github.com/user-attachments/assets/9113f842-e579-4ba9-bb90-4ca4a5200bf6)

### Minimal Reproducible Example (MRE)

​

### Version

v2.0.5

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ha3anarab** [comment]
درود
من هم همین مشکل رو دارم
مسیر فایل دیتابیس کجاست؟ممنون میشم راهنمایی بفرمایید.

**Comment by AmoAlireza** [comment]
> درود من هم همین مشکل رو دارم مسیر فایل دیتابیس کجاست؟ممنون میشم راهنمایی بفرمایید.

`%AppData%\Roaming\Hiddify`
