### ISSUE TITLE
After installing the iOS Hiddify 2.0.5 signature, the app crashes when opened

### ISSUE THREAD

**Issue by bujieshi** [hiddify/hiddify-next#1155]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After installing the iOS Hiddify 2.0.5 signature, the app crashes when opened

### Minimal Reproducible Example (MRE)

After installing the iOS Hiddify 2.0.5 signature, the app crashes when opened

### Version

v2.0.5

### Platform/OS

iOS

### Additional Context

After installing the iOS Hiddify 2.0.5 signature, the app crashes when opened

### Application Config Options

```shell
After installing the iOS Hiddify 2.0.5 signature, the app crashes when opened
```

### Relevant log output

```shell
After installing the iOS Hiddify 2.0.5 signature, the app crashes when opened
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by liklaysh** [comment]
The same problem, make install true Sideloadly, run the app, it just blinks 1 time and closes.

**Comment by hiddify-com** [comment]
This app has two a group

**Comment by bujieshi** [comment]
> This app has two a group

How should I deal with it specifically?

**Comment by Ehsan-Ghazizadeh** [comment]
I have the same issue on IOS 18.1 beta. app crashes right after I run it.

**Comment by mrafieefard** [comment]
> This app has two a group

Why did you close this issue without clearing whats problem?

**Comment by bujieshi** [comment]
> > This app has two a group
> 
> Why did you close this issue without clearing whats problem?

The OP may think that for this kind of project with two groups, just delete one group! There won’t be any big problems.
