### ISSUE TITLE
[FR] Publish as flatpak on flathub

### ISSUE THREAD

**Issue by lumingzh** [hiddify/hiddify-next#117]
### Feature description

Publish as flatpak on flathub will be great for linux users, the users won't be need to take care of app updating anymore. Thank you.

**Comment by 3DRX** [comment]
The auto update by a package manager is great.

**Comment by ValentineMWAY** [comment]
up

**Comment by hiddify-com** [comment]
Thank you for your suggestion.
PR and easy guideline welcome

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
