### ISSUE TITLE
Hiddify not working at all

### ISSUE THREAD

**Issue by SaeedMostWanted** [hiddify/hiddify-next#1171]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Since version 2.0.5, the app stopped working. Apps gets connected, pings are ok, but no connection in apps like YouTube, Telegram, Instagram, . . .

### Minimal Reproducible Example (MRE)

1. Click on connect
2. Open any censored app

### Version

2.0.5

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Morrigan-Ship** [comment]
set tun mode to gvisor and test again

**Comment by SaeedMostWanted** [comment]
> set tun mode to gvisor and test again

Thank you. Problem solved

**Comment by Morrigan-Ship** [comment]
> Thank you. Problem solved
 this is a bug
will fix in next version
