### ISSUE TITLE
"Issues with Non-ASCII Domains in Versions After 1.1.1.1"

### ISSUE THREAD

**Issue by hamidkhoda77** [hiddify/hiddify-next#1205]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Dear Team,

I would like to inform you that starting from version 1.1.1, the conversion of domain addresses containing non-ASCII characters (such as A-Z, 0-9, and -) to ASCII is no longer supported. I have reported this issue several times, but unfortunately, the problem still persists.

Please kindly have your team look into this matter. I greatly appreciate your continuous efforts and cooperation.

Thank you very much.
![image](https://github.com/user-attachments/assets/74b31831-381c-4027-8543-2f63b0be0cec)
![image](https://github.com/user-attachments/assets/163dc99a-b035-45ca-9270-6454960d1506)

### Minimal Reproducible Example (MRE)

![image](https://github.com/user-attachments/assets/0ea6c9ad-450d-464c-9cc5-e446a8a1c3ee)
![image](https://github.com/user-attachments/assets/6be1d13f-042f-4481-a8aa-0c0f7015d917)

### Version

Versions after 1.1.1.1

### Platform/OS

Android, Windows, macOS, Linux, iOS

### Additional Context

![image](https://github.com/user-attachments/assets/1b91b924-6c1b-41d8-b681-3eae6b17c849)
![image](https://github.com/user-attachments/assets/d8748383-df66-451a-98a7-28d90b65f042)

### Application Config Options

```shell
{
  "region": "other",
  "block-ads": false,
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "udp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 12334,
  "tproxy-port": 12335,
  "local-dns-port": 16450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://connectivitycheck.gstatic.com/generate_204",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 16756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "rules": [],
  "mux": {
    "enable": false,
    "padding": false,
    "max-streams": 8,
    "protocol": "h2mux"
  },
  "tls-tricks": {
    "enable-fragment": false,
    "fragment-size": "10-30",
    "fragment-sleep": "2-8",
    "mixed-sni-case": false,
    "enable-padding": false,
    "padding-size": "1-1500"
  },
  "warp": {
    "enable": false,
    "mode": "proxy_over_warp",
    "wireguard-config": "",
    "license-key": "",
    "account-id": "",
    "access-token": "",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "1-3",
    "noise-size": "10-30",
    "noise-delay": "10-30",
    "noise-mode": "m6"
  },
  "warp2": {
    "enable": false,
    "mode": "proxy_over_warp",
    "wireguard-config": "",
    "license-key": "",
    "account-id": "",
    "access-token": "",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "1-3",
    "noise-size": "10-30",
    "noise-delay": "10-30",
    "noise-mode": "m6"
  }
}
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
i think it is not related to hiddify application

**Comment by hamidkhoda77** [comment]
Why is it 100% related to the Hiddify app

I reported this bug after two months of testing. It works on all apps except for the Hiddify app, which has the issue. Although few people use Chinese and Russian domains, you can still check it.
