### ISSUE TITLE
添加配置文件失败

### ISSUE THREAD

**Issue by wwwsajsaj** [hiddify/hiddify-next#1209]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![IMG_20240810_173823](https://github.com/user-attachments/assets/71a7e4eb-c5dc-464c-a47b-179848e4cc3e)

### Minimal Reproducible Example (MRE)

添加配置文件时出现

### Version

v0.14.20

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
use latest version
