### ISSUE TITLE
[feature] Publish in F-droid

### ISSUE THREAD

**Issue by Stu75e** [hiddify/hiddify-next#121]
How to submit to F-Droid: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.

**Comment by linsui** [comment]
I'm confused. Where will it be transformed to?

**Comment by Korb** [comment]
> Iymanjre moved this to Not Planned in `Multiplatform` on Jan 27, 2024

@lymanjre, what project exactly is this issue transformed into, which will only give to F-Droid (or a repository independent of it) permission to download your apk-releases to place them in its catalog?

**Comment by k0tran** [comment]
+1 for this feature. Would be better to have it there. What is the state of things now?

**Comment by DearFox** [comment]
Apparently they don't even plan to do this. 
so you shouldn't wait for that.
