### ISSUE TITLE
機場訂閱鏈接不支持trojan協議的節點的問題

### ISSUE THREAD

**Issue by forjustice** [hiddify/hiddify-next#122]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

訂閱鏈接訂閱後，trojan節點卻不顯示，存在bug。該問題已測試在android和windows中存在。

多謝。

### Reproduce the Bug

1. 安裝軟件
2. 訂閱
3. 打開開關

### Version

0.10.0

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Can you please share an example configuration?

**Comment by forjustice** [comment]
機場訂閱鏈接如下，當前是存在一個trojan節點和3個v2ray節點。多謝。
https://sub.gosakura.online/api/v1/client/subscribe?token=9d259bcc0e3df1d408411180f77290eb

**Comment by HumanMus1c** [comment]
Same, the Trojan proxy of subs can't be url-test  or connect.

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
