### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by AmirArsalanTaqavi** [hiddify/hiddify-next#1231]
### Feature description

Please add the ability to install the app from play store it says this app is not available on this device. it is hassle to install it with apk there
i think you just have to check the box in platforms section for android TV

**Comment by delshad1522** [comment]
Feature description
Please add the ability to install the app from play store it says this app is not available on this device. it is hassle to install it with apk there
i think you just have to check the box in platforms section for android TV

**Comment by hiddify-com** [comment]
added
