### ISSUE TITLE
iOS dev failed

### ISSUE THREAD

**Issue by zzzgydi** [hiddify/hiddify-next#124]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I tried to develop on iOS, but I encountered the following error.

### Reproduce the Bug

SingBoxPacketTunnel:
Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)

<img width="343" alt="image" src="https://github.com/hiddify/hiddify-next/assets/27361820/0dc6d6b3-865b-40de-98d9-f0fbcb8292b3">

### Version

https://github.com/hiddify/hiddify-next/commit/58002a2dffd9b8e9acf3a0aeb2da5d2966c50634

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Great to see you here.
it would be great to have you in our community. Would you please contact me at hiddify@gmail.com?

**Comment by zzzgydi** [comment]
@hiddify-com  Thank you for the invitation, but at the moment, I am focused on my own open-source project and prefer to continue working independently. I look forward to staying connected and potentially collaborating in the future.

**Comment by problematicconsumer** [comment]
@dadaWilliam use flutter version 3.13.x (3.13.9 recommended). You can use [puro](https://puro.dev/) to manage multiple versions of flutter if you need your current installation for other purposes.

**Comment by lymanjre** [comment]
The iOS version is released now. Pls be patient for next release

**Comment by developeranshul1986** [comment]
> The iOS version is released now. Pls be patient for next release

Can we run the code with different bundleid like our own bundleid? Please reply.
