### ISSUE TITLE
error in logs

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#125]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام ارور های زیر در لاگ رو بررسی کنید 

ERROR [1429643179 452ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:2577: reality verification

ERROR dns: exchange failed for ipv4only.arpa. IN A: reality verification failed

ERROR[209265717 5.9s] outbound/urltest[Auto]: context deadline exceeded

ERROR[2088869791 4.8s] inbound/tun[tun-in]: download: write tcp4 172.19.0.1:6508->172.19.0.2:10001: wsasend: An established connection was aborted by the software in your host machine.

### Reproduce the Bug

see error

### Version

0.10

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.

**Comment by 3mehdi** [comment]
> لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.

حل نشده من ورژن اخر دانلود کردم و همچنان این خطا دارم 
[box.log](https://github.com/hiddify/hiddify-next/files/14554100/box.log)

**Comment by Dr-Dev** [comment]
same here
ver 1.1.1
![errors screenshot](https://github.com/hiddify/hiddify-next/assets/18067143/a9b1151f-decf-493f-a5cb-ca9e0b8dedb4)

**Comment by nikto-b** [comment]
Same issue on some windows machines

**Comment by Angry-binky** [comment]
The same error there is a solution has been to disable the firewall did not help. Is there a solution to the problem?

**Comment by arfffus** [comment]
Seems that last version (2.2.0) doesn't work. I've got success with previous one (2.0.5)

**Comment by Vasysik** [comment]
Same problem on Windows 11 with Hiddify 2.1.1 from Microsoft Store

**Comment by ergodeath** [comment]
I fixed it by selecting “Config Options -> Inbound Options -> Service Mode -> VPN (Experimental)”
