### ISSUE TITLE
[FR] add gfw_resist_tls_proxy

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#126]
### Feature description

سلام وقت بخیر 
پیشنهادی دارم من از اسکریپت یکی از دوستان در گیت هاب دارم استفاده میکنم که ادرسشو میذارم 

https://github.com/GFW-knocker/gfw_resist_HTTPS_proxy

این میاد پکت های ارسالی رو هم تاخیر میذاره بینشون هم تقسیم میکنه که عملا من هر وقت این اسکریپت رو اجرا کردم مشکل ایپی کثیف بکل رفع شد 
امکان داره این قابلیت تقسیم و تاخیر بین پکت های ارسالی رو به اپلیکیشن اضافه کنید ؟

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
