### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#127]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

تو اپ هنگامی که محیط برنامه رو فارسی میکنی 
زمانی که ماوس هاور میشه یه مستطیل ردیوس خورده اون گوشه میفته این رو درست کنید بی زحمت 
تو تصویر واضح هست

![1](https://github.com/hiddify/hiddify-next/assets/26691872/7f8bfb78-767c-48b9-982e-1b03fb3f1142)

### Reproduce the Bug

ui bug

### Version

0.10

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
این [ایراد از فریم‌ورک](https://github.com/flutter/flutter/issues/130718) هست که برطرف میشه در ورژن‌های بعدی
