### ISSUE TITLE
[FR] no change name user in app after change in panel

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#129]
### Feature description

سلام خسته نباشید 
نام کاربر بعد از تغییر نام در پنل داخل اپلیکیشن بروز نمیشه
پیشنهاد میشه این قابلیت رو هم اضافه کنید

**Comment by lymanjre** [comment]
لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.
