### ISSUE TITLE
قابلیت پروکسی چین

### ISSUE THREAD

**Issue by hosseinbaghi** [hiddify/hiddify-next#13]
سلام خسته نباشید با اپ خفنتون
لطفا اگ امکانش هست قابلیت پروکسی چین هم اضافه کنید
مثلا ابتدا به کانفیگ خود و بعد به وایرگارد وارپ
خیلی ممنون

**Comment by hiddify-com** [comment]
توی ورژن 2 احتمالا همچین چیزی اضافه بشه

**Comment by lymanjre** [comment]
این ایشو برای پیگیری منتقل شد. فعلا بسته میشود
