### ISSUE TITLE
[FR] اضافه کردن پرچم کشور های مختلف و ای پی

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#131]
### Feature description

سلام خسته نباشید

پیشنهاد میشه بر اساس کانفیگ تو ظاهر کاربری کاربر پرچم کشور و آی پی کشور رو نشون بده

**Comment by lymanjre** [comment]
این قابلیت وجود دارده کافیه ایموجی های پرچم را توی کانفیگ استفاده کنید

**Comment by HassanMohammadi** [comment]
نه بر اساس ای پی خود برنامه پرچم قرار بده بالای اطلاعات کاربر نه بخش پروکسی ها
