### ISSUE TITLE
[FR] قابلیت اپدیت اتومات در اپ

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#132]
### Feature description

سلام خسته نباشید 
امکان اپدیت بطور اتومات در اپ رو پیشنهاد میشه اضافه کنید که خود اپ اپدیت جدید را دریافت کنه و کاربر نیاز به دانلود آن نباشه 
چون در پلی استور اصلا نسخه بروز هم بیاد نمیزنه باید بروز شود بجای update  همون open  نشان داده میشه دلیلش رو شما بهتر میدونید

**Comment by problematicconsumer** [comment]
چک آپدیت خودکار از طریق گوگل پلی به اپ اضافه شده و برای بقیه پلتفورم‌ها هم بهبود داشته
