### ISSUE TITLE
ناپایدار بودن اتصال

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/hiddify-next#133]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در اپلیکیش موردی وجود داره که باگ بزرگی بحساب میاد 
شما وقتی چند مدل تلگرام روی گوشی داری داخل بعضی از آن ها اتصال صورت نمیگیره تنها راه حلش فعال سازی پروکسی و دادن 127.0.0.1  هست تا اتصال برقرار شود در صورتی که نکو باکس این مشکل رو نداره 
دوم ناپایداری در اتصال هست مثلا اگر با هیدیفای نکست متصل بشی قطعی ها واضح نشون داده میشه چه هنگام استفاده از یوتیوب چه تلگرام یهو قط و وصل میشه 
اما نکو باکس خیر 
امیدوارم این باگ حیاتی رفع بشه البته تو نسخه 0.5 این مشکل نیست بازم چک کنید

### Reproduce the Bug

connecting .....

### Version

0.10

### Platform/OS

Android, Windows, macOS, Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.
