### ISSUE TITLE
After switching nodes, nekogram may not be able to quickly connect to the network.

### ISSUE THREAD

**Issue by huajizhige** [hiddify/hiddify-next#134]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

There is a chance that nekogram will keep prompting about connecting when switching apps or nodes or taking a slightly longer time.

### Reproduce the Bug

1.Open hiddify next
 2. Connect nodes
 3.Open nekogram
 4. Switch nodes
 5.Return nekogram

### Version

v0.10.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
