### ISSUE TITLE
initialize inbound/mixed[mixed-in]: set system proxy: set system proxy: unable to set as root))

### ISSUE THREAD

**Issue by 480840342** [hiddify/hiddify-next#136]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

initialize inbound/mixed[mixed-in]: set system proxy: set system proxy: unable to set as root))

### Reproduce the Bug

initialize inbound/mixed[mixed-in]: set system proxy: set system proxy: unable to set as root))

### Expected Behavior

initialize inbound/mixed[mixed-in]: set system proxy: set system proxy: unable to set as root))

### Version

v0.10.0

### Platform/OS

Linux

### Additional Context

initialize inbound/mixed[mixed-in]: set system proxy: set system proxy: unable to set as root))

### Relevant log output

```shell
initialize inbound/mixed[mixed-in]: set system proxy: set system proxy: unable to set as root))
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
