### ISSUE TITLE
Error running app on linux

### ISSUE THREAD

**Issue by Shjpr9** [hiddify/hiddify-next#1365]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After trying to turn on the vpn service this error happened.

### Minimal Reproducible Example (MRE)

1. Add your subscription link
2. Turn on the vpn

### Version

 v2.5.0 Pre-release

### Platform/OS

Linux

### Additional Context

System Information
![System Information](https://github.com/user-attachments/assets/fee3eb45-2a57-4f5d-b957-6b69dc7615c7)

Hiddify error
![Hiddify error](https://github.com/user-attachments/assets/52d77a46-dea5-4d91-902e-a93cd4729fa9)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
fixed
