### ISSUE TITLE
App crashes on Android

### ISSUE THREAD

**Issue by Space-00** [hiddify/hiddify-next#1366]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The latest version which is 2.5.0 crashes as soon as I open it on android, I tested it on several android phones and it crashed on all of them

### Minimal Reproducible Example (MRE)

Test it on android, I tried it on Samsung and Xiaomi phones

### Version

2.5.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
fixed
