### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by soshin1337** [hiddify/hiddify-next#1380]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/user-attachments/assets/61e2c7e5-a4f3-48ab-b085-5f19c226296b)

### Minimal Reproducible Example (MRE)

![image](https://github.com/user-attachments/assets/5de3e629-dbfa-4fc7-8997-b571c84bb7b5)

### Version

2.5.6

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Esk0S** [comment]
Same problem. Try downloading previous version
