### ISSUE TITLE
WARP connecting unexpected error

### ISSUE THREAD

**Issue by Jusxern** [hiddify/hiddify-next#1389]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I got an error "error patching outbound[m4 § 0][custom]: netip.ParsePrefix("/24"):ParseAddr(""): unable to parse IP"

### Minimal Reproducible Example (MRE)

1. Added WARP profile
2. Connect
3. Got an error

### Expected Behavior

Connect to profile

### Version

v2.0.5

### Platform/OS

Windows

### Additional Context

Works great on my phone
Found [This issue](https://github.com/hiddify/hiddify-next/issues/1157) but it doesn't work

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Jusxern** [comment]
Got the same issue

**Comment by MrDrone-ru** [comment]
> error patching outbound

Hey guys, I think I've found the solution.
It is possible that your ISP can detect and block the Wire Guard protocol, which is what is used for WARP (at least to obtain the private key). And without configuration, warp will not work on any version of the program.
To check this, you can download the official Cloudflare WARP client and go to the Connectivity section, or simply go to Config options (Hiddify) and click Generate warp config - if so, you will see an error. (And if you copy all the settings to the clipboard and paste it into Notepad, there will be a parameter wireguard-config : "")
The solution is simple - to generate the config, temporarily connect a VPN))
My tun and TLS fragment parameters can also help, you can import them through the three dots at the top right in Config options.
`{
  "region": "ru",
  "block-ads": false,
  "use-xray-core-when-possible": false,
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "udp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 12334,
  "tproxy-port": 12335,
  "local-dns-port": 16450,
  "tun-implementation": "gvisor",
  "mtu": 9000,
  "strict-route": false,
  "connection-test-url": "http://connectivitycheck.gstatic.com/generate_204",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 16756,
  "enable-tun": false,
  "enable-tun-service": false,
  "set-system-proxy": true,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "rules": [],
  "mux": {
    "enable": false,
    "padding": false,
    "max-streams": 8,
    "protocol": "h2mux"
  },
  "tls-tricks": {
    "enable-fragment": true,
    "fragment-size": "10-22",
    "fragment-sleep": "2-8",
    "mixed-sni-case": false,
    "enable-padding": false,
    "padding-size": "1-1500"
  },
  "warp": {
    "enable": true,
    "mode": "proxy_over_warp",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "2-5",
    "noise-size": "32-96",
    "noise-delay": "20-70",
    "noise-mode": "m4"
  },
  "warp2": {
    "enable": true,
    "mode": "proxy_over_warp",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "2-5",
    "noise-size": "32-96",
    "noise-delay": "20-70",
    "noise-mode": "m4"
  }
}`

**Comment by Jusxern** [comment]
I did managed to fix the problem somehow.

**Comment by VFVF12345** [comment]
всем привет, пожалуйста, помогите мне устранить ошибку исправления error patching outbound[m4 5 0][custom]:
ParseAddr(""): unable to parse IP
![Screenshot_1](https://github.com/user-attachments/assets/f67876f9-82fd-48a0-8c47-bd2cb8a20d61)

**Comment by AndyAwesomee** [comment]
> всем привет, пожалуйста, помогите мне устранить ошибку исправления error patching outbound[m4 5 0][custom]: ParseAddr(""): unable to parse IP ![Screenshot_1](https://private-user-images.githubusercontent.com/126675553/380486333-f67876f9-82fd-48a0-8c47-bd2cb8a20d61.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MTQ1MjcsIm5iZiI6MTczMTcxNDIyNywicGF0aCI6Ii8xMjY2NzU1NTMvMzgwNDg2MzMzLWY2Nzg3NmY5LTgyZmQtNDhhMC04YzQ3LWJkMmNiOGEyMGQ2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQyMzQzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDlkYjY1ZmFlODllNmIyZDE3MjdlZWQyOWU3ZDdlNzJkNGYyMjI2MDdlN2NmYjliYWViNzkxZGY3NTJlYzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LaHpFzEDn8j0WcXQJcnQI8PeLtz3JGEvp7W99kV-Py8)

Выше чел написал же, нужно подключить любой рабочий впн и сгенерировать конфиг warp, в параметрах конфигурации
![Screenshot 2024-11-14 131235](https://github.com/user-attachments/assets/0f6c5528-bbb3-4747-981d-1199a22fd9a7)

**Comment by Alex312-cmd** [comment]
сделал всё как было выше упомянуто, но у меня появилась другая проблема пишет тайм-аут
