### ISSUE TITLE
socks5 prompts invalid URL

### ISSUE THREAD

**Issue by huajizhige** [hiddify/hiddify-next#139]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Adding subscription link from clipboard prompts invalid URL

### Reproduce the Bug

socks5://5bd30k1bbi0b7bb95bna223ed6ah02b537d06e79:5bd30k1bbi0b7bb95bna223ed6ah02b537d06e79@120.232.177.251:32000#IEPL-GuangZhou-ShangHai-JaPan-1000Mbps    

### Version

v0.10.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
