### ISSUE TITLE
The program does not open

### ISSUE THREAD

**Issue by Afx110** [hiddify/hiddify-next#14]
![Screenshot 2023-10-02 at 4 18 39 AM](https://github.com/hiddify/hiddify-next/assets/89361446/d665a4de-6e02-43e3-99f9-cda78619fd19)

**Comment by lymanjre** [comment]
Please check this article[This article ](https://github.com/hiddify/Hiddify-Server/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%DA%A9%D8%A7%D8%B1-%D8%A8%D8%A7-%D9%86%D8%B1%D9%85%E2%80%8C%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%D9%87%DB%8C%D8%AF%DB%8C%D9%81%D8%A7%DB%8C%E2%80%8C%D9%86%DA%A9%D8%B3%D8%AA)  in persian
