### ISSUE TITLE
The problem of running the software on Wayland compositor

### ISSUE THREAD

**Issue by nooob-developer** [hiddify/hiddify-next#141]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

I tried running the hiddify application on Sway WM (Wayland compositior) and received critical errors like "Failed to create GL context" that prevent the app from launching properly.

It seems hiddify is designed for Xorg and does not have full compatibility with Wayland compositors like Sway yet.

I would suggest adding support for Wayland backends like wlroots to allow hiddify to work nicely on Sway and other Wayland desktop environments. This would fix the graphical context creation issues for many users who are on Wayland.

### Reproduce the Bug

Running the program in Wayland compositor

### Expected Behavior

![hiddify](https://github.com/hiddify/hiddify-next/assets/87908673/e5b8f354-51f4-476e-9ac4-0007ef9f48b4)

### Version

v.0.10.0

### Platform/OS

Linux

### Relevant log output

```shell
(hiddify:2208): Gdk-CRITICAL **: 12:12:56.818: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (hiddify:2208): WARNING **: 12:12:56.876: Failed to start Flutter renderer: Unable to create a GL context
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ValentineMWAY** [comment]
same

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
