### ISSUE TITLE
[FR] I need ARM Windows version hiddify.

### ISSUE THREAD

**Issue by dancewithyourghost** [hiddify/hiddify-next#142]
### Feature description

I'm using a Xiaomi Book S which equiped a Snapdragon 8cx gen 2 CPU. Although x86-64 version Hiddify can run on my tablet, it doesn't work very well. It runs slow and requests more computer CPU and RAM. I hope you can compile a ARM version hiddify. Thankyou.

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
