### ISSUE TITLE
Execution failed for task ':app:compileDebugKotlin'.

### ISSUE THREAD

**Issue by GalenBlabla** [hiddify/hiddify-next#1423]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I compiled the Android version 2.5.7, I encountered this problem. There was no issue with make android-prepare, but when I ran flutter run or flutter build app --release, this error occurred. I checked that libcore was properly downloaded and placed in the android/app/libs directory. Previously, there were no issues with packaging. Git Actions also failed to package correctly. I tried rolling back to version 2.3.1, but the same error occurred.

### Minimal Reproducible Example (MRE)

ubuntu22.04 & git actions & windows 11 
```git clone hiddify repo```
```cd repo```
```make android-prepare ```
```flutter run ( or flutter build apk)```

### Version

v2.5.7\v2.3.1

### Platform/OS

Linux

### Additional Context

![2024-10-20 00 10 29](https://github.com/user-attachments/assets/8be4a56e-18f6-4de2-921e-43465c1a5e8a)
<img width="1403" alt="截屏2024-10-20 00 30 18" src="https://github.com/user-attachments/assets/54790688-285c-451d-9973-43e9121b34f2">

### Application Config Options

```shell
I use the Chinese mainland Gradle source ,I am surely that can be successful build before.
# distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-bin.zip
distributionUrl=https://mirrors.cloud.tencent.com/gradle/gradle-7.6.1-bin.zip```
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by Mronezc** [comment]
the compilation has been confusing me, bro, have you solved it?
