### ISSUE TITLE
MacOs: cannot start Vless connection

### ISSUE THREAD

**Issue by eLukianenko** [hiddify/hiddify-next#143]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

MacOs 14.1:  I added via clipboard vless-grpc config (which I successfully use on Android version of Hiddify-next 0.10.0) and after click on "Tap on connect" I am getting this error:
<img width="561" alt="Screenshot 2023-11-08 at 15 22 56" src="https://github.com/hiddify/hiddify-next/assets/4410391/838ac643-f500-4859-8853-062f31d68a3e">

### Reproduce the Bug

1. Add via clipboard new vless-grpc config
2. Click on "Tap on connect"

### Version

0.10.0

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
