### ISSUE TITLE
[FR] اضافه کردن ارتباط از شبکه محلی

### ISSUE THREAD

**Issue by nasrdev0** [hiddify/hiddify-next#144]
### Feature description

تو اپ های قبلی میشد از طریق شبکه محلی و پروکسی socks5 / http اجازه وصل شدن بقیه رو داد
ممنون میشم رو نکست هم بذاریدش
Allow Connections From LAN

**Comment by armagg** [comment]
این خیلی خیلی فیچر لازمی. 
تعداد کانکشن هارو هم کم میکنه
همه افراد توی خونه میتونن با یه کانکشن خیلی راحت وصل بشن

**Comment by problematicconsumer** [comment]
Added in [v0.13.3.dev](https://github.com/hiddify/hiddify-next/releases/tag/v0.13.3.dev).

**Comment by armagg** [comment]
ممنون ازت.
 خوش حال میشم اگه در دولوپمنت برای قسمت از پروژه به کمک نیاز داشتین به پروژه اضافه بشم

**Comment by problematicconsumer** [comment]
حتما [اطلاعات تماس](https://github.com/hiddify/hiddify-next#collaboration-and-contact-information) هست خوشحال میشیم کمک کنی
