### ISSUE TITLE
[FR] Bypass LAN

### ISSUE THREAD

**Issue by i5g5vip** [hiddify/hiddify-next#146]
### Feature description

It would be perfect if it could provide bypass LAN function！！！

**Comment by istek** [comment]
yeah1, plz support bypass the local network.

**Comment by realartin** [comment]
موافقم واقعا بهش نیاز هست

**Comment by problematicconsumer** [comment]
Added in [v0.13.3.dev](https://github.com/hiddify/hiddify-next/releases/tag/v0.13.3.dev).

**Comment by realartin** [comment]
cool 😎

**Comment by realartin** [comment]
check this out "https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md"
