### ISSUE TITLE
[FR] support for links whose content is base64

### ISSUE THREAD

**Issue by biqiguhexuenai** [hiddify/hiddify-next#147]
### Feature description

I hope to support for links whose content is base64.

**Comment by biqiguhexuenai** [comment]
Like this...
https://xn--mes91r2ng7p4a.com/api/v1/client/subscribe?token=c6f1482e32bfe6432d94a4b2c26d3e58

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
