### ISSUE TITLE
black screen v1.6.0 to v2.5.7

### ISSUE THREAD

**Issue by wyxfsj** [hiddify/hiddify-next#1472]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The black screen problem has not been fixed version 1.6.0--2.5.7 
and the installation version also has the same problem

### Minimal Reproducible Example (MRE)

just open the program

### Version

v1.6.0 to v2.5.7

### Platform/OS

Windows

### Additional Context

windows 10 TLSC
core i3 2120
gforce 9800GT

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lufog** [comment]
@wyxfsj as a temporary solution, until the official version with a fix is ​​released, you can use: https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2473144601
