### ISSUE TITLE
قطع شدن اتصال ریلیتی 

### ISSUE THREAD

**Issue by yasbija** [hiddify/hiddify-next#148]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با سلام خیلی ممنون از اپ خوبتون.یه مسئله ای که باهاش برخوردم اینه که اتصال بعد مدتی قطع میشه و باید از داخل اپ اتصال رو خاموش و روشن کنی تا دوباره کانفیگ وصل شه یعنی در واقع ناپایداری در اتصال وجود داره .با تشکر

### Reproduce the Bug

به یه کانفیگ‌ متصل باشین تو محیط تلگرام بعد مدتی روی کانتینگ میرید.

### Version

0.10.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.
