### ISSUE TITLE
خطا هنگام اضافه کردین لینک سابسکریپشن به برنامه 

### ISSUE THREAD

**Issue by yasbija** [hiddify/hiddify-next#149]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

با سلام الان برای یکی میخواستیم نصب کنیم لینک ساب اضافه نمیشه همه چی هم ظاهرا اوکیه و خود لینک تو مرورگر باز میشه و اوکیه  و تو v2rayng آپدیت میشه، به نظرتون مشکل از چیست

### Reproduce the Bug

![IMG_20231110_101918_458](https://github.com/hiddify/hiddify-next/assets/141263484/d0a9d4a0-d1a9-4e4f-956e-9721d665ef24)

### Version

0.10.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
مشکل از اتصال اینترنت هست. با تغییر اینترنت/vpn مجدد تست کنید.
