### ISSUE TITLE
Service startup error [An attempt was made to access a socket in a way forbidden by its access permissions.]

### ISSUE THREAD

**Issue by HumanMus1c** [hiddify/hiddify-next#151]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Service startup error

initialize inbound/direct[dns-in]: listen tcp 127.0.0.1: 6450: bind:An attempt was made to access a socket in a way forbidden by its access permissions.

log file:
[app.log](https://github.com/hiddify/hiddify-next/files/13319001/app.log)
[box.log](https://github.com/hiddify/hiddify-next/files/13319003/box.log)

### Reproduce the Bug

1.start up the program.
2. choose one profile.
3. click "Tap to Connect"
4. an alert pop up:  Service startup error initialize inbound/direct[dns-in]: listen top 127.0.0.1: 6450: bind: An
attempt was made to access a socket in a way forbidden by its
access permissions.

### Expected Behavior

Click "Tap to Connect" should successfully start the service.

### Version

0.10.7 dev

### Platform/OS

Windows

### Relevant log output

```shell
Pasted in "What Happened?" description.
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jepbura** [comment]
I also had this problem before.
To solve this problem, go to the following path:
settings > config options > Mixed port
Then the port from 2323, change it to something else, for example 10808.

**Comment by wangxiaoyan369** [comment]
> I also had this problem before. To solve this problem, go to the following path: settings > config options > Mixed port Then the port from 2323, change it to something else, for example 10808.

not work
