### ISSUE TITLE
[FR] Custom routing rules like Clash Verge / 像 Clash Verge 一样的自定义路由规则

### ISSUE THREAD

**Issue by d0j1a1701** [hiddify/hiddify-next#152]
### Feature description

Sing-Box 有着和 Clash 类似的强大路由功能，已经有人为 Sing-Box 打造了 Clash.Meta 规则转换器（参见 https://github.com/xmdhs/clash2singbox）。我希望 Hiddify 能加入像 Clash Verge 一样的强大路由规则配置页面。

---

Sing-Box has powerful routing capabilities similar to Clash. Someone has already created a Clash.Meta rule converter for Sing-Box (see https://github.com/xmdhs/clash2singbox). I hope Hiddify can add a powerful routing rule configuration page like Clash Verge.

**Comment by problematicconsumer** [comment]
We already support some basic region based routing rules. Custom rules will come soon. But since rule providers are not supported in sing-box it's hard to imagine a one to one with clash configs. In fact, we already use clash2singbox to map outbounds.
