### ISSUE TITLE
After using the system's built-in VPN to shut down the Android version, hiddify still shows that the service is running.

### ISSUE THREAD

**Issue by huajizhige** [hiddify/hiddify-next#153]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

As title

### Reproduce the Bug

1.Connect to the proxy
2.Open the activated VPN prompted by the system in the notification bar
3.Click Disconnect 
4. Successfully reproduce the problem

### Version

v0.10.7dev

### Platform/OS

Android

### Additional Context

![Screenshot_2023-11-11-02-25-36-18_b783bf344239542886fee7b48fa4b892](https://github.com/hiddify/hiddify-next/assets/120686495/2de30121-868b-4239-88e7-a738987f6d06)
![Screenshot_2023-11-11-02-26-38-45_41a74ddf68be21faad2fbbb691b15143](https://github.com/hiddify/hiddify-next/assets/120686495/0f0b1c67-a846-4472-a46c-36059519c8f9)
![Screenshot_2023-11-11-02-26-19-77_dd661fbf574bc01712a840b6c315ea7e](https://github.com/hiddify/hiddify-next/assets/120686495/48295151-e4f3-4b84-a129-002038d3bd85)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
This issue is already [fixed](https://github.com/hiddify/hiddify-next/commit/9bea38f605b401a56d232dd8763118566fcfe5dd) and will be included in next release
