### ISSUE TITLE
مشکل اجرا نشدن در ویندوز 7

### ISSUE THREAD

**Issue by Victor1368** [hiddify/hiddify-next#154]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

میدونم پیشنهاد دادید تا روی ویندوز 10 و 11 نصب کنیم ولی خواستم ببینم کسی تونسته راهی برای اجرا در ویندوز 7 پیدا کنه؟

بعداز نصب برنامه در ویندوز 7 ارور api-ms-win--core-rtlsupport-l1-2-0.dll مواجه میشم
با برنامه هایی تعمییر dll و جاگذاری dll های مختلف و نصب ++C هم مشکل برطرف نشد
روی چندتا ویندوز 7 امتحان کردم و همچنین چند نسخه از هیدیفای نکس + پورتابل هم تست کردم

اگه کسی میدونه مشکل از کجاست لطفا راهنمایی کنه

### Reproduce the Bug

 api-ms-win--core-rtlsupport-l1-2-0.dll

### Version

all

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by sbh96** [comment]
در ویندوز 8.1هم این خطا رو داریم

**Comment by lymanjre** [comment]
مقاله مربوط به نصب را مطالعه کنید. پیش نیازهای گفته شده را نصب نمایید.
