### ISSUE TITLE
Service Startup error

### ISSUE THREAD

**Issue by paingchan** [hiddify/hiddify-next#156]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Service startup error
initialize inbound/mixed[mixed-in]: set system proxy: execute (Jusr/ sbin/networksetup) networksetup -setsocksfirewallproxy Wi-Fi
127.0.0.1 2334: exit status 14

### Reproduce the Bug

when start connect button show this error msg ( initialize inbound/mixed[mixed-in]: set system proxy: execute (Jusr/ sbin/networksetup) networksetup -setsocksfirewallproxy Wi-Fi
127.0.0.1 2334: exit status 14  )

### Version

0.10.0

### Platform/OS

macOS

### Relevant log output

```shell
ERROR2023-11-12 15:31:41.000outbound/shadowsocks[sub.example.com tls faketls direct ss § 443 3]: parse outbound[18]<nil>error: unknown obfs mode tls&obfs-host=mask-api.icloud.com
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
