### ISSUE TITLE
[FR] DNS over HTTPS and DNS over TLS

### ISSUE THREAD

**Issue by Nobelium7** [hiddify/hiddify-next#158]
### Feature description

Add supports for DNS over HTTPS and DNS over TLS in the DNS settings for security and privacy reason to encrypt the DNS. In Hiddify Next Android app.

So that we could use secure DNS resolver. This is to enhance user privacy.

(I have test the 0.10.0 alredy but DNS still leak to other resolver such as OpenDNS or Google, but I would like to only use the DNS resolver which I enter in the settings, this maybe from a remote server side push resolver)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
