### ISSUE TITLE
[FR] جلوگیری از آیپی لیک

### ISSUE THREAD

**Issue by amin2plus** [hiddify/hiddify-next#159]
### Feature description

زمانی که لینک های ساباسکریپشن دارند آپدیت میشوند: 

هایدیفای کانکشن vpn رو قطع میکنه، پروفایل ها رو آپدیت میکنه و بعد مجدد کانکشن رو برقرار میکنه، 

درسته که فقط یک یا چند ثانیه هست ولی خب برنامه هایی که وصل هستند اون لحظه میتونن برای همون چند ثانیه آیپی واقعی رو ببینند و برای افرادی که لینک های پروفایل زیادی دارند این زمان بیشتر هم هست.

میشه کاری کنید که زمانی که پروفایل ها دارند آپدیت میشن نت کل دستگاه قطع بشه به جز خود هایدیفای؟
یا اینکه مثل nekobox/ray گزینه بذارین که با همون اتصال برقرار پروفایل آپدیت کنه؟
چون خود لینک پروفایل https هست چک کردنش آیپی لیک نخواهد داد فقط اینکه توی اون لحظه باقی برنامه ها اتصالشون برقراره مشکل ساز هست

![image](https://github.com/hiddify/hiddify-next/assets/31206022/98b3a2c6-d4bb-4b52-b6fc-d98c23ebc613)

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
