### ISSUE TITLE
امکان مشاهده نام کانفیگ یا لینک ساب در کنترل سنتر اعلان ها

### ISSUE THREAD

**Issue by aref199** [hiddify/hiddify-next#160]
### Feature description

سلام درصورت امکان در قسمت کنترل سنتر یا همان اعلان ها امکان مشاهده نام کانفیگ یا لینک ساب با سرعت لحظه ای اتصال باشه.

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
