### ISSUE TITLE
مصرف غیر متعارف اینترنت

### ISSUE THREAD

**Issue by freeinternetaccess** [hiddify/hiddify-next#17]
در حد بالایی اینترنت مصرف میکنه

**Comment by saaliazar** [comment]
آره منم چک کردم مصرف خیلی بالایی داره غیر از اونی که خودت مصرف میکنی

**Comment by saaliazar** [comment]
مجبور شدم حذف کنم، دو تا بسته 5 گیگ فوری تموم شد
