### ISSUE TITLE
زمان آپدیت خودکار به صورت دقیقه یا عدد اعشار(دابل)

### ISSUE THREAD

**Issue by rashedheydari2001** [hiddify/hiddify-next#170]
### Feature description

آقا این آپدیت خودکار رو روی دقیقه بزارید یا روی عدد دابل 1 ساعت برای ایران شوخیه سرور ها زود از کار میفتن

**Comment by DrAmirB** [comment]
ریسک فیلتر شدن لینک ساب با آپدیتای مکرر زیاد میشه
