### ISSUE TITLE
Doesn't start on boot "Run this program as an administrator"

### ISSUE THREAD

**Issue by thejianyu** [hiddify/hiddify-next#171]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Dear Hiddify Team,

I hope this message finds you well. I wanted to bring to your attention an issue I encountered with your software. In an attempt to streamline the use of the TUN mode, I opted to enable the "Run this program as an administrator" option in the compatibility tab within the software's properties.

Unfortunately, this adjustment has resulted in an unintended consequence—Hiddify no longer initiates automatically during Windows startup. I'd like to highlight another software, "Nekoray," which handles its TUN mode differently. In Nekoray, the TUN mode prompts the user for administrator access after activation, offering a more seamless user experience.

I kindly suggest considering a similar implementation for Hiddify's TUN mode to enhance user convenience. Your attention to this matter is greatly appreciated.

### Reproduce the Bug

1. Open the settings in the app and turn on the option for "Start on boot".
2. Restart the windows.
3. App starts.
4. Right click on the app icon and open "Properties".
5. Go to the "Compatibility" tab.
6. Check the box for "Run this program as an administrator".
7. Restart the windows.
8. App doesn't start.

### Version

v0.10.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is registered before. So we close it here for now
