### ISSUE TITLE
[FR] وارپ خودکار برای سایت های حساس

### ISSUE THREAD

**Issue by thecyanide** [hiddify/hiddify-next#177]
### Feature description

متشکرم از تلاش هاتون و برنامه فوق العاده تر و تمیز و کاربردیتون، چیزی که من متوجه شدم: تلاش بر اینه که این برنامه برای افراد ناوارد استفاده خیلی راحتی داشته باشه.

یکی از کار هایی که میتونه خیلی به این مورد کمک کنه، اضافه کردن یه آپشن برای استفاده از proxy chain وارپ هست برای سایت هایی مثل open ai یا spotify
به طور مثال، داخل برنامه nekobox، امکان این هست که یک کانفیگ wireguard از وارپ کلودفلر جنریت کنیم، و کانفیگ v2ray رو با وارپ chain کنیم تا مشکل مسدود بودن ایپی در بعضی سایت ها حل بشه.
اگر همچین چیزی به طور خودکار داخل برنامه hiddify next انجام بشه، بنظرم بسیار بسیار فوق العاده میشه.

دوباره تشکر‌ میکنم بخاطر زحماتتون. رابط کاربری برنامه فوق العاده تر و تمیز و زیباست.

**Comment by lymanjre** [comment]
در نسخه ۰.۱۵ این قابلیت اضافه شده است
