### ISSUE TITLE
instantly closes and doesn't work

### ISSUE THREAD

**Issue by ValentineMWAY** [hiddify/hiddify-next#178]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I use Fedora 39. This error i get when start application.

`12:32:51 hiddify: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
12:32:51 hiddify: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
12:32:50 hiddify: flutter: 👻 12:32:50.953317 INFO     ConnectivityController - connection status: DISCONNECTED
12:32:50 hiddify: flutter: 👻 12:32:50.921570 INFO     AutoStartService - auto start is [Disabled]
12:32:50 hiddify: linux [Linux 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023]
12:32:50 hiddify: general release
12:32:50 hiddify: flutter: 👻 12:32:50.919502 INFO     bootstrap - hiddify v0.10.0 (1000) [prod]
12:32:50 hiddify: flutter: [D] FilesEditorService: populating geo assets
12:32:50 hiddify: flutter: [I] FilesEditorService: directories: (baseDir: Directory: '/home/jesus/.local/share/app.hiddify.com', tempDir: Directory: '/tmp', workingDir: Directory: '/home/jesus/.local/share/app.hiddify.com')
12:32:50 hiddify: flutter: [D] PlatformServices: getting paths
12:32:50 hiddify: flutter: [D] Pref<bool, dynamic>: getting persisted preference [debug_mode](bool)
12:32:50 hiddify: flutter: [D] Pref<bool, dynamic>: getting persisted preference [enable_analytics](bool)
12:32:50 cat: [46757:46757:1118/123250.555481:ERROR:vulkan_swap_chain.cc(409)] Swapchain is suboptimal.
12:32:50 hiddify: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
12:32:50 com.docker.back: [2023-11-18T08:32:50.437852868Z][com.docker.backend.ipc][I] (7dbc86f6) d1884c38-stats C<-S 42140974-VMDockerdAPI GET /vm/ram-cpu-usage (1.004381875s): {"memAvailableBytes":3756324000,"memBytes":1603020000,"numCPU":10}
12:32:50 systemd: Reloading finished in 523 ms.`

### Reproduce the Bug

Just start application

### Version

0.10.0

### Platform/OS

Linux

### Relevant log output

```shell
12:32:51 hiddify: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
12:32:51 hiddify: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
12:32:50 hiddify: flutter: 👻 12:32:50.953317 INFO     ConnectivityController - connection status: DISCONNECTED
12:32:50 hiddify: flutter: 👻 12:32:50.921570 INFO     AutoStartService - auto start is [Disabled]
12:32:50 hiddify: linux [Linux 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023]
12:32:50 hiddify: general release
12:32:50 hiddify: flutter: 👻 12:32:50.919502 INFO     bootstrap - hiddify v0.10.0 (1000) [prod]
12:32:50 hiddify: flutter: [D] FilesEditorService: populating geo assets
12:32:50 hiddify: flutter: [I] FilesEditorService: directories: (baseDir: Directory: '/home/jesus/.local/share/app.hiddify.com', tempDir: Directory: '/tmp', workingDir: Directory: '/home/jesus/.local/share/app.hiddify.com')
12:32:50 hiddify: flutter: [D] PlatformServices: getting paths
12:32:50 hiddify: flutter: [D] Pref<bool, dynamic>: getting persisted preference [debug_mode](bool)
12:32:50 hiddify: flutter: [D] Pref<bool, dynamic>: getting persisted preference [enable_analytics](bool)
12:32:50 cat: [46757:46757:1118/123250.555481:ERROR:vulkan_swap_chain.cc(409)] Swapchain is suboptimal.
12:32:50 hiddify: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
12:32:50 com.docker.back: [2023-11-18T08:32:50.437852868Z][com.docker.backend.ipc][I] (7dbc86f6) d1884c38-stats C<-S 42140974-VMDockerdAPI GET /vm/ram-cpu-usage (1.004381875s): {"memAvailableBytes":3756324000,"memBytes":1603020000,"numCPU":10}
12:32:50 systemd: Reloading finished in 523 ms.
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Pls install rpm package
