### ISSUE TITLE
[RU] Please fix font sizes in Hiddify Next v.0.11.0

### ISSUE THREAD

**Issue by westsibe** [hiddify/hiddify-next#185]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Device: Redmi 9 (4/64 GB), arm64-v8a, Android 10 (stock).
Language: Russian.

Please see a screenshots (in ver.0.10.0 in main menu was be OK):

### Reproduce the Bug

1. Small font in Main menu.
2. In Proxy List:
a. Click 'Share" and see screenshot-2.

### Expected Behavior

2) All the text string must placed fully.

### Version

0.11.0

### Platform/OS

Android

### Additional Context

![Screenshot_2023-11-19-17-36-02-348_app hiddify com](https://github.com/hiddify/hiddify-next/assets/29564089/b636f870-c2c3-43a2-9d29-15823811d441)
![Screenshot_2023-11-19-17-42-55-472_app hiddify com](https://github.com/hiddify/hiddify-next/assets/29564089/4ccc019e-db76-445b-833f-f969714fbd4d)

### Relevant log output

```shell
Not needed
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
