### ISSUE TITLE
Feature Request: Custom Default Server Selection Options

### ISSUE THREAD

**Issue by AmirHosseinCV** [hiddify/hiddify-next#19]
Currently, the application selects the default server based on the lowest ping. This results in all users connecting to the closest server. It would be great if we could have the option to connect to a randomly available server by default. Even better would be allowing the subscription link server to designate a default option in the response header or selecting the default option based on the order of servers, similar to the V2rayNG application.

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
