### ISSUE TITLE
بررسی هسته جدید ساین باکس و مشکل با ماکس

### ISSUE THREAD

**Issue by AkramiPro** [hiddify/hiddify-next#192]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و خسته نباشید
ساین باکس درن سخه 1.7 کلا ساختار ماکس رو تغییر داده و روش brutal رو برای مدیریت پهنای باند اضافه کرده که خیلی از کانفیگ های قدیمی که از mux استفاده میکنن به مشکل میخورن 
من ایشو درست کردم و بهش گفتم ولی کلا این برنامه نویس ساین باکس اعصاب نداره همش ignore میکنه هر چی بهش میگم .
لطفا از نسخه های در حال توسعه استفاده نکنید . نسخه پایدار الان 1.6.5 هست 
ممنون میشم اینو بررسی کنی

در گذشته برای استفاده از mux فقط کافی بود از سمت کلاینت فعال کنیم ولی الان لازم هست حتما سمت سرور هم در بخش inbound فعال کنیم ولی حتی با انجام این کار هم کانفیگ های قدیمی بازم با mux مشکل دارن . من با vless و trojan تست کردم مشکل داشت 

![image](https://github.com/hiddify/hiddify-next/assets/54323929/9e059abc-5fca-4c88-96cb-2df276a225e4)

### Reproduce the Bug

ماکس رو فعال کن سمت کلاینت

### Version

0.11.1

### Platform/OS

Android, Windows, Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
