### ISSUE TITLE
[FR]  اضافه کردن قابلیت قفل کردن کانفیگ

### ISSUE THREAD

**Issue by Shellgate** [hiddify/hiddify-next#195]
### Feature description

قابلیتی اضافه کنید مثل برنامه Armod vpn که کد ها رو رمز گذاری کنه و امکان پخش کد نباشه

**Comment by MK0ltra** [comment]
The purpose of this project are users not vpn sellers. If you need something for your business, write it yourself.

**Comment by Shellgate** [comment]
Then you pay my servers prices
We don't allow to share codes
We can use other programs
