### ISSUE TITLE
مشکل در کانفیگ ریلیتی و لینک ساب

### ISSUE THREAD

**Issue by SAEEDa4220** [hiddify/hiddify-next#196]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

لینک سابی ساختم که توی اون چند مدل ریلیتی بود ولی هیچکودوم پینگ نداد توی برنامه ویتوری تست کردم اوکی بودن
بعد یکی از کانفیگایی که کار میداد رو تکی وارد کردم توی نکست دیدم کار میده متوجه شدم ممکنه بخاطر path که خود پنل هیدیفای تایین میکنه اینطور بشه 
در کل کانفیگایی که grpc هستن و توسط خود پنل هیدیفای ساخته شدن توی لینک ساب و برنامه هیدیفای نکست کار نمیده 
این مورد رو با چند نفر دیگه با اثبات اسکرینشات در گپ هیدیفای قسمت هیدیفای نکست ذکر کردیم
https://t.me/hiddify_board/289530/350184?single
لطفا مورد رو پیگیری کنید

### Reproduce the Bug

لینک سابسکریپشن ایجاد کنید که دارای چندین ریلیتی باشه
ریلیتی grpc پینگ نمیده ولی اگه به صورت تکی اد بشه کار میکنه

### Version

0.11.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by parsatavafi** [comment]
این مشکل رو من هم هم روی ریلیتی های GRPC و هم روی کانفیگ های روی CDN اروان دارم، وقتی تکی کانفیگ رو اضافه کنم کار می کنه اما با زدن دکمه (بارگذاری در برنامه) در پنل هیدیفای فقط کانفیگ های ریلیتی xTLS رو تست می کنه و متصل میشه.

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
