### ISSUE TITLE
نسخه ios چه زمانی تکمیل میشه ایا برنامه برای ریلیزش دارید؟

### ISSUE THREAD

**Issue by sbh96** [hiddify/hiddify-next#197]
### Feature description

من از چند تا از دوستانی که فلاتر کار می‌کنند برای کانتریبیوت ios درخواست فرستادم
آیا سمت شما پلنی برای ریلز ios دارید؟

**Comment by hiddify-com** [comment]
سلام
لطفا در صورت تمایل به همکاری در بخش ios به contribute@hiddify.com ایمیل بزنید

میخواهیم هز چه‌زودتر برای ios هم اوکی کنیم
