### ISSUE TITLE
unable

### ISSUE THREAD

**Issue by Ashrafty** [hiddify/hiddify-next#2]
am unable to build for windows and android

**Comment by problematicconsumer** [comment]
Please provide more information. What's your operating system? Makefile command are suited for (and tested on) Linux (you can use WSL if you're on Windows or change them accordingly).
Also, I'll make proper releases if next few days.

**Comment by Ashrafty** [comment]
oh okay let me try wsl as i also wait for thou releases

**Comment by Ashrafty** [comment]
![image](https://github.com/hiddify/hiddify-next/assets/40754280/41312793-de8f-4d91-b508-361cbbc749bb)
uhmm yeah i don't know if this is a feature but even when i do "pub get" everything stays red even i have tried to fix it but ultimately i failed to fix em bugs...help

**Comment by problematicconsumer** [comment]
This project relies heavily on code generation. You need to make sure you have all requirements set properly and then use `make` commands that I've put in README.

**Comment by Ashrafty** [comment]
![image](https://github.com/hiddify/hiddify-next/assets/40754280/d2c9b5ca-ba99-4d65-a1ed-6221c5fdf147)
as you can see all is there bro but it still throws errors

**Comment by problematicconsumer** [comment]
Ok, there were some problems with Makefile commands which are fixed now. If you run them on Linux (or WSL) with requirements installed, there should be no issues (you can by all means build this on Windows directly, just need to convert commands to their windows equivalent).
If you still have issue, please share error messages.

**Comment by Ashrafty** [comment]
![image](https://github.com/hiddify/hiddify-next/assets/40754280/ca98fb85-c8c4-45e6-bf2e-b307a1428654)

on WSL i get the command not found error and with android studio well, below is the error message i get



The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:3
+   $ flutter_distributor package --platform windows --targets exe
+   ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by problematicconsumer** [comment]
You don't need to include `$` in your commands! Type them like this: `make gen`

**Comment by Ashrafty** [comment]
make gen
dart run build_runner build --delete-conflicting-outputs
/usr/bin/env: ‘bash\r’: No such file or directory
make: *** [Makefile:8: gen] Error 127

**Comment by problematicconsumer** [comment]
Have you tried googling? Sorry, but these issues are specific to your setup, and it's hard to debug like this
both Makefile and GitHub workflow are working as expected, and you can check them for specific steps

**Comment by Ashrafty** [comment]
ye i have tried googling.... i guess the issue in me alone at the moment...but have you tried running this set up on windows

**Comment by problematicconsumer** [comment]
Yes, as I've mentioned [here](https://github.com/hiddify/hiddify-next/issues/2#issuecomment-1640002158) there were a few problems, and they're fixed now. I did use WSL to build a release today and there were no issues.
I believe The errors you're getting don't have much to do with this project, that's why I can't help you here.

**Comment by Ashrafty** [comment]
since you said most of the project is from a code generator...yea that's where the problem is flutter keeps on throwing error messages...anyways thanks

**Comment by problematicconsumer** [comment]
I will close this, but feel free to comment if you think there's anything I can help with

**Comment by Ashrafty** [comment]
i managed to configure the everything....but upon compiling it just doesn't work like the android app stops on the splash screen and for linux and windows it just doesn't work it throws these long errors like a billion of them...so back to square one
