### ISSUE TITLE
باگ عدم پروکسی کردن آپ ها

### ISSUE THREAD

**Issue by imanmoghimiq30** [hiddify/hiddify-next#20]
سلام ممنون از برنامه خوب تون
1/گوشی من گلکسی نوت ۴ با کاستوم رام lineage os اندروید 11 هست.
بعد نصب نرم افزار و اضافه کردن لینک ساب همه چیز خوب کار میکنه و به بهترین سرور با پینگ پایین وصل میشه اما نرم افزار نمی تونه آپ ها رو پروکسی کنه یعنی قسمت وی پی ان شدنش مشکل داره برای من. اما مثلا اگه با 127.0.0.1:2334بیام تو توییتر یا تلگرام بصورت دستی پروکسی وارد کنم اون موقع اوکی هست اما خودش نمی تونه تمام آپ ها رو پروکسی کنه.
در ضمن قسمت per app proxy گزینه اول که میزنم هیچ اتفاقی نمی افتد و گزینه‌ فعال نمیشه و گزینه وسط و آخر هم که فعال میشه بازم همون مشکل عدم پروکسی کردن آپ ها رو داره.
پ.ن: این مشکل برای منه و برای سه نفر از آشناها که نصب و راه اندازی کردم هیچ مشکلی ندارن :(

2/برای آپ ویندوزی هم وقتی گزینه شروع در زمان بوت رو تیک می زنیم فقط در زمان شروع ویندوز برنامه رو باز میکنه اما انتظار میره بعد باز کردن برنامه خودش کانکت بشه و بعد بره در پس زمینه

3/پیشنهاد:زمانی که آپدیت جدید در دسترس قرار میگیره و پیام میاد در نرم افزار بعد از زدن روی گزینه آپدیت ما رو به صفحه گیت هاب نبره بلکه خودش بیاد فایل جدید رو دانلود کنه چه اندروید و چه باقی سیستم عامل ها
با تشکر

**Comment by problematicconsumer** [comment]
اگر per-app proxy و debug mode خاموش باشن نباید مشکلی باشه. اپ با lineage os تست نشده، ممکنه تفاوت‌هایی با نسخه‌های دیگه اندروید داشته باشه. از غیرفعال بودن این دو گزینه مطمئن شو، مجدد تست کن. با اپ‌های مشابه هم مشکل داری؟

> در ضمن قسمت per app proxy گزینه اول که میزنم هیچ اتفاقی نمی افتد

گزینه اول یا proxy all apps معادل با خاموش کردن per-app proxy هست.

> انتظار میره بعد باز کردن برنامه خودش کانکت بشه و بعد بره در پس زمینه

این فیچر به زودی اضافه میشه

**Comment by imanmoghimiq30** [comment]
ممنون بابت پیگیری هر دو گزینه رو خاموش کردم اما باز هم اتفاقی نیفتاده مشکل فقط با این اپ هست و با hiddify NG و v2rayNG وصل میشم و مشکلی نیست. من همینجور آرم رو گوشی دوست و آشنا نصب میکنم hiddify Next رو تا شایدتو گوشی دیگه ای هم این مشکل ببینم اما متاسفانه یا خوشبختانه همشون قشنگ کار میدن

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
