### ISSUE TITLE
تکمیل قوانین روتینگ

### ISSUE THREAD

**Issue by DrAmirB** [hiddify/hiddify-next#202]
### Feature description

سلام وقت بخیر
قوانین روتینگ ریجن ایران همچنان کامل نیس و نقص داره
در صورت امکان موارد زیر رو برای دیتابیس Chocolate4U بای پس کنین که کامل شه:

geosite:ir
geosite:private
regexp:.*\\.ir$
regexp:.*\\.xn--mgba3a4f16a$

geoip:ir
geoip:private
geoip:arvancloud
geoip:derakcloud
geoip:iranserver
geoip:parspack

با تشکر

**Comment by BaziForYou** [comment]
اگه امکان کاستوم وارد کردن قوانین روتینگ ادد شه بعد ادد دیتابیس ها کنار سیستم اتومات تکمیل میشه هم دایرکت هم پروکسی هم بلاک

**Comment by problematicconsumer** [comment]
Closing in favor of #210
