### ISSUE TITLE
[FR] Dns

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-next#203]
### Feature description

درود با عرض خسته نباشید
DOH , DOT , DNS CRYPT 
با دامنه مدنظر خودمون رو بتونیم اضافه کنیم در تنظیمات

ی مشکل اپ های وی پی ان این هست که دی ان اس درست حسابی روشون ست نمیشه

**Comment by lymanjre** [comment]
لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.

**Comment by realartin** [comment]
درود اپدیت کردم ولی قابلیت تعین doh یا ... بهش اضافه نشده ...
