### ISSUE TITLE
[FR]  تنظیمات جغرافیایی

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-next#204]
### Feature description

درود خسته نباشید
بهتر میشه اگر بشه به صورت دستی در کنار پروفایل هایی که میشه اد کرد تو بخش تنظیماتی جغرافیایی بشه دستی هم ایپی و دامنه به عنوان باپیس اضافه کرد

**Comment by problematicconsumer** [comment]
Closing in favor of #210

**Comment by mostafacpr** [comment]
خسته نباشید
من با اینکه فایل های مسیریابی رو آپدیت کردم ولی وقتی با هیدیفای نکست کانکت هستم سایتهای داخلی باز نمیشه
میشه `راهنمایی` کنین لطفا
