### ISSUE TITLE
Android TV Click Issue

### ISSUE THREAD

**Issue by BaziForYou** [hiddify/hiddify-next#208]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello, there is a significant issue with certain Android TV versions related to remote control functionality.

### Reproduce the Bug

When using the remote, everything operates smoothly until you attempt to press a button; at times, it seems as though the click is registered, but there is no corresponding action. However, when a mouse is connected to the device, it successfully receives the clicks and responds accordingly. This issue complicates simple tasks such as connecting or disconnecting a VPN, as it becomes challenging to rely on the remote alone.

### Expected Behavior

Google TV
Mibox s 2nd gen
Android version 11
Hidify next veraion V0.11.1
Apk hiddify-android-arm7

### Version

V0.11.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
This issue is fixed in [v0.12.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.12.0). There are still some issues when trying to navigate sidebar which will be resolved in future releases (since they're related to framework bugs)

**Comment by itsaeed1** [comment]
Hi . please fix the menu problem. also the application is not available in Android TV Google Play
