### ISSUE TITLE
[FR] Custom Groups

### ISSUE THREAD

**Issue by BaziForYou** [hiddify/hiddify-next#209]
### Feature description

It would be highly beneficial to organize custom configurations more efficiently. Instead of listing all individual configurations alongside each subcategory, we can create groups to categorize them. Within these groups, we can include non-sub configurations as proxies. This approach allows for a streamlined selection process: users choose a group, and the application automatically scans the pre-added proxies within that group, connecting to the best option. This method is particularly useful for non-sub subgroups, where our configurations can be added to address various issues effectively.

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.

**Comment by BaziForYou** [comment]
for reminder as far as I know still has not been added but marked as Done
