### ISSUE TITLE
Bug: Windows client disconnects after a while

### ISSUE THREAD

**Issue by AmirHosseinCV** [hiddify/hiddify-next#21]
After about a half an hour that I use the windows client, it gets disconnected and also disconnects my whole network connection. I do not have such a problem with nekoray using the same server. 

Settings:
TUN mode: On
System Proxy: Off
Admin privilege is given.

Windows 11
Hiddify-Next version: 0.7.0

**Comment by lymanjre** [comment]
Please check out the newer version. V0.8.0. Of exist open this issue again
