### ISSUE TITLE
[FR] Custom Routing Rules

### ISSUE THREAD

**Issue by BaziForYou** [hiddify/hiddify-next#210]
### Feature description

After utilizing our pre-added routing assets or incorporating new ones, it would be fantastic to enhance our database integration. Instead of solely relying on entering a region for auto-selection, providing users with the option to incorporate custom rules would be a valuable addition. Drawing inspiration from v2rayng, users could input or implement their geosite and geoips rules. This would allow for more precise control over direct proxies or blocking in our routing. Additionally, the ability to specify certain IPs and websites for specific actions would fill a current gap in this feature.

**Comment by realartin** [comment]
موافقم واقعا بهش نیاز هست

**Comment by duriann** [comment]
When I open the proxy, the company intranet cannot be opened because the domain name is also cn. Is there any solution?

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.

**Comment by realartin** [comment]
قابلیت تعین لیست بایپس دستی اضافه نشده

**Comment by Vasili-Sk** [comment]
vote up, highly needed feature to save traffic

**Comment by Catsys** [comment]
Ideally, additional custom filters are required to complement geoip resources. You need to add a filter with the tag "proxy" or "direct," allowing the inclusion of a domain (substring) or IP/CIDR in the filter.

This is necessary to permit "direct" access to content that isn't blocked in the country, and to avoid unnecessary delays for instant messengers or high-traffic content like videos (YouTube, films), or corporate networks for work.

Additionally, there are domains that are mistakenly labeled in the wrong interface and need correction.

As you can see, there are numerous reasons why a custom filter is essential. Furthermore, these filters are standard across all v2ray clients, and I believe they are equally vital for Hiddify.

**Comment by SighT26** [comment]
anyone understand how is other region work? no any manual

**Comment by realartin** [comment]
> anyone understand how is other region work? no any manual

in hiddify nothing can be change manually :)

**Comment by willzhang** [comment]
hope support

**Comment by lymanjre** [comment]
The issue is done

**Comment by dvovney** [comment]
> The issue is done

Can you share some details how to configure custom routing?

**Comment by BaziForYou** [comment]
for reminder as far as I know still has not been added but marked as Done

**Comment by ChapayTv** [comment]
I also did not find instructions on how to do this. We really need this function in the panel.

**Comment by VahidGarousi** [comment]
+1

**Comment by CrazyPencill** [comment]
> The issue is done

Please elaborate. I'm only able to change the config, I cannot find any rules editor (like in Shadowrocket on ios for example) Can you explain how to add custom rules? Thank you.

**Comment by cyrmax** [comment]
Hello! Still interested on how to add custom routes.
Don't see this feature neither on Windows, nor on Android.
This really bothers because if some websites have .com or other international domain zone but have Russian IP address, then Hiddify decides to route this via vpn but xray server blocks the connection due to enabled setting to block connections by region.

**Comment by AmokDev** [comment]
+

**Comment by Luccifer** [comment]
+1

**Comment by lukdut** [comment]
How to at least directly route local network IP addresses like 192.168.0.*?

**Comment by VNVetrov** [comment]
Even changing json config by adding "routes" key doesn't help. Seems like program cant recognize this, so for now better to use v2ray on PC and v2rayNG on mobile for custom routing.

**Comment by poshl9k** [comment]
any updates?

**Comment by ani917** [comment]
any news?

**Comment by ahkhanjani** [comment]
+

**Comment by Davidos533** [comment]
+1

**Comment by Jacky-YC** [comment]
+1

**Comment by pouria-ariafar** [comment]
+1

**Comment by roadrout** [comment]
+1

**Comment by mikemails** [comment]
+1

**Comment by cyrmax** [comment]
Finally switched to v2ray-ng and amnezia.
Looks like this project is no longer actively maintained.

**Comment by Kepler139f** [comment]
+1

**Comment by softkdev** [comment]
+1

**Comment by SzenProgs** [comment]
+1

**Comment by xerxesar** [comment]
+1
