### ISSUE TITLE
آپدیت نشدن نسخه قدیمی

### ISSUE THREAD

**Issue by rezaafz** [hiddify/hiddify-next#213]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

من نسخه قدیمی اپ رو روی ویندوز دارم. ولی وقتی روی آپدیت میزنم میگه داری از آخرین نسخه استفاده میکنی!
![photo_2023-11-29_11-13-40](https://github.com/hiddify/hiddify-next/assets/53352623/f2aa9034-87fa-46ff-9a58-cfec167f65ad)

### Reproduce the Bug

با نسخه 0.9.0 روی check for updarte کلیک کنید

### Version

0.9.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
شیوه چک آپدیت در این نسخه و قبل‌تر از اون باگ داره که برطرف شده اما کاربرایی که از این نسخه‌ها استفاده میکنن باید دستی آپدیت کنند.
