### ISSUE TITLE
[Feature]: Configuration Edit Menu 

### ISSUE THREAD

**Issue by nimagp** [hiddify/hiddify-next#216]
### Feature description

Sometimes tweaking the entered configuration or entering one from scratch is required. (Take Up/Down speeds in hysteria as an example) 

Not being able to do this, in many cases, renders hiddify-next useless.

**Comment by problematicconsumer** [comment]
Hiddify Next is a subscription based app. Editing individual configs is not a feature we will work on. Though you will be able to add/change configuration by file (so you'll be able to modify JSON to your liking) in the future.

**Comment by nimagp** [comment]
> Hiddify Next is a subscription based app. Editing individual configs is not a feature we will work on. Though you will be able to add/change configuration by file (so you'll be able to modify JSON to your liking) in the future.

With all due respect for your team's motivation, it takes very much longer to use hiddify next with parameters that are not transferred in the url. A toggle for advanced mode would solve most of this, inexperienced users usually don't look for additional options when the turn on button works.

I'm not sure if this gets in your github inbox, therefore @problematicconsumer .

**Comment by problematicconsumer** [comment]
@nimagp There are multiple apps that offer such features. It would be much work for little gain. Editing json and more options overall are on the roadmap.

**Comment by nimagp** [comment]
I see. Would you accept a pull request regarding this if it were made?
@problematic consumer

**Comment by problematicconsumer** [comment]
Sure, if you follow the overall architecture.
