### ISSUE TITLE
[FR] Save last used config + Display proxy list if service not running

### ISSUE THREAD

**Issue by AndrewBPC** [hiddify/hiddify-next#219]
### Feature description

When I relaunch Hiddify, it uses the auto URL test instead of the last used configuration. After every proxy start, I need to ensure that I am using the correct server. Additionally, I need to view the proxy list without starting the proxy. It would be nice if the main page displayed the selected configuration regardless of its status, showing at least the name and protocol.

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
