### ISSUE TITLE
لیست سایت ها و برنامه های فیلتر شده

### ISSUE THREAD

**Issue by mcuteangel** [hiddify/hiddify-next#22]
سلام
اپ قبلی امکانش رو داره که به طور خودکار خودش سایت ها و برنامه های فیلتر شده رو فقط پروکسی کنه یا لیست سایت های داخلی رو پروکسی نکنه
این قابلیت رو به این اپ هم اضافه کنید لطفاً
برنامه الان خیلی خوب شده، همه نوع کانفیگی قبول میکنه
با تشکر

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
