### ISSUE TITLE
[FR] Custom configuration file path

### ISSUE THREAD

**Issue by Joackk** [hiddify/hiddify-next#220]
### Feature description

I want to put the configuration files and software I use together. Now it seems that he defaults to creating under appdata. Can I customize his work path? What should I do if possible?

**Comment by Joackk** [comment]
> Unfortunately, this is not possible right now and won't be added anytime soon.

I have another question, which is that the subscription link I am using works fine on both Clash and another GUI interface using Sing Box. However, in this GUI, I can successfully add subscriptions, but the nodes cannot use it properly. Why is this? Aren't they all using a single box kernel?

**Comment by problematicconsumer** [comment]
We use a slightly modified version of singbox (which you can find [here](https://github.com/hiddify/hiddify-sing-box)) but this shouldn't have much of an effect. Your configs also won't execute as is, they're modified based on rules (selected region) and other config options. You can check the exact config that is running (with options and rules applied) in the working directory or export it as JSON.
