### ISSUE TITLE
[FR] Can I add routing rules？thank you

### ISSUE THREAD

**Issue by AjaxCao** [hiddify/hiddify-next#221]
### Feature description

"outbounds": [
  {
    "type": "direct",
    "tag": "direct"
  },
  {
    "type": "block",
    "tag": "block"
  }
],
"route": {
  "geoip": {
path：“”，
      "download_url": "https://github.com/Chocolate4U/Iran-sing-box-rules/releases/latest/download/geoip.db"
  },
  "geosite": {
path：“”，
    "download_url": "https://github.com/Chocolate4U/Iran-sing-box-rules/releases/latest/download/geosite.db"
  },
  "rules": [
    {
      "geosite": [
        "category-ads-all",
        "malware",
        "phishing",
        "cryptominers"
      ],
      "outbound": "block"
    },
    {
      "geoip": [
        "malware",
        "phishing"
      ],
      "outbound": "block"
    },
    {
      "geosite": "ir",
      "outbound": "direct"
    },
    {
      "geoip": [
        "ir",
        "private",
        "arvancloud",
        "derakcloud",
        "iranserver",
        "parspack"
      ],
      "outbound": "direct"
    }
  ]
}

**Comment by problematicconsumer** [comment]
Custom routing rules are not supported yet.
