### ISSUE TITLE
[FR] اسکنر آی پی برای کلاینت

### ISSUE THREAD

**Issue by rezaafz** [hiddify/hiddify-next#222]
### Feature description

سلام. آیا این امکان وجود داره که کلاینت هیدیفای یک اسکنر داشته باشه که بتونه آی پی‌های تمیز رو پیدا کنه. یعنی خودش بیاد آی پی‌های کلودفلر رو با استفاده از رنج آی پی‌هایی که ما قبلا بهش دادیم، اسکن کنه بعد آی پی تمیز رو پیدا کنه و بهش وصل بشه.
اینطوری هر کسی بهترین آی پی که برای اینترنتش کار می‌کنه رو توسط کلاینت اتوماتیک پیدا می‌کنه و بهش وصل می‌شه. دیگه نیازی نیست همه این همه وقت و انرژی بذارن که آی پی‌ها رو اسکن کنن، بعد ببینیم که باز هم این آی پی‌ها برای بعضی ها کار نمی‌کنه.

**Comment by amin2plus** [comment]
اینجوری که مصرف باتری خیلی زیاد میشه و پرفورمنس برنامه خیلی داغون میشه، برای اینکار کلی برنامه هست و حتی برنامه آندرویدی و وب اپلیکیشن هم درست کردن دوستان، حتی اسکریپت پیدا کردن ای پی تمیز و گذاشتن خودکار اون ای پی توی اکانت کلادفلر هم هست:
https://github.com/XIU2/CloudflareSpeedTest
