### ISSUE TITLE
not payload sni

### ISSUE THREAD

**Issue by creyt2012** [hiddify/hiddify-next#225]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

no payload sni for vmess

### Reproduce the Bug

no payload sni for vmess

### Version

no payload sni for vmess

### Platform/OS

Android, Windows, macOS, Linux, iOS

### Additional Context

no payload sni for vmess

### Relevant log output

```shell
no payload sni for vmess
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
