### ISSUE TITLE
Unable to connect to the Internet in VPN mode on windows system

### ISSUE THREAD

**Issue by wusimon415** [hiddify/hiddify-next#229]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When the Windows system turns on the VPN mode, it cannot connect to the Internet.
![Snipaste_2023-12-06_09-44-20](https://github.com/hiddify/hiddify-next/assets/147293022/5f3c1767-4c02-43c8-ba1a-8932260daf84)

### Reproduce the Bug

Hiddify-Next has been opened with administrator rights

### Version

0.11.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by TheLastFlame** [comment]
Hi, your VPN is just blocking the connection test address - msftconnecttest.com. It's listed as geosite:private for some reason. You won't be able to open it with your VPN enabled. Just add direct routing of this domain in your VPN settings.

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
