### ISSUE TITLE
The app is not working properly on a Macbook M1Pro

### ISSUE THREAD

**Issue by raminrez** [hiddify/hiddify-next#23]
The Telegram app cannot connect while using hiddifyNext

The server version is : 8.6.3
The client version is : 0.7.1

----

Here is my app log:
[app.log](https://github.com/hiddify/hiddify-next/files/12802131/app.log)

Here is the box log:
[box.log](https://github.com/hiddify/hiddify-next/files/12802138/box.log)

**Comment by lymanjre** [comment]
مشکل در ست شدن پروکسی روی مک M1 هست. پروکسی به صورت دستی ست میشه و کار میکنه

**Comment by raminrez** [comment]
I have created a proxy for Telegram on 127.0.0.1:2334, and Telegram has connected.
However, the app needs to be fixed. This is a temporary solution, and every user of HiddifyNext needs to be made aware of this configuration.

**Comment by shahryarjb** [comment]
> مشکل در ست شدن پروکسی روی مک M1 هست. پروکسی به صورت دستی ست میشه و کار میکنه

با اینکه روی مک در قسمت پروکسی شبکه هم سکیور هم براس http پرت 2334 ست می شه من در کروم
This site can’t be reacheddevheroes.club unexpectedly closed the connection.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_CLOSED
دریافت می کنم

**Comment by danaenayati** [comment]
سلام من هم رو مک m1 pro این مشکل رو دارم. همه چیز درست باز میشه بعضی برنامه ها مثل تلگرام روی connecting میمونه و باز نمیشه.

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
