### ISSUE TITLE
[FR] make subscription list panel could expand to the top.

### ISSUE THREAD

**Issue by HumanMus1c** [hiddify/hiddify-next#230]
### Feature description

![image](https://github.com/hiddify/hiddify-next/assets/46023154/a346634e-2c49-418c-b595-9bca4272e853)

**Comment by problematicconsumer** [comment]
It should (and does on other platforms) expand. It's due to different default scroll behaviour on Windows, which I'll change

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
