### ISSUE TITLE
Insufficiency Contributing Guide. Problematic initial setup in windows.

### ISSUE THREAD

**Issue by TheLastFlame** [hiddify/hiddify-next#233]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I wanted to make some small improvements to a project. I tried to follow CONTRIBUTING.md for the initial setup, however I encountered a number of problems.

1. The library installation commands are not suitable for Windows
![image](https://github.com/hiddify/hiddify-next/assets/131446187/8802fd41-4a56-44a5-b4d1-3ac31c02dd3e)

2. Even after manual downloading I still could not get the project to run.
![image](https://github.com/hiddify/hiddify-next/assets/131446187/6221c427-35e9-4e91-8277-d3d70b92a4b9)

### Reproduce the Bug

.

### Version

-

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Contribution guide is slightly outdated but it shouldn't be a problem. Please run `flutter doctor` and and send the result here.
