### ISSUE TITLE
Hiddify keeps Crashing on MacOS

### ISSUE THREAD

**Issue by raminrez** [hiddify/hiddify-next#234]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

HiddifyNext keep craching on mac os

### Reproduce the Bug

1. I have opened the app
2. I tried to change the profile
3. after that app closed
4. and never opens again! It appeared like a flash and was gone again! 

### Version

0.11.1

### Platform/OS

macOS

### Additional Context

Here is the full version of the log
[log.txt](https://github.com/hiddify/hiddify-next/files/13624141/log.txt)

### Relevant log output

```shell
-------------------------------------
Translated Report (Full Report Below)
------------------------------------- 

Process:               HiddifyNext [42398]
Path:                  /Applications/HiddifyNext.app/Contents/MacOS/HiddifyNext
Identifier:            app.hiddify.com
Version:               0.11.1 (1101)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Thanks for your detailed report. Please test latest version ([v0.12.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.12.0)).

**Comment by raminrez** [comment]
it's stable for now

**Comment by raminrez** [comment]
@problematicconsumer 
It's happened again.
I was using the SSH protocol when it happened.

Here is the `crash log` file:
[hiddify.log](https://github.com/hiddify/hiddify-next/files/13785824/hiddify.log)

Here is my `Config Options`:
```json
{
  "service-mode": "system-proxy",
  "log-level": "debug",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "tcp://8.8.8.8",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "8.8.8.8",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 6450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "bypass-lan": false,
  "enable-fake-dns": false,
  "independent-dns-cache": true,
  "enable-tls-fragment": true,
  "tls-fragment-size": "10-100",
  "tls-fragment-sleep": "50-200",
  "enable-tls-mixed-sni-case": true,
  "enable-tls-padding": true,
  "tls-padding-size": "100-200"
}
```

**Comment by problematicconsumer** [comment]
Please attach your `app.log` file (this file is reset on every app launch, so it's important that you send it when a crash happens). This file is located in working directory, you can access this directory from about tab or going to this path: `~/library/Application support/app.hiddify.com`. Consider enabling debug mode to enrich this log file.
