### ISSUE TITLE
[FR] per-app proxy support import

### ISSUE THREAD

**Issue by bupt2017** [hiddify/hiddify-next#235]
### Feature description

![Screenshot_2023-12-10-01-54-34-647_io nekohasekai sfa-1-1](https://github.com/hiddify/hiddify-next/assets/29458450/fcc574e8-93d1-4e49-ad0f-8c69feb3da18)

I would like to request support for import and export functionality in the per-app proxy, similar to what Sing Box offers. Thank you very much.

![Screenshot_2023-12-10-02-03-06-155_com v2ray ang-1-1](https://github.com/hiddify/hiddify-next/assets/29458450/62ccc682-ebbe-4db2-a98b-d6d3fc38987d)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
