### ISSUE TITLE
proxy mode - hiddify client for windows

### ISSUE THREAD

**Issue by prxpostern** [hiddify/hiddify-next#236]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام . آیا فقط حالت tun وصل میشه یا نه ؟ من اگر بخواهم مثل سایر کلاینت ها فقط سوکس پراکسی استفاده کنم میشه ؟ روی چه پورتی سوکس اجرا میشه ؟ هر چی گشتم ندیدم جایی بشه تنظیمش کرد.  اگر نداره ممنون میشم اضافه کنید . حالت تون اصلا بدرد من نمیخوره .

### Reproduce the Bug

a

### Version

v0.11.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
اپ از سه حالت proxy, system proxy و vpn (tun) پشتیبانی میکنه
تغییر مود از طریق تنظیمات انجام میشه. بقیه گزینه‌ها هم از همین صفحه قابل تغییره: settings > config options
