### ISSUE TITLE
[FR] linux binary builds, for Alpine OS and universal Linux binary

### ISSUE THREAD

**Issue by rony432** [hiddify/hiddify-next#237]
### Feature description

please consider building for alpine linux and universal linux binary

thank you

**Comment by tl123987** [comment]
can not start up

**Comment by rony432** [comment]
what?
all im asking is putting binary build in build.yaml for linux binary next to appimage

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
