### ISSUE TITLE
BUG - hiddify next disconnecting other VPN apss in proxy mode on android

### ISSUE THREAD

**Issue by rony432** [hiddify/hiddify-next#239]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i am using hiddify next on android configured as proxy mode
and using nekobox as always on vpn 

senario A,
when nekobox is connected and active. i try to change profiles in hiddify next when i hit the connect button its dis engages Nekobox, it should not do this because its in proxy mode.
i have i used all other apps in this way, v2rayng, hiddifyng, matsuri, clash, ...
this never happend.

it is a bug at core level. and very annoying

senario B
if i connect hiddify first then connect in nekobox it stays connected.

hope i have explained it well

### Reproduce the Bug

hiddify in proxy mode
connect to hiddify from nekobox using socks proxy port socks5://0.0.0.0:2334/#next
activate and connect
now in hiddify hit connect.

witness the bug

### Expected Behavior

it should not use os VPN privilege in proxy mode

### Version

0.11.1

### Platform/OS

Android

### Additional Context

android 11

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
