### ISSUE TITLE
مشکل http

### ISSUE THREAD

**Issue by alirezax5** [hiddify/hiddify-next#24]
طبق آزمایشم پروکسی هایی که http دارن کار نمی کنه.

**Comment by alirezax5** [comment]
منظورم از http :

vless://uuid@ip:port?security=none&encryption=none&headerType=http&type=tcp#test

که فکر کنم شما اومدید type رو tcp در نظر گرفتید
در صورتی که اگه سینگ باکس استفاده می کنید باید http باشه

**Comment by hiddify-com** [comment]
fixed in 0.8.1
