### ISSUE TITLE
找到的订阅 服务启动错误

### ISSUE THREAD

**Issue by k90ws8** [hiddify/hiddify-next#241]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![屏幕截图 2023-12-13 233325](https://github.com/hiddify/hiddify-next/assets/149854412/55bc5b8d-e600-44ea-babc-35705952dc52)

### Reproduce the Bug

点击连接

### Version

0.11.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
This is the problem in your sub link and is not related to hiddify-next
