### ISSUE TITLE
找到的多个订阅节点出现Block

### ISSUE THREAD

**Issue by k90ws8** [hiddify/hiddify-next#242]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![屏幕截图 2023-12-15 100502](https://github.com/hiddify/hiddify-next/assets/149854412/ed8f573d-5e0b-41eb-ae86-e40b2c012557)
![屏幕截图 2023-12-15 101256](https://github.com/hiddify/hiddify-next/assets/149854412/5121b59c-e932-444c-99bc-48706befb11f)
![屏幕截图 2023-12-15 100741](https://github.com/hiddify/hiddify-next/assets/149854412/21243ed1-d202-4748-bc0f-d38ba36963e9)

### Reproduce the Bug

Block

### Version

0.11.1

### Platform/OS

Windows

### Relevant log output

+0800 2023-12-15 10:35:05 ERROR outbound/hysteria2[SCP1 § 0]: parse outbound[2] 

<nil> 

error: missing obfs password
+0800 2023-12-15 10:35:05 ERROR outbound/hysteria2[SCP2 § 1]: parse outbound[3] 
+0800 2023-12-15 10:38:29 ERROR [1184557845 0ms] outbound/urltest[auto]: EOF
+0800 2023-12-15 10:38:29 ERROR [3459974312 0ms] outbound/urltest[auto]: EOF

<nil> 

error: missing obfs password
+0800 2023-12-15 10:35:24 ERROR outbound/shadowsocks[github.com/freefq - 广东省广州市移动 9 § 9]: parse outbound[9] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkODljYTM3MS1lOTRiLTRkZmUtYWQ2Zi0wMmJkMTNlZGY3YzQ
+0800 2023-12-15 10:35:24 ERROR outbound/shadowsocks[github.com/freefq - 广东省广州市移动 13 § 13]: parse outbound[13] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkODljYTM3MS1lOTRiLTRkZmUtYWQ2Zi0wMmJkMTNlZGY3YzQ
+0800 2023-12-15 10:35:24 ERROR outbound/shadowsocks[github.com/freefq - 广东省广州市移动 15 § 15]: parse outbound[15] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkODljYTM3MS1lOTRiLTRkZmUtYWQ2Zi0wMmJkMTNlZGY3YzQ
+0800 2023-12-15 10:35:48 ERROR outbound/shadowsocks[TG频道@mfbpn-0190-JP § 23]: parse outbound[25] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToyN2ExY2VjNS0yNmJiLTRmODctOWE1ZC1iM2ExMDhjMDE1Mzc
+0800 2023-12-15 10:35:48 ERROR outbound/shadowsocks[TG频道@mfbpn-0191-JP § 24]: parse outbound[26] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToyN2ExY2VjNS0yNmJiLTRmODctOWE1ZC1iM2ExMDhjMDE1Mzc
+0800 2023-12-15 10:35:48 ERROR outbound/shadowsocks[TG频道@mfbpn-0194-SG § 25]: parse outbound[27] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToyN2ExY2VjNS0yNmJiLTRmODctOWE1ZC1iM2ExMDhjMDE1Mzc
+0800 2023-12-15 10:35:48 ERROR outbound/shadowsocks[TG频道@mfbpn-0195-SG § 26]: parse outbound[28] 

<nil> 

error: unknown method: Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToyN2ExY2VjNS0yNmJiLTRmODctOWE1ZC1iM2ExMDhjMDE1Mzc
+0800 2023-12-15 10:35:48 ERROR outbound/shadowsocks[TG频道@mfbpn-0196-KR § 27]: parse outbound[29] 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by YiDDcode** [comment]
## 解决办法
转换订阅链接, [ACL4SSR 在线订阅转换](https://acl4ssr-sub.github.io/)
## 原因分析
请求原始订阅链接获取到base64编码的ss
hiddify-next解析出错, 无法获取正确的"method" "password"

![image](https://github.com/hiddify/hiddify-next/assets/29791674/61d2a29a-f9e0-484b-a760-238240704d6e)

![image](https://github.com/hiddify/hiddify-next/assets/29791674/b50856e4-c7ee-45f0-aeb1-fbeec4f19764)

**Comment by k90ws8** [comment]
Clash和v2订阅支持的协议可以用转换网站
hysteria2[SCP 这个订阅是hy2协议的 好像转换不了
hy2协议的订阅用转换网站显示The following link doesn't contain any valid node info:

**Comment by k90ws8** [comment]
订阅里包含shadowsocks节点的用订阅转换网站可以用了 谢谢

hy2协议的 好像转换不了
hy2协议的节点订阅用转换网站显示The following link doesn't contain any

**Comment by k90ws8** [comment]
用了订阅转换有订阅又出现Block 了
error: ShadowsocksR is deprecated and removed in sing-box 1.6.0
+0800 2023-12-17 16:47:57 ERROR outbound/shadowsocksr[🇯🇵 日本 - 东京 - Datacamp Limited 3]: parse outbound[33] 

<nil> 
error: ShadowsocksR is deprecated and removed in sing-box 1.6.0
+0800 2023-12-17 16:47:57 ERROR outbound/shadowsocksr[🇸🇬 新加坡 - 新加坡 - Akari Networks Limited 4]: parse outbound[58] 


<nil> 


error: ShadowsocksR is deprecated and removed in sing-box 1.6.0
+0800 2023-12-17 16:47:57 ERROR outbound/shadowsocksr[🇨🇳 中国 - 台湾 - Chunghwa Telecom Co., Ltd.]: parse outbound[70] 

<nil> 


error: ShadowsocksR is deprecated and removed in sing-box 1.6.0

error: ShadowsocksR is deprecated and removed in sing-box 1.6.0
+0800 2023-12-17 16:54:28 ERROR outbound/shadowsocksr[🇨🇳 TG频道@mfbpn-2599-CN]: parse outbound[1194] 

<nil> 


error: ShadowsocksR is deprecated and removed in sing-box 1.6.0
+0800 2023-12-17 16:56:03 ERROR [4051601593 5.0s] outbound/urltest[auto]: dial tcp 118.166.246.168:443: i/o timeout
+0800 2023-12-17 16:56:03 ERROR [1566521435 5.0s] outbound/urltest[auto]: dial tcp 118.166.246.168:443: i/o timeout
+0800 2023-12-17 16:56:03 ERROR [1566521435 5.0s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:50523: dial tcp 118.166.246.168:443: i/o timeout

**Comment by hiddify-com** [comment]
I believe that this issue has been resolved in 0.12.0
