### ISSUE TITLE
Error (Xcode): There is no XCFramework  in ios run and build

### ISSUE THREAD

**Issue by sbh96** [hiddify/hiddify-next#246]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when i am running `flutter run` for ios simulator  give me error:

### Reproduce the Bug

Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...                                             12.3s
Running Xcode build...                                                  
Xcode build done.                                           58.7s
Failed to build iOS app
Error (Xcode): There is no XCFramework found at '/Users/behnam/Downloads/hiddify-next/build/ios/framework/release/App.xcframework'.

Error (Xcode): There is no XCFramework found at '/Users/behnam/Downloads/hiddify-next/build/ios/framework/release/Flutter.xcframework'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

### Version

0.11.1

### Platform/OS

iOS

### Additional Context

i think you must add this script in libcore 

 https://stackoverflow.com/questions/69214595/how-to-manually-add-a-xcframework-to-a-flutter-ios-plugin

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
