### ISSUE TITLE
Permission denied on Android 14

### ISSUE THREAD

**Issue by TrackLine** [hiddify/hiddify-next#247]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Fails to start connection to any type of proxy servers with error:
WARN [0000] inbound/tun[tun-in]: bind forwarder to interface: route ip+net: netlinkrib: permission denied 

### Reproduce the Bug

1. Go to the app
2. Tap to Connect
3. Go to the Logs

### Version

0.11.1

### Platform/OS

Android

### Additional Context

Android 14 UQ1A.231205.015
Device: Google Pixel 8 Pro
![Screenshot_20231220-023706](https://github.com/hiddify/hiddify-next/assets/6942458/e64a2671-8501-40b0-9ece-407ff1d58085)

### Relevant log output

```shell
WARN [0000] inbound/tun[tun-in]: bind forwarder to interface: route ip+net: netlinkrib: permission denied
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Google banned netlink socket since Android 11.
