### ISSUE TITLE
V12 unexpected error

### ISSUE THREAD

**Issue by Airuop** [hiddify/hiddify-next#248]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After update app to v12
App crashed
And just show unexpected error with every profile 

### Reproduce the Bug

Update app to v 12
Get profile
Select profile
Start
After start show unexpected error 

### Version

V 12 

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Fixed in [v0.12.2](https://github.com/hiddify/hiddify-next/releases/tag/v0.12.2)
