### ISSUE TITLE
[FR] upgrade to SingBox core 1.7.6

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#252]
### Feature description

درود
لطفا هسته هیدیفای نکست را به سینگ باکس ۱.۷.۶ ارتقا دهید چرا که نسخه ۱.۷ باگ های متعدد برای tuic دارد

سپاس

**Comment by problematicconsumer** [comment]
[v0.12.2](https://github.com/hiddify/hiddify-next/releases/tag/v0.12.2) is based on 1.7.6
