### ISSUE TITLE
clash meta rules not work in it

### ISSUE THREAD

**Issue by netsupcloud** [hiddify/hiddify-next#253]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

clash meta rules not works in it:
also clash meta files are not downloaded:

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,cloudflare.com,DIRECT
  - DOMAIN-SUFFIX,hetzner.com,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,direct,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,PROXY

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://example.com/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://example.com/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 84600

  applications:
    type: http
    behavior: classical
    url: "https://example.com/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

### Reproduce the Bug

clash meta works based on defined rules hiddify doesnt.

### Version

0.12

### Platform/OS

Android, Windows, macOS, Linux, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Duplicate #152
