### ISSUE TITLE
[FR] اجرا نشدن  روی ویندوز

### ISSUE THREAD

**Issue by mehrdad7027R** [hiddify/hiddify-next#254]
### Feature description

من  برنامه رو روی ویندوز نصب  کردم روی Shortcut  کلیک میکنم اما اجرا نمیشه اصلا خطایی هم نمیده

**Comment by alirezaam3** [comment]
منم همین مشکل رو دارم.فقط توی تسک منیجر بازه ولی نمیاره.میبندیش هم دوباره میزنی نمیاره.از ورژن 0.10.0 به بعد نمیاره.با حذف کامل هم درست نشد.برا همون فعلا از 0.10.0 استفاده میکنم.چرا؟؟؟

**Comment by linkho** [comment]
سلام برا منم همینجوره رو ویندوز برنامه اجرا نمیشه بهتر بگم تا نسخه 11 برا من اکیه یعنی درست نصب میشه اجرا هم میشه و مشکلی نداره ولی ای نسخه های بعدش یعنی 12 به بعد کامل نصب میشه بدون هیچ اروری اما برنامه به هیچ وجه اجرا نمیشه نمیدونم چرا لطفا یکی این مشکلو برطرف کنه

**Comment by problematicconsumer** [comment]
برای گزارش باگ از تمپلیت باگ استفاده کنید و توضیحات دقیق بدید.
