### ISSUE TITLE
[Linux] Clicking close button doesn't close the application

### ISSUE THREAD

**Issue by ghost** [hiddify/hiddify-next#255]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

After hitting the close button, the application runs in the background but there is no way to bring it up as it is not visible in the system tray.

This brings up the frustration of accidentally closing the application and trying to run it again only to see that the application does not work because another instance is running. Then I have to kill the first instance using `kill` command or by System Monitor, which is a nuisance.

### Reproduce the Bug

1. Run the AppImage.
2. Hit the (X) button to close the application.
3. Run `ps -ef | grep hiddify`.
4. You can see that the application is still running but is not visible in the system tray.

### Expected Behavior

1. Run the AppImage.
2. Hit the (X) button to close the application.
3. Application is either killed completely or is minimized to the system tray.

### Version

0.12.0

### Platform/OS

Linux

### Additional Context

 I run Debian GNU/Linux 12 and GNOME v43.9 on X11.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
We change the way the app will b eclosed on desktop. Pls update your app
