### ISSUE TITLE
[MacOS] Blank screen on MacOS version

### ISSUE THREAD

**Issue by mahmoud-eslami** [hiddify/hiddify-next#256]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After upgrade to the version 0.12.0 app doesn't run and there is just a blank screen, also app is working normal on the version 0.9.2.
![CleanShot 2023-12-21 at 14 23 37@2x](https://github.com/hiddify/hiddify-next/assets/57481226/8a15dbad-a77a-42a5-b3fc-e002214ae00a)

### Reproduce the Bug

1. Just run the app

### Version

v0.12.0

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Are you running these two versions at the same time?

**Comment by mahmoud-eslami** [comment]
Yes, I changed the name of the older version. However, initially, I upgraded from version 0.11.0 to 0.12.0 and faced this issue. At that time, I was running just one instance.

**Comment by problematicconsumer** [comment]
Running them at the same time (or even using a previous version after using a newer one) can (and in this version definitely will) cause issues.
Please run the following command in your terminal and send the result here: `defaults read app.hiddify.com.plist`

**Comment by problematicconsumer** [comment]
In finder press `command+shift+g` and paste `~/library/Application support/app.hiddify.com`. in the opened folder, there should be a file named `app.log`. Attach here.

**Comment by mahmoud-eslami** [comment]
The file content:
```
17:35:39.362360 - [I] bootstrap: Hiddify Next v0.12.0 (1200) [prod]
general release
macos [Version 14.1.1 (Build 23B81)]
17:35:39.362565 - [I] AutoStartService: auto start is [Disabled]
17:35:39.531108 - [E] ProfileRepositoryImpl: error watching active profile
17:35:39.531226 - [E] ProfileRepositoryImpl: error watching active profile
```
The file itself:
[app.log](https://github.com/hiddify/hiddify-next/files/13742689/app.log)

**Comment by mahmoud-eslami** [comment]
The result:
```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "profile_entries" ("id" TEXT NOT NULL, "type" TEXT NOT NULL, "active" INTEGER NOT NULL CHECK ("active" IN (0, 1)), "name" TEXT NOT NULL, "url" TEXT NULL, "last_update" TEXT NOT NULL, "update_interval" INTEGER NULL, "upload" INTEGER NULL, "download" INTEGER NULL, "total" INTEGER NULL, "expire" TEXT NULL, "web_page_url" TEXT NULL, "support_url" TEXT NULL, PRIMARY KEY ("id"));
INSERT INTO profile_entries VALUES('1f1a62a0-a9d1-441d-b1da-57d125b25a17','remote',1,'TVC | MIX','https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/normal/mix','2023-12-21T17:07:10.390861 +03:30',3600,0,0,10737418240000000,'2050-09-08T16:02:11.000 +04:30','https://github.com/yebekhe/TelegramV2rayCollector','https://t.me/v2raycollector');
INSERT INTO profile_entries VALUES('1f607d26-d0cb-4cca-bc2c-7978fa4a8f5d','local',0,'md3.mydomain.ir',NULL,'2023-12-20T18:07:49.543828 +03:30',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO profile_entries VALUES('161b3c62-2b8c-4ca7-891b-dcd1d9ea7af3','remote',0,'TVC | REALITY','https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/reality','2023-12-21T16:59:19.206930 +03:30',3600,0,0,10737418240000000,'2050-09-08T16:02:11.000 +04:30','https://github.com/yebekhe/TelegramV2rayCollector','https://t.me/v2raycollector');
COMMIT;

```

**Comment by problematicconsumer** [comment]
Thanks for your cooperation, There seems to be a problem with mapping of objects. I'll look into it.

**Comment by mahmoud-eslami** [comment]
Hi new update for this issue on version `0.12.2`

<img width="200" alt="image" src="https://github.com/hiddify/hiddify-next/assets/57481226/89504a09-bfe6-4e75-9223-db66fe37930d">
<img width="200" alt="image" src="https://github.com/hiddify/hiddify-next/assets/57481226/57d02268-9d22-4ee5-9791-44e2f52ca5e8">

The blank screen issue disappeared, but I couldn't add new profile.

this is the log file:
[app.log](https://github.com/hiddify/hiddify-next/files/13759528/app.log)

**Comment by mahmoud-eslami** [comment]
It fixed after delete the sqlite database.
