### ISSUE TITLE
Ver. 0.12.0 is freezing on splash screen (in Android 10 and other smartphones)!

### ISSUE THREAD

**Issue by westsibe** [hiddify/hiddify-next#257]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

App is not launch!

### Reproduce the Bug

1. Launch the app.

### Expected Behavior

Test on Redmi 9 (4/64 GB), Android 10 stock, miui 12.0.4;
Test2 on Huawei (EMUI 9.1), Аndroid 9;
Test3...

### Version

v0.12.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
These were fresh installs or updated from an older version (if so, which version? stable or dev)?

**Comment by westsibe** [comment]
Fresh installs.
(Test3 on Android 12 at other man... The app v0.12.0 is down. Sorry, no details.)

**Comment by westsibe** [comment]
In ver. 0.12.1 - without changes! (app freezing on splash screen in Redmi 9: arm64-v8a)
