### ISSUE TITLE
جدا کردن تنظیمات حرفه‌ای

### ISSUE THREAD

**Issue by Mo3tafa-shafiee** [hiddify/hiddify-next#26]
#ایشونکست
به نظرم مثل خیلی از نرم افزار ها یک گزینه Custom  بذارید که در صورت فعال کردن امکانات مورد نیاز کاربرای حرفه ای تر نمایان بشه .

**Comment by problematicconsumer** [comment]
اسم گمراه‌کننده بود چون اپ نسخه Pro نداره.
همین الان هم تنظیمات advanced یا پیشرفته جداگانه نمایش داده میشه مثل تنظیمات مرتبط با dns و...
دقیق‌تر توضیح بده

**Comment by Mo3tafa-shafiee** [comment]
نه منظورم از حالت عادی یا پیشرفته توی نحوه دسترسی کاربران هست . 
منظورم یه چیزی شبیه به حالت دستی و خودکار نرم‌افزار HiddifyN هست که در حالت دستی تمامی جزئیات در دسترس کاربر هست .

**Comment by hiddify-com** [comment]
اپ قراره به صورت ساده و حرفه ای قابل استفاده باشه 
جدا کردن تجربه خوبی نبود تو HiddifyN
