### ISSUE TITLE
طریقه اضافه کردن سرور وایرگارد به برنامه

### ISSUE THREAD

**Issue by hosseinTSR** [hiddify/hiddify-next#260]
### Feature description

سلام خسته نباشید
از چه طریقی میشه سرور وایرگارد یا وارپ رو داخل برنامه اضافه کرد؟

**Comment by sbh96** [comment]
سلام من هم همین مشکل دارم

**Comment by lymanjre** [comment]
این قابلیت به نسخه جدید اضافه شده است.لطفا آپدیت کنید.
