### ISSUE TITLE
iOS会有吗？

### ISSUE THREAD

**Issue by linzzzzllll** [hiddify/hiddify-next#261]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

iOS会有吗？

### Reproduce the Bug

iOS会有吗？

### Expected Behavior

iOS会有吗？

### Version

iOS会有吗？

### Platform/OS

iOS

### Additional Context

iOS会有吗？

### Relevant log output

```shell
iOS会有吗？
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by chise0713** [comment]
ios的开发者证书挺贵的来着

**Comment by problematicconsumer** [comment]
There definitely will be an iOS version at some point, but since I have little experience with native libraries on iOS and am currently more focused on adding new features for other platforms, progress is slow. It would be nice if you or anyone capable/interested could contribute.

**Comment by GPX-NSlog** [comment]
@problematicconsumer  Hello, I am an iOS developer and I can assist you in listing the App Store
