### ISSUE TITLE
[FR] Default subscription URL

### ISSUE THREAD

**Issue by psjiqi** [hiddify/hiddify-next#262]
### Feature description

Hello, please tell me how to add the default subscription URL in the Android hiddify-next source code.

**Comment by problematicconsumer** [comment]
What do you mean by default subscription url?

**Comment by barry-far** [comment]
> What do you mean by default subscription url?

i think the wanna make their own vpn app using hiddify 😒.

**Comment by psjiqi** [comment]
yes

bardiafa ***@***.***> 于 2023年12月29日周五 23:57写道：
