### ISSUE TITLE
Cannot switch Service Mode

### ISSUE THREAD

**Issue by omidshojaee** [hiddify/hiddify-next#266]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I'm on version 0.12.2 for Windows (installed minutes ago).

I can't switch the Service Mode.

When I click on Proxy or VPN it acts like I've closed the window in the back (Config Options) and it goes back one page (to Settings page).

https://github.com/hiddify/hiddify-next/assets/31741561/9996344c-ed58-44a8-8a5e-0eef165e688e

### Reproduce the Bug

Please refer to attached clip.

### Version

0.12.2

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by barry-far** [comment]
i ran into the same situation :(

**Comment by problematicconsumer** [comment]
Thanks to @RayWangQvQ's PR #267 this issue is fixed. The next minor version will be released soon.
