### ISSUE TITLE
windows-x64-portable.zip file is corrupted for v0.12.(0/1/2)

### ISSUE THREAD

**Issue by neodavinchi** [hiddify/hiddify-next#268]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

hiddify-windows-x64-portable.zip is only 34kb small and contains nothing but 4 files: 1 x ".exe" + 3 x ".url"
(there is no ".dll" files there)
It is true for v0.12.0, v0.12.1, v0.12.2 versions.

### Reproduce the Bug

1. goto https://github.com/hiddify/hiddify-next/releases/tag/v0.12.2
2. click on "hiddify-windows-x64-portable.zip"
3. download
4. unpack all files
5. run "HiddifyNext-portable/HiddifyNext.exe"
6. I've got 4 x System Error windows: "no ***_plugin.dll"

### Expected Behavior

I expect to unpack hiddify-windows-x64-portable.zip, run HiddifyNext.exe and see HiddifyNext windows, like it is for the 0.11.1 release.

### Version

v0.12.0, v0.12.1, v0.12.2

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Fixed, new version will soon be released with portable version.
