### ISSUE TITLE
MACOS minimum req is 10.15

### ISSUE THREAD

**Issue by rony432** [hiddify/hiddify-next#269]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

MACOS minimum req is 10.15 please update info on minimum req from 10.14 to 10.15

### Reproduce the Bug

 0

### Expected Behavior

0

### Version

0.12.2

### Platform/OS

macOS

### Additional Context

 0

### Relevant log output

```shell
0
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
In earlier iterations, minimum version was 10.14, but this recently changed. I'll update documentation.
