### ISSUE TITLE
 Ignore and Later buttons don't work in software update alert dialog

### ISSUE THREAD

**Issue by mahmoud-eslami** [hiddify/hiddify-next#27]
OS: macOS Sonoma 14.0

#### Description:

After each update, I get an alert dialog saying a new update is available. However, when I click the "Ignore" or "Later" buttons in the dialog, it briefly closes and reopens immediately.

It seems these updates are being treated as mandatory updates, though the dialog displays the Ignore/Later options. I'm unable to postpone or skip the updates even though those buttons are present.

**Comment by problematicconsumer** [comment]
This issue was fixed in [0.7.2](https://github.com/hiddify/hiddify-next/releases/tag/v0.7.2). feel free to reopen if that's not the case.
