### ISSUE TITLE
Enhancement of Proxy Configuration Flexibility for Diverse Network Environments

### ISSUE THREAD

**Issue by yihong1120** [hiddify/hiddify-next#270]
### Feature description

Dear Contributors,

I hope this message finds you well. I am reaching out to suggest an enhancement to the Hiddify-Next project that could significantly improve its utility in a variety of network environments, particularly those subject to stringent internet regulations.

**Current Limitation:**
At present, the application's proxy configuration is somewhat rigid, which may hinder its performance in certain scenarios. Users in regions with complex network restrictions often require a more dynamic setup to navigate these constraints effectively.

**Proposed Enhancement:**
It would be highly beneficial to introduce a feature that allows for more granular control over proxy rules and conditions. This could include, but is not limited to, the ability to specify proxy usage based on domain names, IP ranges, or application types. Additionally, the integration of conditional proxy routing based on network status or time of day could offer further adaptability.

**Potential Impact:**
Such an enhancement would not only bolster the application's versatility but also empower users in restrictive regions to maintain consistent access to the free internet. It aligns with the project's ethos of providing secure and private tools for internet accessibility.

**Conclusion:**
I believe this proposal warrants consideration and would be happy to contribute to the discussion and development process. I look forward to your thoughts on this matter.

Best regards,
yihong1120

**Comment by problematicconsumer** [comment]
Duplicate #210 (if I'm not mistaken about what's your fr). Would be great if you could contribute as well.
