### ISSUE TITLE
عدم درج geoip:af در بخش ریجن برای بای پس

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#271]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

درود
چند هفته ست که در فایل geoip.db شکلات نیز، geoip:af اضافه شده است ، در حالیکه هنوز در هیدیفای نکست امکان انتخاب ریجن Afghanistan وجود ندارد

لطفا در بروزرسانی بعدی، این مورد را اضافه فرمایید.

سپاس بی کران

### Reproduce the Bug

.

### Version

0.12.2

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
توی readme چیزی در این مورد نگفتن البته. اضافه میکنم.

**Comment by problematicconsumer** [comment]
اضافه شد

**Comment by Graveyard9988** [comment]
> توی readme چیزی در این مورد نگفتن البته. اضافه میکنم.

در ایشو ها اعلام کردن که geoip:af در geoip.db اضافه شده خیلی وقته

**Comment by Graveyard9988** [comment]
> اضافه شد

سپاس بی کران

**Comment by Graveyard9988** [comment]
فقط از بابت geosite:af بررسی کنید چرا که دولوپر شکلات احتمالا فقط geoip:af را اضافه کرده باشن

**Comment by Graveyard9988** [comment]
https://github.com/Chocolate4U/Iran-sing-box-rules/issues/7
