### ISSUE TITLE
portable.zip运行没有反应

### ISSUE THREAD

**Issue by Yuan84** [hiddify/hiddify-next#273]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

hiddify-windows-x64-portable.zip  windows11 运行后没有反应

### Reproduce the Bug

1. 解压
2. 运行后没有任何反应

### Version

v0.12.3

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lance52587** [comment]
same question

**Comment by problematicconsumer** [comment]
There was a problem in packaging windows portable release, which was fixed for 0.13.x. use [0.13.0 dev](https://github.com/hiddify/hiddify-next/releases/tag/v0.13.0.dev) for now.
