### ISSUE TITLE
Application Opens Multiple Instances With Each Click on Icon

### ISSUE THREAD

**Issue by thejianyu** [hiddify/hiddify-next#277]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The issue occurs when attempting to launch the application using its desktop icon. Instead of focusing on the existing instance, the application creates a new one with each click on the icon. This behavior leads to the accumulation of multiple instances of the application, causing inconvenience and potential performance issues which may lead to connection problems.

### Reproduce the Bug

1. Launch the application by clicking on its desktop icon.
2. Observe that a new instance of the application opens.
3. Repeat step 1, and notice that each click results in the creation of an additional instance.

### Expected Behavior

The application should open only one instance when clicking on the icon. Subsequent clicks on the icon should bring focus to the already running instance without creating new ones.

### Version

v0.12.3

### Platform/OS

Windows

### Additional Context

![image](https://github.com/hiddify/hiddify-next/assets/109133022/75b3c605-1409-40c1-bedd-86a77555905c)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Fixed, will be included in next release. Thanks for reporting.
