### ISSUE TITLE
Windows 11 Security Flags Hiddify App Installer as a Virus

### ISSUE THREAD

**Issue by thejianyu** [hiddify/hiddify-next#278]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When attempting to install the Hiddify app, the extraction process from the compressed file triggers Windows Security to identify the installer as a potential virus. Consequently, Windows Security blocks the execution of the installer unless the user disables Windows Security. This detection and subsequent blockage may cause concern and apprehension among users, potentially deterring them from proceeding with the installation.

### Reproduce the Bug

1. Download the Hiddify app installation file from the official source.
2. Extract the installation file from the compressed archive.
3. Attempt to run the installer.
4. Windows 11 Security detects the installer as a potential virus and blocks its execution.
5. Users are prompted to disable Windows Security to proceed with the installation.

### Expected Behavior

The Hiddify app installer should be extracted and executed without triggering Windows Security warnings. Users should be able to install the application seamlessly without the need to disable Windows Security. This would ensure a smoother and more user-friendly installation process.

### Version

v0.12.3

### Platform/OS

Windows

### Additional Context

![image](https://github.com/hiddify/hiddify-next/assets/109133022/279aec34-b6ab-4a17-b919-e1ebe50c77f4)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
