### ISSUE TITLE
on windows total upload traffic has a bug: its not accumulating

### ISSUE THREAD

**Issue by amihos** [hiddify/hiddify-next#280]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

on windows app, on the buttom left side which shows trrafic stats, the total traffic for upload is resetting all the time and is not accumulating the uploads

![image](https://github.com/hiddify/hiddify-next/assets/35190548/bbe48ac9-f58c-49e7-9ed3-0d2df81c8992)

### Reproduce the Bug

open windows app and connect to the server and watch the traffic stats on the buttom left side

### Expected Behavior

it should show upload traffic accumulating in total section but its resetting acting like speed.

### Version

0.12.3

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
It's not a bug, traffic doesn't accumulate for now.

**Comment by amihos** [comment]
> It's not a bug, traffic doesn't accumulate for now.

but download does. only upload does not.
