### ISSUE TITLE
Where is "Run Config As Is" Feature?

### ISSUE THREAD

**Issue by alidxdydz** [hiddify/hiddify-next#282]
### Feature description

سلام.
قبلا این گزینه بود، چرا حذف کردید؟
با فرگمنت به مشکل خوردم که فکر مینم مشکل همینه.

https://github.com/redpilllabs/Rainb0w-Lite/issues/4#issuecomment-1872598296

**Comment by problematicconsumer** [comment]
متاسفانه خیلی از کاربرا با وجود اینکه این فیچر فقط در حالت دیباگ مود فعال بود مشکل داشتن و باعث کرش برنامه میشد. فعلا این فیچر رو نمیتونم اضافه کنم، اج‌کیس زیاد هست.
در مورد کانفیگ در نظر داشته باش ما فقط قسمت outbound کانفیگ رو استفاده میکنیم و بقیه قسمت‌ها نادیده گرفته میشه. تنظیمات بیشتر اضافه میشه برای تغییر کانفیگ.

**Comment by alidxdydz** [comment]
@problematicconsumer

متاسفانه قسمت outbound که من تعریف میکنم کار نمیکنه.
فرض کن میخوام فقط یه DoH و Fragment Outbound تعریف کنم و سایت غیرفیلتر یا یوتیوبو باز کنم.
ولی کلاینت هیدیفای دنبال urltest میگرده و rule اضافه میکنه.
یه لینک ایشو اضافه کردم و اونجا هم توضیح دادم.

**Comment by problematicconsumer** [comment]
قسمت outbound فقط direct, block و urltest حذف میشه و بقیه با تغییرات حداقلی میمونن.
ایشو رو چک کردم، pr روی کور به زودی مرج میشه فعلا درگیر بقیه قسمت‌ها هستیم.
در ضمن میتونی با تنظیمات مختلف از کانفیگت خروجی json بگیری از داخل اپ و ببینی چه تغییراتی داده و دقیقا چی داره اجرا میشه.
