### ISSUE TITLE
TUN mode not working on some windows devices

### ISSUE THREAD

**Issue by dfaa241b** [hiddify/hiddify-next#283]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

TUN mode is not working on some windows devices. 
To get it working you have to manually add route to your server's IP address via default network adapter.
`route add XX.XX.XX.XX 192.168.1.1 MASK 255.255.255.255 METRIC 2 IF XX`

### Reproduce the Bug

TUN mode doesn't work on random devices

### Version

v0.12.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by dbsxdbsx** [comment]
I am new here. And I think this repo currently is nearly perfect except no tun mode.

**Comment by good-bay** [comment]
> I am new here. And I think this repo currently is nearly perfect except no tun mode.

VPN mode=tun mode

**Comment by dbsxdbsx** [comment]
> > I am new here. And I think this repo currently is nearly perfect except no tun mode.
> 
> VPN mode=tun mode

Thanks. Now  I set it like this:
![image](https://github.com/hiddify/hiddify-next/assets/17372655/973c74f2-1c9e-4f5d-8178-777489ecf58e)
I guess it is the correct tun setting, right? 

By the way, when looking into the code, it seems that the sing-box code is from `libcore/bin/libcore.h`, but I didn't find the file. And I also didn't find the c file and corresponding library. And I wonder how is the file `/singbox_generated_bindings.dart` generated.

**Comment by good-bay** [comment]
> > > I am new here. And I think this repo currently is nearly perfect except no tun mode.
> > 
> > 
> > VPN mode=tun mode
> 
> Thanks. Now I set it like this: ![image](https://private-user-images.githubusercontent.com/17372655/294853054-973c74f2-1c9e-4f5d-8178-777489ecf58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDgyNTQsIm5iZiI6MTcwNDcwNzk1NCwicGF0aCI6Ii8xNzM3MjY1NS8yOTQ4NTMwNTQtOTczYzc0ZjItMWM5ZS00ZjVkLTgxNzgtNzc3NDg5ZWNmNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5NTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYmUyNjgxNGZkNmMxMWExY2IwYTM0NzBmMTkzYjkyZDg2NGYyNDFkNTg3MzJhZmNjZGE0MjM2NGZjYjc2ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9HWckPwc_UztjAdXV3foWs9jM90DGBYmr5-Lyyd1guM) I guess it is the correct tun setting, right?
> 
> By the way, when looking into the code, it seems that the sing-box code is from `libcore/bin/libcore.h`, but I didn't find the file. And I also didn't find the c file and corresponding library. And I wonder how is the file `/singbox_generated_bindings.dart` generated.

I only know that the VPN mode is TUN mode, but I don’t know the specific settings.

**Comment by dbsxdbsx** [comment]
> > > > I am new here. And I think this repo currently is nearly perfect except no tun mode.
> > > 
> > > 
> > > VPN mode=tun mode
> > 
> > 
> > Thanks. Now I set it like this: ![image](https://private-user-images.githubusercontent.com/17372655/294853054-973c74f2-1c9e-4f5d-8178-777489ecf58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDgyNTQsIm5iZiI6MTcwNDcwNzk1NCwicGF0aCI6Ii8xNzM3MjY1NS8yOTQ4NTMwNTQtOTczYzc0ZjItMWM5ZS00ZjVkLTgxNzgtNzc3NDg5ZWNmNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5NTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYmUyNjgxNGZkNmMxMWExY2IwYTM0NzBmMTkzYjkyZDg2NGYyNDFkNTg3MzJhZmNjZGE0MjM2NGZjYjc2ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9HWckPwc_UztjAdXV3foWs9jM90DGBYmr5-Lyyd1guM) I guess it is the correct tun setting, right?
> > By the way, when looking into the code, it seems that the sing-box code is from `libcore/bin/libcore.h`, but I didn't find the file. And I also didn't find the c file and corresponding library. And I wonder how is the file `/singbox_generated_bindings.dart` generated.
> 
> I only know that the VPN mode is TUN mode, but I don’t know the specific settings.

After testing, I think this setting is correct for TUN.

**Comment by good-bay** [comment]
> TUN mode

I tried TUN mode but it doesn't work!

**Comment by dbsxdbsx** [comment]
> > TUN mode
> 
> I tried TUN mode but it doesn't work!

Weird, mine(version 0.13.6) worked on win10.

**Comment by good-bay** [comment]
> > > TUN mode
> > 
> > 
> > I tried TUN mode but it doesn't work!
> 
> Weird, mine(version 0.13.6) worked on win10--- Oh, yes, you must restart the app to make the tun mode initilazed successful.

I am also running a Windows 10 system here, but I have adjusted all the parameters and cannot use TUN mode.

**Comment by dfaa241b** [comment]
> > TUN mode
> 
> I tried TUN mode but it doesn't work!

Try adding route to your proxy server via physical adapter with metric 1 while VPN/TUN is active, check for virtual TUN adapter called singbox in network control panel.

**Comment by good-bay** [comment]
我的物理网络适配器的IP：192.168.1.6，在虚拟网络适配器中如何添加路由？
![Uploading 虚拟网络.PNG…]()

**Comment by Onair-santa** [comment]
Yes TUN/VPN  mode not work. Need add route

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
