### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by realartin** [hiddify/hiddify-next#285]
### Feature description

با عرض درود و خسته نباشید
بابت این کلاینت و زحمات شما صمیمانه متشکرم 

به نظر من ۴ تا مسئله مهم توی هیدیفای نکست واقعا جای خالی اش احساس میشه که اگر اضافه بشه یک کلاینت به تمام معنا هست که البته بیشتر این قابلیت هارو بقیه کلاینت های مطرح دارند

۱- قابلیت mux مشابه بقیه کلاینت ها

۲- قابلیت تغیر هسته در کلاینت به xray

3-قابلیت کاستوم روتینگ داخل کلاینت که کاربر بتونه روتینگ مناسب خودش رو تعین کنه مثلا ایپی های لوکال مدنظر یوزر یا سایت های مدنظر یوزر رو بتونه به صورت دستی از بخش روتینگ داخل کلاینت اضافه کنه به عنوان :

 bypass , proxy , block

۴- ساپورت DOH , DOT

**Comment by problematicconsumer** [comment]
امکان تغییر هسته نیست
برای بقیه موارد ایشو هست و اضافه میشه اگر نیست لطفا ایشوهای جداگانه با توضیحات باز کنید
