### ISSUE TITLE
hiddify next开启代理的情况下更新路由资源文件提示“连接超时”

### ISSUE THREAD

**Issue by thisisjin** [hiddify/hiddify-next#286]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

hiddify next开启代理的情况下更新路由资源文件提示“连接超时”
![image](https://github.com/hiddify/hiddify-next/assets/22115417/a2ce1c8a-a182-4b4c-8c0c-81370ced353d)

### Reproduce the Bug

1.开启“系统代理”；2、打开“设置-路由资源文件”；3.点击更新，提示链接超时。

### Expected Behavior

我通过开启其他APP的TUN代理模式，完成了文件的更新。再就是有个疑问，服务方式的“仅代理”、“系统代理”、“VPN”这三种模式有何不同

### Version

0.12.3

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
