### ISSUE TITLE
MacOs 10.13.6

### ISSUE THREAD

**Issue by Pipo4713** [hiddify/hiddify-next#29]
You can't use this version of the application
"HiddifyNext 2" with this version of macos.
You have macOS 10.13.6. The application requires macOS 10.14 or later.
لطفا اپلیکیشن را برای ورژنهای پایینتر از ۱۰.۱۴ در مک فعال کنید.تشکر

**Comment by problematicconsumer** [comment]
Unfortunately, the lowest possible version of macOS for us to support in Hiddify Next is 10.14 (Mojave) due to upstream constraints
