### ISSUE TITLE
切换geoip.db和geosite.db后代理依然是全局模式

### ISSUE THREAD

**Issue by Jonnyan404** [hiddify/hiddify-next#291]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

- 系统: Android12 MIUI14.0.5
- hiddify next版本: 0.12.2

在路由资源文件里,切换另外2个geoip和geosite,并且重新开启代理后,依然是全局代理,没有跳过大陆和局域网.

### Reproduce the Bug

1. 点击更换 geoip和geosite
2. 重新连接代理
3. 浏览器打开百度,搜索关键字 本机IP,依然会显示代理IP.

### Expected Behavior

1. 国内网站直连,国外网站走代理
2. 或者提供跳过大陆和局域网选项
3. 或者像clash和singbox一样执行用户订阅里的自定义规则

### Version

0.12.2

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Currently, there's no way for the end user to add custom routing rules (will be added soon #210). There are some default rules based on region. Make sure you've selected "CN" as your region from the settings page. This should work fine for most cases.

**Comment by Just-dmc** [comment]
> Currently, there's no way for the end user to add custom routing rules (will be added soon #210). There are some default rules based on region. Make sure you've selected "CN" as your region from the settings page. This should work fine for most cases.

另外，选择中国，谷歌商店不可以下载。可以浏览

**Comment by mike8689** [comment]
我使用1.1.1 ，I am using Hiddify in China, and currently all Tencent apps are unusable.

**Comment by mario-huang** [comment]
> > Currently, there's no way for the end user to add custom routing rules (will be added soon #210). There are some default rules based on region. Make sure you've selected "CN" as your region from the settings page. This should work fine for most cases.
> 
> 另外，选择中国，谷歌商店不可以下载。可以浏览

Me too.
