### ISSUE TITLE
Turn on Auto Connect On Desktop [FR] 

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [hiddify/hiddify-next#294]
### Feature description

In v0.13.1 I noticed that the Auto Connect feature is disabled in Windows, this feature is present in all Windows clients and I strongly request you to put it back in the HiddifyNext app features.
Thanks to  wonderful HiddifyNext team🧡

**Comment by papampi** [comment]
+1 for linux as well

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
