### ISSUE TITLE
i connected successfully but i cant browse any website in my local country

### ISSUE THREAD

**Issue by stephydengfifi** [hiddify/hiddify-next#295]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i connected successfully but i cant browse any website in my local country

### Reproduce the Bug

i connected successfully but i cant browse any website in my local country

### Version

hiddify-windows-x64-setup

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Choose appropriate region from settings (if present) or wait for #210
