### ISSUE TITLE
Rule-set compactibility for Sing-Box 1.8.x

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#299]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

.

### Reproduce the Bug

Here is the resource of new geo files of Iran and other countries:

Bypassing ([based on Chocolate4U](https://github.com/Chocolate4U/Iran-sing-box-rules/tree/rule-set)) :

https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-ir.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-ir.srs

https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-af.srs

https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-cn.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-cn.srs

https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-ru.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-ru.srs

[Blocking](https://github.com/Chocolate4U/Iran-sing-box-rules/tree/rule-set):

https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-category-ads-all.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-malware.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-phishing.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-cryptominers.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-malware.srs
https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-phishing.srs

others:
https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geoip/geoip-cn.srs
https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cn.srs
https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-geolocation-cn.srs  (bypass)
https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-companies@cn.srs  (bypass)

### Version

0.13.5

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
