### ISSUE TITLE
App does not start on android 

### ISSUE THREAD

**Issue by Ashrafty** [hiddify/hiddify-next#3]
i managed to configure the everything....but upon compiling it just doesn't work like the android app stops on the splash screen and for linux and windows it just doesn't work it throws these long errors like a billion of them...so back to square one....am just getting into coding and your project fascinates me allot...so i was requesting you configure this nice project for windows as well

**Comment by hiddify1** [comment]
This project is still under development

We will announce whenever we publish the early version

**Comment by Ashrafty** [comment]
okay sorry for the pressure
