### ISSUE TITLE
Not displaying the auto selected server

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [hiddify/hiddify-next#300]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hi, in version 0.13.5 the auto selected server is not displayed, this problem was not in previous versions.

### Reproduce the Bug

1. Go to HiddifyNext app
2. Start / ON VPN
3. Enter the Configs section
4. Auto config selector

### Version

v0.13.5

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by amihos** [comment]
0.13.6
The problem still exists!

**Comment by SKRapToR20** [comment]
i have the same problem in v0.13.5 and v0.13.6, please fix this.

**Comment by zodiacc7** [comment]
خیلی اذیت میکنه لطفا درستش کنید

**Comment by SKRapToR20** [comment]
it's useless now ! fix if bro, fix it !

**Comment by amihos** [comment]
The problem still exists on version 0.14.20

However, I noticed that there are some subscription links which hiddify shows to which server it connects and there are some for which it does not!

Both of these subscriptions are generated by the same panel.

**Comment by lymanjre** [comment]
This is because of Sing box update not a bug in Hiddify next
