### ISSUE TITLE
نسخه ویندوز کار نمیکنه

### ISSUE THREAD

**Issue by corvtte** [hiddify/hiddify-next#302]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

میزنم رو برنامه که باز بشه یه ویندوز به صورت تمام سفید باز میشه بعد دو ثانیه خودکار بسته میشه کلا از نسخه 11 به بعد هیچ کدوم از نسخه ها برا من کار نمیکنه قبلیا که کلا باز نمیشد اینم که باز میشه اینجوریه
![image](https://github.com/hiddify/hiddify-next/assets/155023632/67632529-98eb-45b0-8f9a-caf8effdb95e)

### Reproduce the Bug

white screen

### Version

0.13.6

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by corvtte** [comment]
> پاک کن از نو نصب کن ببین مشکل پابرجاست یا نه

به صورت کامل پاک کردم از اول نصب کردم بازم همون جوریه

**Comment by problematicconsumer** [comment]
آدرس `%AppData%\Hiddify\hiddify` رو توی آدرس‌بار اکسپلورر ویندوز وارد کن. توی فولدر باز شده فایل app.log هست اونو بفرست

**Comment by MahanGame150** [comment]
اقا منم ویندوزم 10 عه برای منم باز نمیشه چکار  کنیم ؟

**Comment by mahdi-mb** [comment]
سلام متاسفانه هیچ کدوم از ورژن ها روی ویندوز ۱۰ اجرا نمیشن فقط چند ثانیه یه صفحه ی سفید میاد و بدون هیچ پیام خطا یا اروری بسته میشه ورژن پرتابل هم همینچوریه

**Comment by amirsajjadieh** [comment]
سلام
نرم افزار ویندوز به صورت اتوماتیک کانک نمیشه و هر وقت ویندوز ری ایتارت میکنیم باید بصورتدستی برنامه را فعال کنیم
در تنظیمات برنامه stat at login فعاله
