### ISSUE TITLE
[FR] تغییر رنگ ایکن نرم افزار کنار ساعت هنگام متصل بودن

### ISSUE THREAD

**Issue by abedin70** [hiddify/hiddify-next#304]
### Feature description

لطفا کاری کنید وقتی نرم افزار متصل هست ایکن پایین کنار ساعت هم رنگش تغییر کنه مثلا قرمز یا سبز یا...
ممنون
![2024-01-09_121658](https://github.com/hiddify/hiddify-next/assets/18644417/6d25e298-bad9-4e11-aa72-9f81565ff6a7)

**Comment by lymanjre** [comment]
این فیچر قبلا درخواست شده و در لیست قرار گرفته است. این ایشو فعلا بسته می شود
