### ISSUE TITLE
[FR] Add update all assets 

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#306]
### Feature description

It would be nice to have "Update all assets" and "Update in use assets" in routing assets 3 dots menu, instead of clicking them one by one

**Comment by papampi** [comment]
In "Assets Config" page all sub menus (3 dots)  has only one option 
We can have one less click if remove 3 dots menu and just have an update icon

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
