### ISSUE TITLE
Windows Size and Position

### ISSUE THREAD

**Issue by ten2120** [hiddify/hiddify-next#307]
### Feature description

درود،
لطفا یک گزینه برای یادآوری اندازه پنجره و مکان پنجره اضافه کنید. برنامه بعد از هر بار اجرا، هم آخرین مکان و هم آخرین سایزی که تغییر داده شده بود رو بیاد بیاره. 
در آخرین نسخه، برنامه بعد از هربار اجرا، (تقریبا) در گوشه بالا سمت چپ اسکرین و در حالت ماکسیمایز (نه فول اسکرین) باز میشه.
سپاس.

**Comment by problematicconsumer** [comment]
Duplicate #298
