### ISSUE TITLE
Routing assets update/download failed. Unexpected connection error.

### ISSUE THREAD

**Issue by HumanMus1c** [hiddify/hiddify-next#308]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I try to update and download routing assets, caused one error all the time with or without proxy.

![image](https://github.com/hiddify/hiddify-next/assets/46023154/b94edb7c-2559-4dd2-ba12-5bca7cd30601)
![image](https://github.com/hiddify/hiddify-next/assets/46023154/5a90edc0-f90f-4604-84d5-025c35cbbf9a)

### Reproduce the Bug

1.go to settings - Routing Assets
2.update or download Assets.
3.error.

### Version

v13.6

### Platform/OS

Windows

### Additional Context

[box.log](https://github.com/hiddify/hiddify-next/files/13872250/box.log)
[app.log](https://github.com/hiddify/hiddify-next/files/13872251/app.log)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
