### ISSUE TITLE
باگ بر روی ورژن 0.8 جهت اضافه نکردن لینک هیستریا 2

### ISSUE THREAD

**Issue by Bahmei** [hiddify/hiddify-next#31]
داخل این ورژن هر کاری میکنم جهت اضافه کردن لینک هیستریا 2 بهم ارور میده.
این متن ارور هست
Invalid Configs

decode config: invalid character

'h' looking for beginning of value:

row 1, column 1

**Comment by hiddify-com** [comment]
fixed in 0.8.1

**Comment by Bahmei** [comment]
الان داخل ورژن 0.8.1 لینک هیستریا 2 اضافه میشه ولی زمانی که دکمه اتصال رو میزنیم دلخل تب proixes زیر اسمس کانکسنمون میزنه بلاک و دیتای ردو بدل نمیشه
