### ISSUE TITLE
Android App gets killed by LMK (possibly?!)

### ISSUE THREAD

**Issue by deathline94** [hiddify/hiddify-next#310]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

after connecting to a server and then locking the phone for about 15 mins , app and vpn connection gets dropped from background and auto closes.
android 13 , battery optimizer features are off , memory limiter is off.

### Reproduce the Bug

Connect to a server , lock the phone and set it aside . wait for 15 mins , VOILA

### Version

13.6 stable

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
