### ISSUE TITLE
[EN] app on ios (iphone)

### ISSUE THREAD

**Issue by AvatarStark** [hiddify/hiddify-next#311]
### Feature description

Very good app and very requested one that they have made here, I come to make a suggestion to see if you could fulfill it, I could release this app on iPhone because there are several people who use iPhone and there is no application like it is available on iOS devices

**Comment by hiddify-com** [comment]
We wantbto release it on app store but we face with validation failed
Would you please help us?

**Comment by AvatarStark** [comment]
> We wantbto release it on app store but we face with validation failed Would you please help us?

yes of course, if it is in my hands with pleasure
