### ISSUE TITLE
Not displaying any contents on MacOS 11

### ISSUE THREAD

**Issue by bingsunny0730** [hiddify/hiddify-next#312]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i installed this dmg file，but display nothing in the surface. Only top menu is displayed. I can hardly use the software.  How can i do?

### Reproduce the Bug

when opening the software, no display everything, include surface texts & contents.

### Expected Behavior

Please fix this bug.

### Version

v1.3.6

### Platform/OS

macOS

### Additional Context

![macOS 11-2024-01-10-17-07-38](https://github.com/hiddify/hiddify-next/assets/131505889/914aa904-888e-4bed-ae0e-861c44780c12)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
In finder press `command+shift+g` and paste `~/library/Application support/app.hiddify.com`. in the opened folder, there should be a file named `app.log`. Attach here.

**Comment by bingsunny0730** [comment]
![sshot-18889997](https://github.com/hiddify/hiddify-next/assets/131505889/0735b88a-5727-4eea-9689-484bcdb85eef)
sry, i forgot to reply😱. I followed your guide to do that, but it showed no this file. 
![GIF 2024-1-25 19-42-30](https://github.com/hiddify/hiddify-next/assets/131505889/423fe323-036d-4948-924a-070bac67ba65)
Anyway, i installed the latest version  0.14.20 & the same problem occured. Could it be an error with the installation package?

**Comment by lymanjre** [comment]
Follow the instructions and solve the error
