### ISSUE TITLE
اعمال نشدن فیلترشکن برای اپ رسمی تلگرام روی مک

### ISSUE THREAD

**Issue by mnhiddify** [hiddify/hiddify-next#32]
سلام وقت بخیر  
hiddify next 0.8.0
رو macOS
اتصال و وب گردی و اپ واتس اپ مشکلی نداره ولی اپ تلگرام وصل نمیشه
با اپ v2box , foxray اوکی هستش

**Comment by danaenayati** [comment]
سلام من هم این مشکل رو دارم! مک m1 pro

**Comment by lymanjre** [comment]
ایشو مشابه شما در دست بررسی است. این ایشو بسته میشود

**Comment by alizera** [comment]
> ایشو مشابه شما در دست بررسی است. این ایشو بسته میشود

ممنون. کدوم ایشو؟
