### ISSUE TITLE
[FR]用户自定义规则和规则集

### ISSUE THREAD

**Issue by istek** [hiddify/hiddify-next#324]
### Feature description

希望在安卓客户端和桌面客户端，增加用户自定义规则和规则集，可以考虑使用singbox 1.8以后新增的2进制规则集，使得HN可以以规则形式代理数据流量。

**Comment by lymanjre** [comment]
1st: Pls type in english.
2nd: This feature is requested by ppl several time and we are gonna making it happen. Be patient pls
