### ISSUE TITLE
تشخیص ویروس، virustotal

### ISSUE THREAD

**Issue by Hosseyn1402** [hiddify/hiddify-next#33]
ویروس توتال
اپ هیدیفای نکست رو ویروسی تشخیص میده!!!
![Screenshot_20231006_022142_MiXplorer](https://github.com/hiddify/hiddify-next/assets/125098403/a011e801-824c-4fa5-9eee-3aa57447df15)

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود

**Comment by pouriavelaei** [comment]
ویندوز دفندر ابتدای دانلود جلوش میگیره میگه ویروسه
