### ISSUE TITLE
هیدیفای نمست iOS

### ISSUE THREAD

**Issue by AmirShayanH** [hiddify/hiddify-next#330]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

درود دوستان. وقتتون بخیر.
امروز نسخه iOS رو‌در تست فلایت منتشر مردین. اما بعد از مدت کوتاهی لینک مربوط به تست فلایت غیرفعال شده.
راهنمایی میفرمایید که مشکل از کجاس؟

### Reproduce the Bug

.

### Version

0.13.6 dev

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by amirsaam** [comment]
that was only an initial release to gather info about bugs, link was expired due to some technical issues that needs to be fixed then a new build will be pushed to testflight
