### ISSUE TITLE
Android Crash - Keeps Disconnecting 

### ISSUE THREAD

**Issue by alidxdydz** [hiddify/hiddify-next#331]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام.
ساب مروبوط به کانفیگهای YeBeKhe اضافه شدو گزینه TLS Fragment فعال شد.
بعد 5 دقیقه تو پس زمینه دیسکانکت میشه.
هم vless که به Fragment نیاز داره
هم tuic که به Fragment نیاز نداره

احتمال میدم هر دو مورد دلیل دیسکانکت شدن هستن.
باگ TLS Fragment
تعداد بالای کانفیگ تو هر ساب که selector و test هنگ میکنه.
کاش مثلا وقتی داخل یه ساب بیشتر از 50 تا کانفیگ قرار داره، ساب رو تو چند پارت 50 کانفیگی اضافه کنه

### Reproduce the Bug

اضافه کردن ساب YeBeKhe
فعال کردن TLS Fragment
وصل شدن به vless و tuic و ...

### Version

v0.13.16

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
لطفا اپ را به آخرین نسخه آپدیت نمایید. مشکل حل شده است.
