### ISSUE TITLE
Shadowsocks 2022

### ISSUE THREAD

**Issue by pvolkov** [hiddify/hiddify-next#333]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

An error is observed when using Shadowsocks 2022 (based on X-UI) and Hiddify Next. I am creating a new SS2022 inbound with the following characteristics:
![01](https://github.com/hiddify/hiddify-next/assets/457569/3b3548ee-bf7a-4b50-b9ba-6d646e28e87a)

I add the subscription to Hiddify Next, select SS2022. When checking the availability of connections, the check for SS2022 shows nothing.
![02](https://github.com/hiddify/hiddify-next/assets/457569/e76e0ce3-73e6-482c-bce7-551715ea5f4c)

Am I doing something wrong?

PS. I tested the subscription link in v2rayNG, and SS2022 works there.

### Reproduce the Bug

1. Create Shadowsocks inbound
2. Encryption "2022-blake3-aes-256-gcm"
3. Add Subscription link to Hiddify Next
4. Select Shadowsocks

### Expected Behavior

When selecting SS2022, the connection will be established.

### Version

0.13.6

### Platform/OS

Android, Windows, macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mike-vines** [comment]
I believe, https://github.com/hiddify/ray2sing/pull/3 should fix this.

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
