### ISSUE TITLE
[FR] proxy-by-apps page add clipboard import function

### ISSUE THREAD

**Issue by XieyilinMain** [hiddify/hiddify-next#337]
### Feature description

Proxy apps like AnXray and CatBox supports importing and exporting per-app bypass settings via clipboard, which may be more seamlessly when switch between these proxy apps.

It' s one great function for those who want to switch to Hiddify from other proxy apps

![Screenshot_2024-01-15-11-37-50-424_moe cb4a-edit](https://github.com/hiddify/hiddify-next/assets/130215387/d362d192-65c0-448f-b556-7f72a53e6b0c)

**Comment by lymanjre** [comment]
this feature is requested several times and we are going to develop it. pls be patient. This issue will be transformed to the project and I will close it here.
