### ISSUE TITLE
No podspec found for `Libcore` in `./Frameworks/Libcore.xcframework`

### ISSUE THREAD

**Issue by aweifly** [hiddify/hiddify-next#339]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

cd ios,  pod install, then:  No podspec found for `Libcore` in `./Frameworks/Libcore.xcframework`

### Reproduce the Bug

No podspec found for `Libcore` in `./Frameworks/Libcore.xcframework`

### Version

v0.13.6

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kamyarst** [comment]
@aweifly same issue here, how did you manage to fix it?
