### ISSUE TITLE
کانفیگ های هیستریای دو رو در ورژن نسخه 8 قبول نمیکنه

### ISSUE THREAD

**Issue by Amirraan** [hiddify/hiddify-next#34]
ارورشم اینه

Failed to add profile
Invalid Configs
decode config: invalid character
'h looking for beginning of value:
row 1, column 1

**Comment by lymanjre** [comment]
ایشو مشابه ایشوی شما ثبت شده و‌در دست بررسی هست. بنابراین این ایشو بسته میشود
