### ISSUE TITLE
[FR] hiddify开机不能自动连接

### ISSUE THREAD

**Issue by hou6807628** [hiddify/hiddify-next#341]
### Feature description

开机无法自动连接，版本号0.13.6，需要手动点击连接

**Comment by hou6807628** [comment]
之前的0.12可以

**Comment by problematicconsumer** [comment]
This feature has been removed. Will be added in future

**Comment by Pandolar** [comment]
> This feature has been removed. Will be added in future

So, why was this feature canceled?

**Comment by ppp2020** [comment]
2026年了 还是不能自动连接
