### ISSUE TITLE
Auto connect on start doesnt work after 0.12.3

### ISSUE THREAD

**Issue by 4erdenko** [hiddify/hiddify-next#346]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Tested new and old versions, latest worked auto connect was on 0.12.3

### Reproduce the Bug

Close app. Open app.

### Version

0.13.6

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
This feature has been removed. Will be added in future

**Comment by LitenBuzzTh** [comment]
> This feature has been removed. Will be added in future
@problematicconsumer 
It is such a useful feature, and we would be glad if you kindly consider adding it in the next dev version.
