### ISSUE TITLE
Android(v0.13.6）成功连接后，打开youtobe或google play时，页面加载不出内容。

### ISSUE THREAD

**Issue by YoloLordGrim** [hiddify/hiddify-next#348]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

hiddify next 成功连接后，打开youtobe或google play时，页面加载不出内容（全是空白），切换其他代理工具后（clash meta），youtobe和google play可正常使用(同一个机场相同节点)，当再次切换回hiddify后youtobe/google play就可以正常使用了。

### Reproduce the Bug

这种情况每天都会出现，本人小白不懂技术，希望有大佬帮忙解决一下，不胜感激！

### Version

v0.13.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app

**Comment by bilibili9331770** [comment]
安卓端Google应用商店可以打开，但是不能下载更新应用，换其他代理软件可以正常使用

**Comment by tangyuemo** [comment]
> 安卓端Google应用商店可以打开，但是不能下载更新应用，换其他代理软件可以正常使用
客户端更改一下地区

**Comment by SIYEQING** [comment]
> > 安卓端Google应用商店可以打开，但是不能下载更新应用，换其他代理软件可以正常使用
> 客户端更改一下地区

成功解决 谷歌商店无法更新软件和下载软件的问题。

**Comment by jidongfd** [comment]
> > > 安卓端Google应用商店可以打开，但是不能下载更新应用，换其他代理软件可以正常使用
> > > 客户端更改一下地区
> 
> 成功解决 谷歌商店无法更新软件和下载软件的问题。

怎么解决的。

**Comment by xzzfxz** [comment]
> > > > 安卓端Google应用商店可以打开，但是不能下载更新应用，换其他代理软件可以正常使用
> > > > 客户端更改一下地区
> > 
> > 
> > 成功解决 谷歌商店无法更新软件和下载软件的问题。
> 
> 怎么解决的。

在app的配置里面有一个地区的设置，把地区改为非中国的，我用俄罗斯的可以
