### ISSUE TITLE
cant install rpm package on fedora

### ISSUE THREAD

**Issue by aligoldenhat** [hiddify/hiddify-next#355]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i am trying to install hiddify rpm (dnf install ./hiddify-rpm-x64.rpm) package on my fedora 39 and i get an conflict problem
How can i fix it?

```
Error: 
 Problem: conflicting requests
  - nothing provides libayatana-appindicator3.so.1()(64bit) needed by hiddify-0.14.20+1420-1420.x86_64 from @commandline
  - nothing provides libayatana-ido3-0.4.so.0()(64bit) needed by hiddify-0.14.20+1420-1420.x86_64 from @commandline
  - nothing provides libayatana-indicator3.so.7()(64bit) needed by hiddify-0.14.20+1420-1420.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)
```

i can fix it by adding copr package

### Reproduce the Bug

install rpm package

### Version

v0.14.20

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by LordCasser** [comment]
Same issue on fedora 39

**Comment by lymanjre** [comment]
Pls install 3 dependencies first then try installing it again. This issue will be transformed to the project and I will close it here.

**Comment by nimagp** [comment]
The dependency isn't in the repositories to start with. @lymanjre

**Comment by vortex4242** [comment]
Search for missing libraries: use the package manager (dnf) to search for and install missing libraries. You can search for these libraries using the following commands:dnf search libayatana-appindicator3
dnf search libayatana-ido3
dnf search libayatana-indicator3Once you have found the appropriate packages, install them using dnf install.Enabling additional repositories:If the required libraries are not available in Fedora's default repositories, you may need to enable additional repositories that provide these libraries. Look for third-party repositories or alternative sources where these libraries are available.Compile from source: If the required libraries are not available in any repository, you may need to compile them from source. This involves downloading the source code for each library, compiling it, and installing it on your system. This method is more complicated and requires knowledge of compiling software from source code.

dnf search libayatana-appindicator3
dnf search libayatana-ido3
dnf search libayatana-indicator3
