### ISSUE TITLE
Interference of the license with the principles of free software

### ISSUE THREAD

**Issue by aetoray** [hiddify/hiddify-next#356]
Hiddify Next claims that it is an open source and free program, but according to the [principles of free software](https://en.wikipedia.org/wiki/Free_and_open-source_software#Four_essential_freedoms_of_Free_Software), this program has violated one of the principles due to its license!
Is this problem solved?

**Comment by lymanjre** [comment]
Pls mention the exact term that violated the principles. We will consider and check it out. Thanks
