### ISSUE TITLE
app gets open automatically

### ISSUE THREAD

**Issue by l3lack-eyes** [hiddify/hiddify-next#358]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

1-app gets open automatically even when it is not enabled on windows 
![image](https://github.com/hiddify/hiddify-next/assets/138435463/ce211dc6-c4cf-407f-b5da-ce7ae5cfabc3)
2-app gets open on top left of my screen . the older versions where not like this.
![Uploading image.png…]()

### Reproduce the Bug

1

### Version

v0.14.20

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
