### ISSUE TITLE
[FR] mac电脑 启动弹出意外错误弹框。

### ISSUE THREAD

**Issue by AjaxCao** [hiddify/hiddify-next#359]
### Feature description

MacBook-Pro:~ pp $ /Applications/Hiddify\ Next.app/Contents/MacOS/Hiddify\ Next ; exit;
flutter: upgrader: parseAppcastItemsFromUri exception: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = raw.githubusercontent.com, port = 0, uri=https://raw.githubusercontent.com/hiddify/hiddify-next/main/appcast.xml
config options: {ExecuteAsIs:false LogLevel:warn ResolveDestination:false IPv6Mode:3 RemoteDnsAddress:tcp://8.8.8.8 RemoteDnsDomainStrategy:0 DirectDnsAddress:8.8.8.8 DirectDnsDomainStrategy:0 MixedPort:2334 LocalDnsPort:6450 MTU:9000 StrictRoute:true TUNStack: ConnectionTestUrl:https://cp.cloudflare.com/ URLTestInterval:600000000000 EnableClashApi:true ClashApiPort:6756 EnableTun:false SetSystemProxy:true BypassLAN:false AllowConnectionFromLAN:false EnableFakeDNS:false EnableDNSRouting:true IndependentDNSCache:true GeoIPPath:geo-assets/sagernet-sing-geoip-geoip.db GeoSitePath:geo-assets/sagernet-sing-geosite-geosite.db Rules:[{Domains:domain:.cn,geosite:cn IP:geoip:cn Port: Network: Protocol: Outbound:bypass}] TLSTricks:{EnableFragment:false FragmentSize:10-100 FragmentSleep:50-200 EnableMixedSNICase:false EnablePadding:false PaddingSize:100-200}}
** Error: Command requires admin privileges.

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app

**Comment by babimantou** [comment]
我的就出现意外错误，请问怎么解决
