### ISSUE TITLE
Support SagerNet config format

### ISSUE THREAD

**Issue by Amirraan** [hiddify/hiddify-next#36]
وقتی کانفیگ های درون nekobox رو تبدیل به کیو ار کد  میکنم هیدیفای نکست نمیتونه کانفیگ رو وارد کنه، ولی کانفیگ های درون هیدیفای ان جی رو تبدیل به کیو ار کد میکنم، هیدیفای نکست بدون مشکل کانفیگ رو دریافت میکنه

+ لطفا قابلیت تبدیل کانفیگ ها به  کیو ار کد رو اضافه کنید با تشکر

**Comment by problematicconsumer** [comment]
اپ‌های NekoBox و SagerNet فرمت خاص خودشون (SN) دارن که در حال حاضر پشتیبانی نمیشه.
میتونید از فرمت‌های Standard این اپ‌ها(Vless, vmess etc) استفاده کنید.

**Comment by hiddify-com** [comment]
It is not planned now as there is no documentation about that format
