### ISSUE TITLE
Start at login and proxy switch bugs

### ISSUE THREAD

**Issue by natasun** [hiddify/hiddify-next#363]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

There are two bugs I figured out on desktop version:
1. When I'm connected to my Clash Meta subscription, and switching the proxy to another, nothing changes, the app shows it has changed but the server actually is not changed. so searching IP location, it would be still same previous connection. To fix, you need to disconnect and connect Hiddify Next again.
2. checking the Start at login and Start Minimized are not working. Everytime I turn the PC on, I need to open the app manually and start connecting.

### Reproduce the Bug

1. Add a clash subscription
2. connect to one of the configs
3. go on IP detector websites
4. switch the config
5. go on IP detector websites, IP is still shows the previous config's IP

### Expected Behavior

Switching the config without restarting connection.

### Version

0.14.20

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
