### ISSUE TITLE
win10 v0.14.20 Prompt unexpected error

### ISSUE THREAD

**Issue by fsckzy** [hiddify/hiddify-next#365]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

win10 v0.14.20 Prompt unexpected error

### Reproduce the Bug

![1234](https://github.com/hiddify/hiddify-next/assets/34021474/3544b5fc-c1c0-48fd-a538-340689c445aa)

### Version

v0.14.20

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app
