### ISSUE TITLE
[FR] linux 无界面安装使用 Hiddify

### ISSUE THREAD

**Issue by Avey777** [hiddify/hiddify-next#368]
### Feature description

使用linux系统时，很多时候是没有安装桌面环境的， 是否可以通过 URL 进行配置Hiddify 的代理呢？
但是 v2rayA 不支持Linux系统的 系统代理，导致在linux 无GUI系统中 无法使用

参考：https://github.com/v2rayA/v2rayA
https://snapcraft.io/install/v2raya/debian#install

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
