### ISSUE TITLE
Unexpected crash upon hitting "Connect"

### ISSUE THREAD

**Issue by deathline94** [hiddify/hiddify-next#369]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

On android 13 and using latest beta (0.15) and after setting up everything , adding my sub link and updating it , upon hitting connect the app force closes and crashes . easily reproducing . 

### Reproduce the Bug

adding my sub link and updating it , upon hitting connect the app force closes and crashes . easily reproducing . 

### Version

0.15

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
fixed
