### ISSUE TITLE
warp+   beta version in hiddify windows

### ISSUE THREAD

**Issue by emad1381** [hiddify/hiddify-next#373]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When i try to connect warp+ ( I entered the license and IP as per the guide : warp://license@cleanip:port/?ifp=5-10) i get an unexpected error and the program no longer works and no configuration is connected anymore. I close the program and run it again, but again I run into problems when running Warp Plus. This is if I have no problem with running normal warp

### Reproduce the Bug

1.I entered the warp config as instructed
2.import license warp+ as guide
3.click to run warp+ config
4.I get an unexpected error show to display

### Version

v 0.15.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
