### ISSUE TITLE
v0.15.1.dev not connecting to some    

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#374]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Seems like v0.15.1.dev has changed some settings and its not connecting to filtered domains any more while 14.2 can connect with no problem.

### Reproduce the Bug

Click connect, check proxies, proxies with filtered subdomains not connecting anymore.
All config settings same as 14.2  

### Version

v0.15.1.dev

### Platform/OS

Android, Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by papampi** [comment]
v0.15.1.dev:
![photo1706259084 (1)](https://github.com/hiddify/hiddify-next/assets/1108483/7a53d067-b4fb-40e5-9aab-af9e0eae318a)

v0.14.2:
![photo1706259084](https://github.com/hiddify/hiddify-next/assets/1108483/7fd89d3d-3562-457c-a7ca-dd09fc66e148)

**Comment by papampi** [comment]
Problem not fixed with 15.3 either

**Comment by hiddify-com** [comment]
give you config plz

**Comment by papampi** [comment]
Fixed in 15.4, thanks
