### ISSUE TITLE
IPV6 can't be imporet via Wireguard link (0.15.1)

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#376]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Your default wireguard link is not compatible with ipv6 

### Reproduce the Bug

.

### Version

0.15.3

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
give complete issue with test config
