### ISSUE TITLE
Avoid writing logs on disk

### ISSUE THREAD

**Issue by nimagp** [hiddify/hiddify-next#377]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

If you import a config by its URL, there will be a field in log object prompting singbox to write the logs to disk. This creates unnecessary I/O and can damage storage devices. 
```json
"log": {
    "level": "info",
    "output": "box.log",
    "timestamp": true
  },
```

### Reproduce the Bug

Import any config, really.

### Expected Behavior

This field not being the in the log object

### Version

Any

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
