### ISSUE TITLE
Unexpected error! when setting URL test interval to 1 hour

### ISSUE THREAD

**Issue by amihos** [hiddify/hiddify-next#379]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when i set URL Test Interval to 1 hour, when i press connect it shows unexpected error and it disconnects. After few seconds or tries the app crashes and closes.

### Reproduce the Bug

Go to settings, go to config optins and set URL Test interval to 1 hour. 
Other settings: Bypass Lan: ON
IPv6: preferred
Enable TLS Fragment: ON
enablt TLS mixed sni case : ON
enable TLS Padding: ON

### Expected Behavior

It should connect and works normally. 

### Version

0.15.4

### Platform/OS

Android

### Additional Context

https://github.com/hiddify/hiddify-next/assets/35190548/9d6e282c-719a-4d44-906b-e3b935d458c5

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
