### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrzZz18** [hiddify/hiddify-next#380]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I want to use Hiddify Next, the program does not work and exits.
I installed the pre-release version(0.15.4),my android is 13 and my phone is Poco x3 pro.

https://github.com/hiddify/hiddify-next/assets/145968057/f857a92c-da03-43da-96df-35c24dce2364

### Reproduce the Bug

https://github.com/hiddify/hiddify-next/assets/145968057/832d8dca-d392-4780-a107-b7294f1799c3

### Version

V 0.15.4

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
pls send app.log to use to debug it. This issue will be transformed to the project and I will close it here.

**Comment by MrzZz18** [comment]
> pls send app.log to use to debug it. This issue will be transformed to the project and I will close it here.
> 

For app log i just use the app till i can share with you,but the problem is here that the application doesn't work and starts.the Version(0.15.2)to(0.15.4) i can't use.but the version (0.14.2) is still working on my phone.

**Comment by moli1369** [comment]
این نسخه تست هست از گوگل پلی دانلود کن نسخه در حال حاضر 0.13.6 هست مشکل کرش رو نداره.تست کن نتیجه رو بگو

**Comment by MrzZz18** [comment]
> این نسخه تست هست از گوگل پلی دانلود کن نسخه در حال حاضر 0.13.6 هست مشکل کرش رو نداره.تست کن نتیجه رو بگو

نسخه های بعدی رو نصب کردم مشکل رفع شد مثل اینکه،ورژن ۰.۱۶.۱۶.
