### ISSUE TITLE
start mimimized mode doesn't work

### ISSUE THREAD

**Issue by yjplayerhyw** [hiddify/hiddify-next#383]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

start mimimized mode doesn't work

### Reproduce the Bug

start mimimized mode doesn't work

### Version

0.15.3

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
