### ISSUE TITLE
Traffic not goes through WARP for Singbox: SSH config using hiddify next in both desktop and mobile.

### ISSUE THREAD

**Issue by typerhack** [hiddify/hiddify-next#384]
**Describe the bug**
When using Sing-box: SSH config in hiddify next the traffic does not go through WARP.

**To Reproduce**
1.Make sure in setting all traffic goes through the WARP.
2. Open hiddify next
3. Import config Singbox: SSH
4. Connect
5. search for "what is my ip" or alternatively use "https://whatismyipaddress.com/"
6. It shows the IP of the server.
7. This bah

**Expected behavior**
It should hide the traffic behind the WARP. Only WARP IP should be shown.

**Screenshots**
I rather not show my IP.

**Desktop: **
 - OS: Win 10
 - Browser Edge, Firefox
 - Edge: Version 120.0.2210.144, Firefox: 122.0 (64-bit)

**Smartphone: **
 - Device: S21 FE
 - OS: Android 14
 - Browser Chrome
 - Version 121.0.6167.101

**Additional context**
This behavior can be seen in both desktop and mobile. I think I should mention that sing-box app works fine, and the traffic goes through WARP.

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
