### ISSUE TITLE
چرا نسخه ویندوز رو درست نمی کنید؟

### ISSUE THREAD

**Issue by corvtte** [hiddify/hiddify-next#385]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

خیلیا از جمله خودم گزارش کردن که بعد از نسخه 11 برنامه قبل از اینکه باز بشه کرش میکنه بعد از این همه نسخه که بیرون امده هنوز این مشکلو رفع نکردید با وجود اینکه بارها گفته شده راجبش نمیدونم چرا درست نشده متوجه نمیشید مشکل از کجاست یا اون دسته از کاربرا که نمیتونن از اپ ویندوز استفاده کنن براتون فاقد اهمیتن؟ 

[app.log](https://github.com/hiddify/hiddify-next/files/14074995/app.log)

### Reproduce the Bug

08:13:15.789169 - [D] bootstrap: [logs repository] initialized in 30ms
08:13:15.789169 - [I] bootstrap: hiddify v0.15.4 (1504) [prod]
general release
windows ["Windows 10 Pro" 10.0 (Build 22631)]

### Version

0.15.4

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by zebka** [comment]
Hi guys, i have the same issue. my hiddify app completely connected to the warp and I can test the delay but no throughput in the connection.

**Comment by mahdi-mb** [comment]
سلام متاسفانه هیچ کدوم از ورژن ها روی ویندوز ۱۰ اجرا نمیشن حتی آخرین نسخه
فقط چند ثانیه یه صفحه ی سفید میاد و بدون هیچ پیام خطا یا اروری بسته میشه ورژن پرتابل هم همینچوریه
![2024-03-24_12-33-02](https://github.com/hiddify/hiddify-next/assets/14259244/a7744e84-56df-4201-8935-dc3e84cf14cd)

**Comment by lucaswhob** [comment]
با سلام
دقیقا همین مشکل روبروی آخرین نسخه ویندوز 11 دارم صفحه سفید چند ثانیه و بسته شدن 
اینم لاگ Event Viewer ویندوز :
`Faulting application name: Hiddify.exe, version: 1.1.1.10101, time stamp: 0x65fab8eb
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000001d
Fault offset: 0x000001f001a3164d
Faulting process id: 0x0x350
Faulting application start time: 0x0x1DAA965CF508BCD
Faulting application path: D:\hiddify\Hiddify.exe
Faulting module path: unknown
Report Id: 43511097-e91a-4c95-be23-6f1aae4d388d
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by lucaswhob** [comment]
> تمامی فایهای درون مسیر کار برنامه را پاک کنید. برنامه را یکبار uninstall کنید و مجددا نصب کنید. مشکل باید حل بشه. مسیر برنامه: %AppData\Roaming\Hiddify\hiddify

با سلام 4 تا 5 بار تمام مراحل و تکرار کردم هم ویندوز 10 هم ویندوز 11 متاسفانه صفحه سفید بعد از چند ثانیه بسته میشه

**Comment by ghasem1122** [comment]
من تموم این کارایی که گفتید انجام دادم ولی یک صفحه سیاه از vpn برام به نمایش می گذارد

**Comment by david9922** [comment]
منم روی ویندوز 10 نصب کردم و صفحه سفید میاد بالا و هیچ منویی نشون نمیده غیر از دگمه ضربدر (close) و مینیمایز

**Comment by m2vnet2** [comment]
جالبه که منم مشکل صفحه سیاه رو دارم

**Comment by my7amin** [comment]
Close Hiddify Program
Go to C:\Users\"your windows account name"\AppData\Roaming\Hiddify\hiddify
Delete db.sqlite
Open Hiddify
Enjoy
