### ISSUE TITLE
Unexpected Error: v0.15.4 on Windows 11

### ISSUE THREAD

**Issue by omidshojaee** [hiddify/hiddify-next#386]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I get this error when pressing the "Connect" button:

![Screenshot 2024-01-28 161609](https://github.com/hiddify/hiddify-next/assets/31741561/cc188287-9e23-4d9a-b3d0-648f7aaf7c80)

The exact same config with exact same settings of the program works fine on v0.14.20.

The config is a subscription link generated by HiddifyManager.

### Reproduce the Bug

Import a subscription link generated by HiddifyManager and click on "Connect" button.

### Version

0.15.4

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
