### ISSUE TITLE
باگ ریلیتی grpc

### ISSUE THREAD

**Issue by Delta-Sheriff** [hiddify/hiddify-next#39]
سلام ، ریلیتی grpc رو اپ جدید اصلا کار نمیده اتو سی دی ان و مابقی اوکین ولی 
چندین آپدیت دادید ولی هنوز این مشکل رو حل نکردید ...

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
