### ISSUE TITLE
Crashes of custom config and failure import 

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#392]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After importing this config:

### Reproduce the Bug

{
  "outbounds": [
    {
      "detour": "WARP",
      "server": "212.102.47.198",
      "server_port": 443,
      "password": "shadowsocks",
      "method": "aes-128-cfb",
      "tag": "us",
      "type": "shadowsocks"
    },
    {
      "tag": "WARP",
      "type": "custom",
      "warp": {
        "host": "auto",
        "key": ""
      }
    }
  ]
}

### Expected Behavior

Hiddify Next 0.15.4 crashes and config can't be imported

### Version

0.15.4

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
