### ISSUE TITLE
Crashes and failure connection

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#393]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Crashes after clicking on "connect" for this subscription link:

https://mrpooyax.camdvr.org/api/ramezan/alpha.php?sub=1

### Reproduce the Bug

.

### Version

0.15.4

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
