### ISSUE TITLE
Battery draining

### ISSUE THREAD

**Issue by BlackDevill11** [hiddify/hiddify-next#396]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام میشه هیدیفای نکست رو بهینه کنید متاسفانه مصرف باتری زیادی داره متشکرم بابت زحماتتون.

### Reproduce the Bug

...

### Version

All

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
