### ISSUE TITLE
Bug: Unspected Error when connecting if change URL Test Interval

### ISSUE THREAD

**Issue by sanek184** [hiddify/hiddify-next#398]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Bug: Unspected Error when connecting if change URL Test Interval
![screenshot 22153](https://github.com/hiddify/hiddify-next/assets/10418650/619a4ccc-e2ad-41e1-bd20-b96691485717)
![screenshot 22154](https://github.com/hiddify/hiddify-next/assets/10418650/31af3930-2ef4-4fa0-8100-8b9b449b1ee1)

### Reproduce the Bug

Unspected Error when connecting if change URL Test Interval

### Version

0.15.4

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
