### ISSUE TITLE
Cannot connect to warp on pc

### ISSUE THREAD

**Issue by HeyShah** [hiddify/hiddify-next#399]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i cannot connect to warp conf (warp://162.159.195.171:8854/?ifp=5-10 in my case) in any ways
i have tweaked all the settings and tried but still got Unexpected error  or just app freezes on connecting(functions but when trying to exit it freezes and cannot cancel connecting) 
![image](https://github.com/hiddify/hiddify-next/assets/115167216/cc965426-d245-4c85-a275-dbdb515ae09e)
![image](https://github.com/hiddify/hiddify-next/assets/115167216/3bfe41e8-268a-4214-be7f-5282e1c3406c)
using default settings with region IR here even thou no other regions worked

also same config works on my phone just fine

### Reproduce the Bug

use a warp config and try to connect to it with desktop version

### Expected Behavior

connects normally

### Version

0.15.4

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
