### ISSUE TITLE
مشکل لود اکانتهای اینستاگرام

### ISSUE THREAD

**Issue by Amirbazz** [hiddify/hiddify-next#40]
ظاهرا اپ یه مشکلاتی تو لود اینستا داره

با v2rayng با همون کانفیگ لود میشه راحت

 کش اینستا رو پاک کنین تست کنین با نکست مشکل لود داره ظاهرا

اکسپلور اوکیه ولی وقتی پروفایل یکی باز میکنی لود نمیشه هیچی
با تغییر dns ها هم اوکی نشد
عجیب بود برام

نسخه 0.8.0

![IMG_20231006_195652.jpg](https://github.com/hiddify/hiddify-next/assets/120129395/2a5fc14e-cc1a-4e7a-8bfd-ca9dfec7e697)

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
