### ISSUE TITLE
[FR] LOCAL Region detection can be auto by ip test or like clash should be imported from susbscription

### ISSUE THREAD

**Issue by netsupcloud** [hiddify/hiddify-next#402]
### Feature description

[FR] Region detection can be auto by public ip test or like clash can be imported from subscription

also default auto update can be 20 hours after install because its not a good idea to be disabled by default

also clash subscription link will not be detected by (import from clipboard) and it must be manually added its better to filter json or yaml data from clash link that is readable by hiddify and import it automatically

**Comment by Jolymmiles** [comment]
You can make pull request with this feature.

**Comment by netsupcloud** [comment]
in new version country detection for each proxy is implemented
but i was mean local region detection can be auto in settings
