### ISSUE TITLE
Hiddify RPM install failed on Nobora (Fedora based)

### ISSUE THREAD

**Issue by nimbold** [hiddify/hiddify-next#406]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I've been trying to install RPM version of Hiddify on Nobora Linux (Fedora based) and I got "Conflict" error. Later I tried this:
`sudo rpm -ivh hiddify-rpm-x64.rpm` 
to see what's wrong and I got this error:
```
error: Failed dependencies:
        libayatana-appindicator3.so.1()(64bit) is needed by hiddify-0.15.4+1504-1504.x86_64
        libayatana-ido3-0.4.so.0()(64bit) is needed by hiddify-0.15.4+1504-1504.x86_64
        libayatana-indicator3.so.7()(64bit) is needed by hiddify-0.15.4+1504-1504.x86_64
```
I then tried to find the dependency packages but I couldn't find it in any repository!

Is it possible to add these into the RPM package itself?

P.S: AppImage package works great and has no problem. Also a Faltpack version on Flathub would work wonders for Linux users.

### Reproduce the Bug

1. On Nobora Linux or Fedora based OS
2. Install by running the install command (or by just double clicking to install in GUI package manager)
3.  Shows error

### Expected Behavior

Install without problem and download dependencies if needed.

### Version

0.15.4

### Platform/OS

Linux

### Additional Context

![Screenshot_20240202_064549](https://github.com/hiddify/hiddify-next/assets/11913706/c4f86d56-cc85-4a5b-9299-0b8aa171f7bd)
![Screenshot_20240202_064639](https://github.com/hiddify/hiddify-next/assets/11913706/85a1353b-425d-4c7d-b5c8-44be01d5e7d8)
Screenshots of package manager and Konsole run

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by Jolymmiles** [comment]
just install this dependencies

**Comment by nimbold** [comment]
I tried searching in the default repositories and couldn't find them. It also would have download automatically if it was present in them.
Thanks, now I'll try going through the web for dependency packages.

**Comment by Jolymmiles** [comment]
> I tried searching in the default repositories and couldn't find them. It also would have download automatically if it was present in them.
> Thanks, now I'll try going through the web for dependency packages. 

I find all of them in centos repo on browser.

**Comment by nimbold** [comment]
> > I tried searching in the default repositories and couldn't find them. It also would have download automatically if it was present in them.
> > Thanks, now I'll try going through the web for dependency packages.
> 
> I found all of them in centos repo on browser.
Thank you, found them all in here as well https://rpmfind.net/linux/rpm2html/search.php

I will mark it as solved.

**Comment by nimbold** [comment]
In the  latest version there are multiple dependency errors and I couldn't find any of the packages in RPM repositories.
![Screenshot_20240210_170823](https://github.com/hiddify/hiddify-next/assets/11913706/622a5234-acfc-4338-9277-fb52eec13ce1)
Also Appimage pakcage is broekn and won't run.

**Comment by nimbold** [comment]
In the latest version (0.15.15):
The dependencies mentioned in OP are just needed.
They can be found on **rpmfind.net** and after installing, the Hiddify RPM can be installed without issue.
