### ISSUE TITLE
کرش

### ISSUE THREAD

**Issue by alirezahasheminezhad** [hiddify/hiddify-next#408]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام
موقع جابجا شدن بین نت و وایفای اپ کرش میکنه
اخرین نسخه بتا که وارت ساپورت میکنه
همچنین رو ویندوز بعضی سیستم ها اوکیه بعضی ها صفحه سفید میاد چند ثانیه بعد غیب میشه وین ۱۰ یا ۱۱ 

### Reproduce the Bug

. 

### Version

0.15.4

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Edward1361** [comment]
> ### Search first
> * [x]  I searched and no similar issues were found
> 
> ### What Happened?
> سلام موقع جابجا شدن بین نت و وایفای اپ کرش میکنه اخرین نسخه بتا که وارت ساپورت میکنه همچنین رو ویندوز بعضی سیستم ها اوکیه بعضی ها صفحه سفید میاد چند ثانیه بعد غیب میشه وین ۱۰ یا ۱۱
> 
> ### Reproduce the Bug
> .
> 
> ### Expected Behavior
> _No response_
> 
> ### Version
> 0.15.4
> 
> ### Platform/OS
> Android, Windows
> 
> ### Additional Context
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> * [ ]  I'm willing to submit a PR (Thank you!)

سلام ، من هم دقیقا مشکل بیرون پریدن در ویندوز رو دارم و نمیدونم علت چی هست

**Comment by lymanjre** [comment]
این ایشو تکراری است و قبلا ثبت شده است. لطفا نسخه آخر را تست کنید
