### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by imbear** [hiddify/hiddify-next#409]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hiddify raise a Unexpected Error

### Reproduce the Bug

1. Add a subscription
2. Click[Tap to connect]

### Version

v0.15.4

### Platform/OS

Android, Windows

### Additional Context

**I modifiy the profile, and remain one server that can raise the error.**

```
{
    "dns": {},
    "experimental": {},
    "inbounds": [],
    "log": {},
    "outbounds": [
        {
            "tag": "select",
            "type": "selector",
            "default": "urltest",
            "outbounds": [
                "urltest",
                "nobody_Taiwan_hysteria_61"
            ]
        },
        {
            "server": "www2.dtku48.xyz",
            "server_port": 22334,
            "tag": "nobody_Taiwan_hysteria_61",
            "tls": {
                "enabled": true,
                "server_name": "www2.dtku48.xyz",
                "alpn": [
                    "h3"
                ],
                "insecure": true
            },
            "type": "hysteria",
            "auth_str": "dongtaiwang.com",
            "down": "55 Mbps",
            "up": "11 Mbps"
        },
        {
            "tag": "direct",
            "type": "direct"
        },
        {
            "tag": "block",
            "type": "block"
        },
        {
            "tag": "dns-out",
            "type": "dns"
        },
        {
            "tag": "urltest",
            "type": "urltest",
            "outbounds": [
                "nobody_Taiwan_hysteria_61"
            ]
        }
    ],
    "route": {}
}
```

### Relevant log output
![2024-02-03 095953](https://github.com/hiddify/hiddify-next/assets/2120811/97e7eef6-8b27-40db-bd88-732051a991ed)

_No response_

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Coderx7** [comment]
I also face this error whenever I set service type to `VPN`

**Comment by vortex4242** [comment]
It looks like you have provided JSON configuration for a network application or service. It includes various outbound connections and settings for handling network traffic. Here's a breakdown of the configuration:dns: DNS settings configuration, but it's empty in the JSON you provided. experimental: Experimental configurations, also empty. inbounds: DNS configuration, but it's empty in the JSON you provided: inbound connections configuration, but it's empty in the JSON you provided. log: Logging configuration, but it's empty. outbounds: Outbound connections configuration. It defines various types of outbound connections including: a selector named "select" that chooses between "urltest" and "nobody_Taiwan_hysteria_61". an outbound connection to "www2.dtku48.xyz" with TLS enabled using the "hysteria" type and setting upload and download speeds. a direct outbound connection (bypassing any proxy). Blocking outbound connection (blocking all traffic). outbound DNS connection. outbound URL test connection that uses outbound connection "nobody_Taiwan_hysteria_61". route: This configuration seems to be related to network and proxy routing.

**Comment by lymanjre** [comment]
Pls update to the latest version. That should be fixed
