### ISSUE TITLE
CDN WS h2 Not working

### ISSUE THREAD

**Issue by KSMM-INFINITY** [hiddify/hiddify-next#41]
I realised that hiddify next cannot handle websocket but it can work with grpc easily.

**Comment by hiddify-com** [comment]
which config you have used?

**Comment by KSMM-INFINITY** [comment]
Hello,
TLS h2 CDN configs (VLESS and Trojan) which use Websocket transport don't
work with HiddifyNext but they work with V2rayNG or HiddifyNG without of
any problem.
I really appreciate your support.
Best Regards

**Comment by KSMM-INFINITY** [comment]
![20231006_230159.jpg](https://github.com/hiddify/hiddify-next/assets/40823266/19a19bae-ba4d-4f6e-8c4c-a857df485c6a)

![20231006_230306.jpg](https://github.com/hiddify/hiddify-next/assets/40823266/82bcb32a-e832-4510-96d0-f408f1ce76ac)

As you can see, tls h2 ws configs don't work on HiddifyNext but they work on V2rayNG.

**Comment by lymanjre** [comment]
this is issue is transferred to be investigated. I close it here by the way
