### ISSUE TITLE
Crash on switch with wifi to mobile or mobile datato wifi

### ISSUE THREAD

**Issue by Ashx1364** [hiddify/hiddify-next#419]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام
با تشکر‌از برنامه خوبتون
 وقتی وای فای روشن و موبایل دیتا خاموش . اول وای فای خاموش میکنیم بعد موبایل دیتا روشن میکنیم ، ارتباط قطع میشه و لازم یکبار قطع و وصل کنیم تا مجدد وصل بشه که هیچ اتفاقی روی گوشی نمی افته ، اما برنامه ببندیم باز کنیم روی صفحه لوگو اول میمونه و تا force stop نمکنیم اتفاقی نمی افته ، همین اتفاق برعکس هم می افته یعنی از موبایل دیتا به وای فای ، کلا نت ورک اداپتوری  باهاش وصلیم به هر دلیلی خاموش  بشه یا عوض بشه برنامه به
![Screenshot_20240206-145713_Hiddify Next](https://github.com/hiddify/hiddify-next/assets/159136917/41d4462b-79ff-458f-be25-392820084139)
 مشکل میخوره

### Reproduce the Bug

![Screenshot_20240206-145713_Hiddify Next](https://github.com/hiddify/hiddify-next/assets/159136917/c825b9be-8f4d-4313-918a-0f701d1b005c)

### Version

0.15.4

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
سلام. لطفا نسخه آخر را تست کنید. این مشکل باید حل شده باشه. ایشو فعلا بسته میشود
