### ISSUE TITLE
مشکل اتصال و رد و بدل شدن دیتا در کانکشنهای هیستریا 2 در ورژن 0.8.1

### ISSUE THREAD

**Issue by Bahmei** [hiddify/hiddify-next#42]
الان داخل ورژن 0.8.1 لینک هیستریا 2 اضافه میشه ولی زمانی که دکمه اتصال رو میزنیم دلخل تب proixes زیر اسمس کانکشنمون میزنه بلاک و دیتای ردو بدل نمیشه

**Comment by lymanjre** [comment]
روی نسخه 0.8.11 چک کنید مشکل حل شده. این ایشو بسته میشود. در صورت تکرار مشکل آن را باز نمایید مجددا
