### ISSUE TITLE
دو تا مشکل تو نسخه 0.15.4

### ISSUE THREAD

**Issue by jabbarpour** [hiddify/hiddify-next#426]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام. قبل از هر چیز واقعا دمتون گرم، بی نظریرید و بزرگترین کمک رو دارید به مردم میکنید.
من ورژن 0.15.4 رو نصب کردم و حین کار به ۲ تا باگ کوچیک رسیدم که مطمئنم خودتون ازش با خبرید ولی گفتم باز بهتون اطلاع بدم تا برطرف کنید.
اولیش اینکه وقتی به اینترنت خط یا WiFi وصلیم و برنامه هم کانکته، نوع کانکشن رو عوض می‌کنیم و از روی خط میریم روی WiFi یا برعکس، برنامه هنگ میکنه و باید Force Stop کنیم.
دومی هم اینکه اگه Notification برنامه رو غیر فعال کنیم برنامه وصل نمیشه و حتما باید Notification فعال باشه.

### Reproduce the Bug

۱. زمانی که برنامه connect هست، اینترنت رو از روی خط به وا‌ی‌فای یا برعکس تغییر میدیم، برنامه هنگ میکنه.
۲. نوتیفیکیشن حتما باید فعال باشخ، غیر فعال کنیم، connect نمیشه

### Version

0.15.4

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این باگ باید در نسخه آخر حل شده باشه. لطفا آخرین آپدیت را چک کنید. ایشو بسته میشود. اگر مشکل پابرجا بود ایشو را باز کنید
