### ISSUE TITLE
کرکش کردن برنامه ورژن 0.8.1 با فعال کردن گذینه Execute Config As Is

### ISSUE THREAD

**Issue by Bahmei** [hiddify/hiddify-next#43]
داخل ورژن 0.8.1 زمانی که داخل تنظیمات گذینه Execute Config As Is رو فعال میکنیم و بعد از آن زمانی که دکمه اتصال رو بزنیم برنامه کرش میکنه.

**Comment by problematicconsumer** [comment]
این گزینه برای تست هست و تنها با debug mode در دسترسه. طبیعی هست که باعث مشکل بشه
