### ISSUE TITLE
[FR] Request to Add TLS Fragment Button in Home Page

### ISSUE THREAD

**Issue by solirf** [hiddify/hiddify-next#437]
### Feature description

سلام و خسته نباشید بابت همه زحماتتون
فکر میکنم اگر کلید روشن و خاموش TLS Fragment به صفحه Home یا منو سمت چپ برنامه اضافه بشه خیلی عالی میشه برای دسترسی سریع تر و کسانی که خیلی با نرم افزار آشنایی ندارند ( منظور افراد مسن هست )

**Comment by AliM1988** [comment]
بهتره تنظیمات فرگمنت و mux به ازای هر کانفیگ باشه نه بعنوان تنظیمات کلی. چون هر اپراتور تنظیمات متفاوتی نیازه داره.
اپ ایفونی streisand بخوبی این کار رو کرده.

**Comment by solirf** [comment]
همین الان هم می توانید برای هر کانفیک به صورت جدا فعال کنید ، به صفحه آموزش ها مراجعه کنید

**Comment by AliM1988** [comment]
@solirf متاسفانه نتونستم این مطلب رو پیدا کنم. ممکنه راهنمایی کنید

**Comment by solirf** [comment]
@AliM1988 
https://github.com/hiddify/hiddify-next/wiki/URL-Scheme

قسمت Fragment رو ببینید

**Comment by lymanjre** [comment]
این درخواست انجام شده است
