### ISSUE TITLE
لینک نا معتبر

### ISSUE THREAD

**Issue by Ms4sD** [hiddify/hiddify-next#438]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

وقتی یک کانفیگ اضافه میکی میگه لینک نامعتبر و انقدر باید پاک کنی نصب کنی شاید یک بار اوکی باشه

### Reproduce the Bug

وقتی یک کانفیگ اضافه میکی میگه لینک نامعتبر و انقدر باید پاک کنی نصب کنی شاید یک بار اوکی باشه

### Version

0.15.5

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
احتمالا لینکتون فیلتره 

در هر صورت باگ را دقیق گزارش بدید تا بشه بررسی کرد و یک نمونه بذارید
