### ISSUE TITLE
Fragment problem

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#440]
### What Happened?

Seems like same issus as #374

### Reproduce the Bug

Not connecting to filtered domains

### Version

0.15.6

### Platform/OS

Android, Linux

**Comment by karimi12** [comment]
I had this problem in new version too.
Additionally, mux not working true

**Comment by papampi** [comment]
Not fixed on version 0.15.8 and 0.15.9 while 0.15.4 can connect 
0.15.8 won't connect at all and all shows a red ❌ 
0.15.9 it connects but device won't tunnel and hiddify shows unknown ip

**Comment by momohammadi** [comment]
This bug is still in version 0.15.9 with one change, if you disable the TLS Padding option it works fine, while in version 0.15.4 with all options enabled and all conditions are the same as with this enabled The option (TLS Padding) is also connected

Android version: 12
Xiaomi note9 se
شدیقخهی رث

**Comment by papampi** [comment]
Yes, in 0.15.9 with TLS padding disabled it connects. 
Problem with not tunneling device is caused by enabling the "Bypass Lan"

**Comment by papampi** [comment]
Fixed in 0.15.15
