### ISSUE TITLE
not adding warp as before

### ISSUE THREAD

**Issue by alieffe** [hiddify/hiddify-next#444]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

وقت بخیر
وارپ بصورت کانفیگ‌های نسخه 15.4 اضافه نمیشه. نه بصورت تکی و نه حتی اگه داخل لینک سابسکریبشن باشه
قسمت وارپ داخل تنظیمات هم فعال میکنم کلید وارپ پلاس هم اضافه میکنم ولی چیزی توی کانفیگ‌ها اضافه نمیشه

### Reproduce the Bug

فقط تونستم به این صورت وارپ را اضافه کنم

`{ "log": { "level": "warn", "output": "box.log", "timestamp": true }, "dns": { "servers": [ { "tag": "dns-remote", "address": "udp://1.1.1.1", "address_resolver": "dns-direct", "detour": "select" }, { "tag": "dns-direct", "address": "1.1.1.1", "address_resolver": "dns-local", "detour": "direct" }, { "tag": "dns-local", "address": "local", "detour": "direct" }, { "tag": "dns-block", "address": "rcode://success" } ], "rules": [ { "domain_suffix": ".ir", "geosite": "ir", "server": "dns-direct" }, { "domain": "cp.cloudflare.com", "server": "dns-remote", "rewrite_ttl": 3000 } ], "final": "dns-remote", "independent_cache": true }, "inbounds": [ { "type": "tun", "tag": "tun-in", "mtu": 9000, "inet4_address": "172.19.0.1/28", "inet6_address": "fdfe:dcba:9876::1/126", "auto_route": true, "strict_route": true, "endpoint_independent_nat": true, "sniff": true, "sniff_override_destination": true }, { "type": "mixed", "tag": "mixed-in", "listen": "127.0.0.1", "listen_port": 2334, "sniff": true, "sniff_override_destination": true }, { "type": "direct", "tag": "dns-in", "listen": "127.0.0.1", "listen_port": 6450, "override_address": "1.1.1.1", "override_port": 53 } ], "outbounds": [ { "type": "selector", "tag": "select", "outbounds": [ "auto", "WARP § 0" ], "default": "auto" }, { "type": "urltest", "tag": "auto", "outbounds": [ "WARP § 0" ], "url": "http://cp.cloudflare.com/", "interval": "10m0s" }, { "type": "wireguard", "tag": "WARP § 0", "local_address": [ "172.16.0.2/24", "2606:4700:110:8d2c:25b6:a253:bc4d:63ac/128" ], "private_key": "wC5e8QTMfxgt/Qlchh/5dYqNDMV0y3ZaLlAsJpST0Gk=", "server": "162.159.195.171", "server_port": 8854, "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=", "reserved": "AAAA", "mtu": 1280, "fake_packets": "5-10" }, { "type": "dns", "tag": "dns-out" }, { "type": "direct", "tag": "direct" }, { "type": "direct", "tag": "bypass" }, { "type": "block", "tag": "block" } ], "route": { "geoip": { "path": "geo-assets/sagernet-sing-geoip-geoip.db" }, "geosite": { "path": "geo-assets/sagernet-sing-geosite-geosite.db" }, "rules": [ { "inbound": "dns-in", "outbound": "dns-out" }, { "port": 53, "outbound": "dns-out" }, { "clash_mode": "Direct", "outbound": "direct" }, { "clash_mode": "Global", "outbound": "select" }, { "domain_suffix": ".ir", "geosite": "ir", "geoip": "ir", "outbound": "bypass" } ], "auto_detect_interface": true, "override_android_vpn": true }, "experimental": { "cache_file": { "enabled": true, "path": "clash.db" }, "clash_api": { "external_controller": "127.0.0.1:6756" } } }`

### Version

v15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
لطفا نسخه آخر را چک کنید. این مورد باید حل شده باشه. ایشو بسته میشود
