### ISSUE TITLE
Hiddify Stop responding after 1 minute in latest pre-release 0.15.6

### ISSUE THREAD

**Issue by MohsenHNSJ** [hiddify/hiddify-next#445]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

OS: Android 13 - One UI 5.1
Prorocol: WARP 
I am using version 0.15.4 for about a week with no problem, today updated to 0.15.6, but I noticed connection to vpn was dropped after one minute of starting the vpn.
I tried to change the proxy but I noticed the app is not responding in any way, it's just frozen.

I forced stop the app, tried again, same thing happened, the app freezes after one minute of working. Either foreground or background while using another app.

I tried restarting my phone, but the problem persisted.

As my phone is rooted, so I can downgrade apps without the need for clearing data, I downgraded to 0.15.4 and everything worked just fine again.

The latest changes seems to break the core function of the app for me.

### Reproduce the Bug

1_Add a warp proxy
2_Start connection
3_Wait for 1-2 minutes and the app freezes.

### Version

0.15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MohsenHNSJ** [comment]
Let me know how I can somehow provide more information for debugging. Like logs or something ...
Happy to help.

**Comment by miladj3** [comment]
I got this error since updating to 1.5.6,  this problem occurred when I use warp config,
I think version 1.5.4 is an RC version

**Comment by lymanjre** [comment]
Please update to the latest version and check if the issue persists. That should be solved.
I ll close the issue now

**Comment by Siavash1291** [comment]
I have the same problem on Android 12, Hiddify 1.4.0
