### ISSUE TITLE
Crash android application 

### ISSUE THREAD

**Issue by karimi12** [hiddify/hiddify-next#446]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When i opened application and click on connect application crashed

### Reproduce the Bug

Use Mi 11T

go to application
click on connect

### Expected Behavior

connect to a server

### Version

0.15.6

### Platform/OS

Android

### Additional Context

![photo_2024-02-10_14-27-29](https://github.com/hiddify/hiddify-next/assets/16267391/e48276df-3657-492a-a60d-1637fd08854a)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Please attach the link you have problem with

**Comment by lymanjre** [comment]
As you didn`t answer us, we assume the issue id fixed. If not please open the issue.
