### ISSUE TITLE
didn't connect to some servers

### ISSUE THREAD

**Issue by karimi12** [hiddify/hiddify-next#447]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

All of configs in a subscription link is ok on latest version bit on 0.15.6 not connect 
This configurations use mux and fragments.

### Reproduce the Bug

1. Go to application
2. choice a config 

### Expected Behavior

i expected connect to a server

### Version

v0.15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Please try our latest version. This issue will be closed. If the issue persist, Please open it
