### ISSUE TITLE
Change config

### ISSUE THREAD

**Issue by karimi12** [hiddify/hiddify-next#448]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I connected to a config I decided to change  my  config but the config didn't change and had to disconnect and connect

### Reproduce the Bug

1. Go to application
2. connect to a config 
3. change your config

### Version

v0.15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is repetitive so I close it
