### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by idaryoosh** [hiddify/hiddify-next#45]
چنتا پیشنهاد:
۱. تغییر آیکون هوم
۲. اسکرول بین دو تب پایین (کشیدن به چپ و راست)
۳. نمایش پینگ تو صفحه اصلی
۴. حل پیغام ناتیفکشن.
وقتی ناتفیکشن رو خاموش کنیم کانکت نمیشه
۵. کانفیگ های تکی تو یه صفحه جم بشن بهتره

ممنون از توجهتون

**Comment by idaryoosh** [comment]
بخش qr خیلی ضعیف عمل میکنه و از گالری عکس رو نمیخونه
لطفا قابلیت اد کردن‌کانفیگ بصورت فایل رو اضافه کنید
لطفا قابلیتی اضافه کنید که لینک سابی که مخصوص نرم افزاری مث نکوباکس یا کت باکس هس رو دریافت کنه

**Comment by lymanjre** [comment]
ایشو برای بررسی منتقل شد. فعلا ایشو بسته میشود و مورد در دست بررسی است.
