### ISSUE TITLE
Failed to add profile

### ISSUE THREAD

**Issue by deathline94** [hiddify/hiddify-next#451]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

This error happens when trying to add a sub link containing either a "warp://" or "wireguard://" links
used to work just fine in previous version

![123](https://github.com/hiddify/hiddify-next/assets/11331137/98b01467-93a0-456f-8be6-992875a3e150)

### Reproduce the Bug

Make a sub link containing a WireGuard/WARP config
try to add it
not going to happen !

### Version

v0.15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Barbodgh** [comment]
have the same problem here. waiting for a solution

**Comment by lymanjre** [comment]
This issue is fixed. Pls use latest version
