### ISSUE TITLE
Tun Mode Not working in Windows (0.15.6)

### ISSUE THREAD

**Issue by solirf** [hiddify/hiddify-next#452]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Tun Mode Not working in Windows (0.15.6)

### Reproduce the Bug

it works well on v 0.15.4

### Version

V 0.15.6

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by omidshojaee** [comment]
+1

**Comment by solirf** [comment]
Thanks , Working well on 0.15.9

**Comment by lymanjre** [comment]
You have to open app with admin privilege or use vpn service
