### ISSUE TITLE
Not Found Windows Installer V.0.15.6

### ISSUE THREAD

**Issue by KEANU2003** [hiddify/hiddify-next#456]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when i tried to download windows installer v.0.15.6 zip file wasn't available and i saw 'Not Found' Error.

### Reproduce the Bug

1.Go to https://github.com/hiddify/hiddify-next/releases
2.Click on https://github.com/hiddify/hiddify-next/releases/download/v0.15.6/hiddify-windows-x64-setup.zip
3.See Error

### Expected Behavior

FIX IT ASAP.

### Version

v0.15.6

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hadifarnoud** [comment]
same issue with MacOS link. not found

**Comment by hbdMahsa** [comment]
Change the end of the link from .zip to .exe

**Comment by lymanjre** [comment]
Use new version links. it s fixed
