### ISSUE TITLE
پیشنهاد نحوه آپدیت نرم افزار

### ISSUE THREAD

**Issue by Mo3tafa-shafiee** [hiddify/hiddify-next#46]
به نظرم تو همه نسخه های نرم افزار این قابلیت بذارین که با تایید کاربر آخرین نسخه به صورت درون برنامه ای دانلود و نصب بشه . نه که به Google play یا Github هدایت بشه .

**Comment by soroushgkh** [comment]
پسشنهاد می کنم توی نسخه هیدیفای نکست مثل هیدیفای ان جی حالت لود بالانس و تنظیم پروکسی روی حالت همه جز فیلتر شده و نشده اضافه شه.

**Comment by lymanjre** [comment]
این مورد در آپدیتهای آتی در دست بررسی و انجام قرار می گیرد. فعلا این ایشو بسته میشود و مورد شما برای پیگیری منتقل میشود. با سپسا از همراهی شما
