### ISSUE TITLE
Ubuntu VPN mode not working

### ISSUE THREAD

**Issue by llaravell** [hiddify/hiddify-next#462]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

VPN mode in Linux Ubuntu with CPU arch x86_64 not working on new pre-release [v0.15.6](https://github.com/hiddify/hiddify-next/releases/tag/v0.15.6).
But in version [v0.15.4](https://github.com/hiddify/hiddify-next/releases/tag/v0.15.4).
Try 3 TUN implementations but not working and looks like my internet connection is broken

### Reproduce the Bug

In Ubuntu OS:
1 - Go to settings
2 - Scroll down to inbounds options
3 - Select service mode and choose VPN

### Version

v0.15.6

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Pls update to the latest version that should be fixed. You can use VPN service as well
