### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Amir2367** [hiddify/hiddify-next#465]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام هیدیفای عزیز

آخرین نسخه تست(draft) رو صبح وقتی نصب کردم
وقتی با کانفیگ وارپ وصل میشم بعد چند دقیقه برنامه کرش میکنه و vpn قط میشه

2 وقتی گزینه های Allow Connection Lan و Bypass Lan فعال میشن باعث میشه کانفیگ وارپ با وجود وصلی هیچ دیتایی رد و بدل نکنه و قط شه

### Reproduce the Bug

سلام هیدیفای عزیز

آخرین نسخه تست(draft) رو صبح وقتی نصب کردم
وقتی با کانفیگ وارپ وصل میشم بعد چند دقیقه برنامه کرش میکنه و vpn قط میشه

2 وقتی گزینه های Allow Connection Lan و Bypass Lan فعال میشن باعث میشه کانفیگ وارپ با وجود وصلی هیچ دیتایی رد و بدل نکنه و قط شه

### Version

0.15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by AntiGFW614** [comment]
با سلام.
پس از انتشار نسخه های 0.15.6 و 0.15.9 یک اشکال اساسی در برنامه به وجود آمده که در ادامه برای تیم هیدیفای شرح داده شده است:

داخل نسخه جدید 0.15.6 و 0.15.9 زمانی که bypass lan روشن باشه کانفیگ ها پینگ میدن ولی هیچ اپلیکیشن و سایتی رو باز نمیکنه 
ولی زمانی که خاموش باشه همه چی اوکی هست و کار میکنه.
