### ISSUE TITLE
[FR] Allow menu bar only mode for macOS

### ISSUE THREAD

**Issue by rusmux** [hiddify/hiddify-next#468]
### Feature description

When I close the app, it stays in the dock:

<img width="965" alt="image" src="https://github.com/hiddify/hiddify-next/assets/85135806/b16d9db3-22e5-4c4c-907b-6136f1c5d3a9">

However, connecting and opening the dashboard is done in the menu bar:

<img width="196" alt="image" src="https://github.com/hiddify/hiddify-next/assets/85135806/f6e304c5-2463-47d1-ae4e-4baea99e7b57">

There is no need to keep the app in the dock, especially since even if you click on it, it will not open the dashboard. For me right now, it just clutters up the space. I like the way it's done in the WireGuard client, where the application appears in the dock only when the dashboard is opened.

Thank you!

**Comment by problematicconsumer** [comment]
Added, will ship in next release
