### ISSUE TITLE
Discrepancies in Download Badge URLs Leading to 404 Errors

### ISSUE THREAD

**Issue by hayschan** [hiddify/hiddify-next#469]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The download badge URLs in the README.md and Release page for Windows, macOS, and Linux platforms are incorrect, resulting in "404 not found" errors. These discrepancies include differences in naming conventions, capitalization, and file extensions, which prevent users from accessing the correct download files.

**Specific Issues with Badge URLs:**

1. **Windows Setup Package:**
   - **Problematic URL:** `https://github.com/hiddify/hiddify-next/releases/download/v0.15.8/hiddify-windows-x64-setup.zip`
   - **Correct URL:** `https://github.com/hiddify/hiddify-next/releases/download/v0.15.8/Hiddify-Windows-Setup-x64.exe`
   - **Differences:** The problematic URL uses lowercase, includes a `.zip` extension instead of `.exe`, and the naming convention differs (`hiddify-windows-x64-setup` vs. `Hiddify-Windows-Setup-x64`).

2. **Windows Portable Package:**
   - **Problematic URL:** `https://github.com/hiddify/hiddify-next/releases/download/v0.15.9/hiddify-windows-x64-portable.zip`
   - **Correct URL:** `https://github.com/hiddify/hiddify-next/releases/download/v0.15.9/Hiddify-Windows-Portable-x64.zip`
   - **Differences:** The issue here includes lowercase usage and a slight difference in naming convention (`hiddify-windows-x64-portable` vs. `Hiddify-Windows-Portable-x64`).

3. **macOS DMG Package:**
   - **Problematic URL:** `https://github.com/hiddify/hiddify-next/releases/download/v0.15.9/hiddify-macos-universal.zip`
   - **Correct URL:** `https://github.com/hiddify/hiddify-next/releases/download/v0.15.9/Hiddify-MacOS.dmg`
   - **Differences:** The incorrect URL uses lowercase, a `.zip` extension instead of `.dmg`, and a different naming convention (`hiddify-macos-universal` vs. `Hiddify-MacOS`).

### Reproduce the Bug

1. Navigate to the README.md page or the [Release](https://github.com/hiddify/hiddify-next/releases) page of the Hiddify repository.
2. In the download section, click on any download badge link for Windows, macOS, or Linux.
3. Observe that the link redirects to a "404 not found" error page instead of starting a download.

### Expected Behavior

The badge links should accurately reflect the file naming conventions, capitalization, and correct file extensions, ensuring users can successfully download the application without encountering errors.

### Version

The issue is observed in the README.md and Release page as of the current date.

### Platform/OS

Windows, macOS, Linux

### Additional Context

Correcting the badge URLs to match the actual file names, capitalization, and extensions in the GitHub releases will resolve the navigation errors and improve the user experience.

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by hayschan** [comment]
After checking the files, here are the files affected:
1. [.github/release_message.md](https://github.com/hiddify/hiddify-next/blob/main/.github/release_message.md)
2. README files and the translation files of the README.

**Comment by irgod** [comment]
Hi
Hiddify Next software on Windows 10 was identified as a Trojan (Trojan Script/Wacatac.B!ml)!
Please explain that Hiddify is a Trojan and a virus!!
Thanks

👉 Trojan Script/Wacatac.B!ml

**Comment by hayschan** [comment]
> Hi Hiddify Next software on Windows 10 was identified as a Trojan (Trojan Script/Wacatac.B!ml)! Please explain that Hiddify is a Trojan and a virus!! Thanks
> 
> 👉 Trojan Script/Wacatac.B!ml

I don't think your situation is related to this issue. Please open a new issue for that.

**Comment by lymanjre** [comment]
Use latest version. It s fixed
