### ISSUE TITLE
Adding a configuration 

### ISSUE THREAD

**Issue by Danialkabiri** [hiddify/hiddify-next#470]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Still having problems with adding a warp personal license key 

### Reproduce the Bug

Add profile 

### Version

0.15.8

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Use latest version. Should be solved
