### ISSUE TITLE
Problem feedback

### ISSUE THREAD

**Issue by lxtx528** [hiddify/hiddify-next#471]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello boss, after upgrading Windows to 0.15.9, the connection speed was very fast and normal, but after the upgrade, it still shows 0.15.6 and the version number has not been changed. There is no problem with Windows at the moment.

The Android connection is very slow, and after clicking on the link, it will get stuck there for a while before there is a response. The connection speed is very slow and there is a problem.

After upgrading to 0.15.9 on Mac OS, the app icon disappeared and the connection speed was slightly slower than Windows, but much better than Android. However, the first connection was a bit slow, and the subsequent repeated connections were very fast.

### Reproduce the Bug

I just tried the Mac OS version here, but it was slow during the first cold start. Repeatedly starting later is normal, and the Windows version does not have this issue.

### Expected Behavior

IOS side hopes to update as soon as possible, the current version 0.15.5 is not available, feedback is complete.

### Version

0.15.9

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Try using latest version and see if it s solved. The issue is closed
