### ISSUE TITLE
bypass Lan Bug

### ISSUE THREAD

**Issue by AntiGFW614** [hiddify/hiddify-next#476]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello.
After the release of versions 0.15.6 and 0.15.9, a basic bug has appeared in the program, which is described below for the Hiddify team:

In the new version 0.15.6 and 0.15.9, when the bypass lan is turned on, the configurations are pinged, but it does not open any application or site.
But when it is off, everything is ok and works.

### Reproduce the Bug

1-Config option
2-bypass Lan
In the new version 0.15.6 and 0.15.9, when the bypass lan is turned on, the configurations are pinged, but it does not open any application or site.

### Version

v0.15.6-v0.15.9

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by AntiGFW614** [comment]
The mentioned problem also exists in the Windows version

**Comment by xianren78** [comment]
you are absolutely right...

**Comment by hiddify-com** [comment]
Will be fixed

**Comment by papampi** [comment]
Not fixed in 0.15.11

**Comment by papampi** [comment]
Fixed in 0.15.15

**Comment by lymanjre** [comment]
FIXED
