### ISSUE TITLE
doesn't work proxy or vpn mode

### ISSUE THREAD

**Issue by miladj3** [hiddify/hiddify-next#477]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When it is connected, and the connection is established, neither in VPN mode nor in proxy mode, none of them works while the connection is established.

### Reproduce the Bug

1. connected
2. change service mode to VPN 
3. telegram or any filtered app don't work,  and my IP in google is that public ip iran
4. change service mode to PROXY
5. set telegram to proxy port
6. it doesn't work 

### Expected Behavior

"I was hoping to tunnel my phone or Ubuntu using VPN mode or a work proxy port."

### Version

1.15.8 , 1.15.9

### Platform/OS

Android, Linux

### Relevant log output

```shell
there is no log
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nimbold** [comment]
Having the exact issue on Nobara Linux (Fedora based). Nothing passes by either VPN service or Proxy mode.

**Comment by problematicconsumer** [comment]
You need to reconnect after changing config options for them to take effect.

**Comment by nimbold** [comment]
Everything except "VPN service" mode is working in the latest version (0.15.15).
Normal **VPN** mode works (when using sudo) and it passes the traffic through Hiddify. The same is OK with **Proxy** and **System Proxy** mode, but **VPN service** mode doesn't pass any traffic through Hiddify.
Here is the log when using **VPN service** mode:

```
03:46:10.105059 - [D] Pref<bool, dynamic>: updating preference [started_by_user](bool) to [true]
03:46:10.107484 - [W] ConfigOptionRepositoryImpl: error getting preference[url-test-interval], expected type: [int] - received value: [10m](String)
03:46:10.108267 - [I] ConnectionRepositoryImpl: config options: {
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": true,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "udp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 6450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": false,
  "enable-tun-service": true,
  "set-system-proxy": false,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "enable-tls-fragment": true,
  "tls-fragment-size": "50-100",
  "tls-fragment-sleep": "10-20",
  "enable-tls-mixed-sni-case": false,
  "enable-tls-padding": false,
  "tls-padding-size": "100-200",
  "enable-mux": false,
  "mux-padding": false,
  "mux-max-streams": 8,
  "mux-protocol": "h2mux",
  "enable-warp": false,
  "warp-detour-mode": "outbound",
  "warp-license-key": "",
  "warp-clean-ip": "auto",
  "warp-port": 0,
  "warp-noise": "",
  "geoip-path": "geo-assets/chocolate4u-iran-sing-box-rules-geoip.db",
  "geosite-path": "geo-assets/chocolate4u-iran-sing-box-rules-geosite.db",
  "rules": [
    {
      "domains": "domain:.ir,geosite:ir",
      "ip": "geoip:ir",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ]
}
Memory Limit: false
03:46:10.109011 - [D] FFISingboxService: starting, memory limit: [false]
03:46:10.109389 - [I] ConnectionNotifier: connection status: CONNECTING
03:46:10.111203 - [D] SystemTrayNotifier: updating system tray
03:46:13.097122 - [I] ConnectionNotifier: connection status: CONNECTED
03:46:13.097334 - [D] IpInfoNotifier: disposing
03:46:13.097532 - [D] ProxyRepositoryImpl: getting current ip info using [https://ipapi.co/json/]
03:46:13.099217 - [D] SystemTrayNotifier: updating system tray
03:46:38.505204 - [D] FFISingboxService.watchGroups: stopping

```

**Comment by miladj3** [comment]
this issue has been resolved at  v0.15.15 dev

**Comment by BehradJi** [comment]
> this issue has been resolved at v0.15.15 dev

I am using v0.15.15 dev AUR package on Archlinux and I can confirm that VPN Service does not work.

**Comment by lymanjre** [comment]
Resolved

**Comment by NicSatou** [comment]
resolved? no, the same thing happening too. App says it's connected, even shows supposed ip, but actual ip remains unchanged

**Comment by drhouse-md** [comment]
found a solution - change region to others

**Comment by AndrewKusov** [comment]
I encounter this problem on all devices. Changing the region (I tried Turkey) really helps.
