### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by amihos** [hiddify/hiddify-next#484]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![Screenshot_2024-02-15-21-09-36-32_dd661fbf574bc01712a840b6c315ea7e](https://github.com/hiddify/hiddify-next/assets/35190548/b0224828-7e80-4adb-b694-3be8e1be8503)

### Reproduce the Bug

1. Install the latest version (0.15.11 dev).
2.  Add your subscription link and load the list of servers.
3. Press connect without changing any options or configs in the menu.
After following these steps, you may encounter an unexpected error: create service: parse route options: parse dns server[dns-remote]: unknown DNS server format: http://1.1.1.1

### Expected Behavior

it should connect to one of the servers

### Version

0.15.11 dev

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Reset dns config

**Comment by amihos** [comment]
It didn't work or fix anything

https://github.com/hiddify/hiddify-next/assets/35190548/d0527c86-0226-4b2b-907c-4668bd2d3e2f

**Comment by amihos** [comment]
@hiddify-com Also check telegram group. Multiple users are reporting this issue.
