### ISSUE TITLE
Reported IP of the connected server is not correct/ getting updated

### ISSUE THREAD

**Issue by amihos** [hiddify/hiddify-next#485]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

App finds better servers and connect to them but the connected IP reported by the app doesn't get updated with the new connected server. So there will be mismatch between connected servers's IP and the reported and shown ip
![Screenshot_2024-02-16-01-21-52-46_dd661fbf574bc01712a840b6c315ea7e](https://github.com/hiddify/hiddify-next/assets/35190548/3d90108c-0029-4b82-838d-3a4aa7cca515)

### Reproduce the Bug

Insert a subscription link with many servers
Press connect watch the IP app shows
Then wait for the app to test more servers in the background. If it finds a better one and connect, watch that the precious IP doesn't change. 

### Expected Behavior

It should update this IP as well to match the IP of the newly connected server. 

### Version

0.15.11 dev

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Long press on the IP to refresh.

**Comment by problematicconsumer** [comment]
in next release, IP address will hide after some time to reflect it might be invalid
