### ISSUE TITLE
Invalid url error in Windows version

### ISSUE THREAD

**Issue by Barbodgh** [hiddify/hiddify-next#486]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when I want to enter a warp url in winodws, I get an error message indicating that the url is invalid. on Android version the same config works fine. configs are like this:
warp://162.159.192.147:955/?ifp=5-10

### Reproduce the Bug

1. Open up the app
2. Copy a warp cofig like the one attached in this report
3. click on "New Profile"
4. click on "Add From Clipboard"
5. See the related error (Invalid URL)

### Expected Behavior

Adding these types of configs to the profile

### Version

v0.14.20

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
WARP is not supported in v14. Please try version 15 and older
