### ISSUE TITLE
اتصال به پورت mixed از طریق دیگر سیستم های تحت شبکه

### ISSUE THREAD

**Issue by RevEngine3r** [hiddify/hiddify-next#49]
### Feature description

سلام لطفا در تنظیمات برنامه امکان تغییر رنج listen رو قرار بدید تا بشه مثلا روی 0.0.0.0 تنظیم کرد تا سیستم های دیگه هم در شبکه بتونن از پروکسی استفاده کنن باتشکر
![Screenshot_2023-10-08-13-34-54-721_moe nb4a-edit](https://github.com/hiddify/hiddify-next/assets/91720115/c67abbc6-ac01-4aee-9ab7-2403a7440909)

**Comment by lymanjre** [comment]
ایشو جهت بررسی منتقل شد. فعلا بسته میشود
