### ISSUE TITLE
Freeze and crash after sleeping mode

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#496]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

بعد از خارج کردن موبایل از حالت استندبای، کانفیگ های Warp دچار فریز اپ و فورس کلوز می شوند

### Reproduce the Bug

.

### Version

0.15.5

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
ایشو تکراری است قبلا ثبت شده این ایشو بسته میشود
