### ISSUE TITLE
i have problem with windows setup file (windows defender problem)

### ISSUE THREAD

**Issue by Mohammad5-M** [hiddify/hiddify-next#498]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/hiddify/hiddify-next/assets/107820798/1bc5954c-ddf2-40fa-836c-3c4e5abb4779)

### Reproduce the Bug

just install the windows version and suddenly the error popup

### Version

15.15.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nimbold** [comment]
Because it's a third party app, not installed via store and maybe unsigned, windows defender is alarming you that it might be a malicious software.
If you are willing to run it, just click Run anyway.

**Comment by hbdMahsa** [comment]
ویندوز و آویرا که من چک کردم hiddifyservice.exe رو ویروس یا مشکوک تشخیص میدن
بقیه برنامه مشکلی نداره

**Comment by lymanjre** [comment]
Pls try latest version. It s solved
