### ISSUE TITLE
لاک نبودن نوتیف ورژن جدید

### ISSUE THREAD

**Issue by Amirbazz** [hiddify/hiddify-next#50]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

نوتیف اپ بعد از اتصال لاک نیس

![IMG_20231008_141916_125](https://github.com/hiddify/hiddify-next/assets/120129395/09c1bbe1-fa25-4657-9a21-362d066ba951)
![IMG_20231008_141916_257](https://github.com/hiddify/hiddify-next/assets/120129395/c0cde2ad-59ab-45f5-b4c9-f2deeb2b42b5)

### Reproduce the Bug

.

### Version

v0.8.11

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
