### ISSUE TITLE
URL test Interval BUG

### ISSUE THREAD

**Issue by DrAmirB** [hiddify/hiddify-next#501]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام. وقت بخیر
یه باگی در قسمت url test interval هس که وقتی عدد رو بیشتر از ۳۱ دقیقه میذاریم ارور میده در عددای کمتر اروری مشاهده نمیشه.

![Screenshot_2024-02-17-21-39-10-748_app hiddify com](https://github.com/hiddify/hiddify-next/assets/120129395/6f58ae33-37c1-4274-a93c-ae6e7695c962)

### Reproduce the Bug

.

### Version

v0.15.15

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
باید کمتر از idel timeout باشه
