### ISSUE TITLE
TLS Padding Bug

### ISSUE THREAD

**Issue by mhmd-hb** [hiddify/hiddify-next#502]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

tls ws configs works fine with just tls fragments enabled, but when user enable tls padding. those configs start to show timeout error.

### Reproduce the Bug

1. enable tls padding with 1-10 value.
2. tap on connect button
3. app shows timeout on tls ws configs

### Version

v0.15.15.dev
v0.16.0.dev

### Platform/OS

Android
windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mahanmi** [comment]
> > I have the same problem non of my VLESS WS TLS Configs work even with the fragment I have tried both marzban and 3x-ui panels and it happens I don't have any problems on apps like V2rayNG and streisand
> 
> 
> 
> just disable tls padding.

Where is it?

**Comment by mhmd-hb** [comment]
> > > I have the same problem non of my VLESS WS TLS Configs work even with the fragment I have tried both marzban and 3x-ui panels and it happens I don't have any problems on apps like V2rayNG and streisand
> > 
> > 
> > just disable tls padding.
> 
> Where is it?

**Comment by mhmd-hb** [comment]
> > > I have the same problem non of my VLESS WS TLS Configs work even with the fragment I have tried both marzban and 3x-ui panels and it happens I don't have any problems on apps like V2rayNG and streisand
> > 
> > 
> > just disable tls padding.
> 
> Where is it?

config options >> tls tricks section >> turn off enable tls padding option

**Comment by mahanmi** [comment]
> > > > I have the same problem non of my VLESS WS TLS Configs work even with the fragment I have tried both marzban and 3x-ui panels and it happens I don't have any problems on apps like V2rayNG and streisand
> > > 
> > > 
> > > just disable tls padding.
> > 
> > 
> > Where is it?
> 
> config options >> tls tricks section >> turn off enable tls padding option

I tried what you said but it didn't solve my problem

![image](https://github.com/hiddify/hiddify-next/assets/101924479/350132a1-5bda-4627-92b1-652996e99afe)

just my non TLS configs work in hiddify 

![image](https://github.com/hiddify/hiddify-next/assets/101924479/82074a69-3a15-47b8-a3cd-b6322e65a888)

**Comment by mhmd-hb** [comment]
tls fragments size : 5-10
tls fragment sleep : 1-5

**Comment by mhmd-hb** [comment]
> > > > > I have the same problem non of my VLESS WS TLS Configs work even with the fragment I have tried both marzban and 3x-ui panels and it happens I don't have any problems on apps like V2rayNG and streisand
> > > > 
> > > > 
> > > > just disable tls padding.
> > > 
> > > 
> > > Where is it?
> > 
> > 
> > config options >> tls tricks section >> turn off enable tls padding option
> 
> I tried what you said but it didn't solve my problem
> 
> ![image](https://private-user-images.githubusercontent.com/101924479/313442673-350132a1-5bda-4627-92b1-652996e99afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDMyNzIsIm5iZiI6MTcxMDk0Mjk3MiwicGF0aCI6Ii8xMDE5MjQ0NzkvMzEzNDQyNjczLTM1MDEzMmExLTViZGEtNDYyNy05MmIxLTY1Mjk5NmU5OWFmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDNlNTQ2ZGVlYmJhMGJmOTFhNGE1YjEwMTE1NjI0NjFiMGViN2JmZTI0NTEzYTk1MTYwOGRlODlhZTA0ZmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PQnQgIIKdPkjTZOMKRpVxmJKnMNUxy41Mm9L58brVP8)
> 
> just my non TLS configs work in hiddify
> 
> ![image](https://private-user-images.githubusercontent.com/101924479/313442712-82074a69-3a15-47b8-a3cd-b6322e65a888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDMyNzIsIm5iZiI6MTcxMDk0Mjk3MiwicGF0aCI6Ii8xMDE5MjQ0NzkvMzEzNDQyNzEyLTgyMDc0YTY5LTNhMTUtNDdiOC1hM2NkLWI2MzIyZTY1YTg4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjZiOWViZGM1ODcyMzAyOTRhMmQwODM0NmQ5OGQwNWM3YzBkN2UzZjBkZjAyNWYyYmE5YjczYWQzNjEzMWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YgdqT25WE6RKwAvasKEQbUf0l9bL4QgTdhwybIZpOvI)

tls fragments size : 5-10
tls fragment sleep : 1-5

**Comment by hiddify-com** [comment]
TLS Padding is expected to be higher than 1200
