### ISSUE TITLE
Expiration date

### ISSUE THREAD

**Issue by AlexKoup** [hiddify/hiddify-next#504]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Infinite subscription period is displayed if the value is greater than 1 year. The subscription expiration date is not displayed at all unless the traffic limit is set.

### Reproduce the Bug

Add subscription from marzban

### Version

0.15.15 dev

### Platform/OS

Android, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
These are mostly aesthetic. If you're interested in exact expiration date, download etc. check profile edit page.  I've added detailed information in the end (in [v0.16.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.16.0.dev)).

**Comment by AlexKoup** [comment]
> These are mostly aesthetic. If you're interested in exact expiration date, download etc. check profile edit page.  I've added detailed information in the end (in [v0.16.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.16.0.dev)).

Information on the profile editing page also disappears if the traffic limit in GB is not set.
