### ISSUE TITLE
Don't Show Connection ip for  the long time 

### ISSUE THREAD

**Issue by Amir2367** [hiddify/hiddify-next#505]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

By changing the subscription configurations or changing the Warp in Warp configurations, the IP configuration is not shown on the main screen, it is shown blurry, even with a long touch, it is not shown and it remains in this state.

https://github.com/hiddify/hiddify-next/assets/83357422/27bd4efb-857f-4ced-a6fa-8a45304e5cdc

### Reproduce the Bug

By changing the subscription configurations or changing the Warp in Warp configurations, the IP configuration is not shown on the main screen, it is shown blurry, even with a long touch, it is not shown and it remains in this state.

https://github.com/hiddify/hiddify-next/assets/83357422/27bd4efb-857f-4ced-a6fa-8a45304e5cdc

### Version

0.15.15 today draft

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
We use third-party services to fetch IP address, if for any reason your IP is blocked/limited `Unknown IP` is shown instead. You can manually check these services:
```
https://ipapi.co/json/
https://ipinfo.io/json/
```
