### ISSUE TITLE
ارور service startup error

### ISSUE THREAD

**Issue by yusefes** [hiddify/hiddify-next#51]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام، از گوشی پیکسل ۷ استفاده میکنم و بعد از اپدیت به اندروید ۱۴، برای استفاده از این اپ با ارور service startup روبرو میشم. 
![Screenshot_20231009-113519](https://github.com/hiddify/hiddify-next/assets/29953138/13c1c352-5a00-41b4-9a8e-31f07db7ffbc)

### Reproduce the Bug

ارور حین اجرای پروکسی ظاهر میشه. 

### Version

0.8.11

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by i-Naji** [comment]
use a real device.

**Comment by lymanjre** [comment]
روی اندروید ۱۴ این مشکل وجود دارد. در صورت امکان دان گرید کنید به نسخه ۱۳ تا آپدیت فیکس شدن منتشر شود.

این ایشو برای بررسی منتقل شد. فعلا بسته میشود
