### ISSUE TITLE
Auto not select lowest ping

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#510]
### What Happened?

When select auto hiddify not select lowest ping proxy

![SmartSelect_20240218_210003](https://github.com/hiddify/hiddify-next/assets/1108483/6655f3e0-a85a-4033-b8a5-03fe99787f5f)

### Reproduce the Bug

Connect
Select auto profile

### Expected Behavior

Chose lowest ping , fastest connection

### Version

0.16.0

### Platform/OS

Android, Linux

**Comment by problematicconsumer** [comment]
There's a threshold (50ms), below that it doesn't make sense to switch

**Comment by papampi** [comment]
Seems like it does not switch even when there is more than 50ms difference 

![SmartSelect_20240221_225320_aRDP Free](https://github.com/hiddify/hiddify-next/assets/1108483/a79f79ac-ba40-4780-b589-c8a52e0fe153)

**Comment by papampi** [comment]
@problematicconsumer can you confirm this issue?
