### ISSUE TITLE
AppImage doesn' t start

### ISSUE THREAD

**Issue by Graninius** [hiddify/hiddify-next#513]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The AppImage doesn't open. 

### Reproduce the Bug

1. Download AppImage
2. Move it to my portable apps' folder.
3. Try to start it.

### Version

v.0.16.0 dev

### Platform/OS

Linux
Manjaro KDE, unstable

### Additional Context

v. 0.14.20 is working well

### Relevant log output

```shell
/tmp/.mount_hiddifqxOUU7/AppRun: string 3: cd: $(dirname $0): No such file or directory
/tmp/.mount_hiddifqxOUU7/AppRun: string 8: /home/user/: It's a directory
/tmp/.mount_hiddifqxOUU7/AppRun: string 8: exec: /home/user/: can't start: It's a directory
```

**Comment by Aryangh1379** [comment]
Hi, I think the problem is these lines in the `AppRun` file:
```
     2	cd "\$(dirname "\$0")"
     7	    exec ./$appName $@
```

these changes should be made for `AppRun` file:
 ```
cd "$(dirname "$0")"
 export LD_LIBRARY_PATH=usr/lib
-if [ "$1" == "HiddifyService" ];then
-    exec ./$@
+if [ "" == "HiddifyService" ];then
+    exec ./
 else
-    exec ./hiddify
+    exec ./ 
 fi
```

**Comment by Aryangh1379** [comment]
**Hi, I'm back again, the appimage bug is fixed in version 0.16.4.dev, please consider label the issue as solved if that error doesn't persist.**

**Comment by Graninius** [comment]
I also confirm it. The bug is fixed. (0.16.7dev)

**Comment by Graninius** [comment]
0.16.16dev - we got it again
`tmp/.mount_hiddifUw0JYW/AppRun: строка 28: exec: hiddify: not found
`

**Comment by Graninius** [comment]
fixed
