### ISSUE TITLE
vpn service is considered as a threat by windows security and will be deleted on next restart

### ISSUE THREAD

**Issue by amihos** [hiddify/hiddify-next#516]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When you enable the VPN service (a new feature), the Windows security system detects it as a threat and deletes or deactivates it on the next restart. After this, the normal VPN also stops working.

### Reproduce the Bug

1- put connection mode on vpn service (the new added feature)
2- connect
3- restart

### Expected Behavior

It should not get detected as a threat and should survive restart

### Version

0.16 dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Pls use Microsoft Store version. We fix this issue
