### ISSUE TITLE
windows Virus Alert !

### ISSUE THREAD

**Issue by jaavid** [hiddify/hiddify-next#520]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/hiddify/hiddify-next/assets/1959108/2c71731b-0a61-4d5c-992e-101fd60ab82e)

### Reproduce the Bug

after download windows show error

### Version

v0.16.0.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by plashenkov** [comment]
> v0.16.0.dev

v0.15.6 has HiddifyService.exe, but AV reports nothing about it.
v0.15.9 already has a malware according to Microsoft Defender

**Comment by aminvandh** [comment]
Why windows security report this as malware ?

**Comment by A7rik** [comment]
I had the same problem with kaspersky antivirus, solved on v0.16.0.dev

**Comment by miladj3** [comment]
I got this error
![GG2BSZhXcAA-4cM](https://github.com/hiddify/hiddify-next/assets/16199445/92d28f97-1a77-44de-be65-dca59474083b)

**Comment by hiddify-com** [comment]
This is a false positive from windows defender

We have already contacted them for that


In the meanwhile we have removed tunnel service due to its false positive


We are also working on alternative solution to avoid such issue

**Comment by hiddify-com** [comment]
خوب بعد از مکاتبه با ویندوز دفندر، اشتباهشون رو رفع کردند
![image](https://github.com/hiddify/hiddify-next/assets/114227601/7c5e1b2a-5f46-4712-9798-8148b4607304)
