### ISSUE TITLE
فریز و کرش بعد از خارج کردن گوشی از حالت صفحه خاموش در توییک یا وایرگارد

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#524]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هر کانفیگ توییک یا وایرگارد که متصلیم و صفحه موبایل خاموش است، پس از چند دقیقه که صفحه را روشن می کنیم ، اپ فریز می شود و سپس کرش می کند

### Reproduce the Bug

.

### Version

0.15.6

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این ایشو تکراری است. قبلا ثبت شده
