### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by shabda7** [hiddify/hiddify-next#53]
### Feature description

سلام. لطفا گزینه‌ی proxy only را در برنامه بگذارید که بتوان برنامه هیدیفای را با برنامه‌هایی مثل ادگارد همزمان استفاده کرد. با تشکر

**Comment by lymanjre** [comment]
روی نسخه اندروید مدنظر بوده است.

فعلا این ایشو بسته میشود و برای بررسی منتقل میشود
