### ISSUE TITLE
hiddify stops working after a while

### ISSUE THREAD

**Issue by sitsaz** [hiddify/hiddify-next#530]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In version v0.16.0.dev and even lower versions (version 0.14.20 has no problem), after adding the ability to display IP and server status in the software, the server IP is no longer displayed after a while after the filter breaker starts working. and the filter breaker stops working

### Reproduce the Bug

1- Connect to the server by activating the mixed sni case option
2- Work with the filter breaker for a while
3- The filter breaker stops working and you have to reconnect again

### Version

0.16.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is repetitive
