### ISSUE TITLE
[FR] Gray out a menu bar icon when proxy is not connected

### ISSUE THREAD

**Issue by rusmux** [hiddify/hiddify-next#535]
### Feature description

May be useful for quick understanding whether the proxy is connected or not. Example from WireGuard when it is not connected:

<img width="120" alt="image" src="https://github.com/hiddify/hiddify-next/assets/85135806/8af4e007-d437-4cb1-9c3d-0e84d3ee12fe">

**Comment by lymanjre** [comment]
This feature is requested before and the issue is repetitive
