### ISSUE TITLE
عدم ایمپورت

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#54]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

.

### Reproduce the Bug

vmess://eyJhZGQiOiIxMDQuMTguNDAuMjA4IiwiYWlkIjoiMCIsImFscG4iOiIiLCJmcCI6IiIsImhvc3QiOiIiLCJpZCI6IjY3ZjUyOWZkLWZjNmEtNDhjMy1iMWMwLWY4MmEyN2I5MTU5NSIsIm5ldCI6ImdycGMiLCJwYXRoIjoiYXJnbyIsInBvcnQiOiI0NDMiLCJwcyI6IlZtZXNzR3JwYyAtIE1yTGludVgiLCJzY3kiOiJhZXMtMTI4LWdjbSIsInNuaSI6ImNsaWVudC1wcm9vLnYydnBuY2hhbm5lbC53ZWJzaXRlIiwidGxzIjoidGxzIiwidHlwZSI6Imd1biIsInYiOiIyIn0=

کانفیگ فوق ایمپورت نمی شود...اخرین نسخه گوگل پلی نصب می باشد

### Version

0.8.11

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود

**Comment by hiddify-com** [comment]
fixed
