### ISSUE TITLE
Bug report in warp uri

### ISSUE THREAD

**Issue by deathline94** [hiddify/hiddify-next#541]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

its not a big deal but never the less its a bug :
when you add this uri to use warp in warp function , it adds 2 different profiles when it actually should only add 1 named "WarpInWarp" (or am i mistaken and this is how it supposed to work??) . heres the uri :

warp://auto?ifp=5-10&ifps=40-100&ifpd=10-20#Warp&&detour=warp://auto?ifp=5-10&ifps=40-100&ifpd=10-20#WarpInWarp

### Reproduce the Bug

adding this uri in the app :
warp://auto?ifp=5-10&ifps=40-100&ifpd=10-20#Warp&&detour=warp://auto?ifp=5-10&ifps=40-100&ifpd=10-20#WarpInWarp

### Version

0.16 dev

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
That s normal
