### ISSUE TITLE
I'm having compatibility issues when compiling the code

### ISSUE THREAD

**Issue by vignycn** [hiddify/hiddify-next#542]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Resolving dependencies... 
  cross_file 0.3.3+8 (0.3.4 available)
  flutter_native_splash 2.3.10 (2.3.13 available)
  http 1.2.0 (1.2.1 available)
  intl 0.18.1 (0.19.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.4 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.3 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  meta 1.11.0 (1.12.0 available)
  shared_preferences_web 2.2.2 (2.3.0 available)
  test 1.24.9 (1.25.2 available)
  test_api 0.6.1 (0.7.0 available)
  test_core 0.5.9 (0.6.0 available)
  url_launcher_web 2.2.3 (2.3.0 available)
  vm_service 13.0.0 (14.0.0 available)
  web 0.4.2 (0.5.0 available)
  web_socket_channel 2.4.3 (2.4.4 available)
Got dependencies!
17 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

### Reproduce the Bug

I'm running flutter pub get when I get the

### Expected Behavior

It should pull the plugin normally, then compile and run normally

### Version

0.14.20

### Platform/OS

macOS

### Additional Context

My guess is that the problem is a version conflict in flutter_test. This is due to the fact that your hiddify project relies on meta version ^1.12.0, while any version of the flutter_test package from the SDK relies on meta version 1.11.0, and these two versions are incompatible, leading to version resolution failures.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Kindly read [Contribution Guide](https://github.com/hiddify/hiddify-next/blob/main/CONTRIBUTING.md) and makefile
