### ISSUE TITLE
Windows version status bar icon

### ISSUE THREAD

**Issue by HeliusHao** [hiddify/hiddify-next#545]
### Feature description

After establishing a connection in the Windows version, can the status bar icon change color to visually distinguish whether it is in a connected or disconnected state? Thank you

**Comment by HeliusHao** [comment]
For example, green

**Comment by KarimFereidooni** [comment]
The latest version that I installed (0.14.20) does not change color, which means that it is not clear from the icon whether it is connected or not.
It would be great if it specified the selected configuration in the icon tooltip

**Comment by HamidRezaAshkiyan** [comment]
Totally agree.
Nekoray achives this by chaning the color base on the state of VPN.
For example if it is VPN: yellow 
if it is local proxy blue
and so one. 

or even open vpn do that with a hollow in its logo and red beside it. and when it is trying to connect it is yellow and then finally green. 

i like both approaches. 

disconnected: 
<img width="134" alt="image" src="https://github.com/hiddify/hiddify-next/assets/38791873/6fae5e2b-efd0-451b-8924-cfba7d68009c">

connected:
<img width="141" alt="image" src="https://github.com/hiddify/hiddify-next/assets/38791873/24427779-0cd8-45be-90fc-847bd4d56822">

**Comment by HamidRezaAshkiyan** [comment]
oh i forgot something to mention it is better to change the title of this issue to something more universal, cause right now i'm using mac and this feature can be applied to all os versions.

> ### Feature description
> After establishing a connection in the Windows version, can the status bar icon change color to visually distinguish whether it is in a connected or disconnected state? Thank you

**Comment by lymanjre** [comment]
The issue is requested before so this is repetitive and should be closed
