### ISSUE TITLE
TLS-h2-WS-CDN not working

### ISSUE THREAD

**Issue by KSMM-INFINITY** [hiddify/hiddify-next#55]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

This app cannot handle TLS_h2_WS_CDN configs. I've used the same configs with hiddifyNG or v2rayNG and they work properly but when I try to use this config on hiddify next, it cannot connect. TLS_h2_gRPC_CDN configs work on hiddify next without of any problem. The problem is TLS_h2_WS_CDN.
![Screenshot_20231011-140133](https://github.com/hiddify/hiddify-next/assets/40823266/19288533-5bdc-4e51-917d-fcbd0e0fe597)

### Reproduce the Bug

1. Enable VLESS tls_h2_WS_CDN proxy in the panel.
2. Import subscription link into hiddify next.
3. Tap on connect.
4. Go to proxies tab in hiddify next.
5. Tap on check connection icon to see the delays for each proxy.
6. You will find out tls_h2_ws_cdn configs are not working and they won't respond to the delay test.

### Version

0.8.11

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
this is issue is transferred to be investigated. I close it here by the way
