### ISSUE TITLE
HiddifyNext does not display anything on Intel Mac.

### ISSUE THREAD

**Issue by zaminsirat** [hiddify/hiddify-next#550]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Great project.
When I install Hiddify on my MacBook Pro with an Intel chip, it does not show anything but a dark window. However, I notice my cursor changing in some areas like buttons.

<img width="873" alt="Screenshot 2024-02-22 at 4 28 53 PM" src="https://github.com/hiddify/hiddify-next/assets/62739986/d452bf54-5721-4001-ba8d-5b7b8bf306b9">

### Reproduce the Bug

install app
allow security on preferences
when click on app not working...

### Version

v0.14.20

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Delete all files in working directory and try again
