### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by gohtorohetfilterchi** [hiddify/hiddify-next#554]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After updating to version 0.16.3, if the Warp section is active in the configuration option menu, the connection button on the main screen will be disabled, to reactivate the connection, the Warp section must be turned off.

### Reproduce the Bug

Menu
Config option
Warp option
Enable warp
Back to the main page of the program
Tap to connect = It is inactive and does not 

### Expected Behavior

It should be connected like the previous versions, but it 

### Version

0.16.3

### Platform/OS

Android

### Relevant log output

```shell
Unfortunately, the output does not
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
It s fixed. Pls try the latest update
