### ISSUE TITLE
Failed to add the configuration file

### ISSUE THREAD

**Issue by zhuxining** [hiddify/hiddify-next#558]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I used ClashX.Meta, I was able to add the download configuration, but when I used hiddify, it said "Failed to add the configuration file."
ClashX.Meta App:https://github.com/MetaCubeX/ClashX.Meta
agent install shell:https://github.com/mack-a/v2ray-agent
<img width="868" alt="image" src="https://github.com/hiddify/hiddify-next/assets/12285468/f2cd98c0-0a5a-41d3-a79b-ad5b0ac72e0e">

#### app.log
15:04:17.633648 - [W] ProfileRepositoryImpl: error adding profile
DioException [unknown]: null
Error: HttpException: Connection closed before full header was received, uri = https://xx.xxxx.com:24085/s/clashMetaProfiles/6175……
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _FutureListener.handleError (dart:async/future_impl.dart:180)
#2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#3      Future._propagateToListeners (dart:async/future_impl.dart:879)
#4      Future._completeError (dart:async/future_impl.dart:655)
#5      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#6      _Completer.completeError (dart:async/future_impl.dart:27)
#7      Future.any.onError (dart:async/future.dart:618)
#8      _RootZone.runBinary (dart:async/zone.dart:1666)
#9      _FutureListener.handleError (dart:async/future_impl.dart:177)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#11     Future._propagateToListeners (dart:async/future_impl.dart:879)
#12     Future._completeError (dart:async/future_impl.dart:655)
#13     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

#### url: configuration file
mixed-port: 7890
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true

external-controller: 127.0.0.1:9090

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443]
    HTTP:
      ports: [80]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#DNS_Proxy'
    - 'tls://1.0.0.1#DNS_Proxy'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true

proxy-providers:
  aoczocurbf_provider:
    type: http
    path: ./aoczocurbf_provider.yaml

### Version

0.14.20 (1420)

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Pls try the latest version

**Comment by zongrongyue** [comment]
1.几的版本还能添加的订阅链接，最新版2.0.5就不能添加了，这种添加订阅链接失败的情况，我只在hiddify 上遇到过
