### ISSUE TITLE
 hiddify خطای اتصال در سیستم عامل مک

### ISSUE THREAD

**Issue by majidefathi** [hiddify/hiddify-next#562]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام ممنون از این برنامه کاربردی - روی گوشی اندروید و سیستم عامل ویندوز بدون مشکل اتصال انجام میشه ولی روی سیستم عامل مک این خطا را دریافت میکنم وقتی میزنم کانکت بشه - لازم به ذکره همه ی ورژن ها هم نصب کردم ولی باز مشکل پابرجاست : 

initialize inbound/mixed [mixed-in]: set system proxy: execute (/usr/ sbin/networksetup) networksetup -setsocksfirewallproxy Wi-Fi
127.0.0.1 2334: exit status 14

![Screenshot 2024-02-24 at 17 26 04](https://github.com/hiddify/hiddify-next/assets/141501431/47890354-9837-4631-8b42-de78b2ff1ca9)
![Screenshot 2024-02-24 at 17 37 37](https://github.com/hiddify/hiddify-next/assets/141501431/985ac4f2-125a-4ea5-aa44-bf1242b0ad66)

### Reproduce the Bug

initialize inbound/mixed [mixed-in]: set system proxy: execute (/usr/ sbin/networksetup) networksetup -setsocksfirewallproxy Wi-Fi

### Version

All version

### Platform/OS

macOS

### Additional Context

![Screenshot 2024-02-24 at 17 37 37](https://github.com/hiddify/hiddify-next/assets/141501431/4cd8b325-516d-432f-9c7a-c3349c7c9f44)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
نسخه آخر را تست کنید. باید فیکس شده باشه

**Comment by hamidrezaalirezaei** [comment]
سلام من هم مشابه همین خطا رو دریافت می‌کنم. شما راه حلش رو پیدا کردید؟
