### ISSUE TITLE
کرش به هنگام ایمپورت (عدم ایمپورت)

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#564]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هنگام ایمپورت کانفیگ زیر، هیدیفای اندروید کرش می کند و ایمپورت نمی شود:
منظورم به صورت کپی و ایمپورت محتویات جیسون هستش نه ایمپورت با لینک ساب!
کانفیگ:
https://pastebin.com/raw/H5syqh6x

### Reproduce the Bug

.

### Expected Behavior
در ضمن، اگر موبایل به مدت زیادی در حالت اسلیپ یا خواب باشد، هیدیفای یا قطع می شود و یا کرش می کند
_No response_

### Version

0.16.4

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
fixed
