### ISSUE TITLE
باگ نسخه ۱۶.۷

### ISSUE THREAD

**Issue by JUPITERR85** [hiddify/hiddify-next#565]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام وقتتون بخیر
ببخشید تو نسخه ۱۶.۷ من یه باگی که میبینم اینه که وقتی گزینه وارپ توی تنظیمات برنامه روشنه هیچ سروری کانکت نمیشه

### Reproduce the Bug

۱.داخل قسمت کانفینک اپشن 
۲. گزینه وارپ

### Version

v0.16.7

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by miladj3** [comment]
منم این مشکل رو دارم. 
![Uploading Screenshot from 2024-02-26 22-32-20.png…]()

**Comment by miladj3** [comment]
منم این مشکل رو دارم و اینکه نمیتونه تنظیمات وارپ را بگیره.
![Screenshot from 2024-02-26 22-32-20](https://github.com/hiddify/hiddify-next/assets/16199445/8846cacd-701b-4a63-916b-391490c1816e)

**Comment by javadgh6** [comment]
I faced the same issue in macOS version. I have to turn the warp toggle off to be able to use the software.

**Comment by moli1369** [comment]
این مشکل وجود داره در صورتی میخوای از وارپ استفاده کنی باید توی پنل ستش کنی api رو

**Comment by lymanjre** [comment]
نسخه جدید را تست کن حل شده
