### ISSUE TITLE
Some links not working on 0.16.7 dev

### ISSUE THREAD

**Issue by karimi12** [hiddify/hiddify-next#566]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Some config working on V2rayNG and HiddifyNext 0.14.20 but not working on0.16.7 dev
Configs contain 
Vless + CDN +TLS + mux(in schema + configs) + fragment(in schema + configs)
hysteria2 (I tested my config on iOS and windows and android was ok )

Unfortunately i can't see my configs in hiddify please add a page in application for showing and editing json config 

### Reproduce the Bug

1. go to prixies

### Version

v0.16.7 dev

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by 2duat** [comment]
0.16.7 不稳定，点击开始链接需要等很长时间，

**Comment by lymanjre** [comment]
fixed
