### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by Mo3tafa-shafiee** [hiddify/hiddify-next#57]
### Feature description

به نظرم اگر توی صفحه اصلی برنامه که دکمه اتصال قرار داره ... بعد از انجام اتصال یه سری اطلاعات نمایش داده بشه خیلی کاربری هست .
مثل نمونه زیر :

پینگ : 504
آی پی : 4.105.25.251
لوکیشن : آلمان
تبادل داده: 58.5📤 - 281.2📥

خیلی ریز و جمع و جور یه گوشه پایین همون صفحه اصلی نمایش بده خوبه . 
متشکر

**Comment by lymanjre** [comment]
در طراحی نسخ بعدی در نظر قرار گرفته است. فعلا در اولویت نیست.  
این ایشو برای بررسی منتقل شد. فعلا بسته میشود

**Comment by karimi12** [comment]
ای کاش امکان نمایش یک پیام هم ریو صفحه اول وجود داشته بشه مثلا یک subscription  link  آپدیت می شود. یک پیام هم امکان نمایش بالی لوگو وجود داشته باشه عالی می شه
