### ISSUE TITLE
Allow connection from LAN not working in Linux OS !

### ISSUE THREAD

**Issue by persian85** [hiddify/hiddify-next#570]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The feature "Allow connection form LAN" doesn't  work on Linux OS. (Mine is Ubuntu Jammy). It is also working on Windows OS but I couldn't make it work on Linux. Please solve this. Thank you ;-)

### Reproduce the Bug

![Screenshot from 2024-02-27 08-37-11](https://github.com/hiddify/hiddify-next/assets/76115728/d821e853-56b1-46d0-974d-bc055385ac95)

### Version

0.16.7

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
fixed
