### ISSUE TITLE
UDS:DangerousObject.Multi.Generic

### ISSUE THREAD

**Issue by hamid7508** [hiddify/hiddify-next#571]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

kaspersky detected hiddify.exe as threats
![Screenshot (201)](https://github.com/hiddify/hiddify-next/assets/31630760/366e0096-979c-45e3-aeb1-d11a29cb96a4)
Event: Malicious object detected
User: *\hr.ghorbani
User type: Initiator
Application name: explorer.exe
Application path: C:\Windows
Component: File Anti-Virus
Result description: Detected
Name: UDS:DangerousObject.Multi.Generic
Precision: Exactly
Threat level: High
Object type: File
Object name: Hiddify.exe
Object path: C:\Users\hr.ghorbani\Downloads\Programs\hiddify-next
MD5 of an object: F4FC7F171E4D46048C31D677087AD432
Reason: Cloud Protection

### Reproduce the Bug

just extract on a pc that have kaspersky :)

### Expected Behavior

Receive a respectful response. This position was first raised in the Telegram group of the Hiddify project, but the admins of the group fired me :))

### Version

v0.16.7.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by D8mbSniper** [comment]
I've just reported this event to Kaspersky as false positive

**Comment by hiddify-com** [comment]
@D8mbSniper Thanks

**Comment by D8mbSniper** [comment]
Kaspersky just replied to me. 


```
Hello,

Kaspersky Lab applications classify the specified objects as legitimate software and do not identify them as malicious. The notifications displayed to the user are informative and correct.
``` 

Trying to convince them now that automatically removing HiddifyNext.exe while unarchiving is not seems like "informative notification" :)

**Comment by hiddify-com** [comment]
fixed all false positives from Anti Virus
