### ISSUE TITLE
Hotkey درخواست[FR] 

### ISSUE THREAD

**Issue by mostafacpr** [hiddify/hiddify-next#573]
### Feature description

ضمن عرض سلام و خسته نباشین
لطفا در صورت امکان قابلیت تعریف کلید میانبر برای کانکت و دیسکانکت کردن در نسخه ویندوز اضافه بشه مثل وی تو ری ان
و طبق ایشو های دیگه اگه رنگ آیکون هم در حالت های مختلف تغییر کنه عالی میشه. 
رنگ پیش فرض آیکن در تسکبار سفیده که به سختی دیده میشه
باتشکر از زحمات بی دریغ وبی چشمداشتتون.
خداقوت
![hiddi](https://github.com/hiddify/hiddify-next/assets/120664716/c38b36c1-0d69-472d-82c9-35fb9cc14a7b)

**Comment by lymanjre** [comment]
این ایشو قبلا ثبت شده بنابراین اینجا بسته میشود
