### ISSUE TITLE
Show different IP's for one config

### ISSUE THREAD

**Issue by Amir2367** [hiddify/hiddify-next#575]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

We connect to a vless configuration with the default IP of Germany, but several different IPs are shown on the page every time.

https://github.com/hiddify/hiddify-next/assets/83357422/e5848c9c-d369-410b-9d9a-1aa76893bfeb

### Reproduce the Bug

1.We connect to the vless configuration with the German IP

2.On the main page, it shows several IPs with each IP refresh

### Version

0.16.16

### Platform/OS

Android

### Additional Context

https://github.com/hiddify/hiddify-next/assets/83357422/d44c0e42-4f24-4808-ad7f-1322b7a578de

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
fixed try latest update
