### ISSUE TITLE
doesn't connect after 0.15.9

### ISSUE THREAD

**Issue by sallyoneee** [hiddify/hiddify-next#576]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

the connect button doesn't work at all in the version after 0.15.9 (something that I felt like needs to be mentioned is that my internet connection requires logging in after connecting)

### Reproduce the Bug

1.Go to dashboard
2.click on connect

### Version

0.16

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
fixed
