### ISSUE TITLE
[FR] Can hidden-next be installed into Docker?

### ISSUE THREAD

**Issue by chenxudong2020** [hiddify/hiddify-next#579]
### Feature description

Can hidden-next be installed into Docker? After installing Docker, it can be used as a proxy for other LAN machines to directly access the internet. At the same time, hidden-next can import nodes or subscribe through a web interface.

**Comment by hiddify-com** [comment]
Yes
we have published the cli
check it from https://github.com/hiddify/hiddify-next-core/releases/

please bundle it with alpine image and help us to publish it in docker hub

**Comment by chenxudong2020** [comment]
> ### Feature description
> Can hidden-next be installed into Docker? After installing Docker, it can be used as a proxy for other LAN machines to directly access the internet. At the same time, hidden-next can import nodes or subscribe through a web interface.
I want to start hiddify directly and configure nodes or subscription links on the web page, but currently this software can only specify configuration files or subscription links at startup, which is not flexible and uses a clash page interface

**Comment by chenxudong2020** [comment]
> ### Feature description
> Can hidden-next be installed into Docker? After installing Docker, it can be used as a proxy for other LAN machines to directly access the internet. At the same time, hidden-next can import nodes or subscribe through a web interface.
I want to start hiddify directly and configure nodes or subscription links on the web page, but currently this software can only specify configuration files or subscription links at startup, which is not flexible and uses a clash page interface

**Comment by lymanjre** [comment]
fixed via publishing cli
