### ISSUE TITLE
اجرا نشدن برنامه در آخرین ورژن اوبونتو و مانجارو

### ISSUE THREAD

**Issue by imaniy1994** [hiddify/hiddify-next#58]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام من روی اخرین ورژن اوبونتو و مانجارو تست کردم و برنامه اصلا اجرا نشد.

### Reproduce the Bug

برنامه رو دانلود کردم
از حالت فشرده خارج کردم
بعد روش کلیک کردم.

### Version

v0.8.11

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
طبق آموزش موجود پیش برید، فایل باید دسترسی اجرا داشته باشه.
[آموزش کار با نرم‌افزار هیدیفای‌نکست](https://github.com/hiddify/Hiddify-Server/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%DA%A9%D8%A7%D8%B1-%D8%A8%D8%A7-%D9%86%D8%B1%D9%85%E2%80%8C%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%D9%87%DB%8C%D8%AF%DB%8C%D9%81%D8%A7%DB%8C%E2%80%8C%D9%86%DA%A9%D8%B3%D8%AA)
اطلاعات بیشتر: [How to Use AppImage in Linux](https://itsfoss.com/use-appimage-linux/)

**Comment by imaniy1994** [comment]
> طبق آموزش موجود پیش برید، فایل باید دسترسی اجرا داشته باشه. [آموزش کار با نرم‌افزار هیدیفای‌نکست](https://github.com/hiddify/Hiddify-Server/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%DA%A9%D8%A7%D8%B1-%D8%A8%D8%A7-%D9%86%D8%B1%D9%85%E2%80%8C%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%D9%87%DB%8C%D8%AF%DB%8C%D9%81%D8%A7%DB%8C%E2%80%8C%D9%86%DA%A9%D8%B3%D8%AA) اطلاعات بیشتر: [How to Use AppImage in Linux](https://itsfoss.com/use-appimage-linux/)


با نصب پکیج زیر برنامه اجرا شد.
طبق سرچ هایی که کردم به نظر یک برنامه پیش نیاز برای فایل های appimage هستش.
libfuse2
