### ISSUE TITLE
Linux AppImage version doesn't open

### ISSUE THREAD

**Issue by SudoerReodus** [hiddify/hiddify-next#583]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Linux AppImage version doesn't open with version v0.16.9.dev and v0.16.16.dev 
(Version v0.16.7.dev opens just fine)

`/tmp/.mount_HiddifEaFc7z/AppRun: line 28: exec: hiddify: not found`

### Reproduce the Bug

1. Boot into Fedora 39 (e.g. From a LiveCD or regular installation)
2. Download Hiddify-Linux-x64.AppImage version v0.16.16.dev or v0.16.9.dev (Version v0.16.7.dev opens just fine)
3- chmod +x Hiddify-Linux-x64.AppImage; ./Hiddify-Linux-x64.AppImage 

### Expected Behavior

It should open hiddify-next (but doesn't)

### Version

v0.16.16.dev and v0.16.9.dev

### Platform/OS

Linux

### Relevant log output

```shell
/tmp/.mount_HiddifEaFc7z/AppRun: line 28: exec: hiddify: not found
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by imkarimkarim** [comment]
second it.

log output: `/tmp/.mount_HiddifthcaPd/AppRun: line 28: exec: hiddify: not found`
Version: v0.16.16.dev

**Comment by netsupcloud** [comment]
also on ubuntu 20 fails to load library 

libc.so.6: version 'GLIBC_2.34' not found

**Comment by imkarimkarim** [comment]
> also on ubuntu 20 fails to load library
> 
> libc.so.6: version 'GLIBC_2.34' not found

i had the same issues but I updated to 22.04 and it got fixed. i think it has something to do with kernel version if im not wrong.

**Comment by imkarimkarim** [comment]
🔔 update: i have `v0.16.16.dev` AppImage up and running at:

OS: Kubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-21-generic
DE: Plasma 5.24.7

@netsupcloud @SudoerReodus

**Comment by shahrooz1397** [comment]
i have the same issue on arch linux 
appimg wont run
i've set the executalbe permision but wont run

**Comment by hiddify-com** [comment]
fixed
