### ISSUE TITLE
[FR] Proxy Chain

### ISSUE THREAD

**Issue by SudoerReodus** [hiddify/hiddify-next#589]
### Feature description

Please add the ability to chain various configs / profiles through each other. (Like that of Nekoray)

**Comment by problematicconsumer** [comment]
Limited chaining options will be added in future, but ideally these should be implemented in the raw json file provided to the app.
Hiddify is profile based, there are no plans for individual proxy management

**Comment by vortex4242** [comment]
Uncomment random or dynamic and comment static!

**Comment by vortex4242** [comment]
Uncomment random or dynamic and comment static!
