### ISSUE TITLE
مستقیم کردن تمام ترافیک داخلی

### ISSUE THREAD

**Issue by rezaafz** [hiddify/hiddify-next#59]
### Feature description

سلام. روی اپ هیدیفای نکست جداسازی ترافیک داخلی کاملا درست کار نمیکنه. سایت های .ir مستقیم هستند ولی بقیشون نه. مثلا sanjesh.org رو که زدم از تونل vpn میگذرونه.
این موضوع خیلی مهمیه. چون مستقیم کردن ترافیک سایت های ایرانی هم احتمال فیلترشدن کانفیگ ها رو کمتر میکنه، هم ترافیک روی سرورها خیلی کمتر میشه

**Comment by lymanjre** [comment]
این مورد قبلا ثبت شده و در دست بررسی است بنابراین ایشو شما فعلا بسته میشود
