### ISSUE TITLE
Unable to connect config with format (Vmess Ws no tls)

### ISSUE THREAD

**Issue by Amir2367** [hiddify/hiddify-next#594]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Config with the format (Vmess Ws no Tls) is connected in other programs such as Nekobox, but it is not connected in the Hidify program itself, the following example:
![Screenshot_2024-03-01-15-12-52-345_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/9bf7c724-3dde-4bb5-ac96-05b7d1fb0833)
![Screenshot_2024-03-01-15-12-51-043_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/3c84f984-42c5-4dc8-a995-e1cae0d52824)

### Reproduce the Bug

Config with the format (Vmess Ws no Tls) is connected in other programs such as Nekobox, but it is not connected in the Hidify program itself, the following example:

![Screenshot_2024-03-01-15-12-52-345_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/1af5b0a6-f93a-4909-96e8-9eca2e3cca2f)
![Uploading Screenshot_2024-03-01-15-12-51-043_app.hiddify.com.jpg…]()

### Version

0.16.16

### Platform/OS

Android

### Additional Context

![Screenshot_2024-03-01-15-12-52-345_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/da0f863d-d143-4d09-8630-37cc55322c5e)
![Screenshot_2024-03-01-15-12-51-043_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/15bfddf3-836d-41a7-bec8-809948bc43ee)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Would you please share the current-config.json and give me the original link you have set?

**Comment by Amir2367** [comment]
> Would you please share the current-config.json and give me the original link you have set?

Of course, this is an example config that works on Nekobox but not on Hiddify

vmess://eyJhZGQiOiJ6aXBzaG9wLnBiZGphcnVtLmluZm8iLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6InppcHNob3AucGJkamFydW0uaW5mbyIsImlkIjoiZjhmODUyYzktMTViNi00ODI5LWExZDYtZjYwYTAxMjY5OWMwIiwibmV0Ijoid3MiLCJwYXRoIjoiL3Z0dnk3bGU4Q0RscmpITEM1ZFVrNUFaS3lFIiwicG9ydCI6IjgwIiwicHMiOiLwn4es8J+Hp0dCLTE2NS4yMzIuMzMuMjI2LTAyMzQiLCJzY3kiOiJhdXRvIiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6IiIsInYiOiIyIn0=


![Screenshot_2024-03-10-15-02-21-228_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/9eb13fbf-4833-4091-bcc9-dcb5056aed01)
![Screenshot_2024-03-10-15-02-19-674_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/427770b3-0c09-4a50-b269-e3e2f6684582)
![Screenshot_2024-03-10-15-01-53-080_moe nb4a](https://github.com/hiddify/hiddify-next/assets/83357422/25445514-2133-4a44-9001-890ca72aec1e)

**Comment by Amir2367** [comment]
> Would you please share the current-config.json and give me the original link you have set?

Of course, this is an example config that works on Nekobox but not on Hiddify

vmess://eyJhZGQiOiIxMDMuMTU5LjIwNi4zNSIsImFpZCI6IjAiLCJhbHBuIjoiIiwiZnAiOiIiLCJob3N0IjoiIiwiaWQiOiJlMmU1MTFiMC03ZGVmLTRlMWItZDIzOC02Y2I1MzkxYjJlM2YiLCJuZXQiOiJ3cyIsInBhdGgiOiIvIiwicG9ydCI6IjMxOTQ1IiwicHMiOiLwn4e58J+HvFRXLTEwMy4xNTkuMjA2LjM1LTA0NzQiLCJzY3kiOiJhdXRvIiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6IiIsInYiOiIyIn0=

![Screenshot_2024-03-10-15-14-39-466_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/abe8de5e-8961-423d-85aa-c65b332f5b96)
![Screenshot_2024-03-10-15-14-38-255_app hiddify com](https://github.com/hiddify/hiddify-next/assets/83357422/6784b6b6-c3d0-46ec-a729-3e402ae56e6a)

**Comment by sdgsdsdhshd** [comment]
This question seems to be the same as #528 , did the comment mention deleting the configuration? ED=2048 can make it usable, but once updated, we need to redo this operation

**Comment by lymanjre** [comment]
Fixed try latest update
