### ISSUE TITLE
v0.16.16.dev detected as virus 

### ISSUE THREAD

**Issue by SudoerReodus** [hiddify/hiddify-next#595]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

v0.16.16.dev is being detected as containing viruses by 21 different Anti Virus softwares:

https://www.virustotal.com/gui/file/eb995db79d4ddd2dc49d94124b8debce89e38deaf19a7e2c03c8db831309d4ec/detection

### Reproduce the Bug

https://www.virustotal.com/gui/file/eb995db79d4ddd2dc49d94124b8debce89e38deaf19a7e2c03c8db831309d4ec/detection

### Version

v0.16.16.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
We are in contact with Windows defender to fix the issue

**Comment by hiddify-com** [comment]
It seems that it is fixed in the signed file [msix](https://github.com/hiddify/hiddify-next/releases/download/v0.16.16.dev/Hiddify-Windows-Setup-x64.Msix)
