### ISSUE TITLE
/tmp/.mount_HiddifqMEnQy/AppRun: line 28: exec: hiddify: not found Fedora 38

### ISSUE THREAD

**Issue by parisa-hr** [hiddify/hiddify-next#597]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

./Hiddify-Linux-x64.AppImage 
/tmp/.mount_HiddifqMEnQy/AppRun: line 28: exec: hiddify: not found

### Reproduce the Bug

cant run app image

### Expected Behavior

/tmp/.mount_HiddifqMEnQy/AppRun: line 28: exec: hiddify: not found

### Version

v0.16.16.dev 

### Platform/OS

Linux

### Additional Context

Fedora 38

### Relevant log output

```shell
/tmp/.mount_HiddifqMEnQy/AppRun: line 28: exec: hiddify: not found
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
fixed
