### ISSUE TITLE
مشکل اجرای برنامه در windows 10

### ISSUE THREAD

**Issue by withpouriya** [hiddify/hiddify-next#598]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

چه توی نسخه استیبل چه اخرین نسخه pre release که 0.16 هستش من نه نسخه پورتیبل و نه نسخه نصبی رو نمیتونم روی ویندوز نصب کنم متاسفانه
ویندوز من 10 64 بیت پرو هستش و طبق چیزیکه توی گیتهابتون خوندم نباید مشکلی داشته باشه اما هیچ جوره اجرا نشد هیچ اروری هم داده نشد چه در مرحله نصب چه وقتی برنامه کرش میکنه
فقط چند ثانیه بعد از اینکه میخواد اجراه بشه یه window باز میشه و بعد exit میشه
دیپندنسی خاصی مورد نیاز هست؟

### Reproduce the Bug

.

### Version

v.0.16

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
سلام لطفا لاگ موجود در 
%appdata%/hiddify
را بفرستید

**Comment by hiddify-com** [comment]
No response --> close
