### ISSUE TITLE
عدم اجرا و کرش در ویندوز ۱۰ 

### ISSUE THREAD

**Issue by Yaseehj2024** [hiddify/hiddify-next#599]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام متاسفانه نسخه ویندوزی در زمان اجرا در ویندوز ۱۰ بعد از نسخه ی ۰.۱۱ کرش میکنه و بعد از صفحه سفید میاد بیرون
روی سه سیستم با ویندوز ۱۰ این مشکل وجود نداره و همه نسخه ها اجرا میشه ولی این سیستم که سی پی یو قدبمی تری داره کرش میکنه
اینم خطا در log
18:50:37.872263 - [I] bootstrap: Starting Logger Contoller
18:50:37.872263 - [D] bootstrap: [logger controller] initialized in 0ms
18:50:37.872263 - [I] bootstrap: hiddify v0.16.16 (1616) [dev]
general release
windows ["Windows 10 Enterprise" 10.0 (Build 19045)]
18:50:37.873264 - [I] bootstrap: Starting GeoAssets
18:50:37.873264 - [D] GeoAssetRepositoryImpl: initializing
18:50:37.873264 - [D] DioHttpClient: setting proxy port: [2334]
18:50:37.920262 - [D] bootstrap: [geo assets repository] initialized in 47ms
18:50:37.920262 - [I] bootstrap: Starting Profile Repository
18:50:37.924261 - [D] bootstrap: [profile repository] initialized in 3ms
18:50:37.924261 - [I] bootstrap: Starting Singbox Service Provider
18:50:37.924261 - [D] FFISingboxService: initializing
18:50:37.924261 - [D] bootstrap: [sing-box] initialized in 0ms
18:50:37.924261 - [I] bootstrap: Starting Active Profile
18:50:37.924261 - [D] ActiveProfile: watching active profile
18:50:37.950259 - [D] AppDatabase: populating default geo assets
18:50:37.963259 - [D] bootstrap: [active profile] initialized in 39ms

### Reproduce the Bug

کلیک و صفحه ی سفید

### Version

0.16.16

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by vortex4242** [comment]
Make sure your older processor meets the minimum system requirements for the version of Windows you're using and the app you're trying to run. Make sure all your drivers, especially graphics drivers, are up to date.   Sometimes outdated drivers can cause compatibility issues with newer software. Try running the app in compatibility mode for an earlier version of Windows.   Right-click the app executable, go to Properties, then the Compatibility tab, and select an earlier version of Windows. Make sure both Windows 10 and the app you're trying to run are fully up to date.   Updates often contain bug fixes and compatibility improvements. Compatibility issues persist, consider running the application in a virtual machine with an earlier version of Windows installed.

**Comment by hiddify-com** [comment]
Would you please test the latest draft at 
https://github.com/hiddify/hiddify-next/releases/download/draft/Hiddify-Windows-Setup-x64.exe

and share the log?

Thanks

**Comment by hiddify-com** [comment]
no log -->close
