### ISSUE TITLE
هنگ کردن برنامه

### ISSUE THREAD

**Issue by liMilCo** [hiddify/hiddify-next#60]
### مشکل ?

برق رفت و کامپیوتر یک دفعه خاموش شد، بعد از بالا اومدن برنامه هیدیفای نکست دیگه باز نمیشد، ورژن های قدیمی تر را تست کردم به هیچ وجه بالا نمیومد فقط یک صفحه سفید از برنامه نشون میداد و هیچ کاری نمیکرد ...
با آنیستال کردن برنامه و نسب مجدد هم مشکل حل نمیشد ...

### راه حل

در نهایت در شاخه :
C:\Users\\{MyUser}\AppData\Roaming\
فلدر Hiddify را حذف کردم و بلاخره برنامه بالا اومد ...

### Version

تمام ورژن ها تا 0.8.11

### Platform/OS

Windows

**Comment by lymanjre** [comment]
ایشو جهت بررسی منتقل میشود. فعلا ایشو شما بسته میشود
