### ISSUE TITLE
HiddifyService.exe has security problems

### ISSUE THREAD

**Issue by ButcherWithSmile** [hiddify/hiddify-next#600]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I've scanned the HiddifyService.exe file on VirusTotal and some of the popular security services found security issues. Please consider this problem and solve it asap.

### Reproduce the Bug

https://www.virustotal.com/gui/file/f1b624ce3469f8a2865d86db3c02e35ec807b571457f45222b0854215e4b4730/detection

### Version

v0.16.16

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
It seems that it is fixed in the signed file [msix](https://github.com/hiddify/hiddify-next/releases/download/v0.16.16.dev/Hiddify-Windows-Setup-x64.Msix)
