### ISSUE TITLE
clash manual entry for sub link works on win 10 but fails on windows 11

### ISSUE THREAD

**Issue by netsupcloud** [hiddify/hiddify-next#602]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

clash manual entry for sub link works on win 10 but fails on windows 11 as unexpected error

### Reproduce the Bug

use windows 11 and import clash sub link by manual entry

### Version

0.16.16

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
incomplete
