### ISSUE TITLE
flutter run question

### ISSUE THREAD

**Issue by aweifly** [hiddify/hiddify-next#604]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

flutter run , then:

Swift Compiler Error (Xcode): Value of type 'LibboxBoxService' has no member 'sleep'
/Users/hanpi/Documents/Workspace/fly/hiddify-next-0.16.16.dev/ios/SingBoxPacketTunnel/SingBox/Extens
ionProvider.swift:156:23

### Reproduce the Bug

flutter run , then:

Swift Compiler Error (Xcode): Value of type 'LibboxBoxService' has no member 'sleep'
/Users/hanpi/Documents/Workspace/fly/hiddify-next-0.16.16.dev/ios/SingBoxPacketTunnel/SingBox/Extens
ionProvider.swift:156:23

### Version

v0.16.6 dev

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
Kindly check contribution guide and Makefile
