### ISSUE TITLE
Crash in Windows

### ISSUE THREAD

**Issue by neganmj** [hiddify/hiddify-next#605]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In windows 10, there was no version of the program that runs correctly, after installation it just crashes over and over, i deleted the folder in roming and another folders that admins tolds to delete,
i did even remove the software with a professional Program Remover but nothing can change.

No matter what, it just crash with a blank white page after a few seconds in both Setup and Portable version of EVERY Damn Releases !! What the Hell ?!? You guys / dev or whatever supposed to listen to this big issue, None of the goddamn ADMINS Care about our issue.
I'm using an amd cpu, my spec are higher than minimum system requirements, i don't know what should i suppose to do to fix this damn bug!
If you want member's support, just **fix** this Bullshit !🖕
If you can not, Just stop upload these useless Windows versions.

### Reproduce the Bug

Fucking blank white page

### Version

EVERY FUCKING VERSION

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
:)))))
Unfortunately we can not still reproduce the issue. we need more information or access to such system to understand the issue.
By the way would you please share your `app.log` in `%appdata%/hiddify` folder?

**Comment by neganmj** [comment]
> :))))) Unfortunately we can not still reproduce the issue. we need more information or access to such system to understand the issue. By the way would you please share your `app.log` in `%appdata%/hiddify` folder after installing latest draft at https://github.com/hiddify/hiddify-next/releases/download/draft/Hiddify-Windows-Setup-x64.exe?

[app.log](https://github.com/hiddify/hiddify-next/files/14512134/app.log)

**Comment by hiddify-com** [comment]
we found that the issue is with the system with dedicated gpu.
is it the case also for you?

**Comment by hiddify-com** [comment]
no response

**Comment by neganmj** [comment]
> we found that the issue is with the system with dedicated gpu. is it the case also for you?

No i don't think it's about the gpu, it's rx 570

**Comment by hiddify-com** [comment]
It is AMD CPU?

**Comment by neganmj** [comment]
> It is AMD CPU?

Yes it is.

**Comment by freeopensky** [comment]
same problem here
white blank window and close.
AMD CPU with windows 10 and windows 11
log file is attached
[app.log](https://github.com/hiddify/hiddify-next/files/14583308/app.log)
