### ISSUE TITLE
URL Scheme support

### ISSUE THREAD

**Issue by FeliksMarello** [hiddify/hiddify-next#61]
### Feature description

Hello!
If we're talking about adding a subscription link, which is very important for a modern client, I kindly request you to consider the possibility of adding so-called URL schemes to your application. They will enhance the user experience and make interaction easier.
For example, many applications on all platforms support this feature:
CLASH:
clashx://install-config?url=URL
ShadowRocket:
sub://URL
You can find all the examples here:
https://docs.marzban.ru/examples/url-scheme

We need this in order to allow users to add a subscription to the application with just one click from the subscription page.
![image](https://github.com/hiddify/hiddify-next/assets/24405246/f0ec4ca6-cd2d-46f8-a621-2a77802d181e)
If you add this feature, your application will become the ultimate solution for Windows users.

Thanx!

**Comment by problematicconsumer** [comment]
Hiddify Next already supports a wide range of schemes for deep linking. You can check them [here](https://github.com/hiddify/hiddify-next/blob/ada68384a4fbdf8c1c7120ff817c82ebda1e0af8/lib/utils/link_parsers.dart#L11). Though not all platforms have this feature at the moment.
Feed free to specify schemes you think should be added in the future.

**Comment by uprt** [comment]
@problematicconsumer  does this feature ever work?
I see in the code that you mentioned, there's a 'ss' schema in rawProtocols array,
but when I try to import from the clipboard a URL like "ss://2022-blake3-aes-128-gcm:lRmEQBJPsr174h6AF6zXqA%3D%3D@myhostname.com:555#MyServer", Hiddify-Next says:
![image](https://github.com/hiddify/hiddify-next/assets/15909793/08171944-7078-43c0-987c-375ee8c2285d)
and in the app logs I see only:
10:22:57.745981 - [W] ProfilesRepositoryImpl: error parsing config
10:22:57.985714 - [W] ProfilesNotifier: failed to add profile

Version is the latest one, v0.10.0 (1000) [prod]
