### ISSUE TITLE
naive proxy protocol support

### ISSUE THREAD

**Issue by UncleUncleWang** [hiddify/hiddify-next#611]
### Feature description

Dear developer, is support for the naive proxy protocol in the development plan?
hiddify next is such an excellent cross-platform proxy tool, I have used it on Android, Windows 11, and macOS. At the same time, naive proxy is an excellent protocol, but it lacks good client support. Can it be developed to support this protocol? Thank you so much

**Comment by hiddify-com** [comment]
PR welcomed
