### ISSUE TITLE
راه اندازی نسخه تور 

### ISSUE THREAD

**Issue by moli1369** [hiddify/hiddify-next#612]
### Feature description

سلام کاش قابلیتی میذاشتین که بشه فعال یا غیر فعالش کرد برای زمانی که کلا جواب نمیده و به صورت جامعه آزاد باشیم یعنی گزینه باشه که فعالش کرد هر گوشی رو به عنوان پروکسی بشناسه و شبیه توپولوژی  تور کار کنه و بتونیم از فیلترینگ خارج بشیم و همه سرور ها بهم متصل شه و اگر سروری کانفیگی فعالش کرد بتونه افراد دیگه که این گزینه رو فعال کنه میتونن از سرور های کلود و آزاد برای خود و دیگران استفاده کنه اما به نحوی باشه که سرور های که فراگمنتشون فعال باشه این کار رو کنن چون اگر ازاد باشه درصد فیلتر شدن سرور ها بالا میره.

**Comment by hiddify-com** [comment]
PR Welcomed
