### ISSUE TITLE
نمایش زمان و حجم باقی مانده[FR] 

### ISSUE THREAD

**Issue by mlm1102003** [hiddify/hiddify-next#613]
### Feature description

سلام
برای نمایش حجم و زمان باقی مانده تو برنامه  چه کدی رو باید تو لیست سرور ها قرار داد ؟

**Comment by mlm1102003** [comment]
از پنل دیگه استفاده می کنم 

میشه کاری کرد حجم و زمان رو این برنامه نشون بده ؟

**Comment by hiddify-com** [comment]
https://github.com/hiddify/hiddify-next/wiki/URL-Scheme
