### ISSUE TITLE
Not connecting all configs when Warp Options is on

### ISSUE THREAD

**Issue by Amir2367** [hiddify/hiddify-next#614]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When Warp Options is on, the connection button is disabled and nothing happens

https://github.com/hiddify/hiddify-next/assets/83357422/9fe02a19-d762-45ec-af25-cfc464f9ff08

### Reproduce the Bug

When Warp Options is on, the connection button is disabled and nothing happens

### Version

Draft versions from 7 days ago to one hour ago

### Platform/OS

Android

### Additional Context

https://github.com/hiddify/hiddify-next/assets/83357422/c6e47197-b2ee-4570-9942-7d7644e3c5a9

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Fixed in latest version
