### ISSUE TITLE
VPN Service Mode Speed Degradation Issue

### ISSUE THREAD

**Issue by SadraKafiri** [hiddify/hiddify-next#616]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After establishing a connection to a server in "VPN Service" mode, I noticed a significant degradation in speed after a few minutes. The issue is accompanied by a warning message:

`router: Hiddify!notifyNetworkUpdate 1`

This warning seems to be correlated with the drastic reduction in speed. the issue persists until I disconnect and reconnect to the VPN service. the problem is resolved temporarily.

### Reproduce the Bug

1. Open the application and connect to a server in 'VPN Service' mode.
2. Monitor the network performance for a few minutes.
3. Waiting for warning in logs

### Version

0.16.16 dev

### Platform/OS

Windows

### Additional Context

![photo_2024-03-07_13-59-37](https://github.com/hiddify/hiddify-next/assets/87757302/6ab5e42c-6eb8-4ac9-afe1-6b8d6271a3a0)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
refactored vpn service

**Comment by SadraKafiri** [comment]
bug still exist in 0.17.8 dev
