### ISSUE TITLE
قابلیت allow insecure 

### ISSUE THREAD

**Issue by mortezaghb95** [hiddify/hiddify-next#617]
### Feature description

لطفا امکان فعال کردن allow insecure رو در برنامه قرار بدین چون بعضی کانفیگ ها فقط با فعال بودن این گزینه کار میکنن

**Comment by hiddify-com** [comment]
add `insecure=1` to the url

**Comment by mortezaghb95** [comment]
I added allowInsecure=1 or Insecure=1 , but not work

Like this:

vless://####################...type=grpc&serviceName=&security=tls&fp=&alpn=&allowInsecure=1&sni=#################...
