### ISSUE TITLE
Missing VPN Permission in Android

### ISSUE THREAD

**Issue by leic4u** [hiddify/hiddify-next#62]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Device: Xiaomi 11 ( M2011K2C )
OS: MIUI 14.0.10 based on Android 13

The tip appears when I connect to my profile, and I can't find where I can configure VPN permissions

### Reproduce the Bug

1. Download the app from google play store and install it.
2. Open the app, add a new profile.
3. Tap to connect.

### Expected Behavior

VPN permissions can be automatically configured and the VPN connection can be enabled.

### Version

v.0.8.11

### Platform/OS

Android

### Additional Context

![1697134023554](https://github.com/hiddify/hiddify-next/assets/32786903/29466bad-83d8-4877-954d-d8cc0c3e9ac6)

### Relevant log output

```shell
No logs
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is transferred to be investigated. I close it now by the way

**Comment by UjuiUjuMandan** [comment]
@lymanjre 
Wait, is this marked as resolved? The issue still exists in latest v1.10.0 .

**Comment by AmrElsayyad** [comment]
Please, reopen this issue, since it's still not fixed in the latest version: 4.1.1

**Comment by junwonkim07** [comment]
The issue still exists in v4.1.1

Please reopen the issue

I'm running on Pixel 4

**Comment by paulhybryant** [comment]
+1, same error

**Comment by istarkov** [comment]
Pixel 9a same error

**Comment by TheRealAlexV** [comment]
I'm having the same issue

**Comment by istarkov** [comment]
in my case I had another VPN setup marked as "Always On" in VPN settings. Switching always on fixed the issue.
