### ISSUE TITLE
The white tray icon is hard to see

### ISSUE THREAD

**Issue by someonemax** [hiddify/hiddify-next#620]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The white tray icon is hard to see (to check whether the app is running or not), especially on lower contrast displays or for people with lower contrast vision.

Please switch the tray icon to the regular blue-filled hiddify icon (like in the program's title bar).

This will also improve the consistency of the program's icons used in various places.

Current system tray icon:

<img width="143" alt="Screenshot 2024-03-08 194339" src="https://github.com/hiddify/hiddify-next/assets/76533230/c327f400-b89d-4904-83d3-78227a509480">

Current program title bar icon:

<img width="132" alt="Screenshot 2024-03-08 194646" src="https://github.com/hiddify/hiddify-next/assets/76533230/a8ce370f-94d7-4e5e-9250-1500ccbd2546">

### Reproduce the Bug

Open the hiddify-next program on Windows and compare the icon on the system tray with the icon on the program's title bar.

### Version

0.16.16 dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by AlivE-git** [comment]
it would be great if the tray icon changed color as in the main program window.

**Comment by sky96111** [comment]
The tray icon is visually inappropriate in Windows Light theme. While in dark theme it looks great.
So I think just make a reverse color for tray icon in light theme will be nice.

**Comment by sky96111** [comment]
![image](https://github.com/hiddify/hiddify-next/assets/22412214/fd78ee12-7cf9-417d-8a43-925cf614b252)
I made a reversed color icon, which looks nice in light theme

**Comment by someonemax** [comment]
> ![image](https://private-user-images.githubusercontent.com/22412214/313905084-fd78ee12-7cf9-417d-8a43-925cf614b252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzMzMTUsIm5iZiI6MTcxMDkzMzAxNSwicGF0aCI6Ii8yMjQxMjIxNC8zMTM5MDUwODQtZmQ3OGVlMTItN2NmOS00MTdkLThhNDMtOTI1Y2Y2MTRiMjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWNkMzhjYTE3YzBmYzE1MzFmZWI2ZDMxOTk0M2NiOWQyM2Y1ZWIwOWZjNjkzMzg4MjAyMWZhZDU5ODljZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGNLf-XOZL1sUnP4GMc3RRhHvLlPYFdNKpa1xXiO70g) I made a reversed color icon, which looks nice in light theme

This has solved the issue on Windows, but has created a similar issue on Linux.
On Gnome (Fedora 39), the default tray icon used is the black one, which means it's literally invisible on the dark status bar of Gnome, unless you hover your mouse pointer on it. 


![Screenshot from 2024-03-20 14-37-25](https://github.com/hiddify/hiddify-next/assets/76533230/c5904dfd-10a0-41a1-b039-d4ffe25b76f3)


![Screenshot from 2024-03-20 14-37-46](https://github.com/hiddify/hiddify-next/assets/76533230/d06552e1-748a-4d80-935d-d02d6b66ebf6)

**Comment by sky96111** [comment]
A better soltion is add a preference setting ``Tray Icon Theme``, allowing system, light, dark.
But I'm not good at riverpod and made an attempt last night that failed.

**Comment by someonemax** [comment]
> A better soltion is add a preference setting `Tray Icon Theme`, allowing system, light, dark. But I'm not good at riverpod and made an attempt last night that failed.

The issue is that dark theme does not imply dark task/status bar and light theme does not imply light task/status bar.
For example on Gnome the default status bar is black, even on light theme.

I think the best solution would be to use a color that looks good (or at least is visible!) on all taskbar colors. 

For example orange or blue fill with black outline (so even if the user has orange or blue taskbar, the black outline would still make it visible).

**Comment by artenax** [comment]
> This has solved the issue on Windows, but has created a similar issue on Linux
I can confirm. The black icon is not visible on the black panel in **X**ubuntu 22.04 (Xfce).

> light theme does not imply light task/status bar
Yeah. **X**ubuntu 22.04 (Xfce) uses the default gray/white Greybird theme, quite nice btw, but the taskbar is black. With white font on it.

**Comment by Muska-Ami** [comment]
in kde plasma wayland with dark theme, it's completey invisable.
![image](https://github.com/hiddify/hiddify-next/assets/79651409/a6567468-6b1a-41b7-a0c4-50cf8399e0cf)

**Comment by lymanjre** [comment]
The issue is repetitive and registered before
