### ISSUE TITLE
مشکل در نسخه ویندوز و اندروید

### ISSUE THREAD

**Issue by moli1369** [hiddify/hiddify-next#624]
### Feature description

سلام همگی در نسخه گوگل پلی نسخه نمایشی و ng  بعد از اپدیت و حتی ویندوز در صورتی که فایروال رو روشن کنی هیچ کانفیگی رو دریافت نمیکنه اپدیت میشه اما هیچ اتصالی برقرار نمیکنه باید فایروال پنل رو خاموش کنی تا بتونی وصل شی .هچنین نمیتونی دامنه جدیدی اضافه کنی و خطای ارتباط با کلود فلر رو میده با اینکه برای تست پروکسی کلود هم خاموش کردم اما این خطا رو میده ممنون میشم برسی کنید البته خطای اتصال به کلود کاری به فایروال نداره و در کل اتصالی رو برقرار نمیکنه و باید برای اینکه ثبت کنی فایل پشتیبانی رو برگردونی اینجوری میتونی دامنه هات رو برگردونی

**Comment by lymanjre** [comment]
این ایشو نامرتبط با این ریپو است
