### ISSUE TITLE
مشکل فایل نصب

### ISSUE THREAD

**Issue by omidshojaee** [hiddify/hiddify-next#625]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

فایل نسخه 0.17.5-dev درست بیلد نشده و حجمش فقط 991 بایته

![image](https://github.com/hiddify/hiddify-next/assets/31741561/c0402892-530b-4cd6-8f47-2cc954348775)

### Reproduce the Bug

به صفحه releases برید

### Version

0.17.5.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Airuop** [comment]
+ نسخه ویندوز نصبی موجود نیست @hiddify-com

**Comment by lymanjre** [comment]
fixed
