### ISSUE TITLE
Android gVisor

### ISSUE THREAD

**Issue by hrkhl** [hiddify/hiddify-next#626]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After installing the latest version, without changing any settings, and just by clicking the connect button, this error appears:
initialize inbound/tun[tun-in]: unknown stack: gVisor

### Reproduce the Bug

just update and connect

### Version

v0.17.5

### Platform/OS

Android

### Additional Context

![IMG_20240310_174715_499](https://github.com/hiddify/hiddify-next/assets/30599040/fd09c1d4-3a33-47d6-8b49-e049e7f671a7)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Fixed
