### ISSUE TITLE
مشکل در نصب نسخه  ویندوز Official Setup

### ISSUE THREAD

**Issue by majidmcoin** [hiddify/hiddify-next#631]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در هنگام نصب این نسخه ارور زیر نمایش داده میشود

This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

### Reproduce the Bug

![image](https://github.com/hiddify/hiddify-next/assets/88514215/a2512272-9e20-448b-9137-cfe44725dccb)

### Version

v0.17.8.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
it needs time to be signed it is now signed

**Comment by Kouroshariafar** [comment]
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A). 
I have same problem

**Comment by PitBull-UX** [comment]
i have this PB too!
