### ISSUE TITLE
Can't run iOS flutter app with modified bundleid

### ISSUE THREAD

**Issue by developeranshul1986** [hiddify/hiddify-next#632]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I am using this project in my own project with different bundleID but getting the below error
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled

It crashes as soon the app open in the device.

### Reproduce the Bug

Change the bundle id to own project bundle id and after that I am not able to run the app

### Version

v1.8.7

### Platform/OS

iOS

### Relevant log output

```shell
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
check latest version
