### ISSUE TITLE
Android & Windows : timeout problem in warp

### ISSUE THREAD

**Issue by LitenBuzzTh** [hiddify/hiddify-next#635]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

As the title implied, there is a timeout problem when warp is enabled. when the vpn is still connected, and then you disconnect wifi and connect wifi again, the VPN will not work and there will be a red "timeout" text under the connect button.

after, when clicking disconnect, it is stuck at disconnecting, so in order for it to work, you would need to force stop the hiddify from phone settings, then re open it and click connect.

### Reproduce the Bug

1. open the app in android
2. enable warp
3. click connect
4. disconnect your internet
5. reconnect your internet
6. vpn will not work, so you would need to click disconnect vpn
7. sometimes it will be stuck on disconnecting 

### Version

17.8 dev

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by marathon9527** [comment]
i have same problem

**Comment by marathon9527** [comment]
i have same problem,

**Comment by marathon9527** [comment]
i have same problem

OS: windows 10 
version: 0.17.8

Problem status： Timeout

![upload](https://github.com/hiddify/hiddify-next/assets/101632272/270f9c3e-a1a6-47b2-8fae-e3677683329c)

**Comment by LitenBuzzTh** [comment]
update : in the new 0.17.12 dev version, the problem still remains unsolved.

**Comment by lymanjre** [comment]
The issue is repetitive
