### ISSUE TITLE
[FR] Support for iPhone && iPad

### ISSUE THREAD

**Issue by yinleiCoder** [hiddify/hiddify-next#636]
### Feature description

Do you have plans to support iPhone and iPad? I really need it, and it seems that someone has submitted a similar issue before. Can you provide an update on the progress of this matter?

**Comment by lymanjre** [comment]
yes we are in the process of releasing AppStore version. Be patient pls

**Comment by yinleiCoder** [comment]
> yes we are in the process of releasing AppStore version. Be patient pls

thank
