### ISSUE TITLE
About app.   درمورد اپ [FR] 

### ISSUE THREAD

**Issue by praim81** [hiddify/hiddify-next#638]
### Feature description

لطفا hiddify app برای ios هم توسعه بدید و انتشارش بدید خیلی بهش نیاز داریم  🙏🏼🙏🏼🙏🏼
Please develop and release hiddify app for ios we need it  🙏🏼🙏🏼🙏🏼

**Comment by lymanjre** [comment]
در حال انتشار هستیم
