### ISSUE TITLE
لطفا hiddify app برای ios هم توسعه بدید و انتشارش بدید خیلی بهش نیاز داریم 🙏🏼🙏🏼🙏🏼 Please develop and release hiddify app for ios we need it 🙏🏼🙏🏼🙏🏼[FR] 

### ISSUE THREAD

**Issue by praim81** [hiddify/hiddify-next#639]
### Feature description

لطفا hiddify app برای ios هم توسعه بدید و انتشارش بدید خیلی بهش نیاز داریم 🙏🏼🙏🏼🙏🏼
Please develop and release hiddify app for ios we need it 🙏🏼🙏🏼🙏🏼

**Comment by The-Erf** [comment]
سلام مشخص نیست نسخه ایفون کی ریلیز نهایی میشه؟
ایا الان که هنوز ریلیز نشده امکان استفاده از سورس هیدیفای نکست برای ساخت کلاینت شخصی برای ios وجود داره؟

**Comment by UbiVPN** [comment]
اگر عجله دارید، می‌توانید ابتدا این VPN رایگان را امتحان کنید، سپس وقتی نسخه iOS توسط توسعه‌دهنده آماده شد، آن را امتحان کنید.

Android: https://play.google.com/store/apps/details?id=com.UbiVPN.fmobiles
iOS: https://apps.apple.com/us/app/ubivpn/id6475045953
Web: https://ubivpn.com

**Comment by lymanjre** [comment]
دذ حال توسعه است . منتظر انتشارش باشید
