### ISSUE TITLE
Intel macOS does not work

### ISSUE THREAD

**Issue by shahryarjb** [hiddify/hiddify-next#64]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Each config that works in another software like Foxray or V2BOX, it does not work inside `hiddify-next`
When I see the log section

By the way, I changed the ip
```
ERROR [30207082 0ms] outbound/urItest [auto]: dial cp 11.111.111.111:0: connect: can't assign requested
address

ERROR [4009121092 0ms] outbound/uritest [auto]: dial cp 11.111.111.111:0: connect: can't assign
requested address

ERROR [4009121092 0ms] inbound/mixed [mixed-in]: process connection from 127.0.0.1:53420: dial tcp
11.111.111.111:0: connect: can't assign requested address
```

### Reproduce the Bug

macOS version: 13.4 Intel core

### Version

v0.9.0

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is transferred to be investigated. I close it now by the way
