### ISSUE TITLE
Hiddfy beta is full in testflight(ios) app

### ISSUE THREAD

**Issue by Nikiwhoiam** [hiddify/hiddify-next#640]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I cant install hiddify in ios because the beta is full in testflight 

### Reproduce the Bug

1.in hiddfy website click install profile link 
2. Refering to test flight app in ios 17 
3. Show me “beta is full”
4. The icant install hiddify
5. 
![IMG_4774](https://github.com/hiddify/hiddify-next/assets/163155598/9567f24c-8b74-49df-9760-912325904f8e)

### Version

Testflight latest version

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by djsmith0623** [comment]
ME TOO 我也有一样的问题，请问怎样才可以收到iOS的邀请？

**Comment by lymanjre** [comment]
wait till we publish the app on AppStore

**Comment by djsmith0623** [comment]
> wait till we publish the app on AppStore

thank you
