### ISSUE TITLE
warp setting problem in v0.17.8.dev

### ISSUE THREAD

**Issue by garodemane** [hiddify/hiddify-next#643]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I had very good experience with warp new experimental settings in v0.16.16.dev but when I have installed v0.17.8, all my configs were broken.

### Reproduce the Bug

1.setting
2.warp

### Version

v0.17.8.dev

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
fixed in next release
