### ISSUE TITLE
[FR]  Set the App auto connected when OS launched

### ISSUE THREAD

**Issue by dbsxdbsx** [hiddify/hiddify-next#645]
### Feature description

On win10, with the App version 0.14.20,  I've set launching the App when the OS is initialed. Indeed, it is launched, but the service is not automatically connected:
![image](https://github.com/hiddify/hiddify-next/assets/17372655/1f3685dd-bab3-4e44-96e9-fc09d3cae711)

I have to manually connect by mouse-clicking.

**Comment by papampi** [comment]
+1

**Comment by lymanjre** [comment]
Issue is repetitive
