### ISSUE TITLE
H2 Configs doesn't work 

### ISSUE THREAD

**Issue by MikeeSierrah** [hiddify/hiddify-next#65]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

پراکسی های h2 در برنامه متصل نمیشن ایا برنامه دارین که این مشکلو حل کنید یا همیشه قراره اینجوری بمونه   - دلیل اینکه این مشکلو دوباره بیان میکنم اینه که تو لیستتون نگاه کردم  اینکه  که نوشته بودید مشکل این باگ حل شده ولی من همچین چیزیو تو نسخه 9 ندیدم 
![image](https://github.com/hiddify/hiddify-next/assets/144580664/ee5aaa6b-220e-4fd2-9378-1195f83f36cf)

### Reproduce the Bug

وقتی از کانفیگ های h2 استفاده میکنم کاملا اینترنت قطع میشه ولی با h1 بهم پینگ میده و مشکلی نداره - تو برنامه های دیگه تست کردم مشکلی نداشت کانفیگا 

### Version

v0.9.0

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این باگ مجددا بررسی میشه. ایشو شما فعلا بسته میشه
