### ISSUE TITLE
Android tv problem

### ISSUE THREAD

**Issue by MH140000** [hiddify/hiddify-next#650]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Can not move with remote control

### Reproduce the Bug

1. Open app 2. Can move with keyboard but can not work with remote control

### Expected Behavior

Work with remote control

### Version

0.17

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Unfortunately this is flutter issue and hopfulltywill  be fixed soon

**Comment by aleksei95** [comment]
как добавить ключ на Андроид тв, у меня не получается выделить ключ?

**Comment by aleksei95** [comment]
how to add a key to Android TV, I can't select the key in the file manager
