### ISSUE TITLE
Windows version crash!!

### ISSUE THREAD

**Issue by neganmj** [hiddify/hiddify-next#652]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I posted my problem but got no response from your admins on how to fix this damn white screen page!!

### Reproduce the Bug

Just fix this damn shit

### Version

0.16.16

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
we can not reproduce the issue to fix it

**Comment by super302** [comment]
![Snipaste_2024-03-25_13-30-58](https://github.com/hiddify/hiddify-next/assets/30402961/1354b8f0-4e73-4636-96ee-8e04d2444e7c)
我遇到的类似的问题，我怀疑是我的win10是精简版，缺少了相关运行库、框架或字体。目前在v1.0.0和v1.1.1都遇到了这个问题，还没找到具体原因。

**Comment by neganmj** [comment]
> ![Snipaste_2024-03-25_13-30-58](https://private-user-images.githubusercontent.com/30402961/316396566-1354b8f0-4e73-4636-96ee-8e04d2444e7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDk1OTQsIm5iZiI6MTcxMTM0OTI5NCwicGF0aCI6Ii8zMDQwMjk2MS8zMTYzOTY1NjYtMTM1NGI4ZjAtNGU3My00NjM2LTk2ZWUtOGUwNGQyNDQ0ZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA2NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MTliYTYxZjhiZDFmMGZmNWY0NTdkMzIxYWNhY2I1MWNlNzVkNDk5OWE2NTgwZjgzN2I3YjU5OWY4ZjBkNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L94QZndxliNh15pKo9lX0L4YuJfULoHXustrALLC01U) 我遇到的类似的问题，我怀疑是我的win10是精简版，缺少了相关运行库、框架或字体。目前在v1.0.0和v1.1.1都遇到了这个问题，还没找到具体原因。

也许是关于 AMD 处理器，就像在搭载 AMD CPU 的电脑上运行时出现的错误一样
