### ISSUE TITLE
Failed to add WARP profile v0.17.12

### ISSUE THREAD

**Issue by alirezafarvardin** [hiddify/hiddify-next#656]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When trying to import warp://auto from clipboard, the app show failure: "Failed to Add Profile, Invalid Configs".

### Reproduce the Bug

1. New Profile
2. Add From Clipboard

### Version

v0.17.12

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Not reproduceable
