### ISSUE TITLE
فریز شدن اپ پس از خارج کردن از sleep mode در زمان اتصال کانفیگ های هیستریا و توییک و وایرگارد

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#657]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

.

### Reproduce the Bug

.

### Version

0.17.12

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
not enough description
