### ISSUE TITLE
Can't sideload Hiddify Next ios version.

### ISSUE THREAD

**Issue by momalekiii** [hiddify/hiddify-next#658]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After using AltStore, Sideloadly, for Sideload the .ipa file of HN, App successfully loads on the device but when trying to open it, it will crash ASAP right on the Apps Splash Screen!

if it was in need, tell me to share Diag files with you.

Device Os : iOS 17.4

### Reproduce the Bug

1. Sideload using AltStore/Sideloadly
2. Sign the app on your  ID
3. Try to open the app
4. BOOM, you will face the problem (Crash) !

### Version

v0.17.12 Pre-release

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Pls wait for AppStore version
