### ISSUE TITLE
کار نکردن کانفیگ های edgetunnel

### ISSUE THREAD

**Issue by Azadi743** [hiddify/hiddify-next#659]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام کانفیگ های ادج تونل که با استفاده از ورکر کلادفلر ساخته میشن به هیچ وجه  در هیدیفای کار نمیکنند درحالی که در سایر برنامه ها مشکلی ندارن

### Reproduce the Bug

EdgeTunnel Configs Connection Error

### Version

0.17.12

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Use the latest update. It s fixed
