### ISSUE TITLE
Curl reports SSL_ERROR_SYSCALL after using proxy.

### ISSUE THREAD

**Issue by anansi2safe** [hiddify/hiddify-next#669]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After opening the proxy, I encountered the following error when using curl to access Google:
```
> curl -v https://www.google.com
* processing: https://www.google.com
* Uses proxy env variable no_proxy == 'localhost, 127.0.0.1, ::1'
* Uses proxy env variable https_proxy == 'https://127.0.0.1:2334'
*   Trying 127.0.0.1:2334...
* Connected to 127.0.0.1 (127.0.0.1) port 2334
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:2334 
* Closing connection
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:2334
```

### Reproduce the Bug

curl https://www.google.com

### Version

0.14.20

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by anansi2safe** [comment]
I have found a solution to this issue. Please disregard it.

**Comment by eattomatoeveryday** [comment]
> I have found a solution to this issue. Please disregard it.

hi，i meet the same error, may i know how you solve it?
