### ISSUE TITLE
[FR] Add Transproxy mode from Shadowsocks app.

### ISSUE THREAD

**Issue by Anderhar** [hiddify/hiddify-next#673]
### Feature description

Currently, Hiddify offers a choice of two operating modes: VPN and SOCKS5/HTTP proxy, the scope of which is quite limited. But Shadowsocks app for Android has a third, the most flexible mode [Transproxy](https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#how-to-use-transproxy-mode), which provides users of rooted devices with many demanded options (via iptables), like tunneling native clients of VPN services or proxying proxy-incompatible apps without occupying system VPN. This is a very smart override to root support that is definitely lacking in apps like Hiddify.

**Comment by hiddify-com** [comment]
It will be added in the next version
