### ISSUE TITLE
support warp on warp Inline URL

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#675]
### Feature description

please add support **warp on warp Inline URL** e.x:

- warp://license@CleanIP-1@CleanIP-2@CleanIP-3@.../?ifp=5-10
- warp://CleanIP-1@CleanIP-2@CleanIP-3@.../?ifp=5-10
- warp://auto@auto@auto/?ifp=5-10

**Comment by hiddify-com** [comment]
It is already supported

You can use
warp://auto&&Detour=warp://auto

**Comment by Morrigan-Ship** [comment]
i know detour but have bug


I think detour has a bug.

The purpose of "detour" is to combine configs.

It means that the second server knows the first server as the client, not my system
There is only the first server that knows my system as a client

Like warp on warp or wow

Inside wow, the main location (Iran) is hidden, unlike normal warp.

But there is a location leak inside the detour
for example:
warp://auto&&detour=warp://auto
There is a location leak and the original IP is exposed, while it is something like warp on warp
Version 1 one
