### ISSUE TITLE
support ssh URL scheme -i option | parameter

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#676]
### Feature description

its default scheme
`ssh://user:pass@server:22/?pk=pk&hk=hk"`

you can add -i option of ssh to hiddify scheme for servers that dosnt username password for ssh.
like Amazon servers.
my example i recommend for adding feature:

- `ssh://server:22/?i=/Path_cert_file.pem`

**Comment by hiddify-com** [comment]
You need to put the content of Path_cert_file.pem inside pk parameter


However be aware that it needs some configuration on the server side

**Comment by Morrigan-Ship** [comment]
what is hk parameter?
