### ISSUE TITLE
لود نشدن لیست پروکسی ها در نسخه 18 ویندوز

### ISSUE THREAD

**Issue by solirf** [hiddify/hiddify-next#677]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

لود نشدن لیست پروکسی ها در نسخه 18 ویندوز

### Reproduce the Bug

بعد از کانکت شدن منو Proxy در حالت loading می ماند

### Version

v0.18.0.dev

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by javadgh6** [comment]
the same is seen in macOS version in the latest update
<img width="859" alt="Screenshot 2024-03-18 at 1 44 33 PM" src="https://github.com/hiddify/hiddify-next/assets/67070312/99587ff6-e79f-46e2-8f10-21e6a39ce54b">

**Comment by solirf** [comment]
Fixed in Lastest Actions Build
