### ISSUE TITLE
[BUG] iOS IPA v1.0.0 Crash

### ISSUE THREAD

**Issue by bart3nder** [hiddify/hiddify-next#679]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hi.
Hiddify v1.0.0 IPA file crashes and not starts on iOS 17.4 (sideloaded).

### Reproduce the Bug

Sideload IPA file and see.

### Version

v1.0.0

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by deksden** [comment]
Confirming: Sideloaded 1.0.0 via Sideloadly on my iOS 17.4 crashes.

**Comment by beenbin** [comment]
Confirming: Sideloaded 1.1.1 via Sideloadly on my iOS 17.3.1 crashes too

**Comment by warllus** [comment]
Confirming same happen to me

**Comment by lymanjre** [comment]
wait for AppStore version

**Comment by Supreme-A** [comment]
OK

 

发件人: ***@***.*** ***@***.***> 代表 ratu.sh
发送时间: 2024-06-19 20:43
收件人: hiddify/hiddify-next ***@***.***>
抄送: Supreme-A ***@***.***>; Comment ***@***.***>
主题: Re: [hiddify/hiddify-next] [BUG] iOS IPA v1.0.0 Crash (Issue #679)

 

wait for AppStore version

when ETA ?

**Comment by blagobiz** [comment]
An update was released today https://github.com/hiddify/hiddify-next/releases

but on ios 17.6.1 the app crashes and won't launch.

**Comment by blagobiz** [comment]
I made a digital ip subscription but the app still crashes, tell me if there is a link to TrollStore.

**Comment by blagobiz** [comment]
Then what is the solution? Can you tell me

**Comment by blagobiz** [comment]
ok thx
