### ISSUE TITLE
[FR] Socks5(4), http,https proxy with authentication 

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#68]
### Feature description

درود
در بیشتر سیستم های شرکت ها یا ادارات، هر کاربر برای اتصال به اینترنت می بایست پروکسی وارد کند تا به اینترنت متصل شود، پس در صورت امکان قابلیت وارد کردن پروکسی های ساکس۵ و ساکس۴ و https و http (با authentication) را در تنظیمات نرم افزار فراهم کنید (مشابه orbot)
در صورت امکان در جزو اولویت هایتان قرار بگیرد

سپاس

**Comment by lymanjre** [comment]
برای بررسی منتقل شد. این ایشو فعلا بسته میشود
