### ISSUE TITLE
Unable to import HttpUpgrade configs

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#680]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

کانفیگ های مبتنی بر HttpUpgrade در اخرین رلیز 1.0.0 ایمپورت نمی شود. به طور مثال:
vless://5gd14d91-90cd-4844-99c8-4470d7e81178@www.speedtest.net:443?path=%2FXiYmyYgL6wPf&security=tls&encryption=none&alpn=http/1.1&host=google.com&fp=chrome&type=httpupgrade&sni=google.com#CDN+tls+httpupgrade+CDN+vless

### Reproduce the Bug

.

### Version

1.0.0

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
It is not yet supported
It will be supported soon

**Comment by hiddify-com** [comment]
It is already supprted if you use singbox config but for sublink it will be added in next version
