### ISSUE TITLE
دریافت اطلاعات مغایر با حریم خصوصی

### ISSUE THREAD

**Issue by NIKJOO** [hiddify/hiddify-next#684]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و عرض وقت بخیر
چرا برنامه هیدیفای به اطلاعات سیستم دسترسی پیدا میکنه ؟ آیا لزومی برای دریافت این اطلاعات هست ؟ آیا جایی کاربرد داره ؟ اگر بله لطفا" توضیح بفرمائید

### Reproduce the Bug

![2024-03-19_003110](https://github.com/hiddify/hiddify-next/assets/1070842/8b607e1b-a638-41c8-8fb2-401459fe7fec)

### Version

v1.0.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Alexander-McQuen** [comment]
these serious concerns have been reported to them as many as time that possible,  hiddify hides behind the mask of helping people, and by making social games tried to hide the fact that hiddify apps are not safe enough, 

This app is highly vulnerable for being misused by hackers and Iranian government to approaches the clients all over the Iran,

**Comment by hiddify-com** [comment]
همانطور که میدانید نحوه گزارش باگ باید به صورت کامل باشد
قابل مشاهده هست که این اطلاعات توسط یک کتابخانه برنامه مورد نیاز بوده و طبیعتا این اطلاعات در سرورهای هیدیفای ذخیره نمیشود چرا که اساسا هیدیفای سروری ندارد.

ممنون میشیم توضیح دهید در چه موقعی چنین اتفاقی می افتاد

همچنین کانفیگ برنامه را از طریق منو اکسپورت نموده و در اینجا پیست کنید
![share_7814069585449945714](https://github.com/hiddify/hiddify-next/assets/114227601/dc931215-069d-4c2f-9d63-3326fac58f94)

**Comment by hiddify-com** [comment]
خوشحالیم که بلاخره توانستید از گیتهاب استفاده کنید
بهتر است [این داکیمونت ](https://stackoverflow.com/help/minimal-reproducible-example)را هم مطالعه کنید تا متوجه شوید چگونه میتوان یک MRE ساخت و که برای ایجاد ایشو ضروری است.


البته متوجه هستیم به عنوان یک تازه کار امنیتی دنبال دیده شدن هستید اما بهتر بود کمی بیشتر process monitor را یاد میگرفتید تا متوجه شوید که stack trace این call از کجاست.

همانطور که در stack trace مشاهده میکنید این کال توسط flutter engine انجام شده 
![image](https://github.com/hiddify/hiddify-next/assets/114227601/d04e425f-a0b7-44d7-aab8-b1676e83a8bf)

به عنوان نمونه یک پروژه خالی فلاتر از ریپازیتوری آفیشیال https://github.com/flutter/samples/tree/main/material_3_demo نیز چنین موضوعی دارد.

![image](https://github.com/hiddify/hiddify-next/assets/114227601/e6f7241c-12cc-4e44-b467-6b440c684547)


هیدیفای اساس هیچ سرور متصلی به این اپلیکیشن ندارد و طبیعتا هیچ اطلاعاتی به سرورهای هیدیفای ارسال نمیشود.

**Comment by Emrepuf** [comment]
آقای @NIKJOO  ارادت؛

در ادیت اول متن گزارش شما مشاهده کردم پرسیده بودید:

> ### "آیپی که در فنلاند هست و برنامه مرتب با اون در ارتباط هستش آیا به برنامه ربط داره یا به کانفیگ"

که پاکش کردین ولی من کنجکاو شدم بپرسم که این چیشد؛ 

### آیپی فنلاند به کانفیگ **خودتون** ربط داشت یا **عرزشیا و سایبریا** فنلاند؟

ممنون میشم شفاف سازی صورت بگیره چون _بو_ میده *^____^*

**Comment by NIKJOO** [comment]
ممنون که بار دیگه نشون دادید که ابدا" انتقاد پذیر نبوده و به هیچ عنوان رفتار حرفه ای ندارید !
به هر حال فقط اینجا گذاشتم تا دیگران نحوه برخورد شما رو ببینن ، یه کاربر حتی اگر به اشتباه هم چیزی بذاره رفتار حرفه ای اینه که شما پاسخ بدی نه اینکه تمسخر کنی و به حاشیه بکشونی ، به هر حال ، نشون دادید که چقدر در قبال برنامه خودتون مسئولیت دارید و من هم مسائلی رو که میدونم تو توییتر منتشر میکنم و  این صرفا" به جهت آشنا کردن افراد در مورد نحوه ادبیات شما بود

**Comment by hiddify-com** [comment]
پرسیدن سوال اشتباه هیچ اشکالی نداره
اما وقتی مانند مجرم با دیگری رفتار میکنید بدون اینکه کوچکترین بررسی داشته باشید و توییت کنایه آمیز می‌زنید مشخص میشود یک متخصص امنیت تازه کار هستید

**Comment by NIKJOO** [comment]
باشه قبوله ، من تازه کارم
فقط خواستم ادبیات شما در قبل افراد تازه کار رو هم به مردم نشون داده باشم تا جای بحث و حرف و حدیثی دیگه نمونه.

**Comment by hiddify-com** [comment]
اشکالی نداره شما هم بلاخره باید یاد بگیرید چگونه از گیتهاب استفاده کنید،
یک MRE ایجاد کنید
قبل از انتشار یک چیزی که به آن مطمئن نیستید اول دوبار بررسی کنید و تصور نکنید کشف بزرگی کردید و فوری توییت کنایه آمیز نزنید 
سپس به جای آنکه به توسعه دهنده اتهام بزنید، صورت دوستانه با توسعه دهنده در میان بگذارید

اگر توسعه دهنده جوابگو نبود، میتوانید کد را بررسی کنید

اگر هم علم آن را نداشتید، می‌توانید با سایر افراد خبره در میان بگذارید که آیا تصور شما درست بوده است یا خیر

در هر صورت بهتر است قبل از آنکه به توسعه دهنده برچسب بزنید کمی بررسی کنید و دوستانه مطرح کنید

**Comment by NIKJOO** [comment]
در مجموع خواستم اینجا باهاتون تعامل بگیرم تا مردم ببینند که ادبیات شما به چه شکل هستش
آخرین پیام بنده.

**Comment by Morrigan-Ship** [comment]
> ممنون که بار دیگه نشون دادید که ابدا" انتقاد پذیر نبوده و به هیچ عنوان رفتار حرفه ای ندارید !

خب الدنگ محترمانه جوابت رو داد برعکس من
محترمانه و منطقی جوابت رو داده

**Comment by Morrigan-Ship** [comment]
> در مجموع خواستم اینجا باهاتون تعامل بگیرم تا مردم ببینند که ادبیات شما به چه شکل هستش

والا خب سرشون شلوغ هست این همه پیام هست این همه زحمت میکشن
بعد میبینن یکی بهشون اتهام میزنه
حق دارن عصبی بشن هم من هم شما برنامه نویس هستیم

پس درک میکنیم فشار این کار رو پس باید بدونین چجوری با یک برنامه نویس پرکار حرف بزنید که رو مخش راه نرید

**Comment by cr4zyfish** [comment]
من دلیل توییت‌های قبلی و عجیب این آقا یعنی NIKJOO رو نمی‌دونم. ولی این توییت اخیری که داده چی؟ مثل اینکه پنل یک باگ داره میشه وارد قسمت ادمین شد. این یک باگ قدیمی بوده یا موضوع دقیقا چی هست؟

**Comment by Morrigan-Ship** [comment]
> من دلیل توییت‌های قبلی و عجیب این آقا یعنی NIKJOO رو نمی‌دونم. ولی این توییت اخیری که داده چی؟ مثل اینکه پنل یک باگ داره میشه وارد قسمت ادمین شد. این یک باگ قدیمی بوده یا موضوع دقیقا چی هست؟

مطمعن باش اگر باگ جدی بود تا الان همه هزار بار فهمیده بودن
چون این یک برنامه جنجالی هست و همه روش زومن

**Comment by hiddify-com** [comment]
> من دلیل توییت‌های قبلی و عجیب این آقا یعنی NIKJOO رو نمی‌دونم. ولی این توییت اخیری که داده چی؟ مثل اینکه پنل یک باگ داره میشه وارد قسمت ادمین شد. این یک باگ قدیمی بوده یا موضوع دقیقا چی هست؟ یا شاید هم اینا پنل‌هایی هستن که پسورد ندارن کلا جریان چیه؟

اومده یه چیزی روی ورژن 5 ماه پیش ما گفته :))))) مثل اینکه بری در مورد ویندوز xp حرف بزنی. ورژن الان ما 10.12.1 هست. چیزی تونسته پیدا کنه؟

این اقا هیچ سوادی نداره و دنبال دیده شدنه برای همین دروغ منتشر میکنه بعدش هم که معلوم میشه دروغه پاک میکنه بدون اینکه عذرخواهی کنه. دقیقا رفتار مشابه سایبری ها.

 کلی متخصص امنیتی به ما محرمانه باگ ریپورت کردند و ما هرچیزی بوده سریع رفع کردیم و کلی هم ازشون تشکر کردیم.

**Comment by hiddify-com** [comment]
اومده یه چیزی روی ورژن 5 ماه پیش ما گفته :))))) مثل اینکه بری در مورد ویندوز xp حرف بزنی. ورژن الان ما 10.12.1 هست. چیزی تونسته پیدا کنه؟

این اقا هیچ سوادی نداره و دنبال دیده شدنه برای همین دروغ منتشر میکنه بعدش هم که معلوم میشه دروغه پاک میکنه بدون اینکه عذرخواهی کنه. دقیقا رفتار مشابه سایبری ها.

کلی متخصص امنیتی به ما محرمانه باگ ریپورت کردند و ما هرچیزی بوده سریع رفع کردیم و کلی هم ازشون تشکر کردیم. 
نمونه ایمیلی که ما گرفتیم را مشاهده کنید مقایسه کنید با اون آدم که اینقدر بی سواده حتی نفهمیده که کانکشن به ip کانفیگ خودش بوده، ایشو زده بعد فهمیده، ادیت کرده (هیستوری ادیت پست اول رو ببینید):
![image](https://github.com/hiddify/hiddify-next/assets/114227601/9552b3f1-5780-430a-b435-daa934d1bdce)

**Comment by Morrigan-Ship** [comment]
> کلی متخصص امنیتی به ما محرمانه باگ ریپورت کردند و ما هرچیزی بوده سریع رفع کردیم و کلی هم ازشون تشکر کردیم.

گودرت بی نهایت :))
پاینده و موفق باشید پر گودرت ادامه بدید
کارتون درسته حرف ندارین💖💓💞🩷🧡💛💚💙🩶

**Comment by NiREvil** [comment]
> ممنون که بار دیگه نشون دادید که ابدا" انتقاد پذیر نبوده و به هیچ عنوان رفتار حرفه ای ندارید ! به هر حال فقط اینجا گذاشتم تا دیگران نحوه برخورد شما رو ببینن ، یه کاربر حتی اگر به اشتباه هم چیزی بذاره رفتار حرفه ای اینه که شما پاسخ بدی نه اینکه تمسخر کنی و به حاشیه بکشونی ، به هر حال ، نشون دادید که چقدر در قبال برنامه خودتون مسئولیت دارید و من هم مسائلی رو که میدونم تو توییتر منتشر میکنم و این صرفا" به جهت آشنا کردن افراد در مورد نحوه ادبیات شما بود

داداش تو چه زیرخاکی هستی دیگه، انگاری من بیام وایسم جلو روی تو بهت بگم تو **کون‌کشی** و بعد بگم اگه نیستی پس بفرما ثابت کن، خب این مسخره بازی نیست ب نظرت؟ من نه شمارو میشناسم نه توسعه دهنده های این پروژه رو، اومده بودم یه پیشنهاد درباره فونت برنامه بدم ک چشمم خورد ب سسشعر شما، چرا کولی بازی درمیاری مرد حسابی، چرا مث اون ادمای پنج دلاری زیر پل ... دنبال شر میگردی یکی بهت انگشتش بخوره بیافتی زمین کف و خون بالا بیاری دادو هوار کنی ای ملت دیدین گفتم دیدن فلان بود حق با من بود، من الان قبل از اینکه ریپلی بزنم رفتم گزارش قبلیتونم دیدم، اون از این سری هم مسخره تر بود، جسارتا چون مطمعنم تو حوزه امنیت سوادت صفره واسه همین به زبون عامیانه حرف زدم الان، اگر از کولی بازی تموم شدی بگو که بحث تخصصی بکنیم بلکه رفتی پی کارت زیر همون پل و ول کردی این پروژه رو، من تو روسیه بودم Hiddify next دیدم استفاده میکردن تو چین بودم اونموقع HiddifyNG دیدم استفاده میکردن، تو ایران کم ادم حسابی تو این حوزه نداریم و اتفاقا چندتا از اونا دوستای خودمن ک تحسین میکنن همیشه این پروژه رو، توعه پلشت چی میگی این وسط؟ اخه باگی ام گزارش نکردی تو این دو سری، الان ک فقط با این آخری داد زدی من بی سواد بی سوادم تو قبلی ام قشنگ داد زدی تازه میخوام شروع کنم منم ببینین منم بازی منم منم بازی ، خسته شدم از تایپ لاشی برو تو اینستاگرام چندتا بچه سال جمع کن دور خودت براشون دوره بذار دیگه چکار میکنی اینورا 😂😂
من جای توسعه دهنده های این پروژه بودم خیلی بد رفتار میکردم، مگه ملت عنتر تو هستن ک بیای پرت و پلا بنویسی و اینا بخوان کلی وقت بذارن که ثابت کنن روی سوالت اشتباهه اصلا 
اقا راستی نکنه دنبال پول میگردی ؟؟ خدایی جدی هستم اگه پول میخوای بفرس واسم همینجا یه ولت بذار بزنم فقط شرت کم شه، حقیقتا شرم کردم اسمم نیماس ✋اولین بار بود تو گیت‌هاب دیدم کسی کولی بازی دربیاره

**Comment by NiREvil** [comment]
> > ممنون که بار دیگه نشون دادید که ابدا" انتقاد پذیر نبوده و به هیچ عنوان رفتار حرفه ای ندارید ! به هر حال فقط اینجا گذاشتم تا دیگران نحوه برخورد شما رو ببینن ، یه کاربر حتی اگر به اشتباه هم چیزی بذاره رفتار حرفه ای اینه که شما پاسخ بدی نه اینکه تمسخر کنی و به حاشیه بکشونی ، به هر حال ، نشون دادید که چقدر در قبال برنامه خودتون مسئولیت دارید و من هم مسائلی رو که میدونم تو توییتر منتشر میکنم و این صرفا" به جهت آشنا کردن افراد در مورد نحوه ادبیات شما بود
> 
> داداش تو چه زیرخاکی هستی دیگه، انگاری من بیام وایسم جلو روی تو بهت بگم تو **کون‌کشی** و بعد بگم اگه نیستی پس بفرما ثابت کن، خب این مسخره بازی نیست ب نظرت؟ من نه شمارو میشناسم نه توسعه دهنده های این پروژه رو، اومده بودم یه پیشنهاد درباره فونت برنامه بدم ک چشمم خورد ب سسشعر شما، چرا کولی بازی درمیاری مرد حسابی، چرا مث اون ادمای پنج دلاری زیر پل ... دنبال شر میگردی یکی بهت انگشتش بخوره بیافتی زمین کف و خون بالا بیاری دادو هوار کنی ای ملت دیدین گفتم دیدن فلان بود حق با من بود، من الان قبل از اینکه ریپلی بزنم رفتم گزارش قبلیتونم دیدم، اون از این سری هم مسخره تر بود، جسارتا چون مطمعنم تو حوزه امنیت سوادت صفره واسه همین به زبون عامیانه حرف زدم الان، اگر از کولی بازی تموم شدی بگو که بحث تخصصی بکنیم بلکه رفتی پی کارت زیر همون پل و ول کردی این پروژه رو، من تو روسیه بودم Hiddify next دیدم استفاده میکردن تو چین بودم اونموقع HiddifyNG دیدم استفاده میکردن، تو ایران کم ادم حسابی تو این حوزه نداریم و اتفاقا چندتا از اونا دوستای خودمن ک تحسین میکنن همیشه این پروژه رو، توعه پلشت چی میگی این وسط؟ اخه باگی ام گزارش نکردی تو این دو سری، الان ک فقط با این آخری داد زدی من بی سواد بی سوادم تو قبلی ام قشنگ داد زدی تازه میخوام شروع کنم منم ببینین منم بازی منم منم بازی ، خسته شدم از تایپ لاشی برو تو اینستاگرام چندتا بچه سال جمع کن دور خودت براشون دوره بذار دیگه چکار میکنی اینورا 😂😂 من جای توسعه دهنده های این پروژه بودم خیلی بد رفتار میکردم، مگه ملت عنتر تو هستن ک بیای پرت و پلا بنویسی و اینا بخوان کلی وقت بذارن که ثابت کنن روی سوالت اشتباهه اصلا اقا راستی نکنه دنبال پول میگردی ؟؟ خدایی جدی هستم اگه پول میخوای بفرس واسم همینجا یه ولت بذار بزنم فقط شرت کم شه، حقیقتا شرم کردم اسمم نیماس ✋اولین بار بود تو گیت‌هاب دیدم کسی کولی بازی دربیاره

میدونی چی خنده داره؟؟ تو شروع تاکید کردین که حتما انگلیسی عنوان بشه مساله، انگلیسی ننوشته ک هیچ، فارسی نوشته خودشم بجای تیتر انشا نوشته😂✋ این اگه معنیش عقده داشتن نیست پس چیه؟ عقده دیده شدن، عقده مهم بودن، عقده ارزش داشتن، عقده حرفه‌ای بودن

**Comment by Morrigan-Ship** [comment]
> انگاری من بیام وایسم جلو روی تو بهت بگم تو **کون‌کشی** و بعد بگم اگه نیستی پس بفرما ثابت کن، خب این مسخره بازی نیست ب نظرت؟

حق پلاس پرو مکس

**Comment by omidshojaee** [comment]
حق با نیما هست
این برنامه علاوه بر مسائل بالا، رفتارهای مشکوک دیگه‌ای هم داره مثلا مقداری از حافظه دیسک رو مصرف می‌کنه و حتی دیده شده که از RAM و CPU هم استفاده می‌کنه.
من پیشنهاد می‌کنم نیما یه Hello World با فلاتر بنویسه البته اگه بتونه نصبش کنه و Process Monitor رو اجرا کنه بعدش بیاد هرچی دلش خواست گوه بخوره. تا اون موقع لطفا یکی به این الاغ بفهمونه تو نرم‌افزار PC چیزی به اسم دسترسی به اطلاعات سیستم وجود نداره. نرم‌افزار تحت نظارت سیستم‌عامل به منابع دسترسی داره و اون منابع هستن که اطلاعات رو در اختیار برنامه قرار میدن. کلا یه چیزی شنیدی فقط. ریدم تو مغز اونی که Process Monitor رو به تو معرفی کرد.

**Comment by NiREvil** [comment]
> حق با نیما هست این برنامه علاوه بر مسائل بالا، رفتارهای مشکوک دیگه‌ای هم داره مثلا مقداری از حافظه دیسک رو مصرف می‌کنه و حتی دیده شده که از RAM و CPU هم استفاده می‌کنه. من پیشنهاد می‌کنم نیما یه Hello World با فلاتر بنویسه البته اگه بتونه نصبش کنه و Process Monitor رو اجرا کنه بعدش بیاد هرچی دلش خواست گوه بخوره. تا اون موقع لطفا یکی به این الاغ بفهمونه تو نرم‌افزار PC چیزی به اسم دسترسی به اطلاعات سیستم وجود نداره. نرم‌افزار تحت نظارت سیستم‌عامل به منابع دسترسی داره و اون منابع هستن که اطلاعات رو در اختیار برنامه قرار میدن. کلا یه چیزی شنیدی فقط. ریدم تو مغز اونی که Process Monitor رو به تو معرفی کرد.

از درون منهدم شدم از خنده 🤣🤣🤣🤣🤣، حق بود حق

**Comment by Morrigan-Ship** [comment]
> حق با نیما هست این برنامه علاوه بر مسائل بالا، رفتارهای مشکوک دیگه‌ای هم داره مثلا مقداری از حافظه دیسک رو مصرف می‌کنه و حتی دیده شده که از RAM و CPU هم استفاده می‌کنه. من پیشنهاد می‌کنم نیما یه Hello World با فلاتر بنویسه البته اگه بتونه نصبش کنه و Process Monitor رو اجرا کنه بعدش بیاد هرچی دلش خواست گوه بخوره. تا اون موقع لطفا یکی به این الاغ بفهمونه تو نرم‌افزار PC چیزی به اسم دسترسی به اطلاعات سیستم وجود نداره. نرم‌افزار تحت نظارت سیستم‌عامل به منابع دسترسی داره و اون منابع هستن که اطلاعات رو در اختیار برنامه قرار میدن. کلا یه چیزی شنیدی فقط. ریدم تو مغز اونی که Process Monitor رو به تو معرفی کرد.

جهیدم خخخ
