### ISSUE TITLE
HttpUpgrade is available in SingBox 1.8.9

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#687]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Please check source code

It's totally available and I'm using it with official windows and android singbox core.

### Minimal Reproducible Example (MRE)

.

### Expected Behavior

.

### Version

1.0.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
It is already supported but not via rhe sublink

We will add it in feature version
