### ISSUE TITLE
new VPN Service in rpm systems not working

### ISSUE THREAD

**Issue by Juliosezar** [hiddify/hiddify-next#697]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

hi. i tested the new prereleased  vrsion (1.0.0) in fedora with .Appimage and .rpm in new VPN Service and it doesnt work.
the old Vpn mode work fine but not the new one.

### Minimal Reproducible Example (MRE)

![Screenshot from 2024-03-19 19-07-42](https://github.com/hiddify/hiddify-next/assets/101448864/c5ccba51-4ed5-43c8-b23d-ad18442e24f3)
![Screenshot from 2024-03-19 19-07-50](https://github.com/hiddify/hiddify-next/assets/101448864/2b623981-7f62-43d1-99aa-4f21415cac41)

### Version

v1.0.0

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
This issue is repetitive. I close it
