### ISSUE TITLE
WSL windows subsystem for linux

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#699]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

if connect vpn mode in windows
network will lost in WSL
for me systemd enabled in wsl

### Minimal Reproducible Example (MRE)

i puted warp config and connect success
but network lost in WSL

### Version

v1

### Platform/OS

Windows, Linux

### Additional Context

remember if you want check WSL we have two mode in WSL:
- systemd enabled
- systemd disabled
these are different

### Application Config Options

mux enabled
bypass lan enabled
ipv6 route enabled
dns prefer ipv4
vpn tun mode
strict mode enabled
resolve destination enabled
warp settings is off
fragment on

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
You can use cli version

**Comment by Morrigan-Ship** [comment]
> You can use cli version

no its not related to gui or cli version
> if connect vpn mode in windows network will lost in WSL
