### ISSUE TITLE
عدم ایمپورت

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#70]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

https://raw.githubusercontent.com/kavesenatori/sstls/main/xwwx

لینک ساب فوق متشکل از hysteria2 و shadowtls در اخرین نسخه گوگل پلی ایمپورت نمی شود

### Reproduce the Bug

..

### Version

0.9

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
ایشو برای بررسی منتقل شد. ایشو فعلا بسته میشه

**Comment by hiddify-com** [comment]
SN links are not supported
