### ISSUE TITLE
It is recommended to add the global shortcut key switch agent function.

### ISSUE THREAD

**Issue by linkiofo** [hiddify/hiddify-next#706]
### Feature description

It is recommended to add the global shortcut key switch agent function.

**Comment by hiddify-com** [comment]
In complete description

**Comment by linkiofo** [comment]
@hiddify-com 
Function Description: This feature allows you to switch the proxy settings of your application on and off through a predefined global shortcut key combination. It provides me with a direct method to quickly enable or disable the proxy, regardless of when and where, and whether you are using the application. Application Scenarios: When I encounter network connection issues while using my computer and need to quickly enable or disable the proxy. When I am engaged in activities that require or do not require proxy, such as online gaming, chatting, and video watching. Expected Goal: Speed up your operations within application. This feature saves me time from having to click multiple times to enable or disable proxy settings. No matter which application interface on my computer, I can switch the status of the proxy in one step.
