### ISSUE TITLE
[FR] Add PPTP protocol

### ISSUE THREAD

**Issue by Mohammad-Parsa-Elahimanesh** [hiddify/hiddify-next#709]
### Feature description

سلام می‌ خواستم اگر ممکنه پروتوکول pptp هم اضافه کنید به برنامه. من برنامه خوبی خیلی براش پیدا نکردم و از اونجا که در یکسری موبایل های جدید منسوخ شده کار باهاش رو سخت می‌کنه. متشکرم

**Comment by hiddify-com** [comment]
not planned yet but pr welcomed
