### ISSUE TITLE
ارور داخل نسخه دسکتاپ و روشن ماندن پروکسی سیستم

### ISSUE THREAD

**Issue by amin2plus** [hiddify/hiddify-next#71]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

روی ویندور 10
ورژن برنامه 0.9.0
زمانی که برای مدتی با حالت پروکسی روشن میمونه برنامه ، ارور عکس زیر داخل برنامه ظاهر میشه و نت سیستم قطع میشه، 
خود برنامه رو هم باید حتما close کرد و مجدد باز کرد تا بشه به کار باهاش ادامه داد
و پروکسی داخل ستینگز ویندور هم روشن باقی میمونه و باید دستی خاموش بشه تا سری بعد که دکمه کانکت برنامه زده میشه کار کنه!!

![image](https://github.com/hiddify/hiddify-next/assets/31206022/6f4ad271-e821-401c-ba60-c7b7aa0582b7)

### Reproduce the Bug

1. روشن کردن کانکشن روی حالت پروکسی
2. منتظر ماندن (حدود زیر یک ساعت)

### Expected Behavior

مثل ورژن های قبلی مثل 0.8.0 برنامه وصل بمونه تا زمانی که دکمه قطع زده بشه

### Version

0.9.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
ایشو برای بررسی منتقل شد. ایشو فعلا بسته میشه

**Comment by amin2plus** [comment]
پوشه زیر

 C:\Users\myname\AppData\Roaming\Hiddify

رو پاک کردم، 
خود برنامه رو هم اول پاک کردم و مجدد 0.9.0 رو نصب کردم، فعلا این مشکل پیش نیامده

لطفا کاری کنید که برنامه پاک میشه همه دیتاش هم پاک بشه؛ من حتی از play store پاک میکنم و مجدد نصب میکنم، وقتی برنامه که تازه نصب شده رو باز میکنم میبینم همه تنظیمات و کانفیگ ها سر جاشونن همچنان
