### ISSUE TITLE
unsupported desktop environment

### ISSUE THREAD

**Issue by repliqa** [hiddify/hiddify-next#710]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

OS: Debian, running dwm window manager (no desktop environment)
I set up a working VLESS VPN config (tested on android phone) on my Debian desktop, but when I try to connect, I run into the following error:

"Unexpected Error: initialize inbound/mixed[mixed-in]: initialize system proxy: unsupported desktop environment"

### Minimal Reproducible Example (MRE)

Debian 12, running dwm, not running networkmanager

### Expected Behavior

The VPN connection working without errors

### Version

v1.0.0

### Platform/OS

Linux

### Additional Context

![image](https://github.com/hiddify/hiddify-next/assets/96332629/41557194-1b82-4cf2-98a6-94389be29435)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Please use proxy service only
