### ISSUE TITLE
import config problem while connected

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#711]
وقتی warp به صورت مجزا روشن هست و هیدیفای خاموش هست و اینترنت کار میکنه

نمیشه کانفیگ وارپ رو ایمپورت کرد

warp://.....

###version
v1.1.1

### Platform/OS
Windows

**Comment by lymanjre** [comment]
با حالت خاموش که ادد میشه مشکلی نداره

**Comment by Morrigan-Ship** [comment]
> با حالت خاموش که ادد میشه مشکلی نداره

منظورم warp cloudflare رسمی بود وقتی که وصل هست و warp://auto رو ایمپورت میکنم توی هیدیفای ارور میگیرم

بخاطر این هست که هیدیفای به یک لینک درخاست میده برای ساخت کانفیگ و اون لینک ارور 403 میده

**Comment by Morrigan-Ship** [comment]
i cannot reopen it please
