### ISSUE TITLE
[FR] kill switch support

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#712]
### Feature description

add kill switch support for Hiddify

for our security
for freedom..!

**Comment by lymanjre** [comment]
This issue is registered before. I close it cuz it s repetitive

**Comment by daaniyaan** [comment]
Any update on this?

**Comment by Figarround** [comment]
Indeed, a kill switch is very necessary, especially in dictatorships with internet censorship.
