### ISSUE TITLE
[FR] support deny rout IP range or *.subdomain.domain.* range

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#716]
### Feature description

support deny rout IP range like: 192.168.1/24
or \*.subdomain.domain.* range via **Regex**

**Comment by lymanjre** [comment]
For what reason? Pls explain more. I close this issue you can reopen it whenever you what to add eplanations

**Comment by Morrigan-Ship** [comment]
for example i dont want rout some Custom IPs or Domains range
for privacy reason
