### ISSUE TITLE
[FR] support deny .exe | .dll files rout

### ISSUE THREAD

**Issue by Morrigan-Ship** [hiddify/hiddify-next#717]
### Feature description

support deny .exe | .ddl file rout and connect to original Internet

**Comment by lymanjre** [comment]
What do you mean by this issue. Pls explain more. I close this issue. You can open it when you what to explain

**Comment by Morrigan-Ship** [comment]
it is vpn split mode.
for example in express vpn or many vpns like v2rayng in android you can exclude some apps from connecting to vpn

in windows some vpns like express vpn allow you exclude *.exe or *.dll files to connecting to vpn

express vpn:
![image](https://github.com/hiddify/hiddify-next/assets/138357319/8d236040-e5ce-4637-a3fe-8ddb9533a6b3)


"add another app" button will open a windows that you can select .exe or .dll files
also you can select multi files via CTRL or SHIFT keyboard keys
