### ISSUE TITLE
Proxy-providers & rule-providers cant be imported

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#72]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هنوز لینک ساب های کلش (و متا) که دارای
Proxy-providers 
Rule-providers 
هستن در نرم افزار پس از ایمپورت، بخش proxies آنها خالیست!

### Reproduce the Bug

.

### Version

0.9

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
هیدیفای نکست بر پایه سینگ‌باکس هست که از این قابلیت‌ها پشتیبانی نمیکنه
