### ISSUE TITLE
hysteria配置无法正常链接

### ISSUE THREAD

**Issue by LeeLoveShaAnAn** [hiddify/hiddify-next#722]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

在vps上配置好hysteria1后, 将订阅链接导入hiddify后, 始终是超时状态. 相同的订阅配置在手机端使用正常.

### Minimal Reproducible Example (MRE)

1. 导入hysteria1的配置订阅地址
2. 开启服务.
3. 显示超时.

### Version

1.0.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by LeeLoveShaAnAn** [comment]
hysteria2的服务能正常使用.

**Comment by zhangboxing11** [comment]
I'm having the same problem, the node is mojie website
