### ISSUE TITLE
System proxy left enabled when user reboot PC

### ISSUE THREAD

**Issue by Rennats** [hiddify/hiddify-next#728]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Many times i reboot my PC when Hiddify is connected (in system proxy mode) and after reboot i can't have internet access, because system proxy left enabled when PC reboot, but Hiddify don't reconnect automatically.

### Minimal Reproducible Example (MRE)

1. Start Hiddify
2. Use "system proxy" mode
3. Connect to any server with config, apps will use internet via system proxy
4. Reboot PC without exit from Hiddify
5. When system boot up - all apps try use enabled system proxy, but it not work (because Hidify start, but not connected)

### Expected Behavior

Hiddify must turn off system proxy settings before have been closed on reboot.
Also good idea will be add "Auto-reconnect on start" option (when system boot up and automatically start Hiddify, app will be automatically connect last config) and link system proxy state with this option: turn on proxy and connect, if this option enabled  and turn off system proxy, if this option disabled.

### Version

v1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
not a bug of hiddify

**Comment by Rennats** [comment]
Ok, let's modify it to feature request?
Can you add "Auto-reconnect on start" option?

**Comment by art13eck** [comment]
it's a really big problem with not being able to access the internet after rebooting the pc
