### ISSUE TITLE
[FR] Geo Database IR & ...

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#73]
### Feature description

درود
این ریپو ایرانی، کاملترین و به روزترین گرداوردنده geoip و geosite ایران هستش که cn رو هم به خوبی پوشش داده و در تنظیمات نکوباکس هم اخیرا قرار داده شده 

https://github.com/Chocolate4U/Iran-sing-box-rules

لطفا از این منبع برای بای پس آیپی و سایت های داخلی و ریجن های مختلف استفاده کنید

هر روز ریپو نامبرده به‌روزرسانی می شود

حتی الامکان not planned نزنید و اعمال کنید

**Comment by hiddify-com** [comment]
نگران نباشید حتما اعمال میشه

اگه میزنیم not planned in two weeks هست

**Comment by Graveyard9988** [comment]
سپاس بی کران

**Comment by Graveyard9988** [comment]
فراموش نشود

**Comment by problematicconsumer** [comment]
Added in [v0.11.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.11.0)
