### ISSUE TITLE
All connections have timed out

### ISSUE THREAD

**Issue by 120L021026** [hiddify/hiddify-next#735]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When using version 0.14.20, everything is connected normally. However, after updating to version 1.0.0, all connections timed out and still timed out after reinstallation. After returning to version 0.14.20, the connection returned to normal. I cannot determine which aspect of the problem it is.

### Minimal Reproducible Example (MRE)

The steps are as described in the problem description. 

### Version

1.0.0

### Platform/OS

Android, Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by fatkun** [comment]
Same problem. I open a website and it return error "ERR_NAME_NOT_RESOLVED"

**Comment by hydroakri** [comment]
I edit "udp://1.1.1.1" to "tls://1.1.1.1"
then it works

**Comment by 120L021026** [comment]
> Same problem. I open a website and it return error "ERR_NAME_NOT_RESOLVED".
> 
> I found a workaround, everything is OK.
> 
>     1. Change remote DNS to tcp://8.8.8.8
> 
>     2. Change Direct DNS to 8.8.8.8

Thank you for your help. I have successfully connected through the method you provided. But what is the principle behind this?
