### ISSUE TITLE
China website

### ISSUE THREAD

**Issue by Sostay** [hiddify/hiddify-next#736]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Why do Chinese websites always fail to open normally? Regardless of whether the Bypass Lan option is turned on or not, the result is the same...

All websites outside China can be accessed normally

![image](https://github.com/hiddify/hiddify-next/assets/6897274/0471dca4-3108-46d1-a1a4-d4de63b8c5f9)
![image](https://github.com/hiddify/hiddify-next/assets/6897274/50e6ff85-29bd-4d05-b907-bee26fb7fe30)

### Minimal Reproducible Example (MRE)

Open any website in China

![image](https://github.com/hiddify/hiddify-next/assets/6897274/127d4b71-6193-4e24-ae0a-8cbc60165624)

### Version

1.0.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by yinleiCoder** [comment]
i think this is bug when i upgrade v1.0.0

**Comment by donnanszex7654** [comment]
This issue is caused by the local DNS setting. The default setting is 1.1.1.1. When I switch it to local, all Chinese websites can be opened normally.[](https://sing-box.sagernet.org/configuration/dns/server/#tag)

**Comment by Sostay** [comment]
> This issue is caused by the local DNS setting. The default setting is 1.1.1.1. When I switch it to local, all Chinese websites can be opened normally.

It's useful. that's cool!
