### ISSUE TITLE
google play store problem

### ISSUE THREAD

**Issue by 123Diego** [hiddify/hiddify-next#738]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The google play store cannot update the APP, and the APP cannot be downloaded either.

### Minimal Reproducible Example (MRE)

every timeplease fix

### Version

1.0.0

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
fixed
