### ISSUE TITLE
fail to remove windows proxy

### ISSUE THREAD

**Issue by netsupcloud** [hiddify/hiddify-next#740]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

fail to remove windows proxy when we use set system proxy in version 1.1.1 on windows 10 latest update

### Minimal Reproducible Example (MRE)

use set system proxy on windows

### Version

1.1.1.

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
You can turn off the app and the proxy settings will disappear
