### ISSUE TITLE
[FR] درخواست از برنامه نویس

### ISSUE THREAD

**Issue by rezaziyai** [hiddify/hiddify-next#742]
### Feature description

سلام لطفا یکی از برنامه نویس های آپ بم پیام بدن یه ادیت خیلی کوچیک از آپ میخوام تو یه ورژن اختصاصی واسم بدن هزینه شو پرداخت میکنم 
🌱
تلگرام @propmrvip

**Comment by lymanjre** [comment]
امکان این کار وجود ندارد
