### ISSUE TITLE
[FR] Support iran.dat like v2rayNG

### ISSUE THREAD

**Issue by persianpros** [hiddify/hiddify-next#744]
Please take a look at https://github.com/bootmortis/iran-hosted-domains?tab=readme-ov-file#v2rayng and support it if it's possible.

You could also use "iran-geosite.db" like https://github.com/bootmortis/iran-hosted-domains?tab=readme-ov-file#sing-box

**Comment by hiddify-com** [comment]
geosite uses too much memory and we can not include it.

please provide srs files so we can include it
