### ISSUE TITLE
QR code scan

### ISSUE THREAD

**Issue by master88wi** [hiddify/hiddify-next#75]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

https://shadowmere.akiel.dev/ QR code profile scan not working

### Reproduce the Bug

https://shadowmere.akiel.dev/ QR code profile scan not working

### Version

all

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by hillout** [comment]
Confirm, QR scanning on Android not working.

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I wll close it here.

**Comment by lymanjre** [comment]
This issue is foxed
