### ISSUE TITLE
Can't launch the program

### ISSUE THREAD

**Issue by ffsmyusernameistaken** [hiddify/hiddify-next#750]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I open Hiddify, I get this error: "The program cannot be launched because api-ms-win-core-rtlsupport-ll-2-0.dll is missing on the computer. Try reinstalling the program.". I installed the latest Visual C++ Redistributable but that didn't solve the problem. Windows 7.

### Minimal Reproducible Example (MRE)

Launch the program

### Version

v1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
The app does not support win7 because it needs some dependencies. You can install the dependencies and try again but It s highly unlikely to be solved.
