### ISSUE TITLE
Implement in own code

### ISSUE THREAD

**Issue by developeranshul1986** [hiddify/hiddify-next#756]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I want to run the code with custom bundleid or own bundleid instead of the default. Can this be possible to implement with my own bundleid in iOS and own package in Android? Please replay ASAP.

### Minimal Reproducible Example (MRE)

I want to run the code with custom bundleid or own bundleid instead of the default. Can this be possible to implement with my own bundleid in iOS and own package in Android? Please replay ASAP.

### Expected Behavior

I want to run the code with custom bundleid or own bundleid instead of the default. Can this be possible to implement with my own bundleid in iOS and own package in Android? Please replay ASAP.

### Version

v1.8.7

### Platform/OS

Android, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Not possible
