### ISSUE TITLE
Crash in VPN mode after disconnecting from the server

### ISSUE THREAD

**Issue by SadraKafiri** [hiddify/hiddify-next#757]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Sometimes in VPN Mode, the application crashes after disconnecting from the server and immediately force close.

### Minimal Reproducible Example (MRE)

1. Open Hiddify
2. Choose VPN Mode
3. Connect and Disconnect multitimes or change from VPN to System-Proxy

### Version

1.1.0 , 1.0.0

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by LitenBuzzTh** [comment]
exactly, I'm facing this issue too. seems like its not only me🫠

**Comment by lymanjre** [comment]
Try using latest version

**Comment by LitenBuzzTh** [comment]
> Try using latest version

already using the latest version, as I mentioned earlier
