### ISSUE TITLE
[FR] Auto connect at start up

### ISSUE THREAD

**Issue by RealSlakey** [hiddify/hiddify-next#76]
### Feature description

[FR] Auto connect at start up
OS: Windows

**Comment by lymanjre** [comment]
This issue is fixed

**Comment by ash-ketsup** [comment]
Maybe I'm doing something wrong but as of ver. 2.0.5 I still have to click "Tap To Connect" after login.
OS: linux

Also: there is no point in having "Start Minimized" option if it won't auto connect.
