### ISSUE TITLE
اجرا نشدن در ویندوز 7

### ISSUE THREAD

**Issue by Mahdi0ghaznavi** [hiddify/hiddify-next#764]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

درودر بر شما 
درسته گفتید بهتره ویندوز 10 داشته باشیم ولی مایی که نمیتونیم 10 نصب کنیم هیچ راهی وجود نداره بتونیم استفاده کنیم؟
ویندوز 7 و 8 که خب اجرا نمیشه ماها چیکار باید بکنیم ارور api-ms-win--core-rtlsupport-l1-2-0.dll میگیریم  تمام نسخه های
Microsoft Visual C++ 
رو هم نصب کردم بازم همین ارورو دارم
جایگزینی چیزی وجود نداره که وارپ هم روش بیاد؟
...  

### Minimal Reproducible Example (MRE)

api-ms-win--core-rtlsupport-l1-2-0.dll

### Version

all versions

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Amir2367** [comment]
> ### Search first
> * [x]  I searched and no similar issues were found
> 
> ### What Happened?
> درودر بر شما درسته گفتید بهتره ویندوز 10 داشته باشیم ولی مایی که نمیتونیم 10 نصب کنیم هیچ راهی وجود نداره بتونیم استفاده کنیم؟ ویندوز 7 و 8 که خب اجرا نمیشه ماها چیکار باید بکنیم ارور api-ms-win--core-rtlsupport-l1-2-0.dll میگیریم تمام نسخه های Microsoft Visual C++ رو هم نصب کردم بازم همین ارورو دارم جایگزینی چیزی وجود نداره که وارپ هم روش بیاد؟ ...
> 
> ### Minimal Reproducible Example (MRE)
> api-ms-win--core-rtlsupport-l1-2-0.dll
> 
> ### Expected Behavior
> _No response_
> 
> ### Version
> all versions
> 
> ### Platform/OS
> Windows
> 
> ### Additional Context
> _No response_
> 
> ### Application Config Options
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> * [ ]  I'm willing to submit a PR (Thank you!)

لطفا این مورد را در نظر داشته باشین خیلی ها حتی رو ویندوز 10  هم نمیتونند برنامه رو اجرا کنند حداقل ویندوز 7 رو بتونیم اجرا کنیم

**Comment by UbiVPN** [comment]
بسته نصب باید شامل فایل‌های کتابخانه مورد نیاز باشد، احتمال دارد توسط نرم‌افزار ضدویروس حذف شده باشد.

**Comment by Amir2367** [comment]
> بسته نصب باید شامل فایل‌های کتابخانه مورد نیاز باشد، احتمال دارد توسط نرم‌افزار ضدویروس حذف شده باشد.

با غیر فعالسازی حتی حذف ویندوز دیفندر،بازهم مشکل هست
