### ISSUE TITLE
کرش کردن نرم افزار آندرویید در هنگام تعویض شبکه

### ISSUE THREAD

**Issue by ghassemi-ehsan** [hiddify/hiddify-next#765]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در صورتی که‌هم وایفای و هم نت سیم کارت روشن باشد و بر روی شبکه وایفای باشیم ،وقتی که نرم افزار به پروکسی متصل است و وایفای رو خاموش میکنیم که اینترنت بروی حالت اینترنت سیم کارت برود نرم افزار هنگ میکند و کرش میکند

### Minimal Reproducible Example (MRE)

1.wifi is on, mobile data is on
2.connected to proxy with wifi
3.turn off wifi
4.the application hangs.

### Version

v1.1.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by shylb1996** [comment]
6

**Comment by lymanjre** [comment]
ایشو تکراری است و قبلا ثبت شده است
