### ISSUE TITLE
باگ در حالت فعالسازی پروکسی از طریق تایل ناتیفیکیشن

### ISSUE THREAD

**Issue by ghassemi-ehsan** [hiddify/hiddify-next#766]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

هنگامی که به وی پی ان دیگه ای وصل باشم و از طریق تایل ناتیفیکیشن پروکسی هیدیفای رو روشن میکنیم وصل میشود ولی خطای تایم اوت میزند و باید یک بار خاموش و روشن کنم تا پینگ بدهد.
۲.بیشتر اوقات هنگامی که پروکسی فعال است با درگ کردن و نمایش کوییک ستینگ و بخش ناتیفیکیشن پروکسی دیسکانکت میشود(یا شاید نرم افزار کرش میکند)
۳.گاهی اوقات به جای روشن یا خاموش بودن تایل نرم افزار به صورت محو نمایش داده میشود(unavailable )

### Minimal Reproducible Example (MRE)

1.
turn on hiddify by clicking on hiddify quick setting tile
the vpn icon appears but there is no connectivity
open hiddify and you will see timeout error
disconnect and  connect again and then ping will be ok
2.
the hiddify is connected and everything is ok
open quick setting and you will see the hiddify tile in quick setting will be disconnected suddenly

### Version

v1.1.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by UbiVPN** [comment]
بهتر است اسکرین‌شات یا ضبط صفحه‌نمایش ارائه دهید، اینطوری ملموس‌تر است.

**Comment by ghassemi-ehsan** [comment]
برای نمایش باگ اسکرین شات چیزی رو نشون نمیدهد.و چون گهگاه اتفاق می افتد قابل دوباره انجام دادن نیست.
این اتفاق برای اپ مهسا هم افتاد که به احتمال زیاد مربوط به سیستم عامل کاستومی که نصب کردم باشه و نه اپ شما.

**Comment by lymanjre** [comment]
این ایشو تکراری است و قبلا ثبت شده است
