### ISSUE TITLE
Hiddify Android Google Play download app keeps spinning

### ISSUE THREAD

**Issue by Joackk** [hiddify/hiddify-next#769]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

If I use the same node in other proxy software, it will download normally, but if hiddify uses the same node, it will remain stuck in a waiting state for download

### Minimal Reproducible Example (MRE)

Activate the proxy to enter the Google Paly store and update the application, but it will remain stuck in a circle

### Version

1.1.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by shaker6cat** [comment]
I even cannot login my google account on my windows computer, let alone using Google Gemini, when I use the latest version of Hiddify. However, it works as long as I change a vpn client such as Clash Verge with the same nodes. So maybe you can try other client temporarily waiting for developers fixing this bug (i.e. the malfunction about google). It sounds a little bit weird though.

**Comment by windy1lee** [comment]
i have the same problem

**Comment by AiharaMahiru** [comment]
Is there a plan to release the version please? Currently the Google Play Store is a headache to not be able to download.

**Comment by DearZack** [comment]
i have the same problem in v1.5.2

**Comment by Kafurtan** [comment]
i have the same problem in v1.5.2
