### ISSUE TITLE
Some domain names become inaccessible when using hiddify

### ISSUE THREAD

**Issue by Joackk** [hiddify/hiddify-next#771]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I searched for the answer to another question through a search engine and found an article, so I tried to access it, but it prompted me that I couldn't access this website. But I had visited him before, so I closed the proxy and accessed it normally. I also used ping and found that it is normal
![image](https://github.com/hiddify/hiddify-next/assets/45162558/0ed719f2-ae01-4845-8fa7-d2ad7b59e560)
At the same time, I tested using other proxy tools and using the same node, they can all access it normally
At the same time, the log seems to indicate that he has parsed it normally, but I am unable to access it. What is causing this?
![image](https://github.com/hiddify/hiddify-next/assets/45162558/63d0524e-1285-45d7-b31d-f8ca4858c335)

### Minimal Reproducible Example (MRE)

Hiddify, my beloved wife
Connection proxy
Visit www.jianshu.com
Received prompt unable to access

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Use VPN mode or Use different DNS protocol
