### ISSUE TITLE
IDM downloads become slow after enabling the proxy

### ISSUE THREAD

**Issue by Joackk** [hiddify/hiddify-next#772]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I was using the system proxy, I downloaded GitHub files using IDM. Its download speed was very slow, only 20kb/s. When I closed the proxy and changed the proxy tool to download again, the speed became 20M/s. There have been no changes to the configuration of IDM, but the speed seems to differ significantly and the nodes used are also the same

### Minimal Reproducible Example (MRE)

Enable proxy
Download using IDM
Replace proxy tools and conduct comparative testing

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
use VPN mode
