### ISSUE TITLE
[FR] It is recommended to place the working directory in the Hiddify-next folder, or allow users to customize it

### ISSUE THREAD

**Issue by cjchome** [hiddify/hiddify-next#774]
### Feature description

It is recommended to place the working directory in the Hiddify-next folder, or allow users to customize it. This way, if I reinstall the system or port to other computers, I can avoid having to setup the all subscriptions again.

**Comment by fszok** [comment]
I look forward to this feature just like you. The so-called portable version cannot be truly portable. I look forward to the author's changes.

**Comment by acstor** [comment]
Me too....

**Comment by lymanjre** [comment]
An issue is registered like yours so I close it now

**Comment by eXense-auth** [comment]
Here's a portable version.
https://github.com/xmha97/PortableApps/releases?q=Hiddify
You can put any version you want into the container
