### ISSUE TITLE
ویندوز 11 و سی پی یو پینتیوم تا نسخه 11.1 درست کار میکنه 

### ISSUE THREAD

**Issue by m0riii** [hiddify/hiddify-next#776]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

ویندوز 11 و سی پی یو پینتیوم تا نسخه 11.1 درست کار میکنه ولی از اون نسخه به بعد هرچی نصب میکنم تا 1.1.1. کرش میکنه و یه صفحه سفید باز میشه و بسته میشه و غیب میشه (حتی اون پایین آیکون ش کنار ساعت هم نمی مونه!!! 
نسخه 0.11.1 بدون مشکل و کرش کار میکنه الان ولی بعدی ها مشکل دارن 
اخرین نسخه ویندوز 11 هم هست 

### Minimal Reproducible Example (MRE)

ویندوز 11 و سی پی یو پینتیوم تا نسخه 11.1 درست کار میکنه 

### Expected Behavior

ویندوز 11 و سی پی یو پینتیوم تا نسخه 11.1 درست کار میکنه 

### Version

1.1.1

### Platform/OS

Windows

### Additional Context

ویندوز 11 و سی پی یو پینتیوم تا نسخه 11.1 درست کار میکنه 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by UbiVPN** [comment]
بازسازی آن دشوار است

**Comment by lymanjre** [comment]
فایل‌های درون پوشه working directory را پاک کنید و مجدد امتحان کنید
