### ISSUE TITLE
Unexpected Error - while stopping the service and the Windows proxy mode was left 'on'

### ISSUE THREAD

**Issue by MikeVRT** [hiddify/hiddify-next#779]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Try to disconnect after using Hiddify for Windows for a while in System Proxy mode. Connection to Xray Reality - if it's important.
We will encounter an error:
![hn_stop_error](https://github.com/hiddify/hiddify-next/assets/24420926/0b5c68b7-b47c-4275-a504-b1a3f1b9f894)

Furthermore, the internet will be "broken" through the entire system because Hiddify will leave(\*) this option enabled after crashing:
![hn_stop_error_proxy](https://github.com/hiddify/hiddify-next/assets/24420926/652cd60d-c791-4256-b4ce-021dfcd29451)
(\*) The same situation will occur after shutting down Windows with Hiddify connected without manual disconnection.

### Minimal Reproducible Example (MRE)

1. Run Hiddify or setup auto-start with Windows (in my case, W10).
2. Establish a connection (by default, in system proxy mode).
3. Use it for a while (**important!** - no issues if you switch it multiple times, just after the 1st connection).
4. Try to stop the connection (from the taskbar's icon or the in-app circle - it doesn't matter).
5. You will receive an in-app error (see screenshort 1), and the application will leave window's proxy mode 'on' (see screenshort 2).

If you follow (3), it won't be a floating bug; it repeats in 100% of cases of normal app usage. Just don't try to switch the connection on/off immediately after the app starts - it's an abnormal usage scenario (but yes, it does work without any issues).

### Expected Behavior

Ensure correct switching between 'on' and 'off' states in all possible cases regarding the connection.

### Version

v1.0.0, v1.1.1

### Platform/OS

Windows 10

**Comment by lymanjre** [comment]
Use latest version. It s fixed. If not, pls send log files

**Comment by MikeVRT** [comment]
Version 1.4.0 - bug still here.
Moreover, if Hiddify had been switched on (proxy mode) and then Windows is shut down, after the next PC restart, we will have no Internet (proxy left on, Hiddify doesn't work). So, the app doesn't "close the door" after itself.

**Comment by mipselqq** [comment]
fix pls

**Comment by segasilich** [comment]
Version 2.0.5 - bug still here.
