### ISSUE TITLE
version `GLIBC_2.3x' not found

### ISSUE THREAD

**Issue by hsh9544** [hiddify/hiddify-next#78]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Tried to run the AppImage file on Zorin OS 16.3 and got these errors:
```
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hiddify)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_hiddif2hPgKb/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_hiddif2hPgKb/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by usr/lib/libgcc_s.so.1)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libgcc_s.so.1)
```

The output of `ldd --version`:
`ldd (Ubuntu GLIBC 2.31-0ubuntu9.12) 2.31`

What to do now?

### Reproduce the Bug

Just run the AppImage on a linux system

### Version

0.9.2

### Platform/OS

Linux

**Comment by AlirezaIvaz** [comment]
I've same issue in Zorin OS 16.3 based on Ubuntu 20.04 LTS. It seems developers generated app image using a newer version of ubuntu or anything else, I'll try to build it manually in my system and if works, this maybe a solution.

**Comment by lymanjre** [comment]
This issue is fixed

**Comment by hsh9544** [comment]
This issue is not fixed.
```
~> hiddify
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by hiddify)
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)
```

**Comment by hsh9544** [comment]
The issue is fixed in today's release (0.15.6). I tested both the `AppImage` and the `deb` package and they're ok. Thanks for your consideration.

**Comment by hsh9544** [comment]
Only OK on 0.15.6. Newer versions depend on GLIBC_2.32+ again.

**Comment by papampi** [comment]
Can confirm this issue is still exists on newer versions

**Comment by Ualker** [comment]
The latest version still has the same problem

**Comment by amirsh98** [comment]
The latest version still has the same problem

**Comment by MasoudHD** [comment]
This exists even in newer versions. I tested on Ubuntu 24 and it works fine but in debian 11 it is not

**Comment by yunixon** [comment]
Same issue on ubuntu 20

**Comment by amirafa** [comment]
> Only OK on 0.15.6. Newer versions depend on GLIBC_2.32+ again.

it works only on AppImage version

**Comment by Sapport26** [comment]
I can note that for Alt Linux, rpm-package and AppImage have this problem:
libc.so.6(GLIBC_2.33)(64bit) is needed for hiddify-2.0.5+20005-20005.x86_64
libc.so.6(GLIBC_2.34)(64bit) is needed for hiddify-2.0.5+20005-20005.x86_64

it still persists.
