### ISSUE TITLE
Hello, could you please enable hiddify to run on Ubuntu 18.04

### ISSUE THREAD

**Issue by lixiaodongsql** [hiddify/hiddify-next#782]
### Feature description

Hello, could you please enable hiddify to run on Ubuntu 18.04? Thank you very much for your help. I still use Ubuntu 18.04

**Comment by lymanjre** [comment]
Use DEB package pls

**Comment by agennu** [comment]
Hello. I can't run Hiddify (I've tried all the Debian versions). In the terminal, I get this: 
genn@genn-UX31A:~$ hiddify %U
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by hiddify)
hiddify: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)
hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)
genn@genn-UX31A:~$
