### ISSUE TITLE
IDM can't download youtub, with V2RAY it's fine!

### ISSUE THREAD

**Issue by hjlxy303** [hiddify/hiddify-next#787]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

IDM can't download youtub, with V2RAY it's fine!

### Minimal Reproducible Example (MRE)

1

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Joackk** [comment]
I have the same problem. When I use hiddify as a proxy, the download speed of IDM is very slow, but when I use other proxies or directly use the browser, I download very quickly.

**Comment by lymanjre** [comment]
Use VPN mode
