### ISSUE TITLE
مشکل اتصال به کانفیگ

### ISSUE THREAD

**Issue by nightday1243** [hiddify/hiddify-next#789]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام وقت بخیر خسته نباشید
2 تا مشکل جزئی وجود داره که ممنون میشم یه چکش بکنید
مورد اول در نسخه پیسی بنده ویندوز 11 دارم زمانی که روی کانکت کیلیک میکنم اگه به اشتباه مجدد کیلیک قبل از وصل شدن کانفیگ نرم افزار کرش می کنه.
مورد دوم که هم داخل پیسی اتفاق می افته هم پیسی یه سری مواقع داخل v2ray به کانفیگ وصل میشم اما روی این نرم افزار تایم اوت میده
با تشکر

### Minimal Reproducible Example (MRE)

1. در نسخه پیسی بنده ویندوز 11 دارم زمانی که روی کانکت کیلیک میکنم اگه به اشتباه مجدد کیلیک قبل از وصل شدن کانفیگ نرم افزار کرش می کنه.
2. هم داخل پیسی اتفاق می افته هم پیسی یه سری مواقع داخل v2ray به کانفیگ وصل میشم اما روی این نرم افزار تایم اوت میده

### Version

v1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by UbiVPN** [comment]
اگر امکان ارائه عکس یا فیلم از صفحه وجود داشته باشد، می‌تواند به تعیین مشکل کمک بیشتری کند. با توجه به توضیحات شما، حس می‌کنم که سردرگم شده‌ام.

**Comment by lymanjre** [comment]
The explanations are too short. We need more comments to troubleshoot the issue. We need also the logs. I close the issue and if you wanna add more texts you can open it
