### ISSUE TITLE
Inconsistent App Icon Sizing on macOS

### ISSUE THREAD

**Issue by mahmoud-eslami** [hiddify/hiddify-next#79]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I have noticed that the application icon on macOS appears larger compared to other Apps. It's not a big deal, but it would make me and others like me ( As a daily user ) really happy if the icon size could be fixed.

### Reproduce the Bug

1. Install App
2. Check the icon size in the Dock

### Version

v0.9.2

### Platform/OS

macOS

### Additional Context

<img width="1209" alt="image" src="https://github.com/hiddify/hiddify-next/assets/57481226/1c0af3b8-bfcc-443b-97b4-6316a8f70be6">

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by problematicconsumer** [comment]
This issue is resolved as of [v0.12.0](https://github.com/hiddify/hiddify-next/releases/tag/v0.12.0)
