### ISSUE TITLE
Some websites are inaccessible

### ISSUE THREAD

**Issue by kvm66** [hiddify/hiddify-next#790]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Some websites cannot be opened, such as https://www.jb51.net/. I have tried various settings, but still cannot solve the problem.

### Minimal Reproducible Example (MRE)

Some websites cannot be opened, such as https://www.jb51.net/. I have tried various settings, but still cannot solve the problem.

### Version

1.1.1

### Platform/OS

Windows, macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ss548** [comment]
他这个是全局代理 导致好多国内网站访问不了

**Comment by lymanjre** [comment]
Pls provide us with logs. If not we cant debug the issue. I close the issue and if you wanna add more info you can reopen it.
