### ISSUE TITLE
 V1.1.1 version can't run on Kubuntu 20.04LTS.

### ISSUE THREAD

**Issue by SamulePope** [hiddify/hiddify-next#791]
### Feature description

Run "Hiddify-Linux-x64.AppImage" in terminal displays:
` ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by ./hiddify)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by /tmp/.mount_HiddifGSkB7n/lib/libsqlite3_flutter_libs_plugin.so) 
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by /tmp/.mount_HiddifGSkB7n/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.35' not found (required by usr/lib/libgcc_s.so.1)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by usr/lib/libgcc_s.so.1)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by usr/lib/libresolv.so.2)`

The system is Kubuntu 20.04LTS. It seems that the highest version of GLIBC is 2.30 in ubuntu20.04, and it take risks to updates GLIBC to 2.30+. So could you take some measure to make it compatible with 20LTS. Thanks!

**Comment by lymanjre** [comment]
You need to install some prerequisites

**Comment by SamulePope** [comment]
I‘ve read some blog posts about install these libs by change sources because the highest version of GLIBC is 2.30 in ubuntu20.04.  Many peolpe in the comments said this lead to system collapses. Force installing these lib may not be a good solution.
