### ISSUE TITLE
V2rayng and hiddify next

### ISSUE THREAD

**Issue by BachBahmani** [hiddify/hiddify-next#792]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello
Most protocols of my server are available for V2RAYNG but when that profile imported to Hiddify Next just one protocol is available.
Both V2RAYNG and Hiddify Next are in default settings.

Why?

### Minimal Reproducible Example (MRE)

Same

### Expected Behavior

Same access to server protocols 

### Version

1.1.1

### Platform/OS

Android

### Additional Context

None 

### Application Config Options

```shell
{
  "execute-config-as-is": false,
  "log-level": "warn",
  "resolve-destination": false,
  "ipv6-mode": "ipv4_only",
  "remote-dns-address": "udp://1.1.1.1",
  "remote-dns-domain-strategy": "",
  "direct-dns-address": "1.1.1.1",
  "direct-dns-domain-strategy": "",
  "mixed-port": 2334,
  "local-dns-port": 6450,
  "tun-implementation": "mixed",
  "mtu": 9000,
  "strict-route": true,
  "connection-test-url": "http://cp.cloudflare.com/",
  "url-test-interval": 600,
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "enable-tun": true,
  "enable-tun-service": false,
  "set-system-proxy": false,
  "bypass-lan": false,
  "allow-connection-from-lan": false,
  "enable-fake-dns": false,
  "enable-dns-routing": true,
  "independent-dns-cache": true,
  "geoip-path": "geo-assets/sagernet-sing-geoip-geoip.db",
  "geosite-path": "geo-assets/sagernet-sing-geosite-geosite.db",
  "rules": [
    {
      "domains": "domain:.ir,geosite:ir",
      "ip": "geoip:ir",
      "port": null,
      "protocol": null,
      "network": "",
      "outbound": "bypass"
    }
  ],
  "mux": {
    "enable": false,
    "padding": false,
    "max-streams": 8,
    "protocol": "h2mux"
  },
  "tls-tricks": {
    "enable-fragment": false,
    "fragment-size": "1-500",
    "fragment-sleep": "0-500",
    "mixed-sni-case": false,
    "enable-padding": false,
    "padding-size": "1-1500"
  },
  "warp": {
    "enable": false,
    "mode": "proxy_over_warp",
    "clean-ip": "auto",
    "clean-port": 0,
    "noise": "5-10",
    "noise-delay": "20-200"
  }
}
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kekomenos** [comment]
> ### Search first
> 
> - [X] I searched and no similar issues were found
> 
> ### What Happened?
> 
> Hello
> Most protocols of my server are available for V2RAYNG but when that profile when imported to Hiddify Next just one protocol is available.
> Both V2RAYNG and Hiddify Next are in default settings.
> 
> Why?
> 
> ### Minimal Reproducible Example (MRE)
> 
> Same
> 
> ### Expected Behavior
> 
> Same access to server protocols 
> 
> ### Version
> 
> 1.1.1
> 
> ### Platform/OS
> 
> Android
> 
> ### Additional Context
> 
> None 
> 
> ### Application Config Options
> 
> ```shell
> {
>   "execute-config-as-is": false,
>   "log-level": "warn",
>   "resolve-destination": false,
>   "ipv6-mode": "ipv4_only",
>   "remote-dns-address": "udp://1.1.1.1",
>   "remote-dns-domain-strategy": "",
>   "direct-dns-address": "1.1.1.1",
>   "direct-dns-domain-strategy": "",
>   "mixed-port": 2334,
>   "local-dns-port": 6450,
>   "tun-implementation": "mixed",
>   "mtu": 9000,
>   "strict-route": true,
>   "connection-test-url": "http://cp.cloudflare.com/",
>   "url-test-interval": 600,
>   "enable-clash-api": true,
>   "clash-api-port": 6756,
>   "enable-tun": true,
>   "enable-tun-service": false,
>   "set-system-proxy": false,
>   "bypass-lan": false,
>   "allow-connection-from-lan": false,
>   "enable-fake-dns": false,
>   "enable-dns-routing": true,
>   "independent-dns-cache": true,
>   "geoip-path": "geo-assets/sagernet-sing-geoip-geoip.db",
>   "geosite-path": "geo-assets/sagernet-sing-geosite-geosite.db",
>   "rules": [
>     {
>       "domains": "domain:.ir,geosite:ir",
>       "ip": "geoip:ir",
>       "port": null,
>       "protocol": null,
>       "network": "",
>       "outbound": "bypass"
>     }
>   ],
>   "mux": {
>     "enable": false,
>     "padding": false,
>     "max-streams": 8,
>     "protocol": "h2mux"
>   },
>   "tls-tricks": {
>     "enable-fragment": false,
>     "fragment-size": "1-500",
>     "fragment-sleep": "0-500",
>     "mixed-sni-case": false,
>     "enable-padding": false,
>     "padding-size": "1-1500"
>   },
>   "warp": {
>     "enable": false,
>     "mode": "proxy_over_warp",
>     "clean-ip": "auto",
>     "clean-port": 0,
>     "noise": "5-10",
>     "noise-delay": "20-200"
>   }
> }
> ```
> 
> 
> ### Relevant log output
> 
> _No response_
> 
> ### Are you willing to submit a PR? If you know how to fix the bug.
> 
> - [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Pls provide us with the logs. I close the issue and if you wanna add more info you can open it
