### ISSUE TITLE
Unexpected Error  inMalize inbound/mixed/mixed-MI: listen tcp

### ISSUE THREAD

**Issue by non7676** [hiddify/hiddify-next#795]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Unexpected Error 
inMalize inbound/mixed/mixed-MI: listen tcp 127.0.0,2385: bind: An attempt was made to access a socket in a way forbidden by its access permission. 

### Minimal Reproducible Example (MRE)

After opening the app and clicking on the ‘connect’ button, I encounter this error. I tested it with different ports, but the error persists. In Windows, I resolved this error using a PowerShell command with administrative permissions.
`net stop hns && net start hns`

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
It seems the port is not open or you did not open the app with admin privilege
