### ISSUE TITLE
The subscription address cannot be configured successfully.

### ISSUE THREAD

**Issue by yetu418472032** [hiddify/hiddify-next#798]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Subscribing directly using the subscription address provided by the airport is fine. However, if the original subscription address is shortened using a third-party website, the software may fail to subscribe successfully.
![210](https://github.com/hiddify/hiddify-next/assets/33544111/16991b38-c208-4d85-a1c8-55e31b379708)#797

**Comment by yetu418472032** [comment]
It is likely that the shortened link cannot redirect to the actual subscription address (the original subscription link).

**Comment by realaminesl** [comment]
I have the same problem. Subscription links do not work in hiddify next.  Some links are not added, some links that are added do not work.  But I didn't have such a problem until a few hours ago.

**Comment by yetu418472032** [comment]
> I have the same problem. Subscription links do not work in hiddify next. Some links are not added, some links that are added do not work. But I didn't have such a problem until a few hours ago.

Your issue seems different from what I described. My original subscription links were working fine. However, after I shortened them to a new link address, I couldn't configure them successfully. It's possible that the shortened URLs can't directly redirect to the real subscription addresses, causing the error.

**Comment by lymanjre** [comment]
You can check if your 3rd website supports TLS or not

**Comment by yetu418472032** [comment]
The website supports TLS, as observed upon visiting the URL.
