### ISSUE TITLE
hiddify confilict with dae

### ISSUE THREAD

**Issue by coci713** [hiddify/hiddify-next#799]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

if I start dae first , hiddify can not connect .I have wirte pname(hiddify) -> must_direct in config.dae .
but hiddify connect first and then turn on dae ,it works fine

### Minimal Reproducible Example (MRE)

1.start dae 2.open hiddify 3.connect 4 it connecting for long time 5.trun off dae 6.reconnect hiddify 7.hiddify working fine

### Version

v1.1.1

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
What is dae? Can you explain more? I close the issue and if you want to add more info you can reopen it.
