### ISSUE TITLE
No ping on auto CDN _ vless _ GRPC configs

### ISSUE THREAD

**Issue by soshiantmahdavi** [hiddify/hiddify-next#80]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام 
لطفاً اگه میشه راهنماییم کنید
توی هیدیفای نکست auto cdn رو پینگ نمیده اما ریلیتی رو اوکیه در حالی که توی v2rayng یا hiddifyNg  هیچ مشکلی auto cdn  نداره (یعنی احتمالا کانفیگ‌ مشکلی نداره) 
اگه میشه بگین چیکارش کنم
بعدش ی نکته مهم دیگ اینکه لینک سابسکریپشنی که از گزینه (لینک یکسان برای همه برنامه ها ) به دست میاد توی هیدیفای نکست هیچ پینگی نمیده نه ریلیتیش نه auto cdn 
اونم ی چک بکنید لطفاً

### Reproduce the Bug

Go to hiddifyNext
Select auto cdn configs
Click so as to connect
Try ping test
There is no ping fir cdn configs 

### Version

0.9.2

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
لطفا آپدیت کتید مشکل حل شده
