### ISSUE TITLE
The latest version cannot be used on Android

### ISSUE THREAD

**Issue by acstor** [hiddify/hiddify-next#801]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The mobile Android system uses version 1.1.1. Sometimes, the connection node test delay is successful, but the proxy cannot be used. If the software is rolled back to 0.15.9, it can be used again. Make sure there is no problem with the proxy node.

### Minimal Reproducible Example (MRE)

1. Use an Android phone to import usable nodes
2. Very occasional use every day
3. It will reappear from a certain day (no more than two weeks)

### Version

v1.1.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ChthollyWn** [comment]
I also encountered this problem, and neither version 1.1.1 nor version 0.15.9 can be used normally on my Android phone. However, if I use sing-box to directly connect to my node, everything works fine.

**Comment by lymanjre** [comment]
This type of issues cant be debugged unless you provide us with more info and logs. I close the issue and if you wanna add more info and logs you can reopen it.

**Comment by richardlzs** [comment]
这看起来像是dns的问题，我目前使用1.1.1版本，在电脑上可以成功连接到服务器，但是手机上不行，手机的日志显示：
dns: exchange failed for xxxxxx. IN A:context canceled
dns: exchange failed for xxxxxx.IN A:write udp x.x.x.x:port->1.1.1.1:53: use of closed network connection

[translate]
This looks like a dns issue, I'm currently using version 1.1.1 and I can successfully connect to the server on my computer, but not on my phone, the logs from my phone show:
dns: exchange failed for xxxxxx. IN A:context canceled
dns: exchange failed for xxxxxx.IN A:write udp x.x.x.x:port->1.1.1.1:53:use of closed network connection
