### ISSUE TITLE
desktop and android bug

### ISSUE THREAD

**Issue by josbu** [hiddify/hiddify-next#804]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After opening the computer version 1.1.1, the images in the DingTalk chat software cannot be displayed, and the saved emoticons cannot be shown. The cf workers node for the mobile version 1.1.1 is not working, and all the nodes set up by my own VPS cannot access Google and YouTube.

### Minimal Reproducible Example (MRE)

After opening the computer version 1.1.1, the images in the DingTalk chat software cannot be displayed, and the saved emoticons cannot be shown. The cf workers node for the mobile version 1.1.1 is not working, and all the nodes set up by my own VPS cannot access Google and YouTube.

### Version

1.1.1

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Use VPN mode and try again
