### ISSUE TITLE
[FR] Hope to add features similar to kernel authorization

### ISSUE THREAD

**Issue by awsl1414** [hiddify/hiddify-next#807]
### Feature description

Process:
I tried using VPN mode when using hiddify, but it told me that I needed to start it with an administrator
Reason:
I think it's inconvenient to start with an administrator, and the location of the configuration file may also change
Screenshot:
![image](https://github.com/hiddify/hiddify-next/assets/95275520/b74af4c9-5364-4dfa-9f39-39d4f38f4763)

**Comment by lymanjre** [comment]
use VPN service instead
