### ISSUE TITLE
Desktop App Core Switch

### ISSUE THREAD

**Issue by iamlotp** [hiddify/hiddify-next#810]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

The Windows program has the Fragment settings implemented in it, but the app uses "Singbox Core." Therefore Fragment cannot be used. I tried finding if it is possible to change the core to XRAY, yet I couldn't find it neither in the Settings of the app nor in the documents.

### Minimal Reproducible Example (MRE)

1. Import Fragment Config
2. Singbox error
![image](https://github.com/hiddify/hiddify-next/assets/167346050/4d9cff78-6511-4bb0-a1e5-44d8426f097c)

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
Fragment is used in SingBox too

**Comment by iamlotp** [comment]
> Fragment is used in SingBox too

In the Hiddify desktop app the ClientHello Fragmentation option does not help with the circumvention of SNI addresses that are blocked (filtered) by the government, while in the XRAY core, it is possible to use VLESS:// configs which SNI addresses have been blocked. Is this a problem with hiddify, or is it with the singbox core?
