### ISSUE TITLE
ERROR [0001] dns: exchange failed for www.google.com. IN A:remote error: UDP initialization failed When Using "Hysteria1" and Remote "UDP dns"

### ISSUE THREAD

**Issue by moranno** [hiddify/hiddify-next#818]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

ERROR [0001] dns: exchange failed for www.google.com. IN A: remote error: UDP initialization failed. When using "Hysteria1" and remote "UDP DNS", all DNS requests fail, rendering websites inaccessible.

### Minimal Reproducible Example (MRE)

1. Connect to a Hysteria1 node (Note: This issue does not occur with Hysteria2).
2. Attempt to access any website and monitor the log for errors.
3. If Remote DNS is set to tcp://1.1.1.1, the problem does not occur.

### Expected Behavior

DNS requests should successfully resolve without errors, and websites should be accessible when connected through Hysteria1 with remote "UDP DNS".

### Version

v1.1.1

### Platform/OS

Android

### Additional Context

**Screenshots**
![Link to screenshot](https://github.com/hiddify/Hiddify-Manager/assets/77610980/bceb05c5-25a5-4a25-b986-d20412086ac1)

**Video Demonstration**
[Link to video](https://github.com/hiddify/Hiddify-Manager/assets/77610980/ff0db807-1b97-49a7-85c2-c27e402b243f)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
You need to use TCP connections or use UDP DNS traffic

**Comment by Sergey-8** [comment]
for me it help if using Remote (and Direct) DNS Setting to "https://8.8.8.8/dns-query" string (not only 8.8.8.8)
for linux cli use keys:
--dns-direct https://8.8.8.8/dns-query 
--dns-remote https://8.8.8.8/dns-query
