### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Sostay** [hiddify/hiddify-next#819]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/hiddify/hiddify-next/assets/6897274/873727b7-a323-4652-a7eb-fa6c1e85b3ab)

Occasionally, there will be an error prompt, and the process cannot be closed through the task manager. It is very inconvenient to restart the computer (or even multiple times) to solve it.

### Minimal Reproducible Example (MRE)

It often appears when switching between System Proxy and VPN mode.

### Version

V1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mhrezabod** [comment]
i have the same problem

**Comment by lymanjre** [comment]
به نظر میرسد پورت ۲۳۳۴ در دسترس نیست. پورت را خالی کنید یا پورت دیگری انتخاب نمایید

**Comment by lymanjre** [comment]
seems the port is not available. Pls keep the port open or use another one in Settings section

**Comment by Sostay** [comment]
![image](https://github.com/user-attachments/assets/a9f01405-328a-4e4e-8fa6-d4115e134e62)
Endless Torture ......
