### ISSUE TITLE
اصلاح ترجمه دو پهلو timeout

### ISSUE THREAD

**Issue by Mammad3861** [hiddify/hiddify-next#822]
### Feature description

![Screenshot_20240427-095231](https://github.com/hiddify/hiddify-next/assets/108564287/1f832a84-85fd-41b6-a7c5-a9ec09d350f2)

پیشنهاد میشه بجای کلمه اتمام مهلت که ممکنه اشتباه گرفته بشه با پایان زمان مهلت پنل از واژه جایگزینی استفاده بشه
مثل این عکس «عدم موفقیت» یا «ایست» 
![Screenshot_20240427-094454](https://github.com/hiddify/hiddify-next/assets/108564287/ef9d4fa8-190d-4f93-a163-68fed2f438d9)

**Comment by lymanjre** [comment]
سلام . سپاس بابت پیشنهاد شما

لطفا از طریق لینک زیر ترجمه فارسی را تغییر دهید.

https://inlang.com/editor/github.com/hiddify/hiddify-next
