### ISSUE TITLE
[FR] Add auto-reconnect when changing service mode

### ISSUE THREAD

**Issue by imfabulousxd** [hiddify/hiddify-next#831]
### Feature description

Self-explanatory. 
![image](https://github.com/hiddify/hiddify-next/assets/154655943/77d98f86-8fe4-44b2-b1ff-3ece2aa19b81)
Whenever you change it, it automatically reconnects. 
right now I have to open the application again to reconnect and It's annoying

**Comment by lymanjre** [comment]
The issue is repetitive.
