### ISSUE TITLE
Windows app crashing

### ISSUE THREAD

**Issue by SaeedMostWanted** [hiddify/hiddify-next#833]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When you open the windows app, a white screen appears for 5 mins and then, the app crashes and the window disappears.

### Minimal Reproducible Example (MRE)

1. Click on app icon

### Version

1.1.1

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
You just need to remove all files in working directory then try again

**Comment by SaeedMostWanted** [comment]
I did that but still the problem persists.
I even tested another Flutter-based app called "karing" and experienced
the same problem.
