### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shakell65** [hiddify/hiddify-next#834]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

App has been crashed or stopped after screen has locked.

### Minimal Reproducible Example (MRE)

MRE

### Version

1.1.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by ehsanna11111** [comment]
سلام و ممنون از برنامه عالیتون 
اگه ممکن بگید علت نشون دادن این خطا هنگامیکه گزینه وارپ روشنه و قصد کانکت شدن رو دارم چیه؟
![1](https://github.com/hiddify/hiddify-next/assets/134102795/4c462a15-9442-4f09-8988-4153dd0bd021)

**Comment by lymanjre** [comment]
This issue is repetitive, so I close this
