### ISSUE TITLE
[FR] درخواست از برنامه نویس فلاتر

### ISSUE THREAD

**Issue by rezaziyai** [hiddify/hiddify-next#835]
### Feature description

سلام من میخوام به صورت شخصی بذارم داخل تست فلایت واسه مشتری هام 
ممکنه سورس رو واسم بدید با سورس داخل سایت برنامه نویسم نتونست 
ممکنه شما این کارو واسم انجام بدید 
هزینه شو هم پرداخت میکنم
تلگرامم
@propmrvip

**Comment by lymanjre** [comment]
خیر امکان‌پذیر نیست. لایسنس برنامه هرگونه استفاده تجاری را منع کرده و انتشار آن روی پلتفرمهای اپل غیرمجازه
