### ISSUE TITLE
چند باگ کوچیک برای برسی

### ISSUE THREAD

**Issue by MMDPrh** [hiddify/hiddify-next#836]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

سلام و عرض خسته نباشید خدمت دولوپر های عزیز، پیرو این موضوعی که باز کردم میخواستم چند نوع باگ کوچیک که بعضیاشون مدت نسبتا طولانی ای هست که وجود دارن و بعضیاشون در نسخه جدید برنامه ایجاد شدند رو براتون یه توضیحاتی بدم.

- یکی از این موضوعاتی که در نسخه جدید 1.1.1 به وجود اومده و از 1.0.0 هم بودش اینه که برنامه مختص ویندوز قادر به اکسپورت کانفیگ ها از برنامه نیست و زمانی که میخوام با استفاده از Share کانفیگ موجودر رو در کلیپبورد اکسپورت کنم دوتا اتفاق میفته که یا برنامه به کل کرش میخوره و یا یک متن کاملا خالی توی کلیپ بورد کپی میشه.

- پیرو این اپدیت ها یه مشکل که من توی گوشی داشتم همیشه اینه که هربار که کانفیگ در حال کار کردن هست و من گوشی رو خاموش میکنم و چند ثانیه بعد بازم روشن میکنم برنامه به بنظر کرش میخوره یا بسته میشه در هر صورت کانفیگ دیگه کار نمیکنه یا اتمام مهلت میده که من باید دوباره برم و خاموش روشنش کنم و بر اساس اینکه خاموش شدن برنامه بنا به یسری دلایل کمی طولانی هستش باعث میشه یه مقدار ازار دهنده باشه این موضوع.

- علاوه بر مشکل بالا گاهی اوقات داخل اندروید وقتی برنامه باز هست و میخوام کانفیگ رو خاموش روشن کنم یا کانفیگ جدیدی اضافه کنم و روی دکمه روشن شدن بزنم بعد از چند ثانیه یهویی از برنامه خارج میشه.

- در اخر توی دو نسخه ویندوز و اندرویدی که من استفاده میکنم در بعضی مواقع کانفیگ ها به کل دچار اتمام مهلت میشن و دیگه کار نمیکنن تا وقتی من کامل برنامه رو نبندم و باز نکنم.

هیدفای واقعا برنامه خوبی هستشو من نهایت تشکر و قدردانی رو از تمام دولوپرای عزیز این برنامه دارم، این مشکلات بالا صرفا گاهی اوقات باعث میشن که پروسه یه مقدار خسته کننده باشه ازونجایی که زمان کار رو طولانی میکنه تا کانفیگ راه بیفته ولی بعدش تا مدت طولانی ای کار میکنه، اگر این موارد که روزمره پیش میان حل بشن واقا کمک بزرگی میشه ممنون از شما.

### Minimal Reproducible Example (MRE)

_

### Expected Behavior

به صورت کلی از طرف من انتظاری که میره این هستش که برنامه کانفیگ هایی که میخوام از نسخه ویندوز اکسپورت کنم و انتقال بدم رو به درستی به کلیپ بورد وارد کنه و کرش نخوره، و دوم اتمام مهلت های متعدد موقع بستن برنامه یا قفل کردن گوشی رفع بشه و در اخر برنامه کرش های ناگهانی موقع روشن کردن کانفیگ نداشته باشه.

### Version

1.1.1

### Platform/OS

Android, Windows

### Additional Context

_

### Application Config Options

```shell
Default
```

### Relevant log output

```shell
_
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
دوست عزیز این ایشوها قبلا ثبت شده و در نوبت بررسی است. ایشوی شما بسته می‌شود
