### ISSUE TITLE
[FR] 希望增加开机静默自动连接

### ISSUE THREAD

**Issue by waxingren** [hiddify/hiddify-next#837]
### Feature description

现在每次开机都要点一下连接，希望跟clash 一样 能 开机静默连接   win10托盘栏图标是黑的，在全黑的任务栏中不好分辨，希望可以更改颜色
Now I have to click on the connection every time I start the computer. I hope it can be connected silently like Clash. The win10 tray bar icon is black and it is difficult to distinguish it in the completely black taskbar. I hope the color can be changed.
![Snipaste_2024-05-02_02-16-23](https://github.com/hiddify/hiddify-next/assets/166250247/dc1160ce-97b9-4481-abd0-6221f3fa7fb2)

**Comment by wqinf** [comment]
我也遇到了这个问题，希望设置了开机自启动之后，支持自动连接，现在这样很不方便。
I also encountered this problem, hope to set the boot after the boot, support automatic connection, now this is very inconvenient.

**Comment by lymanjre** [comment]
This issue is repetitive and it s under checking out, Pls be patient

**Comment by Sostay** [comment]
别说自动连接了 为啥我设置了开机启动都没用，每次都要手动启动……

**Comment by earthmoon** [comment]
你好，这个可以自动连接吗？为什么我设置了开机自动启动还是要点击一下才可以连接？

**Comment by ppp2020** [comment]
2026年了 还不能自动连接

**Comment by Sostay** [comment]
2026年了咋还有人在用这个不成气候的东西

**Comment by ppp2020** [comment]
> 2026年了咋还有人在用这个不成气候的东西

主要这个首页可以看到剩余流量
我感觉挺好的 
但是现在又换回v2rayN了

**Comment by waxingren** [comment]
> 2026年了咋还有人在用这个不成气候的东西

挺好用的 点一下开关就能用了。主要是无脑  可惜不支持新协议了
