### ISSUE TITLE
Amir2210c

### ISSUE THREAD

**Issue by Amir2210c** [hiddify/hiddify-next#844]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Noting 

### Minimal Reproducible Example (MRE)

1

### Version

v1 .3.8 etc

### Platform/OS

Android, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
So for what error did you register this issue :))
