### ISSUE TITLE
Can't download/update apps from playstore

### ISSUE THREAD

**Issue by eiliatmr** [hiddify/hiddify-next#845]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Apps wont get updated or downloaded on playstore on hiddfy recently.
Yet other apps like v2rayng or nekobox doesn't seem to have this problem.
Im still not sure if its app problem or sth but I'll put the report right here for a review.

### Minimal Reproducible Example (MRE)

Install or update sth in playstore with any network connection.

### Version

1.1.1

### Platform/OS

Android

### Additional Context

I use per app proxy feature but i did try without that and the result was the same

Not just for me, but my other 2 friends.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by pjrobertson** [comment]
I am also having the same problem. @eiliatmr  what did you do to solve the problem?
