### ISSUE TITLE
Application crash on Windows

### ISSUE THREAD

**Issue by HarwoodKinnav** [hiddify/hiddify-next#848]
### What Happened?

When you launch an application, a window appears for a few seconds, after which the application closes.
I believe this is due to the old processor without support sse4.1 and >=Flutter 3.16.0 (Dart 3.2.0)
As far as I understand, this problem was fixed in Flutter 3.19.5 (Dart 3.3.3)

### Minimal Reproducible Example (MRE)

Launch an application on CPU without support sse4.1

### Expected Behavior

Update the program to Flutter 3.19.5 (Dart 3.3.3)

### Version

v1.1.1

### Platform/OS

Windows 11 23H2 build 22631.3527

**Comment by lymanjre** [comment]
Pls remove all files in working directory then try again
