### ISSUE TITLE
[FR] Add custom rules and script configuration

### ISSUE THREAD

**Issue by Joackk** [hiddify/hiddify-next#853]
### Feature description

Can these two features be added? Occasionally we may have some rules that need to be customized, but as soon as the update subscription configuration will be covered, a configuration file can be customized like Clash. Intersection Script is used to perform load balancing and some specific operations. Here are their introduction: https://clash-rge-rev.github.io/guide/merge.html#_2 I wonder if it can be used as a reference

**Comment by lymanjre** [comment]
These features are repetitive, and some people requested this before, so I close your issue. Thanks for sharing your idea.
