### ISSUE TITLE
Bugs in being active for a long time

### ISSUE THREAD

**Issue by Roochiar** [hiddify/hiddify-next#855]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The bug is that when the operating system (Android, Windows) comes back from sleep mode, the program will give an error and have a problem in the execution of its codes, and the operating system will close the program (if the program is active for a long time and sending and receiving data different)

### Minimal Reproducible Example (MRE)

1. run and start VPN
2. Long wait (more than 10 minutes)
3. Putting the operating system (Windows, android) to sleep
4. Wake up the operating system (Windows, android)

### Version

1.1.1

### Platform/OS

Android, Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
The issue is repetitive, so I close your issue.
