### ISSUE TITLE
پیام اتمام مهلت غیر واقعی 

### ISSUE THREAD

**Issue by gachineh** [hiddify/hiddify-next#857]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

توی اپلیکیشن اندروید بدون دلیل مینویسه اتمام مهلت 
در صورتی که یوزر تایم داره

### Minimal Reproducible Example (MRE)

توی اپلیکیشن اندروید بدون دلیل مینویسه اتمام مهلت 
در صورتی که یوزر تایم داره

### Version

1.1.1

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by lymanjre** [comment]
این خطای ترجمه هست که اصلاح شده در آپدیت بعدی درست میشه.
