### ISSUE TITLE
[FR] no system proxy feauture on android

### ISSUE THREAD

**Issue by wh2526422** [hiddify/hiddify-next#859]
### Feature description

why do not have the system proxy feature on android?could you add this feature?

**Comment by lymanjre** [comment]
If you tap on upper right menu on Home screen you can change it to Proxy mode.

**Comment by wh2526422** [comment]
你好，我已收到你的邮件，尽快给你回复。

**Comment by wh2526422** [comment]
I see it, but is the only proxy the same as the system proxy on clash?
