### ISSUE TITLE
crashing Hiddify when using WARP

### ISSUE THREAD

**Issue by TheMarwin** [hiddify/hiddify-next#868]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

- وقتی WARP داخلی هیدیفای رو روشن میکنم بعضی وقتا برنامه کرش میکنه و باید Cash رو پاک کنم (توی ویندوز خودش کلا بسته میشه و باید دوباره بازش کنم)
- خیلی وقت ها توی همون حالت timeout میزنه و باید چند بار خاموش روشن کنم تا اعمال بشه و کانفیگ ها پینگ بده
- مشکل دیگه هم اینه وقتی VPN روی حالت وارپ روشنه و گوشیو خاموش میکنم، بعد از روشن شدنش باید دوباره hiddify رو قطع و وصل کنم تا دوباره وصل بشه
مشکل گزارش شده روی چندین گوشی تست شده و همه این مشکل رو داشتن

### Minimal Reproducible Example (MRE)

No information

### Version

v 1.1.1

### Platform/OS

Android, Windows, iOS

### Relevant log output

![photo_2024-05-10_18-08-26](https://github.com/hiddify/hiddify-next/assets/71283282/90ec9d20-000e-4e9b-9d95-7ff7d9756fb0)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by aliajboy** [comment]
English:

- When WARP is enabled in mobile app, sometimes the app crashes and I have to clear cache and then re-open. In windows, the program it self will close and I have to re-open it.
- more often It returns timeout and have to try many times to get ping and get connected

this problem has tested on several mobile phones and all have the same problem.

**Comment by LitenBuzzTh** [comment]
exactly this issue is also experienced by me. the developer always ignores with irrelevant answers to issues
