### ISSUE TITLE
IPA sideload not available

### ISSUE THREAD

**Issue by AriaKill3r** [hiddify/hiddify-next#872]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I can’t download IPA file and testflight is full
Please share ipa file to i want to sideload it

### Minimal Reproducible Example (MRE)

Go to download hiddify page 
Ios file is 404 not working

### Version

1.1.1

### Platform/OS

iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Neurotoxin001** [comment]
same

**Comment by amirsaam** [comment]
#1029
