### ISSUE TITLE
PowerToys

### ISSUE THREAD

**Issue by xmha97** [hiddify/hiddify-next#896]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hiddify does not run when I enable the following option in the PowerToys app.

https://github.com/hiddify/hiddify-next/assets/23485114/3a720018-1aca-404c-8427-e270ae8e31d1

### Minimal Reproducible Example (MRE)

1. Go to PowerToys app.
2. Check "Move newly created windows to their last know zone".

### Version

v1.1.1

### Platform/OS

Windows

### Additional Context

The Hiddify installed from Microsoft Store.
Also, the problem only occurs with Hiddify, other Flutter apps work properly.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
دمت گرم چه ویدیویی دقیقی ساختی
ولی روی سیستم ما اوکیه
یه عامل دیگه ای هست توش

ضمنا اگه بتونی کمک کنی برای ویدیوهای آموزشی خیلی خوبه
