### ISSUE TITLE
نشان ندادن پینگ تاخیر

### ISSUE THREAD

**Issue by alexfurd1378** [hiddify/hiddify-next#91]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

در ورژن قبلی پینگ تاخیر کانفیگ ها در پراکسی دیده میشد اما در اخرین ورژ این قابلیت نیست
لطفا پینگ تاخیر در قسمت پراکسی روی کانفیگ رو بزارید تا متوجه بشیم کدوم کانفیگ کار میکنه و کدوم کار نمیکنه
دوم ترافیک رد و بدل شده در قسمت نوار ابزار بعد از اتصال این مورد کمک میکنه که کانفیگ داره کار میکنه یا خیر

ممنون میشم این دو مورد رو اضافه کنید چه در اندروید چه ویندوز

### Reproduce the Bug

نزدن پینگ تاخیر در قسمت پراکسی
نشان ندادن سرعت ترافیک در قسمت نوار ابزار بعد از اتصال

### Version

0.9.2

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by trytopassgfw** [comment]
من هم این مشکل رو دارم. روی نسخه ‌ios هم تست کردم این مشکل هست. روی ویندوز هم پینگ رو نمیده. همون کانفیگ روی مثلا v2box نسخه ios داره درست کار میکنه. نسخه ‌ios 0.15.4 dev
پینگ نداشتنه باعث میشه عملا کار هم نکنه
