### ISSUE TITLE
[FR] There is no place to set the clash secret in v1.1.1

### ISSUE THREAD

**Issue by Billyas** [hiddify/hiddify-next#919]
### Feature description

There is no place to set the clash secret in v1.1.1

[if opt.ClashApiSecret == "" {
			opt.ClashApiSecret = generateRandomString(16)
		}](https://github.com/hiddify/hiddify-core/blob/b26588630694cf99f66292d2703476f9deee79d7/config/config.go#L74-L90)

we can‘t get secret, and need to find in workspace config when open connect each time。

**Comment by hiddify-com** [comment]
You can set --web-secret  flag
