### ISSUE TITLE
[FR] Please add port hopping support to hysteria2 

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#920]
### Feature description

Hi and thanks for your awesome works..

Imported links like this:
```
hy2://xxxxxxxxxxxx@a.b.c.d:uvxyz?obfs=salamander&obfs-password=xxxxxx&mport=21001-22000&insecure=1&sni=xxxx.com#hy2
```
But when checked Hiddify imported configs they are showing as:
```
     {
      "type": "hysteria2",
       "tag": "hy2 § 0",
       "server": "a.b.c.d",
       "server_port": uvxyz,
       "obfs": {
         "type": "salamander",
         "password": "xxxxxxxxxx"
       },
       "password": "xxxxxxxxxx",
       "tls": {
         "enabled": true,
         "server_name": "xxxx.com",
         "insecure": true
       }
     }
```

Seems like port hopping (mport variable) is missing in the config .
If not too much work please add it too

Thanks again for all your helps.

**Comment by papampi** [comment]
Sorry just noticed it's a sing-box limit.

**Comment by hanhan9449** [comment]
Does the singbox support it now? And can we reopen it？
