### ISSUE TITLE
1.3.2 Dev not opens on linux

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#923]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Installed 1.3.2.dev on linux but wont open
hiddify run output:
<details>
** (hiddify:100931): CRITICAL **: 11:03:02.136: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.136: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.136: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.136: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_handler_find: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: invalid (NULL) pointer instance

(hiddify:100931): GLib-GObject-CRITICAL **: 11:03:02.137: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(hiddify:100931): Gtk-CRITICAL **: 11:03:02.137: gtk_container_forall: assertion 'GTK_IS_CONTAINER (container)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (hiddify:100931): CRITICAL **: 11:03:02.137: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

</details>

### Minimal Reproducible Example (MRE)

Installed via dpkg -i ... 
Start from application menu ... not opens
Killed hiddify and start from command line 
Output added to check

### Version

1.3.2.dev

### Platform/OS

Linux
Ubuntu 24.04

**Comment by papampi** [comment]
Tried on ubuntu 22.04 too, same problem.

**Comment by nimbold** [comment]
Same with version 1.3.1 (and I think 1.3.2) on Arch.
