### ISSUE TITLE
Force close when importing json

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-next#925]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Whenever I click on import from clipboard, app crashes and does not import any json config

### Minimal Reproducible Example (MRE)

.

### Version

1.3.3

### Platform/OS

Android

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
fixed
