### ISSUE TITLE
Add Warp error

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-next#930]
When click the  "Add Warp" it gives an unexpected error on ubuntu 22.04

```
Unexpected Error
error patching outbound[Remote § 0][custom]: netip.ParsePrefix("/24"): ParseAddr("): unable to parse IP
OK
```

### Minimal Reproducible Example (MRE)

1- Go to + New profile 
2- Click Add Warp
it gives unexpected error

### Version

v1.4.0 and 1.3.6

### Platform/OS

Linux, Ubuntu 22.04

### Additional Context

On my ubuntu 24.04 works fine and import the config , but on but 22.04 gives error

![Screenshot from 2024-06-03 00-31-13](https://github.com/hiddify/hiddify-next/assets/1108483/75b24284-44b4-4483-9240-528a78503952)

**Comment by aminpple** [comment]
منم همین مشکلو با ابدیت جدید دارم

**Comment by hiddify-com** [comment]
please remove the app and reinstall it

**Comment by papampi** [comment]
> please remove the app and reinstall it

Still gives error ... 
Maybe we should remove app data folder as well?
