### ISSUE TITLE
Startup auto connect[FR] 

### ISSUE THREAD

**Issue by zodiacc7** [hiddify/hiddify-next#94]
### Feature description

لطفا قابلیت اتصال خودکار هنگام باز شدن برنامه را اضافه بفرمایید

با سپاس

**Comment by shtir** [comment]
منم به این قابلیت نیاز دارم.

**Comment by MB-KING** [comment]
I need this feature

**Comment by SuraimuUwU** [comment]
I need this feature too

**Comment by lymanjre** [comment]
این قابلیت در آخرین نسخه وجود داره

**Comment by difhel** [comment]
How can I enable this feature? I searched for this option in settings but didn't find anything. The app starts on startup but not autoconnecting.
<img width="872" alt="image" src="https://github.com/hiddify/hiddify-next/assets/78644136/11aa3dad-ade4-435b-a820-fa777876740c">

**Comment by zxyqq** [comment]
me too need this feature
