### ISSUE TITLE
Failed to Run Project 'core' property doesn't exist

### ISSUE THREAD

**Issue by moala-t** [hiddify/hiddify-next#951]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i tried to run the project source code but had problem with 'Assets.core'
the 'core' property dosn't exist in Asset Class
this is the releated code in hiddify-next/lib/features/geo_asset/data/geo_asset_repository.dart

        if (!dirExists || !await geoipFile.exists()) {
          final bundledGeoip = await rootBundle.load(Assets.core.geoip);
          await geoipFile.writeAsBytes(bundledGeoip.buffer.asInt8List());
        }
        if (!dirExists || !await geositeFile.exists()) {
          final bundledGeosite = await rootBundle.load(Assets.core.geosite);
          await geositeFile.writeAsBytes(bundledGeosite.buffer.asInt8List());
        }
        

### Minimal Reproducible Example (MRE)

1. go to this location: hiddify-next/lib/features/geo_asset/data/geo_asset_repository.dart

### Version

v1.4.0

### Platform/OS

Android, Windows, macOS, Linux, iOS

### Relevant log output

```shell
lib/features/geo_asset/data/geo_asset_repository.dart:65:61: Error: Member not found: 'core'.
          final bundledGeoip = await rootBundle.load(Assets.core.geoip);
                                                            ^^^^
lib/features/geo_asset/data/geo_asset_repository.dart:69:63: Error: Member not found: 'core'.
          final bundledGeosite = await rootBundle.load(Assets.core.geosite);
                                                              ^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/moala/flutter-sdk/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Error: Gradle task assembleDebug failed with exit code 1


Exited (1).
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [x] I'm willing to submit a PR (Thank you!)

**Comment by SeyedFoad** [comment]
لطفا مشکل حل عدم ارتباط رو حل کنید ممنون میشم
یا اگر توضیح خاصی هست اطلاع بدین

**Comment by moala-t** [comment]
> لطفا مشکل حل عدم ارتباط رو حل کنید ممنون میشم یا اگر توضیح خاصی هست اطلاع بدین

 به قسمت [contributing guidelines ](https://github.com/hiddify/hiddify- next/blob/2c59583aa2affe9934f1c6f3f6cad93c7131acd3/CONTRIBUTING.md) برین و دستور العمل رو بخونین

**Comment by moala-t** [comment]
[contributing guidelines](https://github.com/hiddify/hiddify-next/blob/2c59583aa2affe9934f1c6f3f6cad93c7131acd3/CONTRIBUTING.md)
به این قسمت برین و دستور العمل رو بخونین

> لطفا مشکل حل عدم ارتباط رو حل کنید ممنون میشم یا اگر توضیح خاصی هست اطلاع بدین
