### ISSUE TITLE
Link timeout

### ISSUE THREAD

**Issue by Avey777** [hiddify/hiddify-next#956]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/hiddify/hiddify-next/assets/35259040/414668df-acdf-45e4-933f-535c8017546c)

### Minimal Reproducible Example (MRE)

I have never been successful since using hiddify.

### Version

v1.4.0

### Platform/OS

Windows, macOS, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by ovo-Tim** [comment]
Same problem. My subscription works well on hiddify Android, but completely can't connect on Linux.
![image](https://github.com/hiddify/hiddify-next/assets/116942368/9c7180e6-5569-4668-ace1-71fa10df6436)
