### ISSUE TITLE
X86 version[FR] 

### ISSUE THREAD

**Issue by shtir** [hiddify/hiddify-next#96]
### Feature description

 درصورت امکان نسخه ۳۲ بیت هم ایجاد شود.

**Comment by hiddify-com** [comment]
https://hackaday.com/2021/06/06/is-32-bits-really-dead/

سیستم هامل ۳۲ بیتی رسما مرده دیگه

ما پشتیبانی نمیکنیم

پیشنهاد میکنیم به ۶۴ بیتی ارتقا دهید
