### ISSUE TITLE
[FR] Add icons that display different colors when the connection status is different

### ISSUE THREAD

**Issue by willow-god** [hiddify/hiddify-next#968]
### Feature description

I hope to add different icons in the status bar in connected and unconnected states, which feels more intuitive.
Thank you to the developers!

**Comment by Hint-ru** [comment]
An even bigger problem arises when the panel is black. A black icon is not visible on a black panel, making it seem like there is an empty space.

**Comment by willow-god** [comment]
Yes, I also found this problem, so I used clash-verge. This developer may be busy and have no time to fix it. I will close this issue first. If it is updated later, I will take a look.
