### ISSUE TITLE
1.1.1.1 is block in china

### ISSUE THREAD

**Issue by hovans** [hiddify/hiddify-next#975]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

1.1.1.1 is block in china,so dns use 1.1.1.1 ,because cannot IP resolved to domain name，all  node  time out 

### Minimal Reproducible Example (MRE)

1.Import node
2.Turn on

### Expected Behavior

change default dns that china can use

### Version

1.4.0

### Platform/OS

Android, Windows, macOS, Linux, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by hovans** [comment]
suggest 直连 dns use: 8.8.8.8 ,which is matain by google。

**Comment by forester-pixel** [comment]
hiddify for android can not use chrome and edge go to internet in china

**Comment by hovans** [comment]
so suggest if user select region(地区) to china(中国 cn)，change direct dns(直连 dns) to:119.29.29.29 or 223.5.5.5 ;otherwise many user in chine cannot use because cannot link to 1.1.1.1

**Comment by hiddify-com** [comment]
fixed
